interface Account_Base extends WebEntity {
  accountcategorycode?: account_accountcategorycode | null;
  accountclassificationcode?: account_accountclassificationcode | null;
  accountid?: string | null;
  accountnumber?: string | null;
  accountratingcode?: account_accountratingcode | null;
  address1_addressid?: string | null;
  address1_addresstypecode?: account_address1_addresstypecode | null;
  address1_city?: string | null;
  address1_composite?: string | null;
  address1_country?: string | null;
  address1_county?: string | null;
  address1_fax?: string | null;
  address1_freighttermscode?: account_address1_freighttermscode | null;
  address1_latitude?: number | null;
  address1_line1?: string | null;
  address1_line2?: string | null;
  address1_line3?: string | null;
  address1_longitude?: number | null;
  address1_name?: string | null;
  address1_postalcode?: string | null;
  address1_postofficebox?: string | null;
  address1_primarycontactname?: string | null;
  address1_shippingmethodcode?: account_address1_shippingmethodcode | null;
  address1_stateorprovince?: string | null;
  address1_telephone1?: string | null;
  address1_telephone2?: string | null;
  address1_telephone3?: string | null;
  address1_upszone?: string | null;
  address1_utcoffset?: number | null;
  address2_addressid?: string | null;
  address2_addresstypecode?: account_address2_addresstypecode | null;
  address2_city?: string | null;
  address2_composite?: string | null;
  address2_country?: string | null;
  address2_county?: string | null;
  address2_fax?: string | null;
  address2_freighttermscode?: account_address2_freighttermscode | null;
  address2_latitude?: number | null;
  address2_line1?: string | null;
  address2_line2?: string | null;
  address2_line3?: string | null;
  address2_longitude?: number | null;
  address2_name?: string | null;
  address2_postalcode?: string | null;
  address2_postofficebox?: string | null;
  address2_primarycontactname?: string | null;
  address2_shippingmethodcode?: account_address2_shippingmethodcode | null;
  address2_stateorprovince?: string | null;
  address2_telephone1?: string | null;
  address2_telephone2?: string | null;
  address2_telephone3?: string | null;
  address2_upszone?: string | null;
  address2_utcoffset?: number | null;
  aging30?: number | null;
  aging30_base?: number | null;
  aging60?: number | null;
  aging60_base?: number | null;
  aging90?: number | null;
  aging90_base?: number | null;
  businesstypecode?: account_businesstypecode | null;
  createdon?: Date | null;
  creditlimit?: number | null;
  creditlimit_base?: number | null;
  creditonhold?: boolean | null;
  customersizecode?: account_customersizecode | null;
  customertypecode?: account_customertypecode | null;
  description?: string | null;
  donotbulkemail?: boolean | null;
  donotbulkpostalmail?: boolean | null;
  donotemail?: boolean | null;
  donotfax?: boolean | null;
  donotphone?: boolean | null;
  donotpostalmail?: boolean | null;
  donotsendmm?: boolean | null;
  emailaddress1?: string | null;
  emailaddress2?: string | null;
  emailaddress3?: string | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  fax?: string | null;
  followemail?: boolean | null;
  ftpsiteurl?: string | null;
  importsequencenumber?: number | null;
  industrycode?: account_industrycode | null;
  isprivate?: boolean | null;
  lastonholdtime?: Date | null;
  lastusedincampaign?: Date | null;
  marketcap?: number | null;
  marketcap_base?: number | null;
  marketingonly?: boolean | null;
  merged?: boolean | null;
  modifiedon?: Date | null;
  name?: string | null;
  numberofemployees?: number | null;
  onholdtime?: number | null;
  opendeals?: number | null;
  opendeals_date?: Date | null;
  opendeals_state?: number | null;
  openrevenue?: number | null;
  openrevenue_base?: number | null;
  openrevenue_date?: Date | null;
  openrevenue_state?: number | null;
  overriddencreatedon?: Date | null;
  ownershipcode?: account_ownershipcode | null;
  participatesinworkflow?: boolean | null;
  paymenttermscode?: account_paymenttermscode | null;
  preferredappointmentdaycode?: account_preferredappointmentdaycode | null;
  preferredappointmenttimecode?: account_preferredappointmenttimecode | null;
  preferredcontactmethodcode?: account_preferredcontactmethodcode | null;
  primarysatoriid?: string | null;
  primarytwitterid?: string | null;
  processid?: string | null;
  revenue?: number | null;
  revenue_base?: number | null;
  sharesoutstanding?: number | null;
  shippingmethodcode?: account_shippingmethodcode | null;
  sic?: string | null;
  stageid?: string | null;
  statecode?: account_statecode | null;
  statuscode?: account_statuscode | null;
  stockexchange?: string | null;
  teamsfollowed?: number | null;
  telephone1?: string | null;
  telephone2?: string | null;
  telephone3?: string | null;
  territorycode?: account_territorycode | null;
  tickersymbol?: string | null;
  timespentbymeonemailandmeetings?: string | null;
  timezoneruleversionnumber?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  websiteurl?: string | null;
}
interface Account_Relationships {
  Account_ActivityPointers?: ActivityPointer_Result[] | null;
  Account_Annotation?: Annotation_Result[] | null;
  Account_Appointments?: Appointment_Result[] | null;
  Account_AsyncOperations?: AsyncOperation_Result[] | null;
  Account_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Account_CustomerAddress?: CustomerAddress_Result[] | null;
  Account_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Account_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Account_Email_EmailSender?: Email_Result[] | null;
  Account_Email_SendersAccount?: Email_Result[] | null;
  Account_Emails?: Email_Result[] | null;
  Account_Faxes?: Fax_Result[] | null;
  Account_Letters?: Letter_Result[] | null;
  Account_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  Account_Phonecalls?: PhoneCall_Result[] | null;
  Account_ProcessSessions?: ProcessSession_Result[] | null;
  Account_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  Account_ServiceAppointments?: ServiceAppointment_Result[] | null;
  Account_SharepointDocument?: SharePointDocument_Result[] | null;
  Account_SharepointDocumentLocation?: SharePointDocumentLocation_Result[] | null;
  Account_SocialActivities?: SocialActivity_Result[] | null;
  Account_SyncErrors?: SyncError_Result[] | null;
  Account_Tasks?: Task_Result[] | null;
  BulkOperation_Accounts?: BulkOperation_Result[] | null;
  CampaignActivity_Accounts?: CampaignActivity_Result[] | null;
  CreatedAccount_BulkOperationLogs2?: BulkOperationLog_Result[] | null;
  CreatedByExternalParty?: ExternalParty_Result | null;
  ModifiedByExternalParty?: ExternalParty_Result | null;
  SocialActivity_PostAuthorAccount_accounts?: SocialActivity_Result[] | null;
  SocialActivity_PostAuthor_accounts?: SocialActivity_Result[] | null;
  Socialprofile_customer_accounts?: SocialProfile_Result[] | null;
  SourceAccount_BulkOperationLogs?: BulkOperationLog_Result[] | null;
  account_BulkOperations?: BulkOperation_Result[] | null;
  account_CampaignResponses?: CampaignResponse_Result[] | null;
  account_IncidentResolutions?: IncidentResolution_Result[] | null;
  account_OpportunityCloses?: OpportunityClose_Result[] | null;
  account_OrderCloses?: OrderClose_Result[] | null;
  account_PostFollows?: PostFollow_Result[] | null;
  account_PostRegardings?: PostRegarding_Result[] | null;
  account_PostRoles?: PostRole_Result[] | null;
  account_QuoteCloses?: QuoteClose_Result[] | null;
  account_actioncard?: ActionCard_Result[] | null;
  account_activity_parties?: ActivityParty_Result[] | null;
  account_awcnpd_feedbacks?: awcnpd_feedback_Result[] | null;
  account_bookableresource_AccountId?: BookableResource_Result[] | null;
  account_connections1?: Connection_Result[] | null;
  account_connections2?: Connection_Result[] | null;
  account_customer_opportunity_roles?: CustomerOpportunityRole_Result[] | null;
  account_customer_relationship_customer?: CustomerRelationship_Result[] | null;
  account_customer_relationship_partner?: CustomerRelationship_Result[] | null;
  account_entitlement_Account?: Entitlement_Result[] | null;
  account_entitlement_Customer?: Entitlement_Result[] | null;
  account_master_account?: Account_Result[] | null;
  account_parent_account?: Account_Result[] | null;
  account_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  accountleads_association?: Lead_Result[] | null;
  contact_customer_accounts?: Contact_Result[] | null;
  contract_billingcustomer_accounts?: Contract_Result[] | null;
  contract_customer_accounts?: Contract_Result[] | null;
  contractlineitem_customer_accounts?: ContractDetail_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  incident_customer_accounts?: Incident_Result[] | null;
  invoice_customer_accounts?: Invoice_Result[] | null;
  lead_customer_accounts?: Lead_Result[] | null;
  lead_parent_account?: Lead_Result[] | null;
  listaccount_association?: List_Result[] | null;
  msdyn_playbookinstance_account?: msdyn_playbookinstance_Result[] | null;
  opportunity_customer_accounts?: Opportunity_Result[] | null;
  opportunity_parent_account?: Opportunity_Result[] | null;
  order_customer_accounts?: SalesOrder_Result[] | null;
  quote_customer_accounts?: Quote_Result[] | null;
  sla_account_sla?: SLA_Result | null;
  slainvokedid_account_sla?: SLA_Result | null;
  slakpiinstance_account?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  userentityinstancedata_account?: UserEntityInstanceData_Result[] | null;
}
interface Account extends Account_Base, Account_Relationships {
  defaultpricelevelid_bind$pricelevels?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  parentaccountid_bind$accounts?: string | null;
  preferredequipmentid_bind$equipments?: string | null;
  preferredserviceid_bind$services?: string | null;
  preferredsystemuserid_bind$systemusers?: string | null;
  primarycontactid_bind$contacts?: string | null;
  sla_account_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  territoryid_bind$territories?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Account_Create extends Account {
  originatingleadid_bind$leads?: string | null;
}
interface Account_Update extends Account {
}
interface Account_Select {
  accountcategorycode: WebAttribute<Account_Select, { accountcategorycode: account_accountcategorycode | null }, { accountcategorycode_formatted?: string }>;
  accountclassificationcode: WebAttribute<Account_Select, { accountclassificationcode: account_accountclassificationcode | null }, { accountclassificationcode_formatted?: string }>;
  accountid: WebAttribute<Account_Select, { accountid: string | null }, {  }>;
  accountnumber: WebAttribute<Account_Select, { accountnumber: string | null }, {  }>;
  accountratingcode: WebAttribute<Account_Select, { accountratingcode: account_accountratingcode | null }, { accountratingcode_formatted?: string }>;
  address1_addressid: WebAttribute<Account_Select, { address1_addressid: string | null }, {  }>;
  address1_addresstypecode: WebAttribute<Account_Select, { address1_addresstypecode: account_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
  address1_city: WebAttribute<Account_Select, { address1_city: string | null }, {  }>;
  address1_composite: WebAttribute<Account_Select, { address1_composite: string | null }, {  }>;
  address1_country: WebAttribute<Account_Select, { address1_country: string | null }, {  }>;
  address1_county: WebAttribute<Account_Select, { address1_county: string | null }, {  }>;
  address1_fax: WebAttribute<Account_Select, { address1_fax: string | null }, {  }>;
  address1_freighttermscode: WebAttribute<Account_Select, { address1_freighttermscode: account_address1_freighttermscode | null }, { address1_freighttermscode_formatted?: string }>;
  address1_latitude: WebAttribute<Account_Select, { address1_latitude: number | null }, {  }>;
  address1_line1: WebAttribute<Account_Select, { address1_line1: string | null }, {  }>;
  address1_line2: WebAttribute<Account_Select, { address1_line2: string | null }, {  }>;
  address1_line3: WebAttribute<Account_Select, { address1_line3: string | null }, {  }>;
  address1_longitude: WebAttribute<Account_Select, { address1_longitude: number | null }, {  }>;
  address1_name: WebAttribute<Account_Select, { address1_name: string | null }, {  }>;
  address1_postalcode: WebAttribute<Account_Select, { address1_postalcode: string | null }, {  }>;
  address1_postofficebox: WebAttribute<Account_Select, { address1_postofficebox: string | null }, {  }>;
  address1_primarycontactname: WebAttribute<Account_Select, { address1_primarycontactname: string | null }, {  }>;
  address1_shippingmethodcode: WebAttribute<Account_Select, { address1_shippingmethodcode: account_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
  address1_stateorprovince: WebAttribute<Account_Select, { address1_stateorprovince: string | null }, {  }>;
  address1_telephone1: WebAttribute<Account_Select, { address1_telephone1: string | null }, {  }>;
  address1_telephone2: WebAttribute<Account_Select, { address1_telephone2: string | null }, {  }>;
  address1_telephone3: WebAttribute<Account_Select, { address1_telephone3: string | null }, {  }>;
  address1_upszone: WebAttribute<Account_Select, { address1_upszone: string | null }, {  }>;
  address1_utcoffset: WebAttribute<Account_Select, { address1_utcoffset: number | null }, {  }>;
  address2_addressid: WebAttribute<Account_Select, { address2_addressid: string | null }, {  }>;
  address2_addresstypecode: WebAttribute<Account_Select, { address2_addresstypecode: account_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
  address2_city: WebAttribute<Account_Select, { address2_city: string | null }, {  }>;
  address2_composite: WebAttribute<Account_Select, { address2_composite: string | null }, {  }>;
  address2_country: WebAttribute<Account_Select, { address2_country: string | null }, {  }>;
  address2_county: WebAttribute<Account_Select, { address2_county: string | null }, {  }>;
  address2_fax: WebAttribute<Account_Select, { address2_fax: string | null }, {  }>;
  address2_freighttermscode: WebAttribute<Account_Select, { address2_freighttermscode: account_address2_freighttermscode | null }, { address2_freighttermscode_formatted?: string }>;
  address2_latitude: WebAttribute<Account_Select, { address2_latitude: number | null }, {  }>;
  address2_line1: WebAttribute<Account_Select, { address2_line1: string | null }, {  }>;
  address2_line2: WebAttribute<Account_Select, { address2_line2: string | null }, {  }>;
  address2_line3: WebAttribute<Account_Select, { address2_line3: string | null }, {  }>;
  address2_longitude: WebAttribute<Account_Select, { address2_longitude: number | null }, {  }>;
  address2_name: WebAttribute<Account_Select, { address2_name: string | null }, {  }>;
  address2_postalcode: WebAttribute<Account_Select, { address2_postalcode: string | null }, {  }>;
  address2_postofficebox: WebAttribute<Account_Select, { address2_postofficebox: string | null }, {  }>;
  address2_primarycontactname: WebAttribute<Account_Select, { address2_primarycontactname: string | null }, {  }>;
  address2_shippingmethodcode: WebAttribute<Account_Select, { address2_shippingmethodcode: account_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
  address2_stateorprovince: WebAttribute<Account_Select, { address2_stateorprovince: string | null }, {  }>;
  address2_telephone1: WebAttribute<Account_Select, { address2_telephone1: string | null }, {  }>;
  address2_telephone2: WebAttribute<Account_Select, { address2_telephone2: string | null }, {  }>;
  address2_telephone3: WebAttribute<Account_Select, { address2_telephone3: string | null }, {  }>;
  address2_upszone: WebAttribute<Account_Select, { address2_upszone: string | null }, {  }>;
  address2_utcoffset: WebAttribute<Account_Select, { address2_utcoffset: number | null }, {  }>;
  aging30: WebAttribute<Account_Select, { aging30: number | null; transactioncurrencyid_guid: string | null }, { aging30_formatted?: string; transactioncurrencyid_formatted?: string }>;
  aging30_base: WebAttribute<Account_Select, { aging30_base: number | null; transactioncurrencyid_guid: string | null }, { aging30_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  aging60: WebAttribute<Account_Select, { aging60: number | null; transactioncurrencyid_guid: string | null }, { aging60_formatted?: string; transactioncurrencyid_formatted?: string }>;
  aging60_base: WebAttribute<Account_Select, { aging60_base: number | null; transactioncurrencyid_guid: string | null }, { aging60_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  aging90: WebAttribute<Account_Select, { aging90: number | null; transactioncurrencyid_guid: string | null }, { aging90_formatted?: string; transactioncurrencyid_formatted?: string }>;
  aging90_base: WebAttribute<Account_Select, { aging90_base: number | null; transactioncurrencyid_guid: string | null }, { aging90_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  businesstypecode: WebAttribute<Account_Select, { businesstypecode: account_businesstypecode | null }, { businesstypecode_formatted?: string }>;
  createdby_guid: WebAttribute<Account_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdbyexternalparty_guid: WebAttribute<Account_Select, { createdbyexternalparty_guid: string | null }, { createdbyexternalparty_formatted?: string }>;
  createdon: WebAttribute<Account_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Account_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  creditlimit: WebAttribute<Account_Select, { creditlimit: number | null; transactioncurrencyid_guid: string | null }, { creditlimit_formatted?: string; transactioncurrencyid_formatted?: string }>;
  creditlimit_base: WebAttribute<Account_Select, { creditlimit_base: number | null; transactioncurrencyid_guid: string | null }, { creditlimit_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  creditonhold: WebAttribute<Account_Select, { creditonhold: boolean | null }, {  }>;
  customersizecode: WebAttribute<Account_Select, { customersizecode: account_customersizecode | null }, { customersizecode_formatted?: string }>;
  customertypecode: WebAttribute<Account_Select, { customertypecode: account_customertypecode | null }, { customertypecode_formatted?: string }>;
  defaultpricelevelid_guid: WebAttribute<Account_Select, { defaultpricelevelid_guid: string | null }, { defaultpricelevelid_formatted?: string }>;
  description: WebAttribute<Account_Select, { description: string | null }, {  }>;
  donotbulkemail: WebAttribute<Account_Select, { donotbulkemail: boolean | null }, {  }>;
  donotbulkpostalmail: WebAttribute<Account_Select, { donotbulkpostalmail: boolean | null }, {  }>;
  donotemail: WebAttribute<Account_Select, { donotemail: boolean | null }, {  }>;
  donotfax: WebAttribute<Account_Select, { donotfax: boolean | null }, {  }>;
  donotphone: WebAttribute<Account_Select, { donotphone: boolean | null }, {  }>;
  donotpostalmail: WebAttribute<Account_Select, { donotpostalmail: boolean | null }, {  }>;
  donotsendmm: WebAttribute<Account_Select, { donotsendmm: boolean | null }, {  }>;
  emailaddress1: WebAttribute<Account_Select, { emailaddress1: string | null }, {  }>;
  emailaddress2: WebAttribute<Account_Select, { emailaddress2: string | null }, {  }>;
  emailaddress3: WebAttribute<Account_Select, { emailaddress3: string | null }, {  }>;
  entityimageid: WebAttribute<Account_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<Account_Select, { exchangerate: number | null }, {  }>;
  fax: WebAttribute<Account_Select, { fax: string | null }, {  }>;
  followemail: WebAttribute<Account_Select, { followemail: boolean | null }, {  }>;
  ftpsiteurl: WebAttribute<Account_Select, { ftpsiteurl: string | null }, {  }>;
  importsequencenumber: WebAttribute<Account_Select, { importsequencenumber: number | null }, {  }>;
  industrycode: WebAttribute<Account_Select, { industrycode: account_industrycode | null }, { industrycode_formatted?: string }>;
  isprivate: WebAttribute<Account_Select, { isprivate: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Account_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  lastusedincampaign: WebAttribute<Account_Select, { lastusedincampaign: Date | null }, { lastusedincampaign_formatted?: string }>;
  marketcap: WebAttribute<Account_Select, { marketcap: number | null; transactioncurrencyid_guid: string | null }, { marketcap_formatted?: string; transactioncurrencyid_formatted?: string }>;
  marketcap_base: WebAttribute<Account_Select, { marketcap_base: number | null; transactioncurrencyid_guid: string | null }, { marketcap_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  marketingonly: WebAttribute<Account_Select, { marketingonly: boolean | null }, {  }>;
  masterid_guid: WebAttribute<Account_Select, { masterid_guid: string | null }, { masterid_formatted?: string }>;
  merged: WebAttribute<Account_Select, { merged: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<Account_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedbyexternalparty_guid: WebAttribute<Account_Select, { modifiedbyexternalparty_guid: string | null }, { modifiedbyexternalparty_formatted?: string }>;
  modifiedon: WebAttribute<Account_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Account_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Account_Select, { name: string | null }, {  }>;
  numberofemployees: WebAttribute<Account_Select, { numberofemployees: number | null }, {  }>;
  onholdtime: WebAttribute<Account_Select, { onholdtime: number | null }, {  }>;
  opendeals: WebAttribute<Account_Select, { opendeals: number | null }, {  }>;
  opendeals_date: WebAttribute<Account_Select, { opendeals_date: Date | null }, { opendeals_date_formatted?: string }>;
  opendeals_state: WebAttribute<Account_Select, { opendeals_state: number | null }, {  }>;
  openrevenue: WebAttribute<Account_Select, { openrevenue: number | null; transactioncurrencyid_guid: string | null }, { openrevenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  openrevenue_base: WebAttribute<Account_Select, { openrevenue_base: number | null; transactioncurrencyid_guid: string | null }, { openrevenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  openrevenue_date: WebAttribute<Account_Select, { openrevenue_date: Date | null }, { openrevenue_date_formatted?: string }>;
  openrevenue_state: WebAttribute<Account_Select, { openrevenue_state: number | null }, {  }>;
  originatingleadid_guid: WebAttribute<Account_Select, { originatingleadid_guid: string | null }, { originatingleadid_formatted?: string }>;
  overriddencreatedon: WebAttribute<Account_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Account_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  ownershipcode: WebAttribute<Account_Select, { ownershipcode: account_ownershipcode | null }, { ownershipcode_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Account_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Account_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Account_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  parentaccountid_guid: WebAttribute<Account_Select, { parentaccountid_guid: string | null }, { parentaccountid_formatted?: string }>;
  participatesinworkflow: WebAttribute<Account_Select, { participatesinworkflow: boolean | null }, {  }>;
  paymenttermscode: WebAttribute<Account_Select, { paymenttermscode: account_paymenttermscode | null }, { paymenttermscode_formatted?: string }>;
  preferredappointmentdaycode: WebAttribute<Account_Select, { preferredappointmentdaycode: account_preferredappointmentdaycode | null }, { preferredappointmentdaycode_formatted?: string }>;
  preferredappointmenttimecode: WebAttribute<Account_Select, { preferredappointmenttimecode: account_preferredappointmenttimecode | null }, { preferredappointmenttimecode_formatted?: string }>;
  preferredcontactmethodcode: WebAttribute<Account_Select, { preferredcontactmethodcode: account_preferredcontactmethodcode | null }, { preferredcontactmethodcode_formatted?: string }>;
  preferredequipmentid_guid: WebAttribute<Account_Select, { preferredequipmentid_guid: string | null }, { preferredequipmentid_formatted?: string }>;
  preferredserviceid_guid: WebAttribute<Account_Select, { preferredserviceid_guid: string | null }, { preferredserviceid_formatted?: string }>;
  preferredsystemuserid_guid: WebAttribute<Account_Select, { preferredsystemuserid_guid: string | null }, { preferredsystemuserid_formatted?: string }>;
  primarycontactid_guid: WebAttribute<Account_Select, { primarycontactid_guid: string | null }, { primarycontactid_formatted?: string }>;
  primarysatoriid: WebAttribute<Account_Select, { primarysatoriid: string | null }, {  }>;
  primarytwitterid: WebAttribute<Account_Select, { primarytwitterid: string | null }, {  }>;
  processid: WebAttribute<Account_Select, { processid: string | null }, {  }>;
  revenue: WebAttribute<Account_Select, { revenue: number | null; transactioncurrencyid_guid: string | null }, { revenue_formatted?: string; transactioncurrencyid_formatted?: string }>;
  revenue_base: WebAttribute<Account_Select, { revenue_base: number | null; transactioncurrencyid_guid: string | null }, { revenue_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  sharesoutstanding: WebAttribute<Account_Select, { sharesoutstanding: number | null }, {  }>;
  shippingmethodcode: WebAttribute<Account_Select, { shippingmethodcode: account_shippingmethodcode | null }, { shippingmethodcode_formatted?: string }>;
  sic: WebAttribute<Account_Select, { sic: string | null }, {  }>;
  slaid_guid: WebAttribute<Account_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Account_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  stageid: WebAttribute<Account_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Account_Select, { statecode: account_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Account_Select, { statuscode: account_statuscode | null }, { statuscode_formatted?: string }>;
  stockexchange: WebAttribute<Account_Select, { stockexchange: string | null }, {  }>;
  teamsfollowed: WebAttribute<Account_Select, { teamsfollowed: number | null }, {  }>;
  telephone1: WebAttribute<Account_Select, { telephone1: string | null }, {  }>;
  telephone2: WebAttribute<Account_Select, { telephone2: string | null }, {  }>;
  telephone3: WebAttribute<Account_Select, { telephone3: string | null }, {  }>;
  territorycode: WebAttribute<Account_Select, { territorycode: account_territorycode | null }, { territorycode_formatted?: string }>;
  territoryid_guid: WebAttribute<Account_Select, { territoryid_guid: string | null }, { territoryid_formatted?: string }>;
  tickersymbol: WebAttribute<Account_Select, { tickersymbol: string | null }, {  }>;
  timespentbymeonemailandmeetings: WebAttribute<Account_Select, { timespentbymeonemailandmeetings: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Account_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Account_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Account_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Account_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Account_Select, { versionnumber: number | null }, {  }>;
  websiteurl: WebAttribute<Account_Select, { websiteurl: string | null }, {  }>;
}
interface Account_Filter {
  accountcategorycode: account_accountcategorycode;
  accountclassificationcode: account_accountclassificationcode;
  accountid: XQW.Guid;
  accountnumber: string;
  accountratingcode: account_accountratingcode;
  address1_addressid: XQW.Guid;
  address1_addresstypecode: account_address1_addresstypecode;
  address1_city: string;
  address1_composite: string;
  address1_country: string;
  address1_county: string;
  address1_fax: string;
  address1_freighttermscode: account_address1_freighttermscode;
  address1_latitude: number;
  address1_line1: string;
  address1_line2: string;
  address1_line3: string;
  address1_longitude: number;
  address1_name: string;
  address1_postalcode: string;
  address1_postofficebox: string;
  address1_primarycontactname: string;
  address1_shippingmethodcode: account_address1_shippingmethodcode;
  address1_stateorprovince: string;
  address1_telephone1: string;
  address1_telephone2: string;
  address1_telephone3: string;
  address1_upszone: string;
  address1_utcoffset: number;
  address2_addressid: XQW.Guid;
  address2_addresstypecode: account_address2_addresstypecode;
  address2_city: string;
  address2_composite: string;
  address2_country: string;
  address2_county: string;
  address2_fax: string;
  address2_freighttermscode: account_address2_freighttermscode;
  address2_latitude: number;
  address2_line1: string;
  address2_line2: string;
  address2_line3: string;
  address2_longitude: number;
  address2_name: string;
  address2_postalcode: string;
  address2_postofficebox: string;
  address2_primarycontactname: string;
  address2_shippingmethodcode: account_address2_shippingmethodcode;
  address2_stateorprovince: string;
  address2_telephone1: string;
  address2_telephone2: string;
  address2_telephone3: string;
  address2_upszone: string;
  address2_utcoffset: number;
  aging30: number;
  aging30_base: number;
  aging60: number;
  aging60_base: number;
  aging90: number;
  aging90_base: number;
  businesstypecode: account_businesstypecode;
  createdby_guid: XQW.Guid;
  createdbyexternalparty_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  creditlimit: number;
  creditlimit_base: number;
  creditonhold: boolean;
  customersizecode: account_customersizecode;
  customertypecode: account_customertypecode;
  defaultpricelevelid_guid: XQW.Guid;
  description: string;
  donotbulkemail: boolean;
  donotbulkpostalmail: boolean;
  donotemail: boolean;
  donotfax: boolean;
  donotphone: boolean;
  donotpostalmail: boolean;
  donotsendmm: boolean;
  emailaddress1: string;
  emailaddress2: string;
  emailaddress3: string;
  entityimageid: XQW.Guid;
  exchangerate: any;
  fax: string;
  followemail: boolean;
  ftpsiteurl: string;
  importsequencenumber: number;
  industrycode: account_industrycode;
  isprivate: boolean;
  lastonholdtime: Date;
  lastusedincampaign: Date;
  marketcap: number;
  marketcap_base: number;
  marketingonly: boolean;
  masterid_guid: XQW.Guid;
  merged: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedbyexternalparty_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  numberofemployees: number;
  onholdtime: number;
  opendeals: number;
  opendeals_date: Date;
  opendeals_state: number;
  openrevenue: number;
  openrevenue_base: number;
  openrevenue_date: Date;
  openrevenue_state: number;
  originatingleadid_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  ownershipcode: account_ownershipcode;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  parentaccountid_guid: XQW.Guid;
  participatesinworkflow: boolean;
  paymenttermscode: account_paymenttermscode;
  preferredappointmentdaycode: account_preferredappointmentdaycode;
  preferredappointmenttimecode: account_preferredappointmenttimecode;
  preferredcontactmethodcode: account_preferredcontactmethodcode;
  preferredequipmentid_guid: XQW.Guid;
  preferredserviceid_guid: XQW.Guid;
  preferredsystemuserid_guid: XQW.Guid;
  primarycontactid_guid: XQW.Guid;
  primarysatoriid: string;
  primarytwitterid: string;
  processid: XQW.Guid;
  revenue: number;
  revenue_base: number;
  sharesoutstanding: number;
  shippingmethodcode: account_shippingmethodcode;
  sic: string;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: account_statecode;
  statuscode: account_statuscode;
  stockexchange: string;
  teamsfollowed: number;
  telephone1: string;
  telephone2: string;
  telephone3: string;
  territorycode: account_territorycode;
  territoryid_guid: XQW.Guid;
  tickersymbol: string;
  timespentbymeonemailandmeetings: string;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
  websiteurl: string;
}
interface Account_Expand {
  Account_ActivityPointers: WebExpand<Account_Expand, ActivityPointer_Select, ActivityPointer_Filter, { Account_ActivityPointers: ActivityPointer_Result[] }>;
  Account_Annotation: WebExpand<Account_Expand, Annotation_Select, Annotation_Filter, { Account_Annotation: Annotation_Result[] }>;
  Account_Appointments: WebExpand<Account_Expand, Appointment_Select, Appointment_Filter, { Account_Appointments: Appointment_Result[] }>;
  Account_AsyncOperations: WebExpand<Account_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Account_AsyncOperations: AsyncOperation_Result[] }>;
  Account_BulkDeleteFailures: WebExpand<Account_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Account_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Account_CustomerAddress: WebExpand<Account_Expand, CustomerAddress_Select, CustomerAddress_Filter, { Account_CustomerAddress: CustomerAddress_Result[] }>;
  Account_DuplicateBaseRecord: WebExpand<Account_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Account_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Account_DuplicateMatchingRecord: WebExpand<Account_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Account_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Account_Email_EmailSender: WebExpand<Account_Expand, Email_Select, Email_Filter, { Account_Email_EmailSender: Email_Result[] }>;
  Account_Email_SendersAccount: WebExpand<Account_Expand, Email_Select, Email_Filter, { Account_Email_SendersAccount: Email_Result[] }>;
  Account_Emails: WebExpand<Account_Expand, Email_Select, Email_Filter, { Account_Emails: Email_Result[] }>;
  Account_Faxes: WebExpand<Account_Expand, Fax_Select, Fax_Filter, { Account_Faxes: Fax_Result[] }>;
  Account_Letters: WebExpand<Account_Expand, Letter_Select, Letter_Filter, { Account_Letters: Letter_Result[] }>;
  Account_MailboxTrackingFolder: WebExpand<Account_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { Account_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  Account_Phonecalls: WebExpand<Account_Expand, PhoneCall_Select, PhoneCall_Filter, { Account_Phonecalls: PhoneCall_Result[] }>;
  Account_ProcessSessions: WebExpand<Account_Expand, ProcessSession_Select, ProcessSession_Filter, { Account_ProcessSessions: ProcessSession_Result[] }>;
  Account_RecurringAppointmentMasters: WebExpand<Account_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { Account_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  Account_ServiceAppointments: WebExpand<Account_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { Account_ServiceAppointments: ServiceAppointment_Result[] }>;
  Account_SharepointDocument: WebExpand<Account_Expand, SharePointDocument_Select, SharePointDocument_Filter, { Account_SharepointDocument: SharePointDocument_Result[] }>;
  Account_SharepointDocumentLocation: WebExpand<Account_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { Account_SharepointDocumentLocation: SharePointDocumentLocation_Result[] }>;
  Account_SocialActivities: WebExpand<Account_Expand, SocialActivity_Select, SocialActivity_Filter, { Account_SocialActivities: SocialActivity_Result[] }>;
  Account_SyncErrors: WebExpand<Account_Expand, SyncError_Select, SyncError_Filter, { Account_SyncErrors: SyncError_Result[] }>;
  Account_Tasks: WebExpand<Account_Expand, Task_Select, Task_Filter, { Account_Tasks: Task_Result[] }>;
  BulkOperation_Accounts: WebExpand<Account_Expand, BulkOperation_Select, BulkOperation_Filter, { BulkOperation_Accounts: BulkOperation_Result[] }>;
  CampaignActivity_Accounts: WebExpand<Account_Expand, CampaignActivity_Select, CampaignActivity_Filter, { CampaignActivity_Accounts: CampaignActivity_Result[] }>;
  CreatedAccount_BulkOperationLogs2: WebExpand<Account_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { CreatedAccount_BulkOperationLogs2: BulkOperationLog_Result[] }>;
  CreatedByExternalParty: WebExpand<Account_Expand, ExternalParty_Select, ExternalParty_Filter, { CreatedByExternalParty: ExternalParty_Result }>;
  ModifiedByExternalParty: WebExpand<Account_Expand, ExternalParty_Select, ExternalParty_Filter, { ModifiedByExternalParty: ExternalParty_Result }>;
  SocialActivity_PostAuthorAccount_accounts: WebExpand<Account_Expand, SocialActivity_Select, SocialActivity_Filter, { SocialActivity_PostAuthorAccount_accounts: SocialActivity_Result[] }>;
  SocialActivity_PostAuthor_accounts: WebExpand<Account_Expand, SocialActivity_Select, SocialActivity_Filter, { SocialActivity_PostAuthor_accounts: SocialActivity_Result[] }>;
  Socialprofile_customer_accounts: WebExpand<Account_Expand, SocialProfile_Select, SocialProfile_Filter, { Socialprofile_customer_accounts: SocialProfile_Result[] }>;
  SourceAccount_BulkOperationLogs: WebExpand<Account_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { SourceAccount_BulkOperationLogs: BulkOperationLog_Result[] }>;
  account_BulkOperations: WebExpand<Account_Expand, BulkOperation_Select, BulkOperation_Filter, { account_BulkOperations: BulkOperation_Result[] }>;
  account_CampaignResponses: WebExpand<Account_Expand, CampaignResponse_Select, CampaignResponse_Filter, { account_CampaignResponses: CampaignResponse_Result[] }>;
  account_IncidentResolutions: WebExpand<Account_Expand, IncidentResolution_Select, IncidentResolution_Filter, { account_IncidentResolutions: IncidentResolution_Result[] }>;
  account_OpportunityCloses: WebExpand<Account_Expand, OpportunityClose_Select, OpportunityClose_Filter, { account_OpportunityCloses: OpportunityClose_Result[] }>;
  account_OrderCloses: WebExpand<Account_Expand, OrderClose_Select, OrderClose_Filter, { account_OrderCloses: OrderClose_Result[] }>;
  account_PostFollows: WebExpand<Account_Expand, PostFollow_Select, PostFollow_Filter, { account_PostFollows: PostFollow_Result[] }>;
  account_PostRegardings: WebExpand<Account_Expand, PostRegarding_Select, PostRegarding_Filter, { account_PostRegardings: PostRegarding_Result[] }>;
  account_PostRoles: WebExpand<Account_Expand, PostRole_Select, PostRole_Filter, { account_PostRoles: PostRole_Result[] }>;
  account_QuoteCloses: WebExpand<Account_Expand, QuoteClose_Select, QuoteClose_Filter, { account_QuoteCloses: QuoteClose_Result[] }>;
  account_actioncard: WebExpand<Account_Expand, ActionCard_Select, ActionCard_Filter, { account_actioncard: ActionCard_Result[] }>;
  account_activity_parties: WebExpand<Account_Expand, ActivityParty_Select, ActivityParty_Filter, { account_activity_parties: ActivityParty_Result[] }>;
  account_awcnpd_feedbacks: WebExpand<Account_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { account_awcnpd_feedbacks: awcnpd_feedback_Result[] }>;
  account_bookableresource_AccountId: WebExpand<Account_Expand, BookableResource_Select, BookableResource_Filter, { account_bookableresource_AccountId: BookableResource_Result[] }>;
  account_connections1: WebExpand<Account_Expand, Connection_Select, Connection_Filter, { account_connections1: Connection_Result[] }>;
  account_connections2: WebExpand<Account_Expand, Connection_Select, Connection_Filter, { account_connections2: Connection_Result[] }>;
  account_customer_opportunity_roles: WebExpand<Account_Expand, CustomerOpportunityRole_Select, CustomerOpportunityRole_Filter, { account_customer_opportunity_roles: CustomerOpportunityRole_Result[] }>;
  account_customer_relationship_customer: WebExpand<Account_Expand, CustomerRelationship_Select, CustomerRelationship_Filter, { account_customer_relationship_customer: CustomerRelationship_Result[] }>;
  account_customer_relationship_partner: WebExpand<Account_Expand, CustomerRelationship_Select, CustomerRelationship_Filter, { account_customer_relationship_partner: CustomerRelationship_Result[] }>;
  account_entitlement_Account: WebExpand<Account_Expand, Entitlement_Select, Entitlement_Filter, { account_entitlement_Account: Entitlement_Result[] }>;
  account_entitlement_Customer: WebExpand<Account_Expand, Entitlement_Select, Entitlement_Filter, { account_entitlement_Customer: Entitlement_Result[] }>;
  account_master_account: WebExpand<Account_Expand, Account_Select, Account_Filter, { account_master_account: Account_Result[] }>;
  account_parent_account: WebExpand<Account_Expand, Account_Select, Account_Filter, { account_parent_account: Account_Result[] }>;
  account_principalobjectattributeaccess: WebExpand<Account_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { account_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  accountleads_association: WebExpand<Account_Expand, Lead_Select, Lead_Filter, { accountleads_association: Lead_Result[] }>;
  contact_customer_accounts: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { contact_customer_accounts: Contact_Result[] }>;
  contract_billingcustomer_accounts: WebExpand<Account_Expand, Contract_Select, Contract_Filter, { contract_billingcustomer_accounts: Contract_Result[] }>;
  contract_customer_accounts: WebExpand<Account_Expand, Contract_Select, Contract_Filter, { contract_customer_accounts: Contract_Result[] }>;
  contractlineitem_customer_accounts: WebExpand<Account_Expand, ContractDetail_Select, ContractDetail_Filter, { contractlineitem_customer_accounts: ContractDetail_Result[] }>;
  createdby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  defaultpricelevelid: WebExpand<Account_Expand, PriceLevel_Select, PriceLevel_Filter, { defaultpricelevelid: PriceLevel_Result }>;
  entityimageid_imagedescriptor: WebExpand<Account_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  incident_customer_accounts: WebExpand<Account_Expand, Incident_Select, Incident_Filter, { incident_customer_accounts: Incident_Result[] }>;
  invoice_customer_accounts: WebExpand<Account_Expand, Invoice_Select, Invoice_Filter, { invoice_customer_accounts: Invoice_Result[] }>;
  lead_customer_accounts: WebExpand<Account_Expand, Lead_Select, Lead_Filter, { lead_customer_accounts: Lead_Result[] }>;
  lead_parent_account: WebExpand<Account_Expand, Lead_Select, Lead_Filter, { lead_parent_account: Lead_Result[] }>;
  listaccount_association: WebExpand<Account_Expand, List_Select, List_Filter, { listaccount_association: List_Result[] }>;
  masterid: WebExpand<Account_Expand, Account_Select, Account_Filter, { masterid: Account_Result }>;
  modifiedby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_playbookinstance_account: WebExpand<Account_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { msdyn_playbookinstance_account: msdyn_playbookinstance_Result[] }>;
  opportunity_customer_accounts: WebExpand<Account_Expand, Opportunity_Select, Opportunity_Filter, { opportunity_customer_accounts: Opportunity_Result[] }>;
  opportunity_parent_account: WebExpand<Account_Expand, Opportunity_Select, Opportunity_Filter, { opportunity_parent_account: Opportunity_Result[] }>;
  order_customer_accounts: WebExpand<Account_Expand, SalesOrder_Select, SalesOrder_Filter, { order_customer_accounts: SalesOrder_Result[] }>;
  originatingleadid: WebExpand<Account_Expand, Lead_Select, Lead_Filter, { originatingleadid: Lead_Result }>;
  ownerid: WebExpand<Account_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Account_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<Account_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  parentaccountid: WebExpand<Account_Expand, Account_Select, Account_Filter, { parentaccountid: Account_Result }>;
  preferredequipmentid: WebExpand<Account_Expand, Equipment_Select, Equipment_Filter, { preferredequipmentid: Equipment_Result }>;
  preferredserviceid: WebExpand<Account_Expand, Service_Select, Service_Filter, { preferredserviceid: Service_Result }>;
  preferredsystemuserid: WebExpand<Account_Expand, SystemUser_Select, SystemUser_Filter, { preferredsystemuserid: SystemUser_Result }>;
  primarycontactid: WebExpand<Account_Expand, Contact_Select, Contact_Filter, { primarycontactid: Contact_Result }>;
  quote_customer_accounts: WebExpand<Account_Expand, Quote_Select, Quote_Filter, { quote_customer_accounts: Quote_Result[] }>;
  sla_account_sla: WebExpand<Account_Expand, SLA_Select, SLA_Filter, { sla_account_sla: SLA_Result }>;
  slainvokedid_account_sla: WebExpand<Account_Expand, SLA_Select, SLA_Filter, { slainvokedid_account_sla: SLA_Result }>;
  slakpiinstance_account: WebExpand<Account_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_account: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Account_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  territoryid: WebExpand<Account_Expand, Territory_Select, Territory_Filter, { territoryid: Territory_Result }>;
  transactioncurrencyid: WebExpand<Account_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_account: WebExpand<Account_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_account: UserEntityInstanceData_Result[] }>;
}
interface Account_FormattedResult {
  accountcategorycode_formatted?: string;
  accountclassificationcode_formatted?: string;
  accountratingcode_formatted?: string;
  address1_addresstypecode_formatted?: string;
  address1_freighttermscode_formatted?: string;
  address1_shippingmethodcode_formatted?: string;
  address2_addresstypecode_formatted?: string;
  address2_freighttermscode_formatted?: string;
  address2_shippingmethodcode_formatted?: string;
  aging30_base_formatted?: string;
  aging30_formatted?: string;
  aging60_base_formatted?: string;
  aging60_formatted?: string;
  aging90_base_formatted?: string;
  aging90_formatted?: string;
  businesstypecode_formatted?: string;
  createdby_formatted?: string;
  createdbyexternalparty_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  creditlimit_base_formatted?: string;
  creditlimit_formatted?: string;
  customersizecode_formatted?: string;
  customertypecode_formatted?: string;
  defaultpricelevelid_formatted?: string;
  industrycode_formatted?: string;
  lastonholdtime_formatted?: string;
  lastusedincampaign_formatted?: string;
  marketcap_base_formatted?: string;
  marketcap_formatted?: string;
  masterid_formatted?: string;
  modifiedby_formatted?: string;
  modifiedbyexternalparty_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  opendeals_date_formatted?: string;
  openrevenue_base_formatted?: string;
  openrevenue_date_formatted?: string;
  openrevenue_formatted?: string;
  originatingleadid_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  ownershipcode_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  parentaccountid_formatted?: string;
  paymenttermscode_formatted?: string;
  preferredappointmentdaycode_formatted?: string;
  preferredappointmenttimecode_formatted?: string;
  preferredcontactmethodcode_formatted?: string;
  preferredequipmentid_formatted?: string;
  preferredserviceid_formatted?: string;
  preferredsystemuserid_formatted?: string;
  primarycontactid_formatted?: string;
  revenue_base_formatted?: string;
  revenue_formatted?: string;
  shippingmethodcode_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  territorycode_formatted?: string;
  territoryid_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Account_Result extends Account_Base, Account_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdbyexternalparty_guid: string | null;
  createdonbehalfby_guid: string | null;
  defaultpricelevelid_guid: string | null;
  masterid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedbyexternalparty_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  originatingleadid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  parentaccountid_guid: string | null;
  preferredequipmentid_guid: string | null;
  preferredserviceid_guid: string | null;
  preferredsystemuserid_guid: string | null;
  primarycontactid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  territoryid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Account_RelatedOne {
  CreatedByExternalParty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  ModifiedByExternalParty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  defaultpricelevelid: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  masterid: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  originatingleadid: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  parentaccountid: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  preferredequipmentid: WebMappingRetrieve<Equipment_Select,Equipment_Expand,Equipment_Filter,Equipment_Fixed,Equipment_Result,Equipment_FormattedResult>;
  preferredserviceid: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  preferredsystemuserid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  primarycontactid: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  sla_account_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_account_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  territoryid: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Account_RelatedMany {
  Account_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  Account_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Account_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  Account_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Account_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Account_CustomerAddress: WebMappingRetrieve<CustomerAddress_Select,CustomerAddress_Expand,CustomerAddress_Filter,CustomerAddress_Fixed,CustomerAddress_Result,CustomerAddress_FormattedResult>;
  Account_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Account_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Account_Email_EmailSender: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Account_Email_SendersAccount: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Account_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Account_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  Account_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  Account_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  Account_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  Account_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Account_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  Account_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  Account_SharepointDocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  Account_SharepointDocumentLocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  Account_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  Account_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  Account_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  BulkOperation_Accounts: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  CampaignActivity_Accounts: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  CreatedAccount_BulkOperationLogs2: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  SocialActivity_PostAuthorAccount_accounts: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  SocialActivity_PostAuthor_accounts: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  Socialprofile_customer_accounts: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  SourceAccount_BulkOperationLogs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  account_BulkOperations: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  account_CampaignResponses: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  account_IncidentResolutions: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  account_OpportunityCloses: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  account_OrderCloses: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  account_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  account_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  account_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  account_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  account_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  account_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  account_awcnpd_feedbacks: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  account_bookableresource_AccountId: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  account_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  account_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  account_customer_opportunity_roles: WebMappingRetrieve<CustomerOpportunityRole_Select,CustomerOpportunityRole_Expand,CustomerOpportunityRole_Filter,CustomerOpportunityRole_Fixed,CustomerOpportunityRole_Result,CustomerOpportunityRole_FormattedResult>;
  account_customer_relationship_customer: WebMappingRetrieve<CustomerRelationship_Select,CustomerRelationship_Expand,CustomerRelationship_Filter,CustomerRelationship_Fixed,CustomerRelationship_Result,CustomerRelationship_FormattedResult>;
  account_customer_relationship_partner: WebMappingRetrieve<CustomerRelationship_Select,CustomerRelationship_Expand,CustomerRelationship_Filter,CustomerRelationship_Fixed,CustomerRelationship_Result,CustomerRelationship_FormattedResult>;
  account_entitlement_Account: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  account_entitlement_Customer: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  account_master_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  account_parent_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  account_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  accountleads_association: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  contact_customer_accounts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  contract_billingcustomer_accounts: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  contract_customer_accounts: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  contractlineitem_customer_accounts: WebMappingRetrieve<ContractDetail_Select,ContractDetail_Expand,ContractDetail_Filter,ContractDetail_Fixed,ContractDetail_Result,ContractDetail_FormattedResult>;
  incident_customer_accounts: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  invoice_customer_accounts: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  lead_customer_accounts: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  lead_parent_account: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  listaccount_association: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  msdyn_playbookinstance_account: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  opportunity_customer_accounts: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  opportunity_parent_account: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  order_customer_accounts: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  quote_customer_accounts: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  slakpiinstance_account: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_account: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
}
interface WebEntitiesRelated {
  accounts: WebMappingRelated<Account_RelatedOne,Account_RelatedMany>;
}
interface WebEntitiesCUDA {
  accounts: WebMappingCUDA<Account_Create,Account_Update,Account_Select>;
}
