interface ActivityPointer_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  instancetypecode?: activitypointer_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: activitypointer_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: activitypointer_statecode | null;
  statuscode?: activitypointer_statuscode | null;
  subject?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface ActivityPointer_Relationships {
  ActivityPointer_AsyncOperations?: AsyncOperation_Result[] | null;
  ActivityPointer_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  ActivityPointer_CampaignActivityItems?: CampaignActivityItem_Result[] | null;
  ActivityPointer_QueueItem?: QueueItem_Result[] | null;
  CreatedActivity_BulkOperationLogs?: BulkOperationLog_Result[] | null;
  activity_campaignresponse?: CampaignResponse_Result[] | null;
  activity_pointer_BulkOperation?: BulkOperation_Result[] | null;
  activity_pointer_BulkOperation_logs?: BulkOperationLog_Result[] | null;
  activity_pointer_activity_mime_attachment?: ActivityMimeAttachment_Result[] | null;
  activity_pointer_appointment?: Appointment_Result[] | null;
  activity_pointer_awcnpd_feedback?: awcnpd_feedback_Result[] | null;
  activity_pointer_campaignactivity?: CampaignActivity_Result[] | null;
  activity_pointer_campaignresponse?: CampaignResponse_Result[] | null;
  activity_pointer_email?: Email_Result[] | null;
  activity_pointer_email_hash?: EmailHash_Result[] | null;
  activity_pointer_fax?: Fax_Result[] | null;
  activity_pointer_incident_resolution?: IncidentResolution_Result[] | null;
  activity_pointer_letter?: Letter_Result[] | null;
  activity_pointer_opportunity_close?: OpportunityClose_Result[] | null;
  activity_pointer_order_close?: OrderClose_Result[] | null;
  activity_pointer_phonecall?: PhoneCall_Result[] | null;
  activity_pointer_quote_close?: QuoteClose_Result[] | null;
  activity_pointer_recurrencerule?: RecurrenceRule_Result[] | null;
  activity_pointer_recurringappointmentmaster?: RecurringAppointmentMaster_Result[] | null;
  activity_pointer_service_appointment?: ServiceAppointment_Result[] | null;
  activity_pointer_socialactivity?: SocialActivity_Result[] | null;
  activity_pointer_task?: Task_Result[] | null;
  activitypointer_activity_parties?: ActivityParty_Result[] | null;
  activitypointer_connections1?: Connection_Result[] | null;
  activitypointer_connections2?: Connection_Result[] | null;
  regardingobjectid_account?: Account_Result | null;
  regardingobjectid_awc_prototype?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation?: BulkOperation_Result | null;
  regardingobjectid_campaign?: Campaign_Result | null;
  regardingobjectid_campaignactivity?: CampaignActivity_Result | null;
  regardingobjectid_contact?: Contact_Result | null;
  regardingobjectid_contract?: Contract_Result | null;
  regardingobjectid_entitlement?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate?: EntitlementTemplate_Result | null;
  regardingobjectid_incident?: Incident_Result | null;
  regardingobjectid_invoice?: Invoice_Result | null;
  regardingobjectid_knowledgearticle?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum?: msdyn_PostAlbum_Result | null;
  regardingobjectid_new_interactionforemail?: InteractionForEmail_Result | null;
  regardingobjectid_opportunity?: Opportunity_Result | null;
  regardingobjectid_quote?: Quote_Result | null;
  regardingobjectid_salesorder?: SalesOrder_Result | null;
  regardingobjectid_site?: Site_Result | null;
  sla_activitypointer_sla?: SLA_Result | null;
  slainvokedid_activitypointer_sla?: SLA_Result | null;
  slakpiinstance_activitypointer?: SLAKPIInstance_Result[] | null;
}
interface ActivityPointer extends ActivityPointer_Base, ActivityPointer_Relationships {
  regardingobjectid_account_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_bind$campaignactivities?: string | null;
  regardingobjectid_contact_bind$contacts?: string | null;
  regardingobjectid_contract_bind$contracts?: string | null;
  regardingobjectid_entitlement_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_bind$incidents?: string | null;
  regardingobjectid_invoice_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
  regardingobjectid_new_interactionforemail_bind$interactionforemails?: string | null;
  regardingobjectid_opportunity_bind$opportunities?: string | null;
  regardingobjectid_quote_bind$quotes?: string | null;
  regardingobjectid_salesorder_bind$salesorders?: string | null;
  regardingobjectid_site_bind$sites?: string | null;
  serviceid_bind$services?: string | null;
  sla_activitypointer_sla_bind$slas?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface ActivityPointer_Create extends ActivityPointer {
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface ActivityPointer_Update extends ActivityPointer {
}
interface ActivityPointer_Select {
  activityadditionalparams: WebAttribute<ActivityPointer_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<ActivityPointer_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<ActivityPointer_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<ActivityPointer_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<ActivityPointer_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<ActivityPointer_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  allparties_guid: WebAttribute<ActivityPointer_Select, { allparties_guid: string | null }, { allparties_formatted?: string }>;
  community: WebAttribute<ActivityPointer_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<ActivityPointer_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<ActivityPointer_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<ActivityPointer_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<ActivityPointer_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<ActivityPointer_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<ActivityPointer_Select, { description: string | null }, {  }>;
  exchangeitemid: WebAttribute<ActivityPointer_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<ActivityPointer_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<ActivityPointer_Select, { exchangeweblink: string | null }, {  }>;
  instancetypecode: WebAttribute<ActivityPointer_Select, { instancetypecode: activitypointer_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<ActivityPointer_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<ActivityPointer_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<ActivityPointer_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<ActivityPointer_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<ActivityPointer_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<ActivityPointer_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<ActivityPointer_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<ActivityPointer_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<ActivityPointer_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<ActivityPointer_Select, { onholdtime: number | null }, {  }>;
  ownerid_guid: WebAttribute<ActivityPointer_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<ActivityPointer_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<ActivityPointer_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<ActivityPointer_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<ActivityPointer_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<ActivityPointer_Select, { prioritycode: activitypointer_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<ActivityPointer_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<ActivityPointer_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<ActivityPointer_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<ActivityPointer_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<ActivityPointer_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<ActivityPointer_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<ActivityPointer_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<ActivityPointer_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<ActivityPointer_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<ActivityPointer_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<ActivityPointer_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<ActivityPointer_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<ActivityPointer_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<ActivityPointer_Select, { statecode: activitypointer_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<ActivityPointer_Select, { statuscode: activitypointer_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<ActivityPointer_Select, { subject: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<ActivityPointer_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<ActivityPointer_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<ActivityPointer_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<ActivityPointer_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<ActivityPointer_Select, { versionnumber: number | null }, {  }>;
}
interface ActivityPointer_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  allparties_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  instancetypecode: activitypointer_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: activitypointer_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: activitypointer_statecode;
  statuscode: activitypointer_statuscode;
  subject: string;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface ActivityPointer_Expand {
  ActivityPointer_AsyncOperations: WebExpand<ActivityPointer_Expand, AsyncOperation_Select, AsyncOperation_Filter, { ActivityPointer_AsyncOperations: AsyncOperation_Result[] }>;
  ActivityPointer_BulkDeleteFailures: WebExpand<ActivityPointer_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { ActivityPointer_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  ActivityPointer_CampaignActivityItems: WebExpand<ActivityPointer_Expand, CampaignActivityItem_Select, CampaignActivityItem_Filter, { ActivityPointer_CampaignActivityItems: CampaignActivityItem_Result[] }>;
  ActivityPointer_QueueItem: WebExpand<ActivityPointer_Expand, QueueItem_Select, QueueItem_Filter, { ActivityPointer_QueueItem: QueueItem_Result[] }>;
  CreatedActivity_BulkOperationLogs: WebExpand<ActivityPointer_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { CreatedActivity_BulkOperationLogs: BulkOperationLog_Result[] }>;
  activity_campaignresponse: WebExpand<ActivityPointer_Expand, CampaignResponse_Select, CampaignResponse_Filter, { activity_campaignresponse: CampaignResponse_Result[] }>;
  activity_pointer_BulkOperation: WebExpand<ActivityPointer_Expand, BulkOperation_Select, BulkOperation_Filter, { activity_pointer_BulkOperation: BulkOperation_Result[] }>;
  activity_pointer_BulkOperation_logs: WebExpand<ActivityPointer_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { activity_pointer_BulkOperation_logs: BulkOperationLog_Result[] }>;
  activity_pointer_activity_mime_attachment: WebExpand<ActivityPointer_Expand, ActivityMimeAttachment_Select, ActivityMimeAttachment_Filter, { activity_pointer_activity_mime_attachment: ActivityMimeAttachment_Result[] }>;
  activity_pointer_appointment: WebExpand<ActivityPointer_Expand, Appointment_Select, Appointment_Filter, { activity_pointer_appointment: Appointment_Result[] }>;
  activity_pointer_awcnpd_feedback: WebExpand<ActivityPointer_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { activity_pointer_awcnpd_feedback: awcnpd_feedback_Result[] }>;
  activity_pointer_campaignactivity: WebExpand<ActivityPointer_Expand, CampaignActivity_Select, CampaignActivity_Filter, { activity_pointer_campaignactivity: CampaignActivity_Result[] }>;
  activity_pointer_campaignresponse: WebExpand<ActivityPointer_Expand, CampaignResponse_Select, CampaignResponse_Filter, { activity_pointer_campaignresponse: CampaignResponse_Result[] }>;
  activity_pointer_email: WebExpand<ActivityPointer_Expand, Email_Select, Email_Filter, { activity_pointer_email: Email_Result[] }>;
  activity_pointer_email_hash: WebExpand<ActivityPointer_Expand, EmailHash_Select, EmailHash_Filter, { activity_pointer_email_hash: EmailHash_Result[] }>;
  activity_pointer_fax: WebExpand<ActivityPointer_Expand, Fax_Select, Fax_Filter, { activity_pointer_fax: Fax_Result[] }>;
  activity_pointer_incident_resolution: WebExpand<ActivityPointer_Expand, IncidentResolution_Select, IncidentResolution_Filter, { activity_pointer_incident_resolution: IncidentResolution_Result[] }>;
  activity_pointer_letter: WebExpand<ActivityPointer_Expand, Letter_Select, Letter_Filter, { activity_pointer_letter: Letter_Result[] }>;
  activity_pointer_opportunity_close: WebExpand<ActivityPointer_Expand, OpportunityClose_Select, OpportunityClose_Filter, { activity_pointer_opportunity_close: OpportunityClose_Result[] }>;
  activity_pointer_order_close: WebExpand<ActivityPointer_Expand, OrderClose_Select, OrderClose_Filter, { activity_pointer_order_close: OrderClose_Result[] }>;
  activity_pointer_phonecall: WebExpand<ActivityPointer_Expand, PhoneCall_Select, PhoneCall_Filter, { activity_pointer_phonecall: PhoneCall_Result[] }>;
  activity_pointer_quote_close: WebExpand<ActivityPointer_Expand, QuoteClose_Select, QuoteClose_Filter, { activity_pointer_quote_close: QuoteClose_Result[] }>;
  activity_pointer_recurrencerule: WebExpand<ActivityPointer_Expand, RecurrenceRule_Select, RecurrenceRule_Filter, { activity_pointer_recurrencerule: RecurrenceRule_Result[] }>;
  activity_pointer_recurringappointmentmaster: WebExpand<ActivityPointer_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { activity_pointer_recurringappointmentmaster: RecurringAppointmentMaster_Result[] }>;
  activity_pointer_service_appointment: WebExpand<ActivityPointer_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { activity_pointer_service_appointment: ServiceAppointment_Result[] }>;
  activity_pointer_socialactivity: WebExpand<ActivityPointer_Expand, SocialActivity_Select, SocialActivity_Filter, { activity_pointer_socialactivity: SocialActivity_Result[] }>;
  activity_pointer_task: WebExpand<ActivityPointer_Expand, Task_Select, Task_Filter, { activity_pointer_task: Task_Result[] }>;
  activitypointer_activity_parties: WebExpand<ActivityPointer_Expand, ActivityParty_Select, ActivityParty_Filter, { activitypointer_activity_parties: ActivityParty_Result[] }>;
  activitypointer_connections1: WebExpand<ActivityPointer_Expand, Connection_Select, Connection_Filter, { activitypointer_connections1: Connection_Result[] }>;
  activitypointer_connections2: WebExpand<ActivityPointer_Expand, Connection_Select, Connection_Filter, { activitypointer_connections2: Connection_Result[] }>;
  createdby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  ownerid: WebExpand<ActivityPointer_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<ActivityPointer_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<ActivityPointer_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<ActivityPointer_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  regardingobjectid_account: WebExpand<ActivityPointer_Expand, Account_Select, Account_Filter, { regardingobjectid_account: Account_Result }>;
  regardingobjectid_awc_prototype: WebExpand<ActivityPointer_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea: WebExpand<ActivityPointer_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype: WebExpand<ActivityPointer_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking: WebExpand<ActivityPointer_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader: WebExpand<ActivityPointer_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation: WebExpand<ActivityPointer_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation: BulkOperation_Result }>;
  regardingobjectid_campaign: WebExpand<ActivityPointer_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign: Campaign_Result }>;
  regardingobjectid_campaignactivity: WebExpand<ActivityPointer_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity: CampaignActivity_Result }>;
  regardingobjectid_contact: WebExpand<ActivityPointer_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact: Contact_Result }>;
  regardingobjectid_contract: WebExpand<ActivityPointer_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract: Contract_Result }>;
  regardingobjectid_entitlement: WebExpand<ActivityPointer_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate: WebExpand<ActivityPointer_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate: EntitlementTemplate_Result }>;
  regardingobjectid_incident: WebExpand<ActivityPointer_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident: Incident_Result }>;
  regardingobjectid_invoice: WebExpand<ActivityPointer_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice: Invoice_Result }>;
  regardingobjectid_knowledgearticle: WebExpand<ActivityPointer_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord: WebExpand<ActivityPointer_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead: WebExpand<ActivityPointer_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance: WebExpand<ActivityPointer_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum: WebExpand<ActivityPointer_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum: msdyn_PostAlbum_Result }>;
  regardingobjectid_new_interactionforemail: WebExpand<ActivityPointer_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { regardingobjectid_new_interactionforemail: InteractionForEmail_Result }>;
  regardingobjectid_opportunity: WebExpand<ActivityPointer_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity: Opportunity_Result }>;
  regardingobjectid_quote: WebExpand<ActivityPointer_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote: Quote_Result }>;
  regardingobjectid_salesorder: WebExpand<ActivityPointer_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder: SalesOrder_Result }>;
  regardingobjectid_site: WebExpand<ActivityPointer_Expand, Site_Select, Site_Filter, { regardingobjectid_site: Site_Result }>;
  sendermailboxid: WebExpand<ActivityPointer_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid: Mailbox_Result }>;
  serviceid: WebExpand<ActivityPointer_Expand, Service_Select, Service_Filter, { serviceid: Service_Result }>;
  sla_activitypointer_sla: WebExpand<ActivityPointer_Expand, SLA_Select, SLA_Filter, { sla_activitypointer_sla: SLA_Result }>;
  slainvokedid_activitypointer_sla: WebExpand<ActivityPointer_Expand, SLA_Select, SLA_Filter, { slainvokedid_activitypointer_sla: SLA_Result }>;
  slakpiinstance_activitypointer: WebExpand<ActivityPointer_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_activitypointer: SLAKPIInstance_Result[] }>;
  transactioncurrencyid: WebExpand<ActivityPointer_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
}
interface ActivityPointer_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  allparties_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface ActivityPointer_Result extends ActivityPointer_Base, ActivityPointer_Relationships {
  "@odata.etag": string;
  allparties_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface ActivityPointer_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_new_interactionforemail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  regardingobjectid_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  sendermailboxid: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  serviceid: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_activitypointer_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_activitypointer_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface ActivityPointer_RelatedMany {
  ActivityPointer_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  ActivityPointer_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  ActivityPointer_CampaignActivityItems: WebMappingRetrieve<CampaignActivityItem_Select,CampaignActivityItem_Expand,CampaignActivityItem_Filter,CampaignActivityItem_Fixed,CampaignActivityItem_Result,CampaignActivityItem_FormattedResult>;
  ActivityPointer_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  CreatedActivity_BulkOperationLogs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  activity_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  activity_pointer_BulkOperation: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  activity_pointer_BulkOperation_logs: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  activity_pointer_activity_mime_attachment: WebMappingRetrieve<ActivityMimeAttachment_Select,ActivityMimeAttachment_Expand,ActivityMimeAttachment_Filter,ActivityMimeAttachment_Fixed,ActivityMimeAttachment_Result,ActivityMimeAttachment_FormattedResult>;
  activity_pointer_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  activity_pointer_awcnpd_feedback: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  activity_pointer_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  activity_pointer_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  activity_pointer_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  activity_pointer_email_hash: WebMappingRetrieve<EmailHash_Select,EmailHash_Expand,EmailHash_Filter,EmailHash_Fixed,EmailHash_Result,EmailHash_FormattedResult>;
  activity_pointer_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  activity_pointer_incident_resolution: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  activity_pointer_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  activity_pointer_opportunity_close: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  activity_pointer_order_close: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  activity_pointer_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  activity_pointer_quote_close: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  activity_pointer_recurrencerule: WebMappingRetrieve<RecurrenceRule_Select,RecurrenceRule_Expand,RecurrenceRule_Filter,RecurrenceRule_Fixed,RecurrenceRule_Result,RecurrenceRule_FormattedResult>;
  activity_pointer_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  activity_pointer_service_appointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  activity_pointer_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  activity_pointer_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  activitypointer_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  activitypointer_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  activitypointer_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  slakpiinstance_activitypointer: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
}
interface WebEntitiesRetrieve {
  activitypointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
}
interface WebEntitiesRelated {
  activitypointers: WebMappingRelated<ActivityPointer_RelatedOne,ActivityPointer_RelatedMany>;
}
interface WebEntitiesCUDA {
  activitypointers: WebMappingCUDA<ActivityPointer_Create,ActivityPointer_Update,ActivityPointer_Select>;
}
