interface awcnpd_feedback_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  awcnpd_satisfactionrating?: awcnpd_rating | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: awcnpd_feedback_instancetypecode | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: awcnpd_feedback_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: awcnpd_feedback_statecode | null;
  statuscode?: awcnpd_feedback_statuscode | null;
  subject?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface awcnpd_feedback_Relationships {
  CampaignResponse_awcnpd_feedbacks?: CampaignResponse_Result[] | null;
  activityid_awcnpd_feedback?: ActivityPointer_Result | null;
  awcnpd_feedback_ActionCards?: ActionCard_Result[] | null;
  awcnpd_feedback_Annotations?: Annotation_Result[] | null;
  awcnpd_feedback_AsyncOperations?: AsyncOperation_Result[] | null;
  awcnpd_feedback_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  awcnpd_feedback_Feedback?: Feedback_Result[] | null;
  awcnpd_feedback_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  awcnpd_feedback_PrincipalObjectAttributeAccesses?: PrincipalObjectAttributeAccess_Result[] | null;
  awcnpd_feedback_ProcessSession?: ProcessSession_Result[] | null;
  awcnpd_feedback_QueueItems?: QueueItem_Result[] | null;
  awcnpd_feedback_SyncErrors?: SyncError_Result[] | null;
  awcnpd_feedback_UserEntityInstanceDatas?: UserEntityInstanceData_Result[] | null;
  awcnpd_feedback_activity_parties?: ActivityParty_Result[] | null;
  awcnpd_feedback_connections1?: Connection_Result[] | null;
  awcnpd_feedback_connections2?: Connection_Result[] | null;
  createdby_awcnpd_feedback?: SystemUser_Result | null;
  createdonbehalfby_awcnpd_feedback?: SystemUser_Result | null;
  modifiedby_awcnpd_feedback?: SystemUser_Result | null;
  modifiedonbehalfby_awcnpd_feedback?: SystemUser_Result | null;
  ownerid_awcnpd_feedback?: Team_Result | null;
  ownerid_awcnpd_feedback1?: SystemUser_Result | null;
  owningbusinessunit_awcnpd_feedback?: BusinessUnit_Result | null;
  owningteam_awcnpd_feedback?: Team_Result | null;
  owninguser_awcnpd_feedback?: SystemUser_Result | null;
  regardingobjectid_account_awcnpd_feedback?: Account_Result | null;
  regardingobjectid_awc_prototype_awcnpd_feedback?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_awcnpd_feedback?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_awcnpd_feedback?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_awcnpd_feedback?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_awcnpd_feedback?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_awcnpd_feedback?: BulkOperation_Result | null;
  regardingobjectid_campaign_awcnpd_feedback?: Campaign_Result | null;
  regardingobjectid_campaignactivity_awcnpd_feedback?: CampaignActivity_Result | null;
  regardingobjectid_contact_awcnpd_feedback?: Contact_Result | null;
  regardingobjectid_contract_awcnpd_feedback?: Contract_Result | null;
  regardingobjectid_entitlement_awcnpd_feedback?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_awcnpd_feedback?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_awcnpd_feedback?: Incident_Result | null;
  regardingobjectid_invoice_awcnpd_feedback?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_awcnpd_feedback?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_awcnpd_feedback?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_awcnpd_feedback?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_awcnpd_feedback?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_awcnpd_feedback?: msdyn_PostAlbum_Result | null;
  regardingobjectid_new_interactionforemail_awcnpd_feedback?: InteractionForEmail_Result | null;
  regardingobjectid_opportunity_awcnpd_feedback?: Opportunity_Result | null;
  regardingobjectid_quote_awcnpd_feedback?: Quote_Result | null;
  regardingobjectid_salesorder_awcnpd_feedback?: SalesOrder_Result | null;
  regardingobjectid_site_awcnpd_feedback?: Site_Result | null;
  sendermailboxid_awcnpd_feedback?: Mailbox_Result | null;
  serviceid_awcnpd_feedback?: Service_Result | null;
  sla_activitypointer_sla_awcnpd_feedback?: SLA_Result | null;
  slainvokedid_activitypointer_sla_awcnpd_feedback?: SLA_Result | null;
  stageid_awcnpd_feedback?: ProcessStage_Result | null;
  transactioncurrencyid_awcnpd_feedback?: TransactionCurrency_Result | null;
}
interface awcnpd_feedback extends awcnpd_feedback_Base, awcnpd_feedback_Relationships {
  ownerid_awcnpd_feedback_bind$systemusers?: string | null;
  ownerid_awcnpd_feedback_bind$teams?: string | null;
  regardingobjectid_account_awcnpd_feedback_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_awcnpd_feedback_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_awcnpd_feedback_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_awcnpd_feedback_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_awcnpd_feedback_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_awcnpd_feedback_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_awcnpd_feedback_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_awcnpd_feedback_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_awcnpd_feedback_bind$campaignactivities?: string | null;
  regardingobjectid_contact_awcnpd_feedback_bind$contacts?: string | null;
  regardingobjectid_contract_awcnpd_feedback_bind$contracts?: string | null;
  regardingobjectid_entitlement_awcnpd_feedback_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_awcnpd_feedback_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_awcnpd_feedback_bind$incidents?: string | null;
  regardingobjectid_invoice_awcnpd_feedback_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_awcnpd_feedback_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_awcnpd_feedback_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_awcnpd_feedback_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_awcnpd_feedback_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_awcnpd_feedback_bind$msdyn_postalbums?: string | null;
  regardingobjectid_new_interactionforemail_awcnpd_feedback_bind$interactionforemails?: string | null;
  regardingobjectid_opportunity_awcnpd_feedback_bind$opportunities?: string | null;
  regardingobjectid_quote_awcnpd_feedback_bind$quotes?: string | null;
  regardingobjectid_salesorder_awcnpd_feedback_bind$salesorders?: string | null;
  regardingobjectid_site_awcnpd_feedback_bind$sites?: string | null;
  serviceid_awcnpd_feedback_bind$services?: string | null;
  sla_activitypointer_sla_awcnpd_feedback_bind$slas?: string | null;
  stageid_awcnpd_feedback_bind$processstages?: string | null;
  transactioncurrencyid_awcnpd_feedback_bind$transactioncurrencies?: string | null;
}
interface awcnpd_feedback_Create extends awcnpd_feedback {
  activityid_awcnpd_feedback_bind$activitypointers?: string | null;
}
interface awcnpd_feedback_Update extends awcnpd_feedback {
}
interface awcnpd_feedback_Select {
  activityadditionalparams: WebAttribute<awcnpd_feedback_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<awcnpd_feedback_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<awcnpd_feedback_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<awcnpd_feedback_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<awcnpd_feedback_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<awcnpd_feedback_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  awcnpd_satisfactionrating: WebAttribute<awcnpd_feedback_Select, { awcnpd_satisfactionrating: awcnpd_rating | null }, { awcnpd_satisfactionrating_formatted?: string }>;
  bcc_guid: WebAttribute<awcnpd_feedback_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  cc_guid: WebAttribute<awcnpd_feedback_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  community: WebAttribute<awcnpd_feedback_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<awcnpd_feedback_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<awcnpd_feedback_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<awcnpd_feedback_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customers_guid: WebAttribute<awcnpd_feedback_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<awcnpd_feedback_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<awcnpd_feedback_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<awcnpd_feedback_Select, { description: string | null }, {  }>;
  exchangeitemid: WebAttribute<awcnpd_feedback_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<awcnpd_feedback_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<awcnpd_feedback_Select, { exchangeweblink: string | null }, {  }>;
  from_guid: WebAttribute<awcnpd_feedback_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<awcnpd_feedback_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<awcnpd_feedback_Select, { instancetypecode: awcnpd_feedback_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isbilled: WebAttribute<awcnpd_feedback_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<awcnpd_feedback_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<awcnpd_feedback_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<awcnpd_feedback_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<awcnpd_feedback_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<awcnpd_feedback_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<awcnpd_feedback_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<awcnpd_feedback_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<awcnpd_feedback_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<awcnpd_feedback_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<awcnpd_feedback_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<awcnpd_feedback_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  overriddencreatedon: WebAttribute<awcnpd_feedback_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<awcnpd_feedback_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<awcnpd_feedback_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<awcnpd_feedback_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<awcnpd_feedback_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  partners_guid: WebAttribute<awcnpd_feedback_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<awcnpd_feedback_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<awcnpd_feedback_Select, { prioritycode: awcnpd_feedback_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<awcnpd_feedback_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<awcnpd_feedback_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<awcnpd_feedback_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resources_guid: WebAttribute<awcnpd_feedback_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<awcnpd_feedback_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<awcnpd_feedback_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<awcnpd_feedback_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<awcnpd_feedback_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<awcnpd_feedback_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<awcnpd_feedback_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<awcnpd_feedback_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<awcnpd_feedback_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<awcnpd_feedback_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<awcnpd_feedback_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<awcnpd_feedback_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<awcnpd_feedback_Select, { statecode: awcnpd_feedback_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<awcnpd_feedback_Select, { statuscode: awcnpd_feedback_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<awcnpd_feedback_Select, { subject: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<awcnpd_feedback_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<awcnpd_feedback_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<awcnpd_feedback_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<awcnpd_feedback_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<awcnpd_feedback_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<awcnpd_feedback_Select, { versionnumber: number | null }, {  }>;
}
interface awcnpd_feedback_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  awcnpd_satisfactionrating: awcnpd_rating;
  bcc_guid: XQW.Guid;
  cc_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  instancetypecode: awcnpd_feedback_instancetypecode;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: awcnpd_feedback_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: awcnpd_feedback_statecode;
  statuscode: awcnpd_feedback_statuscode;
  subject: string;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface awcnpd_feedback_Expand {
  CampaignResponse_awcnpd_feedbacks: WebExpand<awcnpd_feedback_Expand, CampaignResponse_Select, CampaignResponse_Filter, { CampaignResponse_awcnpd_feedbacks: CampaignResponse_Result[] }>;
  activityid_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_awcnpd_feedback: ActivityPointer_Result }>;
  awcnpd_feedback_ActionCards: WebExpand<awcnpd_feedback_Expand, ActionCard_Select, ActionCard_Filter, { awcnpd_feedback_ActionCards: ActionCard_Result[] }>;
  awcnpd_feedback_Annotations: WebExpand<awcnpd_feedback_Expand, Annotation_Select, Annotation_Filter, { awcnpd_feedback_Annotations: Annotation_Result[] }>;
  awcnpd_feedback_AsyncOperations: WebExpand<awcnpd_feedback_Expand, AsyncOperation_Select, AsyncOperation_Filter, { awcnpd_feedback_AsyncOperations: AsyncOperation_Result[] }>;
  awcnpd_feedback_BulkDeleteFailures: WebExpand<awcnpd_feedback_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { awcnpd_feedback_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  awcnpd_feedback_Feedback: WebExpand<awcnpd_feedback_Expand, Feedback_Select, Feedback_Filter, { awcnpd_feedback_Feedback: Feedback_Result[] }>;
  awcnpd_feedback_MailboxTrackingFolders: WebExpand<awcnpd_feedback_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { awcnpd_feedback_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  awcnpd_feedback_PrincipalObjectAttributeAccesses: WebExpand<awcnpd_feedback_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { awcnpd_feedback_PrincipalObjectAttributeAccesses: PrincipalObjectAttributeAccess_Result[] }>;
  awcnpd_feedback_ProcessSession: WebExpand<awcnpd_feedback_Expand, ProcessSession_Select, ProcessSession_Filter, { awcnpd_feedback_ProcessSession: ProcessSession_Result[] }>;
  awcnpd_feedback_QueueItems: WebExpand<awcnpd_feedback_Expand, QueueItem_Select, QueueItem_Filter, { awcnpd_feedback_QueueItems: QueueItem_Result[] }>;
  awcnpd_feedback_SyncErrors: WebExpand<awcnpd_feedback_Expand, SyncError_Select, SyncError_Filter, { awcnpd_feedback_SyncErrors: SyncError_Result[] }>;
  awcnpd_feedback_UserEntityInstanceDatas: WebExpand<awcnpd_feedback_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { awcnpd_feedback_UserEntityInstanceDatas: UserEntityInstanceData_Result[] }>;
  awcnpd_feedback_activity_parties: WebExpand<awcnpd_feedback_Expand, ActivityParty_Select, ActivityParty_Filter, { awcnpd_feedback_activity_parties: ActivityParty_Result[] }>;
  awcnpd_feedback_connections1: WebExpand<awcnpd_feedback_Expand, Connection_Select, Connection_Filter, { awcnpd_feedback_connections1: Connection_Result[] }>;
  awcnpd_feedback_connections2: WebExpand<awcnpd_feedback_Expand, Connection_Select, Connection_Filter, { awcnpd_feedback_connections2: Connection_Result[] }>;
  createdby_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SystemUser_Select, SystemUser_Filter, { createdby_awcnpd_feedback: SystemUser_Result }>;
  createdonbehalfby_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_awcnpd_feedback: SystemUser_Result }>;
  modifiedby_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_awcnpd_feedback: SystemUser_Result }>;
  modifiedonbehalfby_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_awcnpd_feedback: SystemUser_Result }>;
  ownerid_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_awcnpd_feedback: SystemUser_Result } & { ownerid_awcnpd_feedback: Team_Result }>;
  owningbusinessunit_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_awcnpd_feedback: BusinessUnit_Result }>;
  owningteam_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Team_Select, Team_Filter, { owningteam_awcnpd_feedback: Team_Result }>;
  owninguser_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_awcnpd_feedback: SystemUser_Result }>;
  regardingobjectid_account_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Account_Select, Account_Filter, { regardingobjectid_account_awcnpd_feedback: Account_Result }>;
  regardingobjectid_awc_prototype_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_awcnpd_feedback: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_awcnpd_feedback: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_awcnpd_feedback: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_awcnpd_feedback: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_awcnpd_feedback: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_awcnpd_feedback: BulkOperation_Result }>;
  regardingobjectid_campaign_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_awcnpd_feedback: Campaign_Result }>;
  regardingobjectid_campaignactivity_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_awcnpd_feedback: CampaignActivity_Result }>;
  regardingobjectid_contact_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_awcnpd_feedback: Contact_Result }>;
  regardingobjectid_contract_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_awcnpd_feedback: Contract_Result }>;
  regardingobjectid_entitlement_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_awcnpd_feedback: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_awcnpd_feedback: EntitlementTemplate_Result }>;
  regardingobjectid_incident_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_awcnpd_feedback: Incident_Result }>;
  regardingobjectid_invoice_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_awcnpd_feedback: Invoice_Result }>;
  regardingobjectid_knowledgearticle_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_awcnpd_feedback: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_awcnpd_feedback: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_awcnpd_feedback: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_awcnpd_feedback: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_awcnpd_feedback: msdyn_PostAlbum_Result }>;
  regardingobjectid_new_interactionforemail_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { regardingobjectid_new_interactionforemail_awcnpd_feedback: InteractionForEmail_Result }>;
  regardingobjectid_opportunity_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_awcnpd_feedback: Opportunity_Result }>;
  regardingobjectid_quote_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_awcnpd_feedback: Quote_Result }>;
  regardingobjectid_salesorder_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_awcnpd_feedback: SalesOrder_Result }>;
  regardingobjectid_site_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Site_Select, Site_Filter, { regardingobjectid_site_awcnpd_feedback: Site_Result }>;
  sendermailboxid_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid_awcnpd_feedback: Mailbox_Result }>;
  serviceid_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, Service_Select, Service_Filter, { serviceid_awcnpd_feedback: Service_Result }>;
  sla_activitypointer_sla_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SLA_Select, SLA_Filter, { sla_activitypointer_sla_awcnpd_feedback: SLA_Result }>;
  slainvokedid_activitypointer_sla_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, SLA_Select, SLA_Filter, { slainvokedid_activitypointer_sla_awcnpd_feedback: SLA_Result }>;
  stageid_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_awcnpd_feedback: ProcessStage_Result }>;
  transactioncurrencyid_awcnpd_feedback: WebExpand<awcnpd_feedback_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_awcnpd_feedback: TransactionCurrency_Result }>;
}
interface awcnpd_feedback_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  awcnpd_satisfactionrating_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface awcnpd_feedback_Result extends awcnpd_feedback_Base, awcnpd_feedback_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface awcnpd_feedback_RelatedOne {
  activityid_awcnpd_feedback: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_awcnpd_feedback: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_awcnpd_feedback: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_awcnpd_feedback: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_awcnpd_feedback: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_awcnpd_feedback: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_awcnpd_feedback1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_awcnpd_feedback: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_awcnpd_feedback: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_awcnpd_feedback: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_awcnpd_feedback: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_awcnpd_feedback: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_awcnpd_feedback: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_awcnpd_feedback: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_awcnpd_feedback: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_awcnpd_feedback: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_awcnpd_feedback: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_awcnpd_feedback: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_awcnpd_feedback: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_awcnpd_feedback: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_awcnpd_feedback: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_awcnpd_feedback: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_awcnpd_feedback: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_awcnpd_feedback: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_awcnpd_feedback: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_awcnpd_feedback: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_awcnpd_feedback: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_awcnpd_feedback: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_awcnpd_feedback: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_awcnpd_feedback: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_new_interactionforemail_awcnpd_feedback: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  regardingobjectid_opportunity_awcnpd_feedback: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_awcnpd_feedback: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_awcnpd_feedback: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_awcnpd_feedback: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  sendermailboxid_awcnpd_feedback: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  serviceid_awcnpd_feedback: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_activitypointer_sla_awcnpd_feedback: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_activitypointer_sla_awcnpd_feedback: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_awcnpd_feedback: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_awcnpd_feedback: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface awcnpd_feedback_RelatedMany {
  CampaignResponse_awcnpd_feedbacks: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  awcnpd_feedback_ActionCards: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  awcnpd_feedback_Annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  awcnpd_feedback_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  awcnpd_feedback_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  awcnpd_feedback_Feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  awcnpd_feedback_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  awcnpd_feedback_PrincipalObjectAttributeAccesses: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  awcnpd_feedback_ProcessSession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  awcnpd_feedback_QueueItems: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  awcnpd_feedback_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  awcnpd_feedback_UserEntityInstanceDatas: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  awcnpd_feedback_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  awcnpd_feedback_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  awcnpd_feedback_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
}
interface WebEntitiesRetrieve {
  awcnpd_feedbacks: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
}
interface WebEntitiesRelated {
  awcnpd_feedbacks: WebMappingRelated<awcnpd_feedback_RelatedOne,awcnpd_feedback_RelatedMany>;
}
interface WebEntitiesCUDA {
  awcnpd_feedbacks: WebMappingCUDA<awcnpd_feedback_Create,awcnpd_feedback_Update,awcnpd_feedback_Select>;
}
