interface Connection_Base extends WebEntity {
  connectionid?: string | null;
  createdon?: Date | null;
  description?: string | null;
  effectiveend?: Date | null;
  effectivestart?: Date | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  ismaster?: boolean | null;
  modifiedon?: Date | null;
  name?: string | null;
  overriddencreatedon?: Date | null;
  record1objecttypecode?: connection_record1objecttypecode | null;
  record2objecttypecode?: connection_record2objecttypecode | null;
  statecode?: connection_statecode | null;
  statuscode?: connection_statuscode | null;
  versionnumber?: number | null;
}
interface Connection_Relationships {
  Connection_AsyncOperations?: AsyncOperation_Result[] | null;
  Connection_ProcessSessions?: ProcessSession_Result[] | null;
  Connection_SyncErrors?: SyncError_Result[] | null;
  channelaccessprofileruleid?: ChannelAccessProfileRule_Result | null;
  connection_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  connection_related_connection?: Connection_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  profileruleid1?: ChannelAccessProfileRule_Result | null;
  record1id_account?: Account_Result | null;
  record1id_activitypointer?: ActivityPointer_Result | null;
  record1id_appointment?: Appointment_Result | null;
  record1id_awc_prototype?: awc_prototype_Result | null;
  record1id_awcnpd_feedback?: awcnpd_feedback_Result | null;
  record1id_awcnpd_idea?: awcnpd_idea_Result | null;
  record1id_awcnpd_prototype?: awcnpd_prototype_Result | null;
  record1id_campaign?: Campaign_Result | null;
  record1id_campaignactivity?: CampaignActivity_Result | null;
  record1id_competitor?: Competitor_Result | null;
  record1id_constraintbasedgroup?: ConstraintBasedGroup_Result | null;
  record1id_contact?: Contact_Result | null;
  record1id_contract?: Contract_Result | null;
  record1id_email?: Email_Result | null;
  record1id_entitlement?: Entitlement_Result | null;
  record1id_entitlementchannel?: EntitlementChannel_Result | null;
  record1id_entitlementtemplatechannel?: EntitlementTemplateChannel_Result | null;
  record1id_equipment?: Equipment_Result | null;
  record1id_fax?: Fax_Result | null;
  record1id_goal?: Goal_Result | null;
  record1id_incident?: Incident_Result | null;
  record1id_invoice?: Invoice_Result | null;
  record1id_knowledgearticle?: KnowledgeArticle_Result | null;
  record1id_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  record1id_lead?: Lead_Result | null;
  record1id_letter?: Letter_Result | null;
  record1id_list?: List_Result | null;
  record1id_msdyn_postalbum?: msdyn_PostAlbum_Result | null;
  record1id_opportunity?: Opportunity_Result | null;
  record1id_phonecall?: PhoneCall_Result | null;
  record1id_position?: Position_Result | null;
  record1id_pricelevel?: PriceLevel_Result | null;
  record1id_processsession?: ProcessSession_Result | null;
  record1id_product?: Product_Result | null;
  record1id_quote?: Quote_Result | null;
  record1id_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  record1id_resourcegroup?: ResourceGroup_Result | null;
  record1id_salesorder?: SalesOrder_Result | null;
  record1id_serviceappointment?: ServiceAppointment_Result | null;
  record1id_socialactivity?: SocialActivity_Result | null;
  record1id_socialprofile?: SocialProfile_Result | null;
  record1id_systemuser?: SystemUser_Result | null;
  record1id_task?: Task_Result | null;
  record1id_team?: Team_Result | null;
  record1id_territory?: Territory_Result | null;
  record2id_account?: Account_Result | null;
  record2id_activitypointer?: ActivityPointer_Result | null;
  record2id_appointment?: Appointment_Result | null;
  record2id_awc_prototype?: awc_prototype_Result | null;
  record2id_awcnpd_feedback?: awcnpd_feedback_Result | null;
  record2id_awcnpd_idea?: awcnpd_idea_Result | null;
  record2id_awcnpd_prototype?: awcnpd_prototype_Result | null;
  record2id_campaign?: Campaign_Result | null;
  record2id_campaignactivity?: CampaignActivity_Result | null;
  record2id_competitor?: Competitor_Result | null;
  record2id_constraintbasedgroup?: ConstraintBasedGroup_Result | null;
  record2id_contact?: Contact_Result | null;
  record2id_contract?: Contract_Result | null;
  record2id_email?: Email_Result | null;
  record2id_entitlement?: Entitlement_Result | null;
  record2id_entitlementchannel?: EntitlementChannel_Result | null;
  record2id_entitlementtemplatechannel?: EntitlementTemplateChannel_Result | null;
  record2id_equipment?: Equipment_Result | null;
  record2id_fax?: Fax_Result | null;
  record2id_goal?: Goal_Result | null;
  record2id_incident?: Incident_Result | null;
  record2id_invoice?: Invoice_Result | null;
  record2id_knowledgearticle?: KnowledgeArticle_Result | null;
  record2id_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  record2id_lead?: Lead_Result | null;
  record2id_letter?: Letter_Result | null;
  record2id_list?: List_Result | null;
  record2id_msdyn_postalbum?: msdyn_PostAlbum_Result | null;
  record2id_opportunity?: Opportunity_Result | null;
  record2id_phonecall?: PhoneCall_Result | null;
  record2id_position?: Position_Result | null;
  record2id_pricelevel?: PriceLevel_Result | null;
  record2id_processsession?: ProcessSession_Result | null;
  record2id_product?: Product_Result | null;
  record2id_quote?: Quote_Result | null;
  record2id_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  record2id_resourcegroup?: ResourceGroup_Result | null;
  record2id_salesorder?: SalesOrder_Result | null;
  record2id_serviceappointment?: ServiceAppointment_Result | null;
  record2id_socialactivity?: SocialActivity_Result | null;
  record2id_socialprofile?: SocialProfile_Result | null;
  record2id_systemuser?: SystemUser_Result | null;
  record2id_task?: Task_Result | null;
  record2id_team?: Team_Result | null;
  record2id_territory?: Territory_Result | null;
  userentityinstancedata_connection?: UserEntityInstanceData_Result[] | null;
}
interface Connection extends Connection_Base, Connection_Relationships {
  channelaccessprofileruleid_bind$channelaccessprofilerules?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  profileruleid1_bind$channelaccessprofilerules?: string | null;
  record1id_account_bind$accounts?: string | null;
  record1id_activitypointer_bind$activitypointers?: string | null;
  record1id_appointment_bind$appointments?: string | null;
  record1id_awc_prototype_bind$awc_prototypes?: string | null;
  record1id_awcnpd_feedback_bind$awcnpd_feedbacks?: string | null;
  record1id_awcnpd_idea_bind$awcnpd_ideas?: string | null;
  record1id_awcnpd_prototype_bind$awcnpd_prototypes?: string | null;
  record1id_campaign_bind$campaigns?: string | null;
  record1id_campaignactivity_bind$campaignactivities?: string | null;
  record1id_competitor_bind$competitors?: string | null;
  record1id_constraintbasedgroup_bind$constraintbasedgroups?: string | null;
  record1id_contact_bind$contacts?: string | null;
  record1id_contract_bind$contracts?: string | null;
  record1id_email_bind$emails?: string | null;
  record1id_entitlement_bind$entitlements?: string | null;
  record1id_entitlementchannel_bind$entitlementchannels?: string | null;
  record1id_entitlementtemplatechannel_bind$entitlementtemplatechannels?: string | null;
  record1id_equipment_bind$equipments?: string | null;
  record1id_fax_bind$faxes?: string | null;
  record1id_goal_bind$goals?: string | null;
  record1id_incident_bind$incidents?: string | null;
  record1id_invoice_bind$invoices?: string | null;
  record1id_knowledgearticle_bind$knowledgearticles?: string | null;
  record1id_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
  record1id_lead_bind$leads?: string | null;
  record1id_letter_bind$letters?: string | null;
  record1id_list_bind$lists?: string | null;
  record1id_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
  record1id_opportunity_bind$opportunities?: string | null;
  record1id_phonecall_bind$phonecalls?: string | null;
  record1id_position_bind$positions?: string | null;
  record1id_pricelevel_bind$pricelevels?: string | null;
  record1id_processsession_bind$processsessions?: string | null;
  record1id_product_bind$products?: string | null;
  record1id_quote_bind$quotes?: string | null;
  record1id_recurringappointmentmaster_bind$recurringappointmentmasters?: string | null;
  record1id_resourcegroup_bind$resourcegroups?: string | null;
  record1id_salesorder_bind$salesorders?: string | null;
  record1id_serviceappointment_bind$serviceappointments?: string | null;
  record1id_socialactivity_bind$socialactivities?: string | null;
  record1id_socialprofile_bind$socialprofiles?: string | null;
  record1id_systemuser_bind$systemusers?: string | null;
  record1id_task_bind$tasks?: string | null;
  record1id_team_bind$teams?: string | null;
  record1id_territory_bind$territories?: string | null;
  record1roleid_bind$connectionroles?: string | null;
  record2id_account_bind$accounts?: string | null;
  record2id_activitypointer_bind$activitypointers?: string | null;
  record2id_appointment_bind$appointments?: string | null;
  record2id_awc_prototype_bind$awc_prototypes?: string | null;
  record2id_awcnpd_feedback_bind$awcnpd_feedbacks?: string | null;
  record2id_awcnpd_idea_bind$awcnpd_ideas?: string | null;
  record2id_awcnpd_prototype_bind$awcnpd_prototypes?: string | null;
  record2id_campaign_bind$campaigns?: string | null;
  record2id_campaignactivity_bind$campaignactivities?: string | null;
  record2id_competitor_bind$competitors?: string | null;
  record2id_constraintbasedgroup_bind$constraintbasedgroups?: string | null;
  record2id_contact_bind$contacts?: string | null;
  record2id_contract_bind$contracts?: string | null;
  record2id_email_bind$emails?: string | null;
  record2id_entitlement_bind$entitlements?: string | null;
  record2id_entitlementchannel_bind$entitlementchannels?: string | null;
  record2id_entitlementtemplatechannel_bind$entitlementtemplatechannels?: string | null;
  record2id_equipment_bind$equipments?: string | null;
  record2id_fax_bind$faxes?: string | null;
  record2id_goal_bind$goals?: string | null;
  record2id_incident_bind$incidents?: string | null;
  record2id_invoice_bind$invoices?: string | null;
  record2id_knowledgearticle_bind$knowledgearticles?: string | null;
  record2id_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
  record2id_lead_bind$leads?: string | null;
  record2id_letter_bind$letters?: string | null;
  record2id_list_bind$lists?: string | null;
  record2id_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
  record2id_opportunity_bind$opportunities?: string | null;
  record2id_phonecall_bind$phonecalls?: string | null;
  record2id_position_bind$positions?: string | null;
  record2id_pricelevel_bind$pricelevels?: string | null;
  record2id_processsession_bind$processsessions?: string | null;
  record2id_product_bind$products?: string | null;
  record2id_quote_bind$quotes?: string | null;
  record2id_recurringappointmentmaster_bind$recurringappointmentmasters?: string | null;
  record2id_resourcegroup_bind$resourcegroups?: string | null;
  record2id_salesorder_bind$salesorders?: string | null;
  record2id_serviceappointment_bind$serviceappointments?: string | null;
  record2id_socialactivity_bind$socialactivities?: string | null;
  record2id_socialprofile_bind$socialprofiles?: string | null;
  record2id_systemuser_bind$systemusers?: string | null;
  record2id_task_bind$tasks?: string | null;
  record2id_team_bind$teams?: string | null;
  record2id_territory_bind$territories?: string | null;
  record2roleid_bind$connectionroles?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Connection_Create extends Connection {
}
interface Connection_Update extends Connection {
}
interface Connection_Select {
  connectionid: WebAttribute<Connection_Select, { connectionid: string | null }, {  }>;
  createdby_guid: WebAttribute<Connection_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Connection_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Connection_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Connection_Select, { description: string | null }, {  }>;
  effectiveend: WebAttribute<Connection_Select, { effectiveend: Date | null }, { effectiveend_formatted?: string }>;
  effectivestart: WebAttribute<Connection_Select, { effectivestart: Date | null }, { effectivestart_formatted?: string }>;
  entityimageid: WebAttribute<Connection_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<Connection_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<Connection_Select, { importsequencenumber: number | null }, {  }>;
  ismaster: WebAttribute<Connection_Select, { ismaster: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<Connection_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Connection_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Connection_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Connection_Select, { name: string | null }, {  }>;
  overriddencreatedon: WebAttribute<Connection_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Connection_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Connection_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Connection_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Connection_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  record1id_guid: WebAttribute<Connection_Select, { record1id_guid: string | null }, { record1id_formatted?: string }>;
  record1objecttypecode: WebAttribute<Connection_Select, { record1objecttypecode: connection_record1objecttypecode | null }, { record1objecttypecode_formatted?: string }>;
  record1roleid_guid: WebAttribute<Connection_Select, { record1roleid_guid: string | null }, { record1roleid_formatted?: string }>;
  record2id_guid: WebAttribute<Connection_Select, { record2id_guid: string | null }, { record2id_formatted?: string }>;
  record2objecttypecode: WebAttribute<Connection_Select, { record2objecttypecode: connection_record2objecttypecode | null }, { record2objecttypecode_formatted?: string }>;
  record2roleid_guid: WebAttribute<Connection_Select, { record2roleid_guid: string | null }, { record2roleid_formatted?: string }>;
  relatedconnectionid_guid: WebAttribute<Connection_Select, { relatedconnectionid_guid: string | null }, { relatedconnectionid_formatted?: string }>;
  statecode: WebAttribute<Connection_Select, { statecode: connection_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Connection_Select, { statuscode: connection_statuscode | null }, { statuscode_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Connection_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  versionnumber: WebAttribute<Connection_Select, { versionnumber: number | null }, {  }>;
}
interface Connection_Filter {
  connectionid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  effectiveend: Date;
  effectivestart: Date;
  entityimageid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  ismaster: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  record1id_guid: XQW.Guid;
  record1objecttypecode: connection_record1objecttypecode;
  record1roleid_guid: XQW.Guid;
  record2id_guid: XQW.Guid;
  record2objecttypecode: connection_record2objecttypecode;
  record2roleid_guid: XQW.Guid;
  relatedconnectionid_guid: XQW.Guid;
  statecode: connection_statecode;
  statuscode: connection_statuscode;
  transactioncurrencyid_guid: XQW.Guid;
  versionnumber: number;
}
interface Connection_Expand {
  Connection_AsyncOperations: WebExpand<Connection_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Connection_AsyncOperations: AsyncOperation_Result[] }>;
  Connection_ProcessSessions: WebExpand<Connection_Expand, ProcessSession_Select, ProcessSession_Filter, { Connection_ProcessSessions: ProcessSession_Result[] }>;
  Connection_SyncErrors: WebExpand<Connection_Expand, SyncError_Select, SyncError_Filter, { Connection_SyncErrors: SyncError_Result[] }>;
  channelaccessprofileruleid: WebExpand<Connection_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { channelaccessprofileruleid: ChannelAccessProfileRule_Result }>;
  connection_principalobjectattributeaccess: WebExpand<Connection_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { connection_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  connection_related_connection: WebExpand<Connection_Expand, Connection_Select, Connection_Filter, { connection_related_connection: Connection_Result[] }>;
  createdby: WebExpand<Connection_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Connection_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  entityimageid_imagedescriptor: WebExpand<Connection_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  modifiedby: WebExpand<Connection_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Connection_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  ownerid: WebExpand<Connection_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Connection_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  profileruleid1: WebExpand<Connection_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { profileruleid1: ChannelAccessProfileRule_Result }>;
  record1id_account: WebExpand<Connection_Expand, Account_Select, Account_Filter, { record1id_account: Account_Result }>;
  record1id_activitypointer: WebExpand<Connection_Expand, ActivityPointer_Select, ActivityPointer_Filter, { record1id_activitypointer: ActivityPointer_Result }>;
  record1id_appointment: WebExpand<Connection_Expand, Appointment_Select, Appointment_Filter, { record1id_appointment: Appointment_Result }>;
  record1id_awc_prototype: WebExpand<Connection_Expand, awc_prototype_Select, awc_prototype_Filter, { record1id_awc_prototype: awc_prototype_Result }>;
  record1id_awcnpd_feedback: WebExpand<Connection_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { record1id_awcnpd_feedback: awcnpd_feedback_Result }>;
  record1id_awcnpd_idea: WebExpand<Connection_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { record1id_awcnpd_idea: awcnpd_idea_Result }>;
  record1id_awcnpd_prototype: WebExpand<Connection_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { record1id_awcnpd_prototype: awcnpd_prototype_Result }>;
  record1id_campaign: WebExpand<Connection_Expand, Campaign_Select, Campaign_Filter, { record1id_campaign: Campaign_Result }>;
  record1id_campaignactivity: WebExpand<Connection_Expand, CampaignActivity_Select, CampaignActivity_Filter, { record1id_campaignactivity: CampaignActivity_Result }>;
  record1id_competitor: WebExpand<Connection_Expand, Competitor_Select, Competitor_Filter, { record1id_competitor: Competitor_Result }>;
  record1id_constraintbasedgroup: WebExpand<Connection_Expand, ConstraintBasedGroup_Select, ConstraintBasedGroup_Filter, { record1id_constraintbasedgroup: ConstraintBasedGroup_Result }>;
  record1id_contact: WebExpand<Connection_Expand, Contact_Select, Contact_Filter, { record1id_contact: Contact_Result }>;
  record1id_contract: WebExpand<Connection_Expand, Contract_Select, Contract_Filter, { record1id_contract: Contract_Result }>;
  record1id_email: WebExpand<Connection_Expand, Email_Select, Email_Filter, { record1id_email: Email_Result }>;
  record1id_entitlement: WebExpand<Connection_Expand, Entitlement_Select, Entitlement_Filter, { record1id_entitlement: Entitlement_Result }>;
  record1id_entitlementchannel: WebExpand<Connection_Expand, EntitlementChannel_Select, EntitlementChannel_Filter, { record1id_entitlementchannel: EntitlementChannel_Result }>;
  record1id_entitlementtemplatechannel: WebExpand<Connection_Expand, EntitlementTemplateChannel_Select, EntitlementTemplateChannel_Filter, { record1id_entitlementtemplatechannel: EntitlementTemplateChannel_Result }>;
  record1id_equipment: WebExpand<Connection_Expand, Equipment_Select, Equipment_Filter, { record1id_equipment: Equipment_Result }>;
  record1id_fax: WebExpand<Connection_Expand, Fax_Select, Fax_Filter, { record1id_fax: Fax_Result }>;
  record1id_goal: WebExpand<Connection_Expand, Goal_Select, Goal_Filter, { record1id_goal: Goal_Result }>;
  record1id_incident: WebExpand<Connection_Expand, Incident_Select, Incident_Filter, { record1id_incident: Incident_Result }>;
  record1id_invoice: WebExpand<Connection_Expand, Invoice_Select, Invoice_Filter, { record1id_invoice: Invoice_Result }>;
  record1id_knowledgearticle: WebExpand<Connection_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { record1id_knowledgearticle: KnowledgeArticle_Result }>;
  record1id_knowledgebaserecord: WebExpand<Connection_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { record1id_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  record1id_lead: WebExpand<Connection_Expand, Lead_Select, Lead_Filter, { record1id_lead: Lead_Result }>;
  record1id_letter: WebExpand<Connection_Expand, Letter_Select, Letter_Filter, { record1id_letter: Letter_Result }>;
  record1id_list: WebExpand<Connection_Expand, List_Select, List_Filter, { record1id_list: List_Result }>;
  record1id_msdyn_postalbum: WebExpand<Connection_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { record1id_msdyn_postalbum: msdyn_PostAlbum_Result }>;
  record1id_opportunity: WebExpand<Connection_Expand, Opportunity_Select, Opportunity_Filter, { record1id_opportunity: Opportunity_Result }>;
  record1id_phonecall: WebExpand<Connection_Expand, PhoneCall_Select, PhoneCall_Filter, { record1id_phonecall: PhoneCall_Result }>;
  record1id_position: WebExpand<Connection_Expand, Position_Select, Position_Filter, { record1id_position: Position_Result }>;
  record1id_pricelevel: WebExpand<Connection_Expand, PriceLevel_Select, PriceLevel_Filter, { record1id_pricelevel: PriceLevel_Result }>;
  record1id_processsession: WebExpand<Connection_Expand, ProcessSession_Select, ProcessSession_Filter, { record1id_processsession: ProcessSession_Result }>;
  record1id_product: WebExpand<Connection_Expand, Product_Select, Product_Filter, { record1id_product: Product_Result }>;
  record1id_quote: WebExpand<Connection_Expand, Quote_Select, Quote_Filter, { record1id_quote: Quote_Result }>;
  record1id_recurringappointmentmaster: WebExpand<Connection_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { record1id_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  record1id_resourcegroup: WebExpand<Connection_Expand, ResourceGroup_Select, ResourceGroup_Filter, { record1id_resourcegroup: ResourceGroup_Result }>;
  record1id_salesorder: WebExpand<Connection_Expand, SalesOrder_Select, SalesOrder_Filter, { record1id_salesorder: SalesOrder_Result }>;
  record1id_serviceappointment: WebExpand<Connection_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { record1id_serviceappointment: ServiceAppointment_Result }>;
  record1id_socialactivity: WebExpand<Connection_Expand, SocialActivity_Select, SocialActivity_Filter, { record1id_socialactivity: SocialActivity_Result }>;
  record1id_socialprofile: WebExpand<Connection_Expand, SocialProfile_Select, SocialProfile_Filter, { record1id_socialprofile: SocialProfile_Result }>;
  record1id_systemuser: WebExpand<Connection_Expand, SystemUser_Select, SystemUser_Filter, { record1id_systemuser: SystemUser_Result }>;
  record1id_task: WebExpand<Connection_Expand, Task_Select, Task_Filter, { record1id_task: Task_Result }>;
  record1id_team: WebExpand<Connection_Expand, Team_Select, Team_Filter, { record1id_team: Team_Result }>;
  record1id_territory: WebExpand<Connection_Expand, Territory_Select, Territory_Filter, { record1id_territory: Territory_Result }>;
  record1roleid: WebExpand<Connection_Expand, ConnectionRole_Select, ConnectionRole_Filter, { record1roleid: ConnectionRole_Result }>;
  record2id_account: WebExpand<Connection_Expand, Account_Select, Account_Filter, { record2id_account: Account_Result }>;
  record2id_activitypointer: WebExpand<Connection_Expand, ActivityPointer_Select, ActivityPointer_Filter, { record2id_activitypointer: ActivityPointer_Result }>;
  record2id_appointment: WebExpand<Connection_Expand, Appointment_Select, Appointment_Filter, { record2id_appointment: Appointment_Result }>;
  record2id_awc_prototype: WebExpand<Connection_Expand, awc_prototype_Select, awc_prototype_Filter, { record2id_awc_prototype: awc_prototype_Result }>;
  record2id_awcnpd_feedback: WebExpand<Connection_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { record2id_awcnpd_feedback: awcnpd_feedback_Result }>;
  record2id_awcnpd_idea: WebExpand<Connection_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { record2id_awcnpd_idea: awcnpd_idea_Result }>;
  record2id_awcnpd_prototype: WebExpand<Connection_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { record2id_awcnpd_prototype: awcnpd_prototype_Result }>;
  record2id_campaign: WebExpand<Connection_Expand, Campaign_Select, Campaign_Filter, { record2id_campaign: Campaign_Result }>;
  record2id_campaignactivity: WebExpand<Connection_Expand, CampaignActivity_Select, CampaignActivity_Filter, { record2id_campaignactivity: CampaignActivity_Result }>;
  record2id_competitor: WebExpand<Connection_Expand, Competitor_Select, Competitor_Filter, { record2id_competitor: Competitor_Result }>;
  record2id_constraintbasedgroup: WebExpand<Connection_Expand, ConstraintBasedGroup_Select, ConstraintBasedGroup_Filter, { record2id_constraintbasedgroup: ConstraintBasedGroup_Result }>;
  record2id_contact: WebExpand<Connection_Expand, Contact_Select, Contact_Filter, { record2id_contact: Contact_Result }>;
  record2id_contract: WebExpand<Connection_Expand, Contract_Select, Contract_Filter, { record2id_contract: Contract_Result }>;
  record2id_email: WebExpand<Connection_Expand, Email_Select, Email_Filter, { record2id_email: Email_Result }>;
  record2id_entitlement: WebExpand<Connection_Expand, Entitlement_Select, Entitlement_Filter, { record2id_entitlement: Entitlement_Result }>;
  record2id_entitlementchannel: WebExpand<Connection_Expand, EntitlementChannel_Select, EntitlementChannel_Filter, { record2id_entitlementchannel: EntitlementChannel_Result }>;
  record2id_entitlementtemplatechannel: WebExpand<Connection_Expand, EntitlementTemplateChannel_Select, EntitlementTemplateChannel_Filter, { record2id_entitlementtemplatechannel: EntitlementTemplateChannel_Result }>;
  record2id_equipment: WebExpand<Connection_Expand, Equipment_Select, Equipment_Filter, { record2id_equipment: Equipment_Result }>;
  record2id_fax: WebExpand<Connection_Expand, Fax_Select, Fax_Filter, { record2id_fax: Fax_Result }>;
  record2id_goal: WebExpand<Connection_Expand, Goal_Select, Goal_Filter, { record2id_goal: Goal_Result }>;
  record2id_incident: WebExpand<Connection_Expand, Incident_Select, Incident_Filter, { record2id_incident: Incident_Result }>;
  record2id_invoice: WebExpand<Connection_Expand, Invoice_Select, Invoice_Filter, { record2id_invoice: Invoice_Result }>;
  record2id_knowledgearticle: WebExpand<Connection_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { record2id_knowledgearticle: KnowledgeArticle_Result }>;
  record2id_knowledgebaserecord: WebExpand<Connection_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { record2id_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  record2id_lead: WebExpand<Connection_Expand, Lead_Select, Lead_Filter, { record2id_lead: Lead_Result }>;
  record2id_letter: WebExpand<Connection_Expand, Letter_Select, Letter_Filter, { record2id_letter: Letter_Result }>;
  record2id_list: WebExpand<Connection_Expand, List_Select, List_Filter, { record2id_list: List_Result }>;
  record2id_msdyn_postalbum: WebExpand<Connection_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { record2id_msdyn_postalbum: msdyn_PostAlbum_Result }>;
  record2id_opportunity: WebExpand<Connection_Expand, Opportunity_Select, Opportunity_Filter, { record2id_opportunity: Opportunity_Result }>;
  record2id_phonecall: WebExpand<Connection_Expand, PhoneCall_Select, PhoneCall_Filter, { record2id_phonecall: PhoneCall_Result }>;
  record2id_position: WebExpand<Connection_Expand, Position_Select, Position_Filter, { record2id_position: Position_Result }>;
  record2id_pricelevel: WebExpand<Connection_Expand, PriceLevel_Select, PriceLevel_Filter, { record2id_pricelevel: PriceLevel_Result }>;
  record2id_processsession: WebExpand<Connection_Expand, ProcessSession_Select, ProcessSession_Filter, { record2id_processsession: ProcessSession_Result }>;
  record2id_product: WebExpand<Connection_Expand, Product_Select, Product_Filter, { record2id_product: Product_Result }>;
  record2id_quote: WebExpand<Connection_Expand, Quote_Select, Quote_Filter, { record2id_quote: Quote_Result }>;
  record2id_recurringappointmentmaster: WebExpand<Connection_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { record2id_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  record2id_resourcegroup: WebExpand<Connection_Expand, ResourceGroup_Select, ResourceGroup_Filter, { record2id_resourcegroup: ResourceGroup_Result }>;
  record2id_salesorder: WebExpand<Connection_Expand, SalesOrder_Select, SalesOrder_Filter, { record2id_salesorder: SalesOrder_Result }>;
  record2id_serviceappointment: WebExpand<Connection_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { record2id_serviceappointment: ServiceAppointment_Result }>;
  record2id_socialactivity: WebExpand<Connection_Expand, SocialActivity_Select, SocialActivity_Filter, { record2id_socialactivity: SocialActivity_Result }>;
  record2id_socialprofile: WebExpand<Connection_Expand, SocialProfile_Select, SocialProfile_Filter, { record2id_socialprofile: SocialProfile_Result }>;
  record2id_systemuser: WebExpand<Connection_Expand, SystemUser_Select, SystemUser_Filter, { record2id_systemuser: SystemUser_Result }>;
  record2id_task: WebExpand<Connection_Expand, Task_Select, Task_Filter, { record2id_task: Task_Result }>;
  record2id_team: WebExpand<Connection_Expand, Team_Select, Team_Filter, { record2id_team: Team_Result }>;
  record2id_territory: WebExpand<Connection_Expand, Territory_Select, Territory_Filter, { record2id_territory: Territory_Result }>;
  record2roleid: WebExpand<Connection_Expand, ConnectionRole_Select, ConnectionRole_Filter, { record2roleid: ConnectionRole_Result }>;
  relatedconnectionid: WebExpand<Connection_Expand, Connection_Select, Connection_Filter, { relatedconnectionid: Connection_Result }>;
  transactioncurrencyid: WebExpand<Connection_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_connection: WebExpand<Connection_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_connection: UserEntityInstanceData_Result[] }>;
}
interface Connection_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  effectiveend_formatted?: string;
  effectivestart_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  record1id_formatted?: string;
  record1objecttypecode_formatted?: string;
  record1roleid_formatted?: string;
  record2id_formatted?: string;
  record2objecttypecode_formatted?: string;
  record2roleid_formatted?: string;
  relatedconnectionid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Connection_Result extends Connection_Base, Connection_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  record1id_guid: string | null;
  record1roleid_guid: string | null;
  record2id_guid: string | null;
  record2roleid_guid: string | null;
  relatedconnectionid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Connection_RelatedOne {
  channelaccessprofileruleid: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  profileruleid1: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  record1id_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  record1id_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  record1id_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  record1id_awc_prototype: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  record1id_awcnpd_feedback: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  record1id_awcnpd_idea: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  record1id_awcnpd_prototype: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  record1id_campaign: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  record1id_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  record1id_competitor: WebMappingRetrieve<Competitor_Select,Competitor_Expand,Competitor_Filter,Competitor_Fixed,Competitor_Result,Competitor_FormattedResult>;
  record1id_constraintbasedgroup: WebMappingRetrieve<ConstraintBasedGroup_Select,ConstraintBasedGroup_Expand,ConstraintBasedGroup_Filter,ConstraintBasedGroup_Fixed,ConstraintBasedGroup_Result,ConstraintBasedGroup_FormattedResult>;
  record1id_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  record1id_contract: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  record1id_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  record1id_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  record1id_entitlementchannel: WebMappingRetrieve<EntitlementChannel_Select,EntitlementChannel_Expand,EntitlementChannel_Filter,EntitlementChannel_Fixed,EntitlementChannel_Result,EntitlementChannel_FormattedResult>;
  record1id_entitlementtemplatechannel: WebMappingRetrieve<EntitlementTemplateChannel_Select,EntitlementTemplateChannel_Expand,EntitlementTemplateChannel_Filter,EntitlementTemplateChannel_Fixed,EntitlementTemplateChannel_Result,EntitlementTemplateChannel_FormattedResult>;
  record1id_equipment: WebMappingRetrieve<Equipment_Select,Equipment_Expand,Equipment_Filter,Equipment_Fixed,Equipment_Result,Equipment_FormattedResult>;
  record1id_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  record1id_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  record1id_incident: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  record1id_invoice: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  record1id_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  record1id_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  record1id_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  record1id_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  record1id_list: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  record1id_msdyn_postalbum: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  record1id_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  record1id_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  record1id_position: WebMappingRetrieve<Position_Select,Position_Expand,Position_Filter,Position_Fixed,Position_Result,Position_FormattedResult>;
  record1id_pricelevel: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  record1id_processsession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  record1id_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  record1id_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  record1id_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  record1id_resourcegroup: WebMappingRetrieve<ResourceGroup_Select,ResourceGroup_Expand,ResourceGroup_Filter,ResourceGroup_Fixed,ResourceGroup_Result,ResourceGroup_FormattedResult>;
  record1id_salesorder: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  record1id_serviceappointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  record1id_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  record1id_socialprofile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  record1id_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  record1id_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  record1id_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  record1id_territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  record1roleid: WebMappingRetrieve<ConnectionRole_Select,ConnectionRole_Expand,ConnectionRole_Filter,ConnectionRole_Fixed,ConnectionRole_Result,ConnectionRole_FormattedResult>;
  record2id_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  record2id_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  record2id_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  record2id_awc_prototype: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  record2id_awcnpd_feedback: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  record2id_awcnpd_idea: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  record2id_awcnpd_prototype: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  record2id_campaign: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  record2id_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  record2id_competitor: WebMappingRetrieve<Competitor_Select,Competitor_Expand,Competitor_Filter,Competitor_Fixed,Competitor_Result,Competitor_FormattedResult>;
  record2id_constraintbasedgroup: WebMappingRetrieve<ConstraintBasedGroup_Select,ConstraintBasedGroup_Expand,ConstraintBasedGroup_Filter,ConstraintBasedGroup_Fixed,ConstraintBasedGroup_Result,ConstraintBasedGroup_FormattedResult>;
  record2id_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  record2id_contract: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  record2id_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  record2id_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  record2id_entitlementchannel: WebMappingRetrieve<EntitlementChannel_Select,EntitlementChannel_Expand,EntitlementChannel_Filter,EntitlementChannel_Fixed,EntitlementChannel_Result,EntitlementChannel_FormattedResult>;
  record2id_entitlementtemplatechannel: WebMappingRetrieve<EntitlementTemplateChannel_Select,EntitlementTemplateChannel_Expand,EntitlementTemplateChannel_Filter,EntitlementTemplateChannel_Fixed,EntitlementTemplateChannel_Result,EntitlementTemplateChannel_FormattedResult>;
  record2id_equipment: WebMappingRetrieve<Equipment_Select,Equipment_Expand,Equipment_Filter,Equipment_Fixed,Equipment_Result,Equipment_FormattedResult>;
  record2id_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  record2id_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  record2id_incident: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  record2id_invoice: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  record2id_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  record2id_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  record2id_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  record2id_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  record2id_list: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  record2id_msdyn_postalbum: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  record2id_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  record2id_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  record2id_position: WebMappingRetrieve<Position_Select,Position_Expand,Position_Filter,Position_Fixed,Position_Result,Position_FormattedResult>;
  record2id_pricelevel: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  record2id_processsession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  record2id_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  record2id_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  record2id_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  record2id_resourcegroup: WebMappingRetrieve<ResourceGroup_Select,ResourceGroup_Expand,ResourceGroup_Filter,ResourceGroup_Fixed,ResourceGroup_Result,ResourceGroup_FormattedResult>;
  record2id_salesorder: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  record2id_serviceappointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  record2id_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  record2id_socialprofile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  record2id_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  record2id_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  record2id_team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  record2id_territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  record2roleid: WebMappingRetrieve<ConnectionRole_Select,ConnectionRole_Expand,ConnectionRole_Filter,ConnectionRole_Fixed,ConnectionRole_Result,ConnectionRole_FormattedResult>;
  relatedconnectionid: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Connection_RelatedMany {
  Connection_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Connection_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Connection_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  connection_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  connection_related_connection: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  userentityinstancedata_connection: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  connections: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
}
interface WebEntitiesRelated {
  connections: WebMappingRelated<Connection_RelatedOne,Connection_RelatedMany>;
}
interface WebEntitiesCUDA {
  connections: WebMappingCUDA<Connection_Create,Connection_Update,Connection_Select>;
}
