interface PhoneCall_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  category?: string | null;
  createdon?: Date | null;
  description?: string | null;
  directioncode?: boolean | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  isbilled?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  phonenumber?: string | null;
  prioritycode?: phonecall_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: phonecall_statecode | null;
  statuscode?: phonecall_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface PhoneCall_Relationships {
  PhoneCall_Annotation?: Annotation_Result[] | null;
  PhoneCall_AsyncOperations?: AsyncOperation_Result[] | null;
  PhoneCall_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  PhoneCall_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  PhoneCall_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  PhoneCall_ProcessSessions?: ProcessSession_Result[] | null;
  PhoneCall_QueueItem?: QueueItem_Result[] | null;
  PhoneCall_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_phonecall?: SystemUser_Result | null;
  createdonbehalfby_phonecall?: SystemUser_Result | null;
  modifiedby_phonecall?: SystemUser_Result | null;
  modifiedonbehalfby_phonecall?: SystemUser_Result | null;
  ownerid_phonecall?: Team_Result | null;
  ownerid_phonecall1?: SystemUser_Result | null;
  owningbusinessunit_phonecall?: BusinessUnit_Result | null;
  owningteam_phonecall?: Team_Result | null;
  owninguser_phonecall?: SystemUser_Result | null;
  phonecall_PostFollows?: PostFollow_Result[] | null;
  phonecall_PostRegardings?: PostRegarding_Result[] | null;
  phonecall_PostRoles?: PostRole_Result[] | null;
  phonecall_actioncard?: ActionCard_Result[] | null;
  phonecall_activity_parties?: ActivityParty_Result[] | null;
  phonecall_campaignresponse?: CampaignResponse_Result[] | null;
  phonecall_connections1?: Connection_Result[] | null;
  phonecall_connections2?: Connection_Result[] | null;
  phonecall_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  regardingobjectid_account_phonecall?: Account_Result | null;
  regardingobjectid_awc_prototype_phonecall?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_phonecall?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_phonecall?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_phonecall?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_phonecall?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_phonecall?: BulkOperation_Result | null;
  regardingobjectid_campaign_phonecall?: Campaign_Result | null;
  regardingobjectid_campaignactivity_phonecall?: CampaignActivity_Result | null;
  regardingobjectid_contact_phonecall?: Contact_Result | null;
  regardingobjectid_contract_phonecall?: Contract_Result | null;
  regardingobjectid_entitlement_phonecall?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_phonecall?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_phonecall?: Incident_Result | null;
  regardingobjectid_invoice_phonecall?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_phonecall?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_phonecall?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_phonecall?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_phonecall?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_phonecall?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_phonecall?: Opportunity_Result | null;
  regardingobjectid_quote_phonecall?: Quote_Result | null;
  regardingobjectid_salesorder_phonecall?: SalesOrder_Result | null;
  regardingobjectid_site_phonecall?: Site_Result | null;
  serviceid_phonecall?: Service_Result | null;
  sla_phonecall_sla?: SLA_Result | null;
  slainvokedid_phonecall_sla?: SLA_Result | null;
  slakpiinstance_phonecall?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_phonecall?: TransactionCurrency_Result | null;
  userentityinstancedata_phonecall?: UserEntityInstanceData_Result[] | null;
}
interface PhoneCall extends PhoneCall_Base, PhoneCall_Relationships {
  ownerid_phonecall_bind$systemusers?: string | null;
  ownerid_phonecall_bind$teams?: string | null;
  regardingobjectid_account_phonecall_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_phonecall_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_phonecall_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_phonecall_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_phonecall_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_phonecall_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_phonecall_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_phonecall_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_phonecall_bind$campaignactivities?: string | null;
  regardingobjectid_contact_phonecall_bind$contacts?: string | null;
  regardingobjectid_contract_phonecall_bind$contracts?: string | null;
  regardingobjectid_entitlement_phonecall_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_phonecall_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_phonecall_bind$incidents?: string | null;
  regardingobjectid_invoice_phonecall_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_phonecall_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_phonecall_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_phonecall_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_phonecall_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_phonecall_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_phonecall_bind$opportunities?: string | null;
  regardingobjectid_quote_phonecall_bind$quotes?: string | null;
  regardingobjectid_salesorder_phonecall_bind$salesorders?: string | null;
  regardingobjectid_site_phonecall_bind$sites?: string | null;
  serviceid_phonecall_bind$services?: string | null;
  sla_phonecall_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_phonecall_bind$transactioncurrencies?: string | null;
}
interface PhoneCall_Create extends PhoneCall {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface PhoneCall_Update extends PhoneCall {
}
interface PhoneCall_Select {
  activityadditionalparams: WebAttribute<PhoneCall_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<PhoneCall_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<PhoneCall_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<PhoneCall_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<PhoneCall_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<PhoneCall_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  category: WebAttribute<PhoneCall_Select, { category: string | null }, {  }>;
  createdby_guid: WebAttribute<PhoneCall_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<PhoneCall_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<PhoneCall_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<PhoneCall_Select, { description: string | null }, {  }>;
  directioncode: WebAttribute<PhoneCall_Select, { directioncode: boolean | null }, {  }>;
  exchangerate: WebAttribute<PhoneCall_Select, { exchangerate: number | null }, {  }>;
  from_guid: WebAttribute<PhoneCall_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<PhoneCall_Select, { importsequencenumber: number | null }, {  }>;
  isbilled: WebAttribute<PhoneCall_Select, { isbilled: boolean | null }, {  }>;
  isregularactivity: WebAttribute<PhoneCall_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<PhoneCall_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<PhoneCall_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<PhoneCall_Select, { leftvoicemail: boolean | null }, {  }>;
  modifiedby_guid: WebAttribute<PhoneCall_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<PhoneCall_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<PhoneCall_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<PhoneCall_Select, { onholdtime: number | null }, {  }>;
  overriddencreatedon: WebAttribute<PhoneCall_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<PhoneCall_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<PhoneCall_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<PhoneCall_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<PhoneCall_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  phonenumber: WebAttribute<PhoneCall_Select, { phonenumber: string | null }, {  }>;
  prioritycode: WebAttribute<PhoneCall_Select, { prioritycode: phonecall_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<PhoneCall_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<PhoneCall_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<PhoneCall_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<PhoneCall_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<PhoneCall_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  serviceid_guid: WebAttribute<PhoneCall_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<PhoneCall_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<PhoneCall_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<PhoneCall_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<PhoneCall_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<PhoneCall_Select, { statecode: phonecall_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<PhoneCall_Select, { statuscode: phonecall_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<PhoneCall_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<PhoneCall_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<PhoneCall_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<PhoneCall_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<PhoneCall_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<PhoneCall_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<PhoneCall_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<PhoneCall_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<PhoneCall_Select, { versionnumber: number | null }, {  }>;
}
interface PhoneCall_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  category: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  directioncode: boolean;
  exchangerate: any;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  isbilled: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  phonenumber: string;
  prioritycode: phonecall_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: phonecall_statecode;
  statuscode: phonecall_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface PhoneCall_Expand {
  PhoneCall_Annotation: WebExpand<PhoneCall_Expand, Annotation_Select, Annotation_Filter, { PhoneCall_Annotation: Annotation_Result[] }>;
  PhoneCall_AsyncOperations: WebExpand<PhoneCall_Expand, AsyncOperation_Select, AsyncOperation_Filter, { PhoneCall_AsyncOperations: AsyncOperation_Result[] }>;
  PhoneCall_BulkDeleteFailures: WebExpand<PhoneCall_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { PhoneCall_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  PhoneCall_DuplicateBaseRecord: WebExpand<PhoneCall_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { PhoneCall_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  PhoneCall_DuplicateMatchingRecord: WebExpand<PhoneCall_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { PhoneCall_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  PhoneCall_ProcessSessions: WebExpand<PhoneCall_Expand, ProcessSession_Select, ProcessSession_Filter, { PhoneCall_ProcessSessions: ProcessSession_Result[] }>;
  PhoneCall_QueueItem: WebExpand<PhoneCall_Expand, QueueItem_Select, QueueItem_Filter, { PhoneCall_QueueItem: QueueItem_Result[] }>;
  PhoneCall_SyncErrors: WebExpand<PhoneCall_Expand, SyncError_Select, SyncError_Filter, { PhoneCall_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<PhoneCall_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_phonecall: WebExpand<PhoneCall_Expand, SystemUser_Select, SystemUser_Filter, { createdby_phonecall: SystemUser_Result }>;
  createdonbehalfby_phonecall: WebExpand<PhoneCall_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_phonecall: SystemUser_Result }>;
  modifiedby_phonecall: WebExpand<PhoneCall_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_phonecall: SystemUser_Result }>;
  modifiedonbehalfby_phonecall: WebExpand<PhoneCall_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_phonecall: SystemUser_Result }>;
  ownerid_phonecall: WebExpand<PhoneCall_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_phonecall: SystemUser_Result } & { ownerid_phonecall: Team_Result }>;
  owningbusinessunit_phonecall: WebExpand<PhoneCall_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_phonecall: BusinessUnit_Result }>;
  owningteam_phonecall: WebExpand<PhoneCall_Expand, Team_Select, Team_Filter, { owningteam_phonecall: Team_Result }>;
  owninguser_phonecall: WebExpand<PhoneCall_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_phonecall: SystemUser_Result }>;
  phonecall_PostFollows: WebExpand<PhoneCall_Expand, PostFollow_Select, PostFollow_Filter, { phonecall_PostFollows: PostFollow_Result[] }>;
  phonecall_PostRegardings: WebExpand<PhoneCall_Expand, PostRegarding_Select, PostRegarding_Filter, { phonecall_PostRegardings: PostRegarding_Result[] }>;
  phonecall_PostRoles: WebExpand<PhoneCall_Expand, PostRole_Select, PostRole_Filter, { phonecall_PostRoles: PostRole_Result[] }>;
  phonecall_actioncard: WebExpand<PhoneCall_Expand, ActionCard_Select, ActionCard_Filter, { phonecall_actioncard: ActionCard_Result[] }>;
  phonecall_activity_parties: WebExpand<PhoneCall_Expand, ActivityParty_Select, ActivityParty_Filter, { phonecall_activity_parties: ActivityParty_Result[] }>;
  phonecall_campaignresponse: WebExpand<PhoneCall_Expand, CampaignResponse_Select, CampaignResponse_Filter, { phonecall_campaignresponse: CampaignResponse_Result[] }>;
  phonecall_connections1: WebExpand<PhoneCall_Expand, Connection_Select, Connection_Filter, { phonecall_connections1: Connection_Result[] }>;
  phonecall_connections2: WebExpand<PhoneCall_Expand, Connection_Select, Connection_Filter, { phonecall_connections2: Connection_Result[] }>;
  phonecall_principalobjectattributeaccess: WebExpand<PhoneCall_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { phonecall_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  regardingobjectid_account_phonecall: WebExpand<PhoneCall_Expand, Account_Select, Account_Filter, { regardingobjectid_account_phonecall: Account_Result }>;
  regardingobjectid_awc_prototype_phonecall: WebExpand<PhoneCall_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_phonecall: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_phonecall: WebExpand<PhoneCall_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_phonecall: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_phonecall: WebExpand<PhoneCall_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_phonecall: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_phonecall: WebExpand<PhoneCall_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_phonecall: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_phonecall: WebExpand<PhoneCall_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_phonecall: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_phonecall: WebExpand<PhoneCall_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_phonecall: BulkOperation_Result }>;
  regardingobjectid_campaign_phonecall: WebExpand<PhoneCall_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_phonecall: Campaign_Result }>;
  regardingobjectid_campaignactivity_phonecall: WebExpand<PhoneCall_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_phonecall: CampaignActivity_Result }>;
  regardingobjectid_contact_phonecall: WebExpand<PhoneCall_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_phonecall: Contact_Result }>;
  regardingobjectid_contract_phonecall: WebExpand<PhoneCall_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_phonecall: Contract_Result }>;
  regardingobjectid_entitlement_phonecall: WebExpand<PhoneCall_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_phonecall: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_phonecall: WebExpand<PhoneCall_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_phonecall: EntitlementTemplate_Result }>;
  regardingobjectid_incident_phonecall: WebExpand<PhoneCall_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_phonecall: Incident_Result }>;
  regardingobjectid_invoice_phonecall: WebExpand<PhoneCall_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_phonecall: Invoice_Result }>;
  regardingobjectid_knowledgearticle_phonecall: WebExpand<PhoneCall_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_phonecall: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_phonecall: WebExpand<PhoneCall_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_phonecall: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_phonecall: WebExpand<PhoneCall_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_phonecall: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_phonecall: WebExpand<PhoneCall_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_phonecall: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_phonecall: WebExpand<PhoneCall_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_phonecall: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_phonecall: WebExpand<PhoneCall_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_phonecall: Opportunity_Result }>;
  regardingobjectid_quote_phonecall: WebExpand<PhoneCall_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_phonecall: Quote_Result }>;
  regardingobjectid_salesorder_phonecall: WebExpand<PhoneCall_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_phonecall: SalesOrder_Result }>;
  regardingobjectid_site_phonecall: WebExpand<PhoneCall_Expand, Site_Select, Site_Filter, { regardingobjectid_site_phonecall: Site_Result }>;
  serviceid_phonecall: WebExpand<PhoneCall_Expand, Service_Select, Service_Filter, { serviceid_phonecall: Service_Result }>;
  sla_phonecall_sla: WebExpand<PhoneCall_Expand, SLA_Select, SLA_Filter, { sla_phonecall_sla: SLA_Result }>;
  slainvokedid_phonecall_sla: WebExpand<PhoneCall_Expand, SLA_Select, SLA_Filter, { slainvokedid_phonecall_sla: SLA_Result }>;
  slakpiinstance_phonecall: WebExpand<PhoneCall_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_phonecall: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<PhoneCall_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_phonecall: WebExpand<PhoneCall_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_phonecall: TransactionCurrency_Result }>;
  userentityinstancedata_phonecall: WebExpand<PhoneCall_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_phonecall: UserEntityInstanceData_Result[] }>;
}
interface PhoneCall_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  from_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface PhoneCall_Result extends PhoneCall_Base, PhoneCall_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface PhoneCall_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_phonecall: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_phonecall: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_phonecall: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_phonecall: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_phonecall: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_phonecall1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_phonecall: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_phonecall: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_phonecall: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_phonecall: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_phonecall: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_phonecall: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_phonecall: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_phonecall: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_phonecall: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_phonecall: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_phonecall: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_phonecall: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_phonecall: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_phonecall: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_phonecall: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_phonecall: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_phonecall: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_phonecall: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_phonecall: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_phonecall: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_phonecall: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_phonecall: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_phonecall: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_phonecall: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_phonecall: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_phonecall: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_phonecall: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  serviceid_phonecall: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_phonecall_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_phonecall_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_phonecall: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface PhoneCall_RelatedMany {
  PhoneCall_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  PhoneCall_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  PhoneCall_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  PhoneCall_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  PhoneCall_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  PhoneCall_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  PhoneCall_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  PhoneCall_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  phonecall_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  phonecall_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  phonecall_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  phonecall_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  phonecall_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  phonecall_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  phonecall_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  phonecall_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  phonecall_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_phonecall: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_phonecall: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
}
interface WebEntitiesRelated {
  phonecalls: WebMappingRelated<PhoneCall_RelatedOne,PhoneCall_RelatedMany>;
}
interface WebEntitiesCUDA {
  phonecalls: WebMappingCUDA<PhoneCall_Create,PhoneCall_Update,PhoneCall_Select>;
}
