interface Quote_Base extends WebEntity {
  billto_addressid?: string | null;
  billto_city?: string | null;
  billto_composite?: string | null;
  billto_contactname?: string | null;
  billto_country?: string | null;
  billto_fax?: string | null;
  billto_line1?: string | null;
  billto_line2?: string | null;
  billto_line3?: string | null;
  billto_name?: string | null;
  billto_postalcode?: string | null;
  billto_stateorprovince?: string | null;
  billto_telephone?: string | null;
  closedon?: Date | null;
  createdon?: Date | null;
  description?: string | null;
  discountamount?: number | null;
  discountamount_base?: number | null;
  discountpercentage?: number | null;
  effectivefrom?: Date | null;
  effectiveto?: Date | null;
  emailaddress?: string | null;
  exchangerate?: number | null;
  expireson?: Date | null;
  freightamount?: number | null;
  freightamount_base?: number | null;
  freighttermscode?: quote_freighttermscode | null;
  importsequencenumber?: number | null;
  lastonholdtime?: Date | null;
  modifiedon?: Date | null;
  name?: string | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  paymenttermscode?: quote_paymenttermscode | null;
  pricingerrorcode?: qooi_pricingerrorcode | null;
  processid?: string | null;
  quoteid?: string | null;
  quotenumber?: string | null;
  requestdeliveryby?: Date | null;
  revisionnumber?: number | null;
  shippingmethodcode?: quote_shippingmethodcode | null;
  shipto_addressid?: string | null;
  shipto_city?: string | null;
  shipto_composite?: string | null;
  shipto_contactname?: string | null;
  shipto_country?: string | null;
  shipto_fax?: string | null;
  shipto_freighttermscode?: quote_shipto_freighttermscode | null;
  shipto_line1?: string | null;
  shipto_line2?: string | null;
  shipto_line3?: string | null;
  shipto_name?: string | null;
  shipto_postalcode?: string | null;
  shipto_stateorprovince?: string | null;
  shipto_telephone?: string | null;
  skippricecalculation?: qooi_skippricecalculation | null;
  stageid?: string | null;
  statecode?: quote_statecode | null;
  statuscode?: quote_statuscode | null;
  timezoneruleversionnumber?: number | null;
  totalamount?: number | null;
  totalamount_base?: number | null;
  totalamountlessfreight?: number | null;
  totalamountlessfreight_base?: number | null;
  totaldiscountamount?: number | null;
  totaldiscountamount_base?: number | null;
  totallineitemamount?: number | null;
  totallineitemamount_base?: number | null;
  totallineitemdiscountamount?: number | null;
  totallineitemdiscountamount_base?: number | null;
  totaltax?: number | null;
  totaltax_base?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  uniquedscid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  willcall?: boolean | null;
}
interface Quote_Relationships {
  Quote_ActivityPointers?: ActivityPointer_Result[] | null;
  Quote_Annotation?: Annotation_Result[] | null;
  Quote_Appointments?: Appointment_Result[] | null;
  Quote_AsyncOperations?: AsyncOperation_Result[] | null;
  Quote_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Quote_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Quote_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Quote_Emails?: Email_Result[] | null;
  Quote_Faxes?: Fax_Result[] | null;
  Quote_Letters?: Letter_Result[] | null;
  Quote_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  Quote_Phonecalls?: PhoneCall_Result[] | null;
  Quote_ProcessSessions?: ProcessSession_Result[] | null;
  Quote_QuoteClose?: QuoteClose_Result[] | null;
  Quote_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  Quote_ServiceAppointments?: ServiceAppointment_Result[] | null;
  Quote_SharepointDocument?: SharePointDocument_Result[] | null;
  Quote_SharepointDocumentLocation?: SharePointDocumentLocation_Result[] | null;
  Quote_SocialActivities?: SocialActivity_Result[] | null;
  Quote_SyncErrors?: SyncError_Result[] | null;
  Quote_Tasks?: Task_Result[] | null;
  contactquotes_association?: Contact_Result[] | null;
  customerid_account?: Account_Result | null;
  customerid_contact?: Contact_Result | null;
  msdyn_playbookinstance_quote?: msdyn_playbookinstance_Result[] | null;
  quote_QuoteCloses?: QuoteClose_Result[] | null;
  quote_activity_parties?: ActivityParty_Result[] | null;
  quote_awcnpd_feedbacks?: awcnpd_feedback_Result[] | null;
  quote_connections1?: Connection_Result[] | null;
  quote_connections2?: Connection_Result[] | null;
  quote_details?: QuoteDetail_Result[] | null;
  quote_opportunitysalesprocess?: OpportunitySalesProcess_Result[] | null;
  quote_orders?: SalesOrder_Result[] | null;
  quote_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  sla_quote_sla?: SLA_Result | null;
  slainvokedid_quote_sla?: SLA_Result | null;
  slakpiinstance_quote?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  userentityinstancedata_quote?: UserEntityInstanceData_Result[] | null;
}
interface Quote extends Quote_Base, Quote_Relationships {
  campaignid_bind$campaigns?: string | null;
  customerid_account_bind$accounts?: string | null;
  customerid_contact_bind$contacts?: string | null;
  opportunityid_bind$opportunities?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  pricelevelid_bind$pricelevels?: string | null;
  sla_quote_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Quote_Create extends Quote {
}
interface Quote_Update extends Quote {
}
interface Quote_Select {
  accountid_guid: WebAttribute<Quote_Select, { accountid_guid: string | null }, { accountid_formatted?: string }>;
  billto_addressid: WebAttribute<Quote_Select, { billto_addressid: string | null }, {  }>;
  billto_city: WebAttribute<Quote_Select, { billto_city: string | null }, {  }>;
  billto_composite: WebAttribute<Quote_Select, { billto_composite: string | null }, {  }>;
  billto_contactname: WebAttribute<Quote_Select, { billto_contactname: string | null }, {  }>;
  billto_country: WebAttribute<Quote_Select, { billto_country: string | null }, {  }>;
  billto_fax: WebAttribute<Quote_Select, { billto_fax: string | null }, {  }>;
  billto_line1: WebAttribute<Quote_Select, { billto_line1: string | null }, {  }>;
  billto_line2: WebAttribute<Quote_Select, { billto_line2: string | null }, {  }>;
  billto_line3: WebAttribute<Quote_Select, { billto_line3: string | null }, {  }>;
  billto_name: WebAttribute<Quote_Select, { billto_name: string | null }, {  }>;
  billto_postalcode: WebAttribute<Quote_Select, { billto_postalcode: string | null }, {  }>;
  billto_stateorprovince: WebAttribute<Quote_Select, { billto_stateorprovince: string | null }, {  }>;
  billto_telephone: WebAttribute<Quote_Select, { billto_telephone: string | null }, {  }>;
  campaignid_guid: WebAttribute<Quote_Select, { campaignid_guid: string | null }, { campaignid_formatted?: string }>;
  closedon: WebAttribute<Quote_Select, { closedon: Date | null }, { closedon_formatted?: string }>;
  contactid_guid: WebAttribute<Quote_Select, { contactid_guid: string | null }, { contactid_formatted?: string }>;
  createdby_guid: WebAttribute<Quote_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Quote_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Quote_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customerid_guid: WebAttribute<Quote_Select, { customerid_guid: string | null }, { customerid_formatted?: string }>;
  description: WebAttribute<Quote_Select, { description: string | null }, {  }>;
  discountamount: WebAttribute<Quote_Select, { discountamount: number | null; transactioncurrencyid_guid: string | null }, { discountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  discountamount_base: WebAttribute<Quote_Select, { discountamount_base: number | null; transactioncurrencyid_guid: string | null }, { discountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  discountpercentage: WebAttribute<Quote_Select, { discountpercentage: number | null }, {  }>;
  effectivefrom: WebAttribute<Quote_Select, { effectivefrom: Date | null }, { effectivefrom_formatted?: string }>;
  effectiveto: WebAttribute<Quote_Select, { effectiveto: Date | null }, { effectiveto_formatted?: string }>;
  emailaddress: WebAttribute<Quote_Select, { emailaddress: string | null }, {  }>;
  exchangerate: WebAttribute<Quote_Select, { exchangerate: number | null }, {  }>;
  expireson: WebAttribute<Quote_Select, { expireson: Date | null }, { expireson_formatted?: string }>;
  freightamount: WebAttribute<Quote_Select, { freightamount: number | null; transactioncurrencyid_guid: string | null }, { freightamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  freightamount_base: WebAttribute<Quote_Select, { freightamount_base: number | null; transactioncurrencyid_guid: string | null }, { freightamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  freighttermscode: WebAttribute<Quote_Select, { freighttermscode: quote_freighttermscode | null }, { freighttermscode_formatted?: string }>;
  importsequencenumber: WebAttribute<Quote_Select, { importsequencenumber: number | null }, {  }>;
  lastonholdtime: WebAttribute<Quote_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  modifiedby_guid: WebAttribute<Quote_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Quote_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Quote_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Quote_Select, { name: string | null }, {  }>;
  onholdtime: WebAttribute<Quote_Select, { onholdtime: number | null }, {  }>;
  opportunityid_guid: WebAttribute<Quote_Select, { opportunityid_guid: string | null }, { opportunityid_formatted?: string }>;
  overriddencreatedon: WebAttribute<Quote_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Quote_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Quote_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Quote_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Quote_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  paymenttermscode: WebAttribute<Quote_Select, { paymenttermscode: quote_paymenttermscode | null }, { paymenttermscode_formatted?: string }>;
  pricelevelid_guid: WebAttribute<Quote_Select, { pricelevelid_guid: string | null }, { pricelevelid_formatted?: string }>;
  pricingerrorcode: WebAttribute<Quote_Select, { pricingerrorcode: qooi_pricingerrorcode | null }, { pricingerrorcode_formatted?: string }>;
  processid: WebAttribute<Quote_Select, { processid: string | null }, {  }>;
  quoteid: WebAttribute<Quote_Select, { quoteid: string | null }, {  }>;
  quotenumber: WebAttribute<Quote_Select, { quotenumber: string | null }, {  }>;
  requestdeliveryby: WebAttribute<Quote_Select, { requestdeliveryby: Date | null }, { requestdeliveryby_formatted?: string }>;
  revisionnumber: WebAttribute<Quote_Select, { revisionnumber: number | null }, {  }>;
  shippingmethodcode: WebAttribute<Quote_Select, { shippingmethodcode: quote_shippingmethodcode | null }, { shippingmethodcode_formatted?: string }>;
  shipto_addressid: WebAttribute<Quote_Select, { shipto_addressid: string | null }, {  }>;
  shipto_city: WebAttribute<Quote_Select, { shipto_city: string | null }, {  }>;
  shipto_composite: WebAttribute<Quote_Select, { shipto_composite: string | null }, {  }>;
  shipto_contactname: WebAttribute<Quote_Select, { shipto_contactname: string | null }, {  }>;
  shipto_country: WebAttribute<Quote_Select, { shipto_country: string | null }, {  }>;
  shipto_fax: WebAttribute<Quote_Select, { shipto_fax: string | null }, {  }>;
  shipto_freighttermscode: WebAttribute<Quote_Select, { shipto_freighttermscode: quote_shipto_freighttermscode | null }, { shipto_freighttermscode_formatted?: string }>;
  shipto_line1: WebAttribute<Quote_Select, { shipto_line1: string | null }, {  }>;
  shipto_line2: WebAttribute<Quote_Select, { shipto_line2: string | null }, {  }>;
  shipto_line3: WebAttribute<Quote_Select, { shipto_line3: string | null }, {  }>;
  shipto_name: WebAttribute<Quote_Select, { shipto_name: string | null }, {  }>;
  shipto_postalcode: WebAttribute<Quote_Select, { shipto_postalcode: string | null }, {  }>;
  shipto_stateorprovince: WebAttribute<Quote_Select, { shipto_stateorprovince: string | null }, {  }>;
  shipto_telephone: WebAttribute<Quote_Select, { shipto_telephone: string | null }, {  }>;
  skippricecalculation: WebAttribute<Quote_Select, { skippricecalculation: qooi_skippricecalculation | null }, { skippricecalculation_formatted?: string }>;
  slaid_guid: WebAttribute<Quote_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Quote_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  stageid: WebAttribute<Quote_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Quote_Select, { statecode: quote_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Quote_Select, { statuscode: quote_statuscode | null }, { statuscode_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<Quote_Select, { timezoneruleversionnumber: number | null }, {  }>;
  totalamount: WebAttribute<Quote_Select, { totalamount: number | null; transactioncurrencyid_guid: string | null }, { totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalamount_base: WebAttribute<Quote_Select, { totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalamountlessfreight: WebAttribute<Quote_Select, { totalamountlessfreight: number | null; transactioncurrencyid_guid: string | null }, { totalamountlessfreight_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalamountlessfreight_base: WebAttribute<Quote_Select, { totalamountlessfreight_base: number | null; transactioncurrencyid_guid: string | null }, { totalamountlessfreight_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaldiscountamount: WebAttribute<Quote_Select, { totaldiscountamount: number | null; transactioncurrencyid_guid: string | null }, { totaldiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaldiscountamount_base: WebAttribute<Quote_Select, { totaldiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { totaldiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemamount: WebAttribute<Quote_Select, { totallineitemamount: number | null; transactioncurrencyid_guid: string | null }, { totallineitemamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemamount_base: WebAttribute<Quote_Select, { totallineitemamount_base: number | null; transactioncurrencyid_guid: string | null }, { totallineitemamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemdiscountamount: WebAttribute<Quote_Select, { totallineitemdiscountamount: number | null; transactioncurrencyid_guid: string | null }, { totallineitemdiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemdiscountamount_base: WebAttribute<Quote_Select, { totallineitemdiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { totallineitemdiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaltax: WebAttribute<Quote_Select, { totaltax: number | null; transactioncurrencyid_guid: string | null }, { totaltax_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaltax_base: WebAttribute<Quote_Select, { totaltax_base: number | null; transactioncurrencyid_guid: string | null }, { totaltax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Quote_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Quote_Select, { traversedpath: string | null }, {  }>;
  uniquedscid: WebAttribute<Quote_Select, { uniquedscid: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Quote_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Quote_Select, { versionnumber: number | null }, {  }>;
  willcall: WebAttribute<Quote_Select, { willcall: boolean | null }, {  }>;
}
interface Quote_Filter {
  accountid_guid: XQW.Guid;
  billto_addressid: XQW.Guid;
  billto_city: string;
  billto_composite: string;
  billto_contactname: string;
  billto_country: string;
  billto_fax: string;
  billto_line1: string;
  billto_line2: string;
  billto_line3: string;
  billto_name: string;
  billto_postalcode: string;
  billto_stateorprovince: string;
  billto_telephone: string;
  campaignid_guid: XQW.Guid;
  closedon: Date;
  contactid_guid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customerid_guid: XQW.Guid;
  description: string;
  discountamount: number;
  discountamount_base: number;
  discountpercentage: any;
  effectivefrom: Date;
  effectiveto: Date;
  emailaddress: string;
  exchangerate: any;
  expireson: Date;
  freightamount: number;
  freightamount_base: number;
  freighttermscode: quote_freighttermscode;
  importsequencenumber: number;
  lastonholdtime: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  onholdtime: number;
  opportunityid_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  paymenttermscode: quote_paymenttermscode;
  pricelevelid_guid: XQW.Guid;
  pricingerrorcode: qooi_pricingerrorcode;
  processid: XQW.Guid;
  quoteid: XQW.Guid;
  quotenumber: string;
  requestdeliveryby: Date;
  revisionnumber: number;
  shippingmethodcode: quote_shippingmethodcode;
  shipto_addressid: XQW.Guid;
  shipto_city: string;
  shipto_composite: string;
  shipto_contactname: string;
  shipto_country: string;
  shipto_fax: string;
  shipto_freighttermscode: quote_shipto_freighttermscode;
  shipto_line1: string;
  shipto_line2: string;
  shipto_line3: string;
  shipto_name: string;
  shipto_postalcode: string;
  shipto_stateorprovince: string;
  shipto_telephone: string;
  skippricecalculation: qooi_skippricecalculation;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: quote_statecode;
  statuscode: quote_statuscode;
  timezoneruleversionnumber: number;
  totalamount: number;
  totalamount_base: number;
  totalamountlessfreight: number;
  totalamountlessfreight_base: number;
  totaldiscountamount: number;
  totaldiscountamount_base: number;
  totallineitemamount: number;
  totallineitemamount_base: number;
  totallineitemdiscountamount: number;
  totallineitemdiscountamount_base: number;
  totaltax: number;
  totaltax_base: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  uniquedscid: XQW.Guid;
  utcconversiontimezonecode: number;
  versionnumber: number;
  willcall: boolean;
}
interface Quote_Expand {
  Quote_ActivityPointers: WebExpand<Quote_Expand, ActivityPointer_Select, ActivityPointer_Filter, { Quote_ActivityPointers: ActivityPointer_Result[] }>;
  Quote_Annotation: WebExpand<Quote_Expand, Annotation_Select, Annotation_Filter, { Quote_Annotation: Annotation_Result[] }>;
  Quote_Appointments: WebExpand<Quote_Expand, Appointment_Select, Appointment_Filter, { Quote_Appointments: Appointment_Result[] }>;
  Quote_AsyncOperations: WebExpand<Quote_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Quote_AsyncOperations: AsyncOperation_Result[] }>;
  Quote_BulkDeleteFailures: WebExpand<Quote_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Quote_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Quote_DuplicateBaseRecord: WebExpand<Quote_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Quote_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Quote_DuplicateMatchingRecord: WebExpand<Quote_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Quote_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Quote_Emails: WebExpand<Quote_Expand, Email_Select, Email_Filter, { Quote_Emails: Email_Result[] }>;
  Quote_Faxes: WebExpand<Quote_Expand, Fax_Select, Fax_Filter, { Quote_Faxes: Fax_Result[] }>;
  Quote_Letters: WebExpand<Quote_Expand, Letter_Select, Letter_Filter, { Quote_Letters: Letter_Result[] }>;
  Quote_MailboxTrackingFolder: WebExpand<Quote_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { Quote_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  Quote_Phonecalls: WebExpand<Quote_Expand, PhoneCall_Select, PhoneCall_Filter, { Quote_Phonecalls: PhoneCall_Result[] }>;
  Quote_ProcessSessions: WebExpand<Quote_Expand, ProcessSession_Select, ProcessSession_Filter, { Quote_ProcessSessions: ProcessSession_Result[] }>;
  Quote_QuoteClose: WebExpand<Quote_Expand, QuoteClose_Select, QuoteClose_Filter, { Quote_QuoteClose: QuoteClose_Result[] }>;
  Quote_RecurringAppointmentMasters: WebExpand<Quote_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { Quote_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  Quote_ServiceAppointments: WebExpand<Quote_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { Quote_ServiceAppointments: ServiceAppointment_Result[] }>;
  Quote_SharepointDocument: WebExpand<Quote_Expand, SharePointDocument_Select, SharePointDocument_Filter, { Quote_SharepointDocument: SharePointDocument_Result[] }>;
  Quote_SharepointDocumentLocation: WebExpand<Quote_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { Quote_SharepointDocumentLocation: SharePointDocumentLocation_Result[] }>;
  Quote_SocialActivities: WebExpand<Quote_Expand, SocialActivity_Select, SocialActivity_Filter, { Quote_SocialActivities: SocialActivity_Result[] }>;
  Quote_SyncErrors: WebExpand<Quote_Expand, SyncError_Select, SyncError_Filter, { Quote_SyncErrors: SyncError_Result[] }>;
  Quote_Tasks: WebExpand<Quote_Expand, Task_Select, Task_Filter, { Quote_Tasks: Task_Result[] }>;
  campaignid: WebExpand<Quote_Expand, Campaign_Select, Campaign_Filter, { campaignid: Campaign_Result }>;
  contactquotes_association: WebExpand<Quote_Expand, Contact_Select, Contact_Filter, { contactquotes_association: Contact_Result[] }>;
  createdby: WebExpand<Quote_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Quote_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  customerid_account: WebExpand<Quote_Expand, Account_Select, Account_Filter, { customerid_account: Account_Result }>;
  customerid_contact: WebExpand<Quote_Expand, Contact_Select, Contact_Filter, { customerid_contact: Contact_Result }>;
  modifiedby: WebExpand<Quote_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Quote_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_playbookinstance_quote: WebExpand<Quote_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { msdyn_playbookinstance_quote: msdyn_playbookinstance_Result[] }>;
  opportunityid: WebExpand<Quote_Expand, Opportunity_Select, Opportunity_Filter, { opportunityid: Opportunity_Result }>;
  ownerid: WebExpand<Quote_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Quote_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<Quote_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<Quote_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  pricelevelid: WebExpand<Quote_Expand, PriceLevel_Select, PriceLevel_Filter, { pricelevelid: PriceLevel_Result }>;
  quote_QuoteCloses: WebExpand<Quote_Expand, QuoteClose_Select, QuoteClose_Filter, { quote_QuoteCloses: QuoteClose_Result[] }>;
  quote_activity_parties: WebExpand<Quote_Expand, ActivityParty_Select, ActivityParty_Filter, { quote_activity_parties: ActivityParty_Result[] }>;
  quote_awcnpd_feedbacks: WebExpand<Quote_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { quote_awcnpd_feedbacks: awcnpd_feedback_Result[] }>;
  quote_connections1: WebExpand<Quote_Expand, Connection_Select, Connection_Filter, { quote_connections1: Connection_Result[] }>;
  quote_connections2: WebExpand<Quote_Expand, Connection_Select, Connection_Filter, { quote_connections2: Connection_Result[] }>;
  quote_details: WebExpand<Quote_Expand, QuoteDetail_Select, QuoteDetail_Filter, { quote_details: QuoteDetail_Result[] }>;
  quote_opportunitysalesprocess: WebExpand<Quote_Expand, OpportunitySalesProcess_Select, OpportunitySalesProcess_Filter, { quote_opportunitysalesprocess: OpportunitySalesProcess_Result[] }>;
  quote_orders: WebExpand<Quote_Expand, SalesOrder_Select, SalesOrder_Filter, { quote_orders: SalesOrder_Result[] }>;
  quote_principalobjectattributeaccess: WebExpand<Quote_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { quote_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  sla_quote_sla: WebExpand<Quote_Expand, SLA_Select, SLA_Filter, { sla_quote_sla: SLA_Result }>;
  slainvokedid_quote_sla: WebExpand<Quote_Expand, SLA_Select, SLA_Filter, { slainvokedid_quote_sla: SLA_Result }>;
  slakpiinstance_quote: WebExpand<Quote_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_quote: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Quote_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<Quote_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_quote: WebExpand<Quote_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_quote: UserEntityInstanceData_Result[] }>;
}
interface Quote_FormattedResult {
  accountid_formatted?: string;
  campaignid_formatted?: string;
  closedon_formatted?: string;
  contactid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customerid_formatted?: string;
  discountamount_base_formatted?: string;
  discountamount_formatted?: string;
  effectivefrom_formatted?: string;
  effectiveto_formatted?: string;
  expireson_formatted?: string;
  freightamount_base_formatted?: string;
  freightamount_formatted?: string;
  freighttermscode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  opportunityid_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  paymenttermscode_formatted?: string;
  pricelevelid_formatted?: string;
  pricingerrorcode_formatted?: string;
  requestdeliveryby_formatted?: string;
  shippingmethodcode_formatted?: string;
  shipto_freighttermscode_formatted?: string;
  skippricecalculation_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  totalamount_base_formatted?: string;
  totalamount_formatted?: string;
  totalamountlessfreight_base_formatted?: string;
  totalamountlessfreight_formatted?: string;
  totaldiscountamount_base_formatted?: string;
  totaldiscountamount_formatted?: string;
  totallineitemamount_base_formatted?: string;
  totallineitemamount_formatted?: string;
  totallineitemdiscountamount_base_formatted?: string;
  totallineitemdiscountamount_formatted?: string;
  totaltax_base_formatted?: string;
  totaltax_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Quote_Result extends Quote_Base, Quote_Relationships {
  "@odata.etag": string;
  accountid_guid: string | null;
  campaignid_guid: string | null;
  contactid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customerid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  opportunityid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  pricelevelid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Quote_RelatedOne {
  campaignid: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  customerid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  customerid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  opportunityid: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  pricelevelid: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  sla_quote_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_quote_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Quote_RelatedMany {
  Quote_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  Quote_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Quote_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  Quote_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Quote_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Quote_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Quote_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Quote_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  Quote_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  Quote_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  Quote_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  Quote_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  Quote_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Quote_QuoteClose: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  Quote_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  Quote_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  Quote_SharepointDocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  Quote_SharepointDocumentLocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  Quote_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  Quote_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  Quote_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  contactquotes_association: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  msdyn_playbookinstance_quote: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  quote_QuoteCloses: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  quote_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  quote_awcnpd_feedbacks: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  quote_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  quote_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  quote_details: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  quote_opportunitysalesprocess: WebMappingRetrieve<OpportunitySalesProcess_Select,OpportunitySalesProcess_Expand,OpportunitySalesProcess_Filter,OpportunitySalesProcess_Fixed,OpportunitySalesProcess_Result,OpportunitySalesProcess_FormattedResult>;
  quote_orders: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  quote_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_quote: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_quote: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  quotes: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
}
interface WebEntitiesRelated {
  quotes: WebMappingRelated<Quote_RelatedOne,Quote_RelatedMany>;
}
interface WebEntitiesCUDA {
  quotes: WebMappingCUDA<Quote_Create,Quote_Update,Quote_Select>;
}
