interface RecurringAppointmentMaster_Base extends WebEntity {
  activityid?: string | null;
  activitytypecode?: string | null;
  category?: string | null;
  createdon?: Date | null;
  dayofmonth?: number | null;
  daysofweekmask?: number | null;
  deletedexceptionslist?: string | null;
  description?: string | null;
  duration?: number | null;
  effectiveenddate?: Date | null;
  effectivestartdate?: Date | null;
  endtime?: Date | null;
  exchangerate?: number | null;
  expansionstatecode?: recurringappointmentmaster_expansionstatecode | null;
  firstdayofweek?: number | null;
  globalobjectid?: string | null;
  importsequencenumber?: number | null;
  instance?: recurringappointmentmaster_instance | null;
  instancetypecode?: recurringappointmentmaster_instancetypecode | null;
  interval?: number | null;
  isalldayevent?: boolean | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isnthmonthly?: boolean | null;
  isnthyearly?: boolean | null;
  isregenerate?: boolean | null;
  isregularactivity?: boolean | null;
  isunsafe?: number | null;
  isweekdaypattern?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastexpandedinstancedate?: Date | null;
  location?: string | null;
  modifiedon?: Date | null;
  monthofyear?: recurrencerule_monthofyear | null;
  nextexpansioninstancedate?: Date | null;
  occurrences?: number | null;
  outlookownerapptid?: number | null;
  overriddencreatedon?: Date | null;
  patternenddate?: Date | null;
  patternendtype?: recurringappointmentmaster_patternendtype | null;
  patternstartdate?: Date | null;
  prioritycode?: recurringappointmentmaster_prioritycode | null;
  processid?: string | null;
  recurrencepatterntype?: recurringappointmentmaster_recurrencepatterntype | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  seriesstatus?: boolean | null;
  sortdate?: Date | null;
  stageid?: string | null;
  starttime?: Date | null;
  statecode?: recurringappointmentmaster_statecode | null;
  statuscode?: recurringappointmentmaster_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface RecurringAppointmentMaster_Relationships {
  RecurringAppointmentMaster_Annotation?: Annotation_Result[] | null;
  RecurringAppointmentMaster_AsyncOperations?: AsyncOperation_Result[] | null;
  RecurringAppointmentMaster_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  RecurringAppointmentMaster_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  RecurringAppointmentMaster_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  RecurringAppointmentMaster_ProcessSessions?: ProcessSession_Result[] | null;
  RecurringAppointmentMaster_QueueItem?: QueueItem_Result[] | null;
  RecurringAppointmentMaster_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  activityid_recurrencerule?: RecurrenceRule_Result | null;
  createdby_recurringappointmentmaster?: SystemUser_Result | null;
  createdonbehalfby_recurringappointmentmaster?: SystemUser_Result | null;
  modifiedby_recurringappointmentmaster?: SystemUser_Result | null;
  modifiedonbehalfby_recurringappointmentmaster?: SystemUser_Result | null;
  ownerid_recurringappointmentmaster?: Team_Result | null;
  ownerid_recurringappointmentmaster1?: SystemUser_Result | null;
  owningbusinessunit_recurringappointmentmaster?: BusinessUnit_Result | null;
  owningteam_recurringappointmentmaster?: Team_Result | null;
  owninguser_recurringappointmentmaster?: SystemUser_Result | null;
  recurringappointmentmaster_PostFollows?: PostFollow_Result[] | null;
  recurringappointmentmaster_PostRegardings?: PostRegarding_Result[] | null;
  recurringappointmentmaster_PostRoles?: PostRole_Result[] | null;
  recurringappointmentmaster_actioncard?: ActionCard_Result[] | null;
  recurringappointmentmaster_activity_parties?: ActivityParty_Result[] | null;
  recurringappointmentmaster_appointment?: Appointment_Result[] | null;
  recurringappointmentmaster_campaignresponse?: CampaignResponse_Result[] | null;
  recurringappointmentmaster_connections1?: Connection_Result[] | null;
  recurringappointmentmaster_connections2?: Connection_Result[] | null;
  recurringappointmentmaster_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  regardingobjectid_account_recurringappointmentmaster?: Account_Result | null;
  regardingobjectid_awc_prototype_recurringappointmentmaster?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_recurringappointmentmaster?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_recurringappointmentmaster?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_recurringappointmentmaster?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_recurringappointmentmaster?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_recurringappointmentmaster?: BulkOperation_Result | null;
  regardingobjectid_campaign_recurringappointmentmaster?: Campaign_Result | null;
  regardingobjectid_campaignactivity_recurringappointmentmaster?: CampaignActivity_Result | null;
  regardingobjectid_contact_recurringappointmentmaster?: Contact_Result | null;
  regardingobjectid_contract_recurringappointmentmaster?: Contract_Result | null;
  regardingobjectid_entitlement_recurringappointmentmaster?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_recurringappointmentmaster?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_recurringappointmentmaster?: Incident_Result | null;
  regardingobjectid_invoice_recurringappointmentmaster?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_recurringappointmentmaster?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_recurringappointmentmaster?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_recurringappointmentmaster?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_recurringappointmentmaster?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_recurringappointmentmaster?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_recurringappointmentmaster?: Opportunity_Result | null;
  regardingobjectid_quote_recurringappointmentmaster?: Quote_Result | null;
  regardingobjectid_salesorder_recurringappointmentmaster?: SalesOrder_Result | null;
  regardingobjectid_site_recurringappointmentmaster?: Site_Result | null;
  serviceid_recurringappointmentmaster?: Service_Result | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_recurringappointmentmaster?: TransactionCurrency_Result | null;
  userentityinstancedata_recurringappointmentmaster?: UserEntityInstanceData_Result[] | null;
}
interface RecurringAppointmentMaster extends RecurringAppointmentMaster_Base, RecurringAppointmentMaster_Relationships {
  ownerid_recurringappointmentmaster_bind$systemusers?: string | null;
  ownerid_recurringappointmentmaster_bind$teams?: string | null;
  regardingobjectid_account_recurringappointmentmaster_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_recurringappointmentmaster_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_recurringappointmentmaster_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_recurringappointmentmaster_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_recurringappointmentmaster_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_recurringappointmentmaster_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_recurringappointmentmaster_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_recurringappointmentmaster_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_recurringappointmentmaster_bind$campaignactivities?: string | null;
  regardingobjectid_contact_recurringappointmentmaster_bind$contacts?: string | null;
  regardingobjectid_contract_recurringappointmentmaster_bind$contracts?: string | null;
  regardingobjectid_entitlement_recurringappointmentmaster_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_recurringappointmentmaster_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_recurringappointmentmaster_bind$incidents?: string | null;
  regardingobjectid_invoice_recurringappointmentmaster_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_recurringappointmentmaster_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_recurringappointmentmaster_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_recurringappointmentmaster_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_recurringappointmentmaster_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_recurringappointmentmaster_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_recurringappointmentmaster_bind$opportunities?: string | null;
  regardingobjectid_quote_recurringappointmentmaster_bind$quotes?: string | null;
  regardingobjectid_salesorder_recurringappointmentmaster_bind$salesorders?: string | null;
  regardingobjectid_site_recurringappointmentmaster_bind$sites?: string | null;
  serviceid_recurringappointmentmaster_bind$services?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_recurringappointmentmaster_bind$transactioncurrencies?: string | null;
}
interface RecurringAppointmentMaster_Create extends RecurringAppointmentMaster {
  activityid_activitypointer_bind$activitypointers?: string | null;
  activityid_recurrencerule_bind$recurrencerules?: string | null;
}
interface RecurringAppointmentMaster_Update extends RecurringAppointmentMaster {
}
interface RecurringAppointmentMaster_Select {
  activityid: WebAttribute<RecurringAppointmentMaster_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<RecurringAppointmentMaster_Select, { activitytypecode: string | null }, {  }>;
  category: WebAttribute<RecurringAppointmentMaster_Select, { category: string | null }, {  }>;
  createdby_guid: WebAttribute<RecurringAppointmentMaster_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<RecurringAppointmentMaster_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<RecurringAppointmentMaster_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  dayofmonth: WebAttribute<RecurringAppointmentMaster_Select, { dayofmonth: number | null }, {  }>;
  daysofweekmask: WebAttribute<RecurringAppointmentMaster_Select, { daysofweekmask: number | null }, {  }>;
  deletedexceptionslist: WebAttribute<RecurringAppointmentMaster_Select, { deletedexceptionslist: string | null }, {  }>;
  description: WebAttribute<RecurringAppointmentMaster_Select, { description: string | null }, {  }>;
  duration: WebAttribute<RecurringAppointmentMaster_Select, { duration: number | null }, {  }>;
  effectiveenddate: WebAttribute<RecurringAppointmentMaster_Select, { effectiveenddate: Date | null }, { effectiveenddate_formatted?: string }>;
  effectivestartdate: WebAttribute<RecurringAppointmentMaster_Select, { effectivestartdate: Date | null }, { effectivestartdate_formatted?: string }>;
  endtime: WebAttribute<RecurringAppointmentMaster_Select, { endtime: Date | null }, { endtime_formatted?: string }>;
  exchangerate: WebAttribute<RecurringAppointmentMaster_Select, { exchangerate: number | null }, {  }>;
  expansionstatecode: WebAttribute<RecurringAppointmentMaster_Select, { expansionstatecode: recurringappointmentmaster_expansionstatecode | null }, { expansionstatecode_formatted?: string }>;
  firstdayofweek: WebAttribute<RecurringAppointmentMaster_Select, { firstdayofweek: number | null }, {  }>;
  globalobjectid: WebAttribute<RecurringAppointmentMaster_Select, { globalobjectid: string | null }, {  }>;
  groupid_guid: WebAttribute<RecurringAppointmentMaster_Select, { groupid_guid: string | null }, { groupid_formatted?: string }>;
  importsequencenumber: WebAttribute<RecurringAppointmentMaster_Select, { importsequencenumber: number | null }, {  }>;
  instance: WebAttribute<RecurringAppointmentMaster_Select, { instance: recurringappointmentmaster_instance | null }, { instance_formatted?: string }>;
  instancetypecode: WebAttribute<RecurringAppointmentMaster_Select, { instancetypecode: recurringappointmentmaster_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  interval: WebAttribute<RecurringAppointmentMaster_Select, { interval: number | null }, {  }>;
  isalldayevent: WebAttribute<RecurringAppointmentMaster_Select, { isalldayevent: boolean | null }, {  }>;
  isbilled: WebAttribute<RecurringAppointmentMaster_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<RecurringAppointmentMaster_Select, { ismapiprivate: boolean | null }, {  }>;
  isnthmonthly: WebAttribute<RecurringAppointmentMaster_Select, { isnthmonthly: boolean | null }, {  }>;
  isnthyearly: WebAttribute<RecurringAppointmentMaster_Select, { isnthyearly: boolean | null }, {  }>;
  isregenerate: WebAttribute<RecurringAppointmentMaster_Select, { isregenerate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<RecurringAppointmentMaster_Select, { isregularactivity: boolean | null }, {  }>;
  isunsafe: WebAttribute<RecurringAppointmentMaster_Select, { isunsafe: number | null }, {  }>;
  isweekdaypattern: WebAttribute<RecurringAppointmentMaster_Select, { isweekdaypattern: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<RecurringAppointmentMaster_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastexpandedinstancedate: WebAttribute<RecurringAppointmentMaster_Select, { lastexpandedinstancedate: Date | null }, { lastexpandedinstancedate_formatted?: string }>;
  location: WebAttribute<RecurringAppointmentMaster_Select, { location: string | null }, {  }>;
  modifiedby_guid: WebAttribute<RecurringAppointmentMaster_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<RecurringAppointmentMaster_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<RecurringAppointmentMaster_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  monthofyear: WebAttribute<RecurringAppointmentMaster_Select, { monthofyear: recurrencerule_monthofyear | null }, { monthofyear_formatted?: string }>;
  nextexpansioninstancedate: WebAttribute<RecurringAppointmentMaster_Select, { nextexpansioninstancedate: Date | null }, { nextexpansioninstancedate_formatted?: string }>;
  occurrences: WebAttribute<RecurringAppointmentMaster_Select, { occurrences: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<RecurringAppointmentMaster_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<RecurringAppointmentMaster_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  outlookownerapptid: WebAttribute<RecurringAppointmentMaster_Select, { outlookownerapptid: number | null }, {  }>;
  overriddencreatedon: WebAttribute<RecurringAppointmentMaster_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<RecurringAppointmentMaster_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<RecurringAppointmentMaster_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<RecurringAppointmentMaster_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<RecurringAppointmentMaster_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  patternenddate: WebAttribute<RecurringAppointmentMaster_Select, { patternenddate: Date | null }, { patternenddate_formatted?: string }>;
  patternendtype: WebAttribute<RecurringAppointmentMaster_Select, { patternendtype: recurringappointmentmaster_patternendtype | null }, { patternendtype_formatted?: string }>;
  patternstartdate: WebAttribute<RecurringAppointmentMaster_Select, { patternstartdate: Date | null }, { patternstartdate_formatted?: string }>;
  prioritycode: WebAttribute<RecurringAppointmentMaster_Select, { prioritycode: recurringappointmentmaster_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<RecurringAppointmentMaster_Select, { processid: string | null }, {  }>;
  recurrencepatterntype: WebAttribute<RecurringAppointmentMaster_Select, { recurrencepatterntype: recurringappointmentmaster_recurrencepatterntype | null }, { recurrencepatterntype_formatted?: string }>;
  regardingobjectid_guid: WebAttribute<RecurringAppointmentMaster_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<RecurringAppointmentMaster_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  ruleid_guid: WebAttribute<RecurringAppointmentMaster_Select, { ruleid_guid: string | null }, { ruleid_formatted?: string }>;
  scheduledend: WebAttribute<RecurringAppointmentMaster_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<RecurringAppointmentMaster_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  seriesstatus: WebAttribute<RecurringAppointmentMaster_Select, { seriesstatus: boolean | null }, {  }>;
  serviceid_guid: WebAttribute<RecurringAppointmentMaster_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  sortdate: WebAttribute<RecurringAppointmentMaster_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<RecurringAppointmentMaster_Select, { stageid: string | null }, {  }>;
  starttime: WebAttribute<RecurringAppointmentMaster_Select, { starttime: Date | null }, { starttime_formatted?: string }>;
  statecode: WebAttribute<RecurringAppointmentMaster_Select, { statecode: recurringappointmentmaster_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<RecurringAppointmentMaster_Select, { statuscode: recurringappointmentmaster_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<RecurringAppointmentMaster_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<RecurringAppointmentMaster_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<RecurringAppointmentMaster_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<RecurringAppointmentMaster_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<RecurringAppointmentMaster_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<RecurringAppointmentMaster_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<RecurringAppointmentMaster_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<RecurringAppointmentMaster_Select, { versionnumber: number | null }, {  }>;
}
interface RecurringAppointmentMaster_Filter {
  activityid: XQW.Guid;
  activitytypecode: string;
  category: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  dayofmonth: number;
  daysofweekmask: number;
  deletedexceptionslist: string;
  description: string;
  duration: number;
  effectiveenddate: Date;
  effectivestartdate: Date;
  endtime: Date;
  exchangerate: any;
  expansionstatecode: recurringappointmentmaster_expansionstatecode;
  firstdayofweek: number;
  globalobjectid: string;
  groupid_guid: XQW.Guid;
  importsequencenumber: number;
  instance: recurringappointmentmaster_instance;
  instancetypecode: recurringappointmentmaster_instancetypecode;
  interval: number;
  isalldayevent: boolean;
  isbilled: boolean;
  ismapiprivate: boolean;
  isnthmonthly: boolean;
  isnthyearly: boolean;
  isregenerate: boolean;
  isregularactivity: boolean;
  isunsafe: number;
  isweekdaypattern: boolean;
  isworkflowcreated: boolean;
  lastexpandedinstancedate: Date;
  location: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  monthofyear: recurrencerule_monthofyear;
  nextexpansioninstancedate: Date;
  occurrences: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  outlookownerapptid: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  patternenddate: Date;
  patternendtype: recurringappointmentmaster_patternendtype;
  patternstartdate: Date;
  prioritycode: recurringappointmentmaster_prioritycode;
  processid: XQW.Guid;
  recurrencepatterntype: recurringappointmentmaster_recurrencepatterntype;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  ruleid_guid: XQW.Guid;
  scheduledend: Date;
  scheduledstart: Date;
  seriesstatus: boolean;
  serviceid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  starttime: Date;
  statecode: recurringappointmentmaster_statecode;
  statuscode: recurringappointmentmaster_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface RecurringAppointmentMaster_Expand {
  RecurringAppointmentMaster_Annotation: WebExpand<RecurringAppointmentMaster_Expand, Annotation_Select, Annotation_Filter, { RecurringAppointmentMaster_Annotation: Annotation_Result[] }>;
  RecurringAppointmentMaster_AsyncOperations: WebExpand<RecurringAppointmentMaster_Expand, AsyncOperation_Select, AsyncOperation_Filter, { RecurringAppointmentMaster_AsyncOperations: AsyncOperation_Result[] }>;
  RecurringAppointmentMaster_BulkDeleteFailures: WebExpand<RecurringAppointmentMaster_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { RecurringAppointmentMaster_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  RecurringAppointmentMaster_DuplicateBaseRecord: WebExpand<RecurringAppointmentMaster_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { RecurringAppointmentMaster_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  RecurringAppointmentMaster_DuplicateMatchingRecord: WebExpand<RecurringAppointmentMaster_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { RecurringAppointmentMaster_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  RecurringAppointmentMaster_ProcessSessions: WebExpand<RecurringAppointmentMaster_Expand, ProcessSession_Select, ProcessSession_Filter, { RecurringAppointmentMaster_ProcessSessions: ProcessSession_Result[] }>;
  RecurringAppointmentMaster_QueueItem: WebExpand<RecurringAppointmentMaster_Expand, QueueItem_Select, QueueItem_Filter, { RecurringAppointmentMaster_QueueItem: QueueItem_Result[] }>;
  RecurringAppointmentMaster_SyncErrors: WebExpand<RecurringAppointmentMaster_Expand, SyncError_Select, SyncError_Filter, { RecurringAppointmentMaster_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<RecurringAppointmentMaster_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  activityid_recurrencerule: WebExpand<RecurringAppointmentMaster_Expand, RecurrenceRule_Select, RecurrenceRule_Filter, { activityid_recurrencerule: RecurrenceRule_Result }>;
  createdby_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SystemUser_Select, SystemUser_Filter, { createdby_recurringappointmentmaster: SystemUser_Result }>;
  createdonbehalfby_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_recurringappointmentmaster: SystemUser_Result }>;
  modifiedby_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_recurringappointmentmaster: SystemUser_Result }>;
  modifiedonbehalfby_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_recurringappointmentmaster: SystemUser_Result }>;
  ownerid_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_recurringappointmentmaster: SystemUser_Result } & { ownerid_recurringappointmentmaster: Team_Result }>;
  owningbusinessunit_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_recurringappointmentmaster: BusinessUnit_Result }>;
  owningteam_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Team_Select, Team_Filter, { owningteam_recurringappointmentmaster: Team_Result }>;
  owninguser_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_recurringappointmentmaster: SystemUser_Result }>;
  recurringappointmentmaster_PostFollows: WebExpand<RecurringAppointmentMaster_Expand, PostFollow_Select, PostFollow_Filter, { recurringappointmentmaster_PostFollows: PostFollow_Result[] }>;
  recurringappointmentmaster_PostRegardings: WebExpand<RecurringAppointmentMaster_Expand, PostRegarding_Select, PostRegarding_Filter, { recurringappointmentmaster_PostRegardings: PostRegarding_Result[] }>;
  recurringappointmentmaster_PostRoles: WebExpand<RecurringAppointmentMaster_Expand, PostRole_Select, PostRole_Filter, { recurringappointmentmaster_PostRoles: PostRole_Result[] }>;
  recurringappointmentmaster_actioncard: WebExpand<RecurringAppointmentMaster_Expand, ActionCard_Select, ActionCard_Filter, { recurringappointmentmaster_actioncard: ActionCard_Result[] }>;
  recurringappointmentmaster_activity_parties: WebExpand<RecurringAppointmentMaster_Expand, ActivityParty_Select, ActivityParty_Filter, { recurringappointmentmaster_activity_parties: ActivityParty_Result[] }>;
  recurringappointmentmaster_appointment: WebExpand<RecurringAppointmentMaster_Expand, Appointment_Select, Appointment_Filter, { recurringappointmentmaster_appointment: Appointment_Result[] }>;
  recurringappointmentmaster_campaignresponse: WebExpand<RecurringAppointmentMaster_Expand, CampaignResponse_Select, CampaignResponse_Filter, { recurringappointmentmaster_campaignresponse: CampaignResponse_Result[] }>;
  recurringappointmentmaster_connections1: WebExpand<RecurringAppointmentMaster_Expand, Connection_Select, Connection_Filter, { recurringappointmentmaster_connections1: Connection_Result[] }>;
  recurringappointmentmaster_connections2: WebExpand<RecurringAppointmentMaster_Expand, Connection_Select, Connection_Filter, { recurringappointmentmaster_connections2: Connection_Result[] }>;
  recurringappointmentmaster_principalobjectattributeaccess: WebExpand<RecurringAppointmentMaster_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { recurringappointmentmaster_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  regardingobjectid_account_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Account_Select, Account_Filter, { regardingobjectid_account_recurringappointmentmaster: Account_Result }>;
  regardingobjectid_awc_prototype_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_recurringappointmentmaster: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_recurringappointmentmaster: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_recurringappointmentmaster: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_recurringappointmentmaster: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_recurringappointmentmaster: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_recurringappointmentmaster: BulkOperation_Result }>;
  regardingobjectid_campaign_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_recurringappointmentmaster: Campaign_Result }>;
  regardingobjectid_campaignactivity_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_recurringappointmentmaster: CampaignActivity_Result }>;
  regardingobjectid_contact_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_recurringappointmentmaster: Contact_Result }>;
  regardingobjectid_contract_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_recurringappointmentmaster: Contract_Result }>;
  regardingobjectid_entitlement_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_recurringappointmentmaster: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_recurringappointmentmaster: EntitlementTemplate_Result }>;
  regardingobjectid_incident_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_recurringappointmentmaster: Incident_Result }>;
  regardingobjectid_invoice_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_recurringappointmentmaster: Invoice_Result }>;
  regardingobjectid_knowledgearticle_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_recurringappointmentmaster: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_recurringappointmentmaster: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_recurringappointmentmaster: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_recurringappointmentmaster: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_recurringappointmentmaster: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_recurringappointmentmaster: Opportunity_Result }>;
  regardingobjectid_quote_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_recurringappointmentmaster: Quote_Result }>;
  regardingobjectid_salesorder_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_recurringappointmentmaster: SalesOrder_Result }>;
  regardingobjectid_site_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Site_Select, Site_Filter, { regardingobjectid_site_recurringappointmentmaster: Site_Result }>;
  serviceid_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, Service_Select, Service_Filter, { serviceid_recurringappointmentmaster: Service_Result }>;
  stageid_processstage: WebExpand<RecurringAppointmentMaster_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_recurringappointmentmaster: TransactionCurrency_Result }>;
  userentityinstancedata_recurringappointmentmaster: WebExpand<RecurringAppointmentMaster_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_recurringappointmentmaster: UserEntityInstanceData_Result[] }>;
}
interface RecurringAppointmentMaster_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  effectiveenddate_formatted?: string;
  effectivestartdate_formatted?: string;
  endtime_formatted?: string;
  expansionstatecode_formatted?: string;
  groupid_formatted?: string;
  instance_formatted?: string;
  instancetypecode_formatted?: string;
  lastexpandedinstancedate_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  monthofyear_formatted?: string;
  nextexpansioninstancedate_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  patternenddate_formatted?: string;
  patternendtype_formatted?: string;
  patternstartdate_formatted?: string;
  prioritycode_formatted?: string;
  recurrencepatterntype_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  ruleid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  sortdate_formatted?: string;
  starttime_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface RecurringAppointmentMaster_Result extends RecurringAppointmentMaster_Base, RecurringAppointmentMaster_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  groupid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  ruleid_guid: string | null;
  serviceid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface RecurringAppointmentMaster_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  activityid_recurrencerule: WebMappingRetrieve<RecurrenceRule_Select,RecurrenceRule_Expand,RecurrenceRule_Filter,RecurrenceRule_Fixed,RecurrenceRule_Result,RecurrenceRule_FormattedResult>;
  createdby_recurringappointmentmaster: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_recurringappointmentmaster: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_recurringappointmentmaster: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_recurringappointmentmaster: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_recurringappointmentmaster: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_recurringappointmentmaster1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_recurringappointmentmaster: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_recurringappointmentmaster: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_recurringappointmentmaster: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_recurringappointmentmaster: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_recurringappointmentmaster: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_recurringappointmentmaster: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_recurringappointmentmaster: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_recurringappointmentmaster: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_recurringappointmentmaster: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_recurringappointmentmaster: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_recurringappointmentmaster: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_recurringappointmentmaster: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_recurringappointmentmaster: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_recurringappointmentmaster: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_recurringappointmentmaster: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_recurringappointmentmaster: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_recurringappointmentmaster: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_recurringappointmentmaster: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_recurringappointmentmaster: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_recurringappointmentmaster: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_recurringappointmentmaster: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_recurringappointmentmaster: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_recurringappointmentmaster: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_recurringappointmentmaster: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_recurringappointmentmaster: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_recurringappointmentmaster: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_recurringappointmentmaster: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  serviceid_recurringappointmentmaster: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_recurringappointmentmaster: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface RecurringAppointmentMaster_RelatedMany {
  RecurringAppointmentMaster_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  RecurringAppointmentMaster_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  RecurringAppointmentMaster_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  RecurringAppointmentMaster_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  RecurringAppointmentMaster_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  RecurringAppointmentMaster_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  RecurringAppointmentMaster_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  RecurringAppointmentMaster_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  recurringappointmentmaster_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  recurringappointmentmaster_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  recurringappointmentmaster_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  recurringappointmentmaster_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  recurringappointmentmaster_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  recurringappointmentmaster_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  recurringappointmentmaster_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  recurringappointmentmaster_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  recurringappointmentmaster_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  recurringappointmentmaster_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  userentityinstancedata_recurringappointmentmaster: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  recurringappointmentmasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
}
interface WebEntitiesRelated {
  recurringappointmentmasters: WebMappingRelated<RecurringAppointmentMaster_RelatedOne,RecurringAppointmentMaster_RelatedMany>;
}
interface WebEntitiesCUDA {
  recurringappointmentmasters: WebMappingCUDA<RecurringAppointmentMaster_Create,RecurringAppointmentMaster_Update,RecurringAppointmentMaster_Select>;
}
