interface SalesOrder_Base extends WebEntity {
  billto_addressid?: string | null;
  billto_city?: string | null;
  billto_composite?: string | null;
  billto_contactname?: string | null;
  billto_country?: string | null;
  billto_fax?: string | null;
  billto_line1?: string | null;
  billto_line2?: string | null;
  billto_line3?: string | null;
  billto_name?: string | null;
  billto_postalcode?: string | null;
  billto_stateorprovince?: string | null;
  billto_telephone?: string | null;
  createdon?: Date | null;
  datefulfilled?: Date | null;
  description?: string | null;
  discountamount?: number | null;
  discountamount_base?: number | null;
  discountpercentage?: number | null;
  emailaddress?: string | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  freightamount?: number | null;
  freightamount_base?: number | null;
  freighttermscode?: salesorder_freighttermscode | null;
  importsequencenumber?: number | null;
  ispricelocked?: boolean | null;
  lastbackofficesubmit?: Date | null;
  lastonholdtime?: Date | null;
  modifiedon?: Date | null;
  name?: string | null;
  onholdtime?: number | null;
  ordernumber?: string | null;
  overriddencreatedon?: Date | null;
  paymenttermscode?: salesorder_paymenttermscode | null;
  pricingerrorcode?: qooi_pricingerrorcode | null;
  prioritycode?: salesorder_prioritycode | null;
  processid?: string | null;
  requestdeliveryby?: Date | null;
  salesorderid?: string | null;
  shippingmethodcode?: salesorder_shippingmethodcode | null;
  shipto_addressid?: string | null;
  shipto_city?: string | null;
  shipto_composite?: string | null;
  shipto_contactname?: string | null;
  shipto_country?: string | null;
  shipto_fax?: string | null;
  shipto_freighttermscode?: salesorder_shipto_freighttermscode | null;
  shipto_line1?: string | null;
  shipto_line2?: string | null;
  shipto_line3?: string | null;
  shipto_name?: string | null;
  shipto_postalcode?: string | null;
  shipto_stateorprovince?: string | null;
  shipto_telephone?: string | null;
  skippricecalculation?: qooi_skippricecalculation | null;
  stageid?: string | null;
  statecode?: salesorder_statecode | null;
  statuscode?: salesorder_statuscode | null;
  submitdate?: Date | null;
  submitstatus?: number | null;
  submitstatusdescription?: string | null;
  timezoneruleversionnumber?: number | null;
  totalamount?: number | null;
  totalamount_base?: number | null;
  totalamountlessfreight?: number | null;
  totalamountlessfreight_base?: number | null;
  totaldiscountamount?: number | null;
  totaldiscountamount_base?: number | null;
  totallineitemamount?: number | null;
  totallineitemamount_base?: number | null;
  totallineitemdiscountamount?: number | null;
  totallineitemdiscountamount_base?: number | null;
  totaltax?: number | null;
  totaltax_base?: number | null;
  transactioncurrencyid_guid?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
  willcall?: boolean | null;
}
interface SalesOrder_Relationships {
  SalesOrder_ActivityPointers?: ActivityPointer_Result[] | null;
  SalesOrder_Annotation?: Annotation_Result[] | null;
  SalesOrder_Appointments?: Appointment_Result[] | null;
  SalesOrder_AsyncOperations?: AsyncOperation_Result[] | null;
  SalesOrder_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  SalesOrder_Emails?: Email_Result[] | null;
  SalesOrder_Faxes?: Fax_Result[] | null;
  SalesOrder_Letters?: Letter_Result[] | null;
  SalesOrder_MailboxTrackingFolder?: MailboxTrackingFolder_Result[] | null;
  SalesOrder_OrderClose?: OrderClose_Result[] | null;
  SalesOrder_Phonecalls?: PhoneCall_Result[] | null;
  SalesOrder_ProcessSessions?: ProcessSession_Result[] | null;
  SalesOrder_RecurringAppointmentMasters?: RecurringAppointmentMaster_Result[] | null;
  SalesOrder_ServiceAppointments?: ServiceAppointment_Result[] | null;
  SalesOrder_SocialActivities?: SocialActivity_Result[] | null;
  SalesOrder_SyncErrors?: SyncError_Result[] | null;
  SalesOrder_Tasks?: Task_Result[] | null;
  contactorders_association?: Contact_Result[] | null;
  customerid_account?: Account_Result | null;
  customerid_contact?: Contact_Result | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  msdyn_playbookinstance_salesorder?: msdyn_playbookinstance_Result[] | null;
  order_details?: SalesOrderDetail_Result[] | null;
  order_invoices?: Invoice_Result[] | null;
  salesorder_activity_parties?: ActivityParty_Result[] | null;
  salesorder_awcnpd_feedbacks?: awcnpd_feedback_Result[] | null;
  salesorder_connections1?: Connection_Result[] | null;
  salesorder_connections2?: Connection_Result[] | null;
  salesorder_opportunitysalesprocess?: OpportunitySalesProcess_Result[] | null;
  salesorder_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  sla_salesorder_sla?: SLA_Result | null;
  slainvokedid_salesorder_sla?: SLA_Result | null;
  slakpiinstance_salesorder?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  userentityinstancedata_salesorder?: UserEntityInstanceData_Result[] | null;
}
interface SalesOrder extends SalesOrder_Base, SalesOrder_Relationships {
  campaignid_bind$campaigns?: string | null;
  customerid_account_bind$accounts?: string | null;
  customerid_contact_bind$contacts?: string | null;
  opportunityid_bind$opportunities?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
  pricelevelid_bind$pricelevels?: string | null;
  quoteid_bind$quotes?: string | null;
  sla_salesorder_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
}
interface SalesOrder_Create extends SalesOrder {
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface SalesOrder_Update extends SalesOrder {
}
interface SalesOrder_Select {
  accountid_guid: WebAttribute<SalesOrder_Select, { accountid_guid: string | null }, { accountid_formatted?: string }>;
  billto_addressid: WebAttribute<SalesOrder_Select, { billto_addressid: string | null }, {  }>;
  billto_city: WebAttribute<SalesOrder_Select, { billto_city: string | null }, {  }>;
  billto_composite: WebAttribute<SalesOrder_Select, { billto_composite: string | null }, {  }>;
  billto_contactname: WebAttribute<SalesOrder_Select, { billto_contactname: string | null }, {  }>;
  billto_country: WebAttribute<SalesOrder_Select, { billto_country: string | null }, {  }>;
  billto_fax: WebAttribute<SalesOrder_Select, { billto_fax: string | null }, {  }>;
  billto_line1: WebAttribute<SalesOrder_Select, { billto_line1: string | null }, {  }>;
  billto_line2: WebAttribute<SalesOrder_Select, { billto_line2: string | null }, {  }>;
  billto_line3: WebAttribute<SalesOrder_Select, { billto_line3: string | null }, {  }>;
  billto_name: WebAttribute<SalesOrder_Select, { billto_name: string | null }, {  }>;
  billto_postalcode: WebAttribute<SalesOrder_Select, { billto_postalcode: string | null }, {  }>;
  billto_stateorprovince: WebAttribute<SalesOrder_Select, { billto_stateorprovince: string | null }, {  }>;
  billto_telephone: WebAttribute<SalesOrder_Select, { billto_telephone: string | null }, {  }>;
  campaignid_guid: WebAttribute<SalesOrder_Select, { campaignid_guid: string | null }, { campaignid_formatted?: string }>;
  contactid_guid: WebAttribute<SalesOrder_Select, { contactid_guid: string | null }, { contactid_formatted?: string }>;
  createdby_guid: WebAttribute<SalesOrder_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<SalesOrder_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<SalesOrder_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customerid_guid: WebAttribute<SalesOrder_Select, { customerid_guid: string | null }, { customerid_formatted?: string }>;
  datefulfilled: WebAttribute<SalesOrder_Select, { datefulfilled: Date | null }, { datefulfilled_formatted?: string }>;
  description: WebAttribute<SalesOrder_Select, { description: string | null }, {  }>;
  discountamount: WebAttribute<SalesOrder_Select, { discountamount: number | null; transactioncurrencyid_guid: string | null }, { discountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  discountamount_base: WebAttribute<SalesOrder_Select, { discountamount_base: number | null; transactioncurrencyid_guid: string | null }, { discountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  discountpercentage: WebAttribute<SalesOrder_Select, { discountpercentage: number | null }, {  }>;
  emailaddress: WebAttribute<SalesOrder_Select, { emailaddress: string | null }, {  }>;
  entityimageid: WebAttribute<SalesOrder_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<SalesOrder_Select, { exchangerate: number | null }, {  }>;
  freightamount: WebAttribute<SalesOrder_Select, { freightamount: number | null; transactioncurrencyid_guid: string | null }, { freightamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  freightamount_base: WebAttribute<SalesOrder_Select, { freightamount_base: number | null; transactioncurrencyid_guid: string | null }, { freightamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  freighttermscode: WebAttribute<SalesOrder_Select, { freighttermscode: salesorder_freighttermscode | null }, { freighttermscode_formatted?: string }>;
  importsequencenumber: WebAttribute<SalesOrder_Select, { importsequencenumber: number | null }, {  }>;
  ispricelocked: WebAttribute<SalesOrder_Select, { ispricelocked: boolean | null }, {  }>;
  lastbackofficesubmit: WebAttribute<SalesOrder_Select, { lastbackofficesubmit: Date | null }, { lastbackofficesubmit_formatted?: string }>;
  lastonholdtime: WebAttribute<SalesOrder_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  modifiedby_guid: WebAttribute<SalesOrder_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<SalesOrder_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<SalesOrder_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<SalesOrder_Select, { name: string | null }, {  }>;
  onholdtime: WebAttribute<SalesOrder_Select, { onholdtime: number | null }, {  }>;
  opportunityid_guid: WebAttribute<SalesOrder_Select, { opportunityid_guid: string | null }, { opportunityid_formatted?: string }>;
  ordernumber: WebAttribute<SalesOrder_Select, { ordernumber: string | null }, {  }>;
  overriddencreatedon: WebAttribute<SalesOrder_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<SalesOrder_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<SalesOrder_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<SalesOrder_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<SalesOrder_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  paymenttermscode: WebAttribute<SalesOrder_Select, { paymenttermscode: salesorder_paymenttermscode | null }, { paymenttermscode_formatted?: string }>;
  pricelevelid_guid: WebAttribute<SalesOrder_Select, { pricelevelid_guid: string | null }, { pricelevelid_formatted?: string }>;
  pricingerrorcode: WebAttribute<SalesOrder_Select, { pricingerrorcode: qooi_pricingerrorcode | null }, { pricingerrorcode_formatted?: string }>;
  prioritycode: WebAttribute<SalesOrder_Select, { prioritycode: salesorder_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<SalesOrder_Select, { processid: string | null }, {  }>;
  quoteid_guid: WebAttribute<SalesOrder_Select, { quoteid_guid: string | null }, { quoteid_formatted?: string }>;
  requestdeliveryby: WebAttribute<SalesOrder_Select, { requestdeliveryby: Date | null }, { requestdeliveryby_formatted?: string }>;
  salesorderid: WebAttribute<SalesOrder_Select, { salesorderid: string | null }, {  }>;
  shippingmethodcode: WebAttribute<SalesOrder_Select, { shippingmethodcode: salesorder_shippingmethodcode | null }, { shippingmethodcode_formatted?: string }>;
  shipto_addressid: WebAttribute<SalesOrder_Select, { shipto_addressid: string | null }, {  }>;
  shipto_city: WebAttribute<SalesOrder_Select, { shipto_city: string | null }, {  }>;
  shipto_composite: WebAttribute<SalesOrder_Select, { shipto_composite: string | null }, {  }>;
  shipto_contactname: WebAttribute<SalesOrder_Select, { shipto_contactname: string | null }, {  }>;
  shipto_country: WebAttribute<SalesOrder_Select, { shipto_country: string | null }, {  }>;
  shipto_fax: WebAttribute<SalesOrder_Select, { shipto_fax: string | null }, {  }>;
  shipto_freighttermscode: WebAttribute<SalesOrder_Select, { shipto_freighttermscode: salesorder_shipto_freighttermscode | null }, { shipto_freighttermscode_formatted?: string }>;
  shipto_line1: WebAttribute<SalesOrder_Select, { shipto_line1: string | null }, {  }>;
  shipto_line2: WebAttribute<SalesOrder_Select, { shipto_line2: string | null }, {  }>;
  shipto_line3: WebAttribute<SalesOrder_Select, { shipto_line3: string | null }, {  }>;
  shipto_name: WebAttribute<SalesOrder_Select, { shipto_name: string | null }, {  }>;
  shipto_postalcode: WebAttribute<SalesOrder_Select, { shipto_postalcode: string | null }, {  }>;
  shipto_stateorprovince: WebAttribute<SalesOrder_Select, { shipto_stateorprovince: string | null }, {  }>;
  shipto_telephone: WebAttribute<SalesOrder_Select, { shipto_telephone: string | null }, {  }>;
  skippricecalculation: WebAttribute<SalesOrder_Select, { skippricecalculation: qooi_skippricecalculation | null }, { skippricecalculation_formatted?: string }>;
  slaid_guid: WebAttribute<SalesOrder_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<SalesOrder_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  stageid: WebAttribute<SalesOrder_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<SalesOrder_Select, { statecode: salesorder_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<SalesOrder_Select, { statuscode: salesorder_statuscode | null }, { statuscode_formatted?: string }>;
  submitdate: WebAttribute<SalesOrder_Select, { submitdate: Date | null }, { submitdate_formatted?: string }>;
  submitstatus: WebAttribute<SalesOrder_Select, { submitstatus: number | null }, {  }>;
  submitstatusdescription: WebAttribute<SalesOrder_Select, { submitstatusdescription: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<SalesOrder_Select, { timezoneruleversionnumber: number | null }, {  }>;
  totalamount: WebAttribute<SalesOrder_Select, { totalamount: number | null; transactioncurrencyid_guid: string | null }, { totalamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalamount_base: WebAttribute<SalesOrder_Select, { totalamount_base: number | null; transactioncurrencyid_guid: string | null }, { totalamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalamountlessfreight: WebAttribute<SalesOrder_Select, { totalamountlessfreight: number | null; transactioncurrencyid_guid: string | null }, { totalamountlessfreight_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totalamountlessfreight_base: WebAttribute<SalesOrder_Select, { totalamountlessfreight_base: number | null; transactioncurrencyid_guid: string | null }, { totalamountlessfreight_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaldiscountamount: WebAttribute<SalesOrder_Select, { totaldiscountamount: number | null; transactioncurrencyid_guid: string | null }, { totaldiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaldiscountamount_base: WebAttribute<SalesOrder_Select, { totaldiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { totaldiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemamount: WebAttribute<SalesOrder_Select, { totallineitemamount: number | null; transactioncurrencyid_guid: string | null }, { totallineitemamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemamount_base: WebAttribute<SalesOrder_Select, { totallineitemamount_base: number | null; transactioncurrencyid_guid: string | null }, { totallineitemamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemdiscountamount: WebAttribute<SalesOrder_Select, { totallineitemdiscountamount: number | null; transactioncurrencyid_guid: string | null }, { totallineitemdiscountamount_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totallineitemdiscountamount_base: WebAttribute<SalesOrder_Select, { totallineitemdiscountamount_base: number | null; transactioncurrencyid_guid: string | null }, { totallineitemdiscountamount_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaltax: WebAttribute<SalesOrder_Select, { totaltax: number | null; transactioncurrencyid_guid: string | null }, { totaltax_formatted?: string; transactioncurrencyid_formatted?: string }>;
  totaltax_base: WebAttribute<SalesOrder_Select, { totaltax_base: number | null; transactioncurrencyid_guid: string | null }, { totaltax_base_formatted?: string; transactioncurrencyid_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<SalesOrder_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<SalesOrder_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<SalesOrder_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<SalesOrder_Select, { versionnumber: number | null }, {  }>;
  willcall: WebAttribute<SalesOrder_Select, { willcall: boolean | null }, {  }>;
}
interface SalesOrder_Filter {
  accountid_guid: XQW.Guid;
  billto_addressid: XQW.Guid;
  billto_city: string;
  billto_composite: string;
  billto_contactname: string;
  billto_country: string;
  billto_fax: string;
  billto_line1: string;
  billto_line2: string;
  billto_line3: string;
  billto_name: string;
  billto_postalcode: string;
  billto_stateorprovince: string;
  billto_telephone: string;
  campaignid_guid: XQW.Guid;
  contactid_guid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customerid_guid: XQW.Guid;
  datefulfilled: Date;
  description: string;
  discountamount: number;
  discountamount_base: number;
  discountpercentage: any;
  emailaddress: string;
  entityimageid: XQW.Guid;
  exchangerate: any;
  freightamount: number;
  freightamount_base: number;
  freighttermscode: salesorder_freighttermscode;
  importsequencenumber: number;
  ispricelocked: boolean;
  lastbackofficesubmit: Date;
  lastonholdtime: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  onholdtime: number;
  opportunityid_guid: XQW.Guid;
  ordernumber: string;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  paymenttermscode: salesorder_paymenttermscode;
  pricelevelid_guid: XQW.Guid;
  pricingerrorcode: qooi_pricingerrorcode;
  prioritycode: salesorder_prioritycode;
  processid: XQW.Guid;
  quoteid_guid: XQW.Guid;
  requestdeliveryby: Date;
  salesorderid: XQW.Guid;
  shippingmethodcode: salesorder_shippingmethodcode;
  shipto_addressid: XQW.Guid;
  shipto_city: string;
  shipto_composite: string;
  shipto_contactname: string;
  shipto_country: string;
  shipto_fax: string;
  shipto_freighttermscode: salesorder_shipto_freighttermscode;
  shipto_line1: string;
  shipto_line2: string;
  shipto_line3: string;
  shipto_name: string;
  shipto_postalcode: string;
  shipto_stateorprovince: string;
  shipto_telephone: string;
  skippricecalculation: qooi_skippricecalculation;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  stageid: XQW.Guid;
  statecode: salesorder_statecode;
  statuscode: salesorder_statuscode;
  submitdate: Date;
  submitstatus: number;
  submitstatusdescription: string;
  timezoneruleversionnumber: number;
  totalamount: number;
  totalamount_base: number;
  totalamountlessfreight: number;
  totalamountlessfreight_base: number;
  totaldiscountamount: number;
  totaldiscountamount_base: number;
  totallineitemamount: number;
  totallineitemamount_base: number;
  totallineitemdiscountamount: number;
  totallineitemdiscountamount_base: number;
  totaltax: number;
  totaltax_base: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
  willcall: boolean;
}
interface SalesOrder_Expand {
  SalesOrder_ActivityPointers: WebExpand<SalesOrder_Expand, ActivityPointer_Select, ActivityPointer_Filter, { SalesOrder_ActivityPointers: ActivityPointer_Result[] }>;
  SalesOrder_Annotation: WebExpand<SalesOrder_Expand, Annotation_Select, Annotation_Filter, { SalesOrder_Annotation: Annotation_Result[] }>;
  SalesOrder_Appointments: WebExpand<SalesOrder_Expand, Appointment_Select, Appointment_Filter, { SalesOrder_Appointments: Appointment_Result[] }>;
  SalesOrder_AsyncOperations: WebExpand<SalesOrder_Expand, AsyncOperation_Select, AsyncOperation_Filter, { SalesOrder_AsyncOperations: AsyncOperation_Result[] }>;
  SalesOrder_BulkDeleteFailures: WebExpand<SalesOrder_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { SalesOrder_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  SalesOrder_Emails: WebExpand<SalesOrder_Expand, Email_Select, Email_Filter, { SalesOrder_Emails: Email_Result[] }>;
  SalesOrder_Faxes: WebExpand<SalesOrder_Expand, Fax_Select, Fax_Filter, { SalesOrder_Faxes: Fax_Result[] }>;
  SalesOrder_Letters: WebExpand<SalesOrder_Expand, Letter_Select, Letter_Filter, { SalesOrder_Letters: Letter_Result[] }>;
  SalesOrder_MailboxTrackingFolder: WebExpand<SalesOrder_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { SalesOrder_MailboxTrackingFolder: MailboxTrackingFolder_Result[] }>;
  SalesOrder_OrderClose: WebExpand<SalesOrder_Expand, OrderClose_Select, OrderClose_Filter, { SalesOrder_OrderClose: OrderClose_Result[] }>;
  SalesOrder_Phonecalls: WebExpand<SalesOrder_Expand, PhoneCall_Select, PhoneCall_Filter, { SalesOrder_Phonecalls: PhoneCall_Result[] }>;
  SalesOrder_ProcessSessions: WebExpand<SalesOrder_Expand, ProcessSession_Select, ProcessSession_Filter, { SalesOrder_ProcessSessions: ProcessSession_Result[] }>;
  SalesOrder_RecurringAppointmentMasters: WebExpand<SalesOrder_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { SalesOrder_RecurringAppointmentMasters: RecurringAppointmentMaster_Result[] }>;
  SalesOrder_ServiceAppointments: WebExpand<SalesOrder_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { SalesOrder_ServiceAppointments: ServiceAppointment_Result[] }>;
  SalesOrder_SocialActivities: WebExpand<SalesOrder_Expand, SocialActivity_Select, SocialActivity_Filter, { SalesOrder_SocialActivities: SocialActivity_Result[] }>;
  SalesOrder_SyncErrors: WebExpand<SalesOrder_Expand, SyncError_Select, SyncError_Filter, { SalesOrder_SyncErrors: SyncError_Result[] }>;
  SalesOrder_Tasks: WebExpand<SalesOrder_Expand, Task_Select, Task_Filter, { SalesOrder_Tasks: Task_Result[] }>;
  campaignid: WebExpand<SalesOrder_Expand, Campaign_Select, Campaign_Filter, { campaignid: Campaign_Result }>;
  contactorders_association: WebExpand<SalesOrder_Expand, Contact_Select, Contact_Filter, { contactorders_association: Contact_Result[] }>;
  createdby: WebExpand<SalesOrder_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<SalesOrder_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  customerid_account: WebExpand<SalesOrder_Expand, Account_Select, Account_Filter, { customerid_account: Account_Result }>;
  customerid_contact: WebExpand<SalesOrder_Expand, Contact_Select, Contact_Filter, { customerid_contact: Contact_Result }>;
  entityimageid_imagedescriptor: WebExpand<SalesOrder_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  modifiedby: WebExpand<SalesOrder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<SalesOrder_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  msdyn_playbookinstance_salesorder: WebExpand<SalesOrder_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { msdyn_playbookinstance_salesorder: msdyn_playbookinstance_Result[] }>;
  opportunityid: WebExpand<SalesOrder_Expand, Opportunity_Select, Opportunity_Filter, { opportunityid: Opportunity_Result }>;
  order_details: WebExpand<SalesOrder_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { order_details: SalesOrderDetail_Result[] }>;
  order_invoices: WebExpand<SalesOrder_Expand, Invoice_Select, Invoice_Filter, { order_invoices: Invoice_Result[] }>;
  ownerid: WebExpand<SalesOrder_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<SalesOrder_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<SalesOrder_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<SalesOrder_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  pricelevelid: WebExpand<SalesOrder_Expand, PriceLevel_Select, PriceLevel_Filter, { pricelevelid: PriceLevel_Result }>;
  quoteid: WebExpand<SalesOrder_Expand, Quote_Select, Quote_Filter, { quoteid: Quote_Result }>;
  salesorder_activity_parties: WebExpand<SalesOrder_Expand, ActivityParty_Select, ActivityParty_Filter, { salesorder_activity_parties: ActivityParty_Result[] }>;
  salesorder_awcnpd_feedbacks: WebExpand<SalesOrder_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { salesorder_awcnpd_feedbacks: awcnpd_feedback_Result[] }>;
  salesorder_connections1: WebExpand<SalesOrder_Expand, Connection_Select, Connection_Filter, { salesorder_connections1: Connection_Result[] }>;
  salesorder_connections2: WebExpand<SalesOrder_Expand, Connection_Select, Connection_Filter, { salesorder_connections2: Connection_Result[] }>;
  salesorder_opportunitysalesprocess: WebExpand<SalesOrder_Expand, OpportunitySalesProcess_Select, OpportunitySalesProcess_Filter, { salesorder_opportunitysalesprocess: OpportunitySalesProcess_Result[] }>;
  salesorder_principalobjectattributeaccess: WebExpand<SalesOrder_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { salesorder_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  sla_salesorder_sla: WebExpand<SalesOrder_Expand, SLA_Select, SLA_Filter, { sla_salesorder_sla: SLA_Result }>;
  slainvokedid_salesorder_sla: WebExpand<SalesOrder_Expand, SLA_Select, SLA_Filter, { slainvokedid_salesorder_sla: SLA_Result }>;
  slakpiinstance_salesorder: WebExpand<SalesOrder_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_salesorder: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<SalesOrder_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid: WebExpand<SalesOrder_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_salesorder: WebExpand<SalesOrder_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_salesorder: UserEntityInstanceData_Result[] }>;
}
interface SalesOrder_FormattedResult {
  accountid_formatted?: string;
  campaignid_formatted?: string;
  contactid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customerid_formatted?: string;
  datefulfilled_formatted?: string;
  discountamount_base_formatted?: string;
  discountamount_formatted?: string;
  freightamount_base_formatted?: string;
  freightamount_formatted?: string;
  freighttermscode_formatted?: string;
  lastbackofficesubmit_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  opportunityid_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  paymenttermscode_formatted?: string;
  pricelevelid_formatted?: string;
  pricingerrorcode_formatted?: string;
  prioritycode_formatted?: string;
  quoteid_formatted?: string;
  requestdeliveryby_formatted?: string;
  shippingmethodcode_formatted?: string;
  shipto_freighttermscode_formatted?: string;
  skippricecalculation_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  submitdate_formatted?: string;
  totalamount_base_formatted?: string;
  totalamount_formatted?: string;
  totalamountlessfreight_base_formatted?: string;
  totalamountlessfreight_formatted?: string;
  totaldiscountamount_base_formatted?: string;
  totaldiscountamount_formatted?: string;
  totallineitemamount_base_formatted?: string;
  totallineitemamount_formatted?: string;
  totallineitemdiscountamount_base_formatted?: string;
  totallineitemdiscountamount_formatted?: string;
  totaltax_base_formatted?: string;
  totaltax_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface SalesOrder_Result extends SalesOrder_Base, SalesOrder_Relationships {
  "@odata.etag": string;
  accountid_guid: string | null;
  campaignid_guid: string | null;
  contactid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customerid_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  opportunityid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  pricelevelid_guid: string | null;
  quoteid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface SalesOrder_RelatedOne {
  campaignid: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  customerid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  customerid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  opportunityid: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  pricelevelid: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  quoteid: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  sla_salesorder_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_salesorder_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface SalesOrder_RelatedMany {
  SalesOrder_ActivityPointers: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  SalesOrder_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  SalesOrder_Appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  SalesOrder_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  SalesOrder_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  SalesOrder_Emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  SalesOrder_Faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  SalesOrder_Letters: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  SalesOrder_MailboxTrackingFolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  SalesOrder_OrderClose: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  SalesOrder_Phonecalls: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  SalesOrder_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  SalesOrder_RecurringAppointmentMasters: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  SalesOrder_ServiceAppointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  SalesOrder_SocialActivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  SalesOrder_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  SalesOrder_Tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  contactorders_association: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  msdyn_playbookinstance_salesorder: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  order_details: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  order_invoices: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  salesorder_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  salesorder_awcnpd_feedbacks: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  salesorder_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  salesorder_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  salesorder_opportunitysalesprocess: WebMappingRetrieve<OpportunitySalesProcess_Select,OpportunitySalesProcess_Expand,OpportunitySalesProcess_Filter,OpportunitySalesProcess_Fixed,OpportunitySalesProcess_Result,OpportunitySalesProcess_FormattedResult>;
  salesorder_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_salesorder: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_salesorder: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  salesorders: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
}
interface WebEntitiesRelated {
  salesorders: WebMappingRelated<SalesOrder_RelatedOne,SalesOrder_RelatedMany>;
}
interface WebEntitiesCUDA {
  salesorders: WebMappingCUDA<SalesOrder_Create,SalesOrder_Update,SalesOrder_Select>;
}
