interface SocialActivity_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  description?: string | null;
  directioncode?: boolean | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  inresponseto?: string | null;
  isbilled?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postedon?: Date | null;
  postid?: string | null;
  postmessagetype?: socialactivity_postmessagetype | null;
  posttoprofileid?: string | null;
  posturl?: string | null;
  prioritycode?: socialactivity_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  sentimentvalue?: number | null;
  socialadditionalparams?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: socialactivity_statecode | null;
  statuscode?: socialactivity_statuscode | null;
  subject?: string | null;
  threadid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface SocialActivity_Relationships {
  SocialActivity_Annotation?: Annotation_Result[] | null;
  SocialActivity_AsyncOperations?: AsyncOperation_Result[] | null;
  SocialActivity_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  SocialActivity_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  SocialActivity_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  SocialActivity_ProcessSessions?: ProcessSession_Result[] | null;
  SocialActivity_QueueItem?: QueueItem_Result[] | null;
  SocialActivity_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_socialactivity?: SystemUser_Result | null;
  createdonbehalfby_socialactivity?: SystemUser_Result | null;
  modifiedby_socialactivity?: SystemUser_Result | null;
  modifiedonbehalfby_socialactivity?: SystemUser_Result | null;
  ownerid_socialactivity?: Team_Result | null;
  ownerid_socialactivity1?: SystemUser_Result | null;
  owningbusinessunit_socialactivity?: BusinessUnit_Result | null;
  owningteam_socialactivity?: Team_Result | null;
  owninguser_socialactivity?: SystemUser_Result | null;
  postauthor_account?: Account_Result | null;
  postauthor_contact?: Contact_Result | null;
  postauthoraccount_account?: Account_Result | null;
  postauthoraccount_contact?: Contact_Result | null;
  regardingobjectid_account_socialactivity?: Account_Result | null;
  regardingobjectid_asyncoperation?: AsyncOperation_Result | null;
  regardingobjectid_awc_prototype_socialactivity?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_socialactivity?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_socialactivity?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_socialactivity?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_socialactivity?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_socialactivity?: BulkOperation_Result | null;
  regardingobjectid_campaign_socialactivity?: Campaign_Result | null;
  regardingobjectid_campaignactivity_socialactivity?: CampaignActivity_Result | null;
  regardingobjectid_contact_socialactivity?: Contact_Result | null;
  regardingobjectid_contract_socialactivity?: Contract_Result | null;
  regardingobjectid_entitlement_socialactivity?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_socialactivity?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_socialactivity?: Incident_Result | null;
  regardingobjectid_invoice_socialactivity?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_socialactivity?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_socialactivity?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_socialactivity?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_socialactivity?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_socialactivity?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_socialactivity?: Opportunity_Result | null;
  regardingobjectid_quote_socialactivity?: Quote_Result | null;
  regardingobjectid_salesorder_socialactivity?: SalesOrder_Result | null;
  regardingobjectid_site_socialactivity?: Site_Result | null;
  serviceid_socialactivity?: Service_Result | null;
  sla_socialactivity_sla?: SLA_Result | null;
  slainvokedid_socialactivity_sla?: SLA_Result | null;
  slakpiinstance_socialactivity?: SLAKPIInstance_Result[] | null;
  socialactivity_activity_parties?: ActivityParty_Result[] | null;
  socialactivity_connections1?: Connection_Result[] | null;
  socialactivity_connections2?: Connection_Result[] | null;
  socialactivity_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  transactioncurrencyid_socialactivity?: TransactionCurrency_Result | null;
  userentityinstancedata_socialactivity?: UserEntityInstanceData_Result[] | null;
}
interface SocialActivity extends SocialActivity_Base, SocialActivity_Relationships {
  ownerid_socialactivity_bind$systemusers?: string | null;
  ownerid_socialactivity_bind$teams?: string | null;
  postauthor_account_bind$accounts?: string | null;
  postauthor_contact_bind$contacts?: string | null;
  postauthoraccount_account_bind$accounts?: string | null;
  postauthoraccount_contact_bind$contacts?: string | null;
  postfromprofileid_bind$socialprofiles?: string | null;
  regardingobjectid_account_socialactivity_bind$accounts?: string | null;
  regardingobjectid_asyncoperation_bind$asyncoperations?: string | null;
  regardingobjectid_awc_prototype_socialactivity_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_socialactivity_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_socialactivity_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_socialactivity_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_socialactivity_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_socialactivity_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_socialactivity_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_socialactivity_bind$campaignactivities?: string | null;
  regardingobjectid_contact_socialactivity_bind$contacts?: string | null;
  regardingobjectid_contract_socialactivity_bind$contracts?: string | null;
  regardingobjectid_entitlement_socialactivity_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_socialactivity_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_socialactivity_bind$incidents?: string | null;
  regardingobjectid_invoice_socialactivity_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_socialactivity_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_socialactivity_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_socialactivity_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_socialactivity_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_socialactivity_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_socialactivity_bind$opportunities?: string | null;
  regardingobjectid_quote_socialactivity_bind$quotes?: string | null;
  regardingobjectid_salesorder_socialactivity_bind$salesorders?: string | null;
  regardingobjectid_site_socialactivity_bind$sites?: string | null;
  serviceid_socialactivity_bind$services?: string | null;
  sla_socialactivity_sla_bind$slas?: string | null;
  transactioncurrencyid_socialactivity_bind$transactioncurrencies?: string | null;
}
interface SocialActivity_Create extends SocialActivity {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface SocialActivity_Update extends SocialActivity {
}
interface SocialActivity_Select {
  activityadditionalparams: WebAttribute<SocialActivity_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<SocialActivity_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<SocialActivity_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<SocialActivity_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<SocialActivity_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<SocialActivity_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  community: WebAttribute<SocialActivity_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<SocialActivity_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<SocialActivity_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<SocialActivity_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<SocialActivity_Select, { description: string | null }, {  }>;
  directioncode: WebAttribute<SocialActivity_Select, { directioncode: boolean | null }, {  }>;
  exchangerate: WebAttribute<SocialActivity_Select, { exchangerate: number | null }, {  }>;
  from_guid: WebAttribute<SocialActivity_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<SocialActivity_Select, { importsequencenumber: number | null }, {  }>;
  inresponseto: WebAttribute<SocialActivity_Select, { inresponseto: string | null }, {  }>;
  isbilled: WebAttribute<SocialActivity_Select, { isbilled: boolean | null }, {  }>;
  isregularactivity: WebAttribute<SocialActivity_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<SocialActivity_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<SocialActivity_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  modifiedby_guid: WebAttribute<SocialActivity_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<SocialActivity_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<SocialActivity_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<SocialActivity_Select, { onholdtime: number | null }, {  }>;
  overriddencreatedon: WebAttribute<SocialActivity_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<SocialActivity_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<SocialActivity_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<SocialActivity_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<SocialActivity_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  postauthor_guid: WebAttribute<SocialActivity_Select, { postauthor_guid: string | null }, { postauthor_formatted?: string }>;
  postauthoraccount_guid: WebAttribute<SocialActivity_Select, { postauthoraccount_guid: string | null }, { postauthoraccount_formatted?: string }>;
  postedon: WebAttribute<SocialActivity_Select, { postedon: Date | null }, { postedon_formatted?: string }>;
  postfromprofileid_guid: WebAttribute<SocialActivity_Select, { postfromprofileid_guid: string | null }, { postfromprofileid_formatted?: string }>;
  postid: WebAttribute<SocialActivity_Select, { postid: string | null }, {  }>;
  postmessagetype: WebAttribute<SocialActivity_Select, { postmessagetype: socialactivity_postmessagetype | null }, { postmessagetype_formatted?: string }>;
  posttoprofileid: WebAttribute<SocialActivity_Select, { posttoprofileid: string | null }, {  }>;
  posturl: WebAttribute<SocialActivity_Select, { posturl: string | null }, {  }>;
  prioritycode: WebAttribute<SocialActivity_Select, { prioritycode: socialactivity_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<SocialActivity_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<SocialActivity_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  resources_guid: WebAttribute<SocialActivity_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<SocialActivity_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<SocialActivity_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<SocialActivity_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sentimentvalue: WebAttribute<SocialActivity_Select, { sentimentvalue: number | null }, {  }>;
  serviceid_guid: WebAttribute<SocialActivity_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<SocialActivity_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<SocialActivity_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  socialadditionalparams: WebAttribute<SocialActivity_Select, { socialadditionalparams: string | null }, {  }>;
  sortdate: WebAttribute<SocialActivity_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<SocialActivity_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<SocialActivity_Select, { statecode: socialactivity_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<SocialActivity_Select, { statuscode: socialactivity_statuscode | null }, { statuscode_formatted?: string }>;
  subject: WebAttribute<SocialActivity_Select, { subject: string | null }, {  }>;
  threadid: WebAttribute<SocialActivity_Select, { threadid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<SocialActivity_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<SocialActivity_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<SocialActivity_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<SocialActivity_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<SocialActivity_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<SocialActivity_Select, { versionnumber: number | null }, {  }>;
}
interface SocialActivity_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  directioncode: boolean;
  exchangerate: any;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  inresponseto: string;
  isbilled: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  postauthor_guid: XQW.Guid;
  postauthoraccount_guid: XQW.Guid;
  postedon: Date;
  postfromprofileid_guid: XQW.Guid;
  postid: string;
  postmessagetype: socialactivity_postmessagetype;
  posttoprofileid: string;
  posturl: string;
  prioritycode: socialactivity_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sentimentvalue: number;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  socialadditionalparams: string;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: socialactivity_statecode;
  statuscode: socialactivity_statuscode;
  subject: string;
  threadid: string;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface SocialActivity_Expand {
  SocialActivity_Annotation: WebExpand<SocialActivity_Expand, Annotation_Select, Annotation_Filter, { SocialActivity_Annotation: Annotation_Result[] }>;
  SocialActivity_AsyncOperations: WebExpand<SocialActivity_Expand, AsyncOperation_Select, AsyncOperation_Filter, { SocialActivity_AsyncOperations: AsyncOperation_Result[] }>;
  SocialActivity_BulkDeleteFailures: WebExpand<SocialActivity_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { SocialActivity_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  SocialActivity_DuplicateBaseRecord: WebExpand<SocialActivity_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { SocialActivity_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  SocialActivity_DuplicateMatchingRecord: WebExpand<SocialActivity_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { SocialActivity_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  SocialActivity_ProcessSessions: WebExpand<SocialActivity_Expand, ProcessSession_Select, ProcessSession_Filter, { SocialActivity_ProcessSessions: ProcessSession_Result[] }>;
  SocialActivity_QueueItem: WebExpand<SocialActivity_Expand, QueueItem_Select, QueueItem_Filter, { SocialActivity_QueueItem: QueueItem_Result[] }>;
  SocialActivity_SyncErrors: WebExpand<SocialActivity_Expand, SyncError_Select, SyncError_Filter, { SocialActivity_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<SocialActivity_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_socialactivity: WebExpand<SocialActivity_Expand, SystemUser_Select, SystemUser_Filter, { createdby_socialactivity: SystemUser_Result }>;
  createdonbehalfby_socialactivity: WebExpand<SocialActivity_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_socialactivity: SystemUser_Result }>;
  modifiedby_socialactivity: WebExpand<SocialActivity_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_socialactivity: SystemUser_Result }>;
  modifiedonbehalfby_socialactivity: WebExpand<SocialActivity_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_socialactivity: SystemUser_Result }>;
  ownerid_socialactivity: WebExpand<SocialActivity_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_socialactivity: SystemUser_Result } & { ownerid_socialactivity: Team_Result }>;
  owningbusinessunit_socialactivity: WebExpand<SocialActivity_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_socialactivity: BusinessUnit_Result }>;
  owningteam_socialactivity: WebExpand<SocialActivity_Expand, Team_Select, Team_Filter, { owningteam_socialactivity: Team_Result }>;
  owninguser_socialactivity: WebExpand<SocialActivity_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_socialactivity: SystemUser_Result }>;
  postauthor_account: WebExpand<SocialActivity_Expand, Account_Select, Account_Filter, { postauthor_account: Account_Result }>;
  postauthor_contact: WebExpand<SocialActivity_Expand, Contact_Select, Contact_Filter, { postauthor_contact: Contact_Result }>;
  postauthoraccount_account: WebExpand<SocialActivity_Expand, Account_Select, Account_Filter, { postauthoraccount_account: Account_Result }>;
  postauthoraccount_contact: WebExpand<SocialActivity_Expand, Contact_Select, Contact_Filter, { postauthoraccount_contact: Contact_Result }>;
  postfromprofileid: WebExpand<SocialActivity_Expand, SocialProfile_Select, SocialProfile_Filter, { postfromprofileid: SocialProfile_Result }>;
  regardingobjectid_account_socialactivity: WebExpand<SocialActivity_Expand, Account_Select, Account_Filter, { regardingobjectid_account_socialactivity: Account_Result }>;
  regardingobjectid_asyncoperation: WebExpand<SocialActivity_Expand, AsyncOperation_Select, AsyncOperation_Filter, { regardingobjectid_asyncoperation: AsyncOperation_Result }>;
  regardingobjectid_awc_prototype_socialactivity: WebExpand<SocialActivity_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_socialactivity: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_socialactivity: WebExpand<SocialActivity_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_socialactivity: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_socialactivity: WebExpand<SocialActivity_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_socialactivity: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_socialactivity: WebExpand<SocialActivity_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_socialactivity: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_socialactivity: WebExpand<SocialActivity_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_socialactivity: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_socialactivity: WebExpand<SocialActivity_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_socialactivity: BulkOperation_Result }>;
  regardingobjectid_campaign_socialactivity: WebExpand<SocialActivity_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_socialactivity: Campaign_Result }>;
  regardingobjectid_campaignactivity_socialactivity: WebExpand<SocialActivity_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_socialactivity: CampaignActivity_Result }>;
  regardingobjectid_contact_socialactivity: WebExpand<SocialActivity_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_socialactivity: Contact_Result }>;
  regardingobjectid_contract_socialactivity: WebExpand<SocialActivity_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_socialactivity: Contract_Result }>;
  regardingobjectid_entitlement_socialactivity: WebExpand<SocialActivity_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_socialactivity: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_socialactivity: WebExpand<SocialActivity_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_socialactivity: EntitlementTemplate_Result }>;
  regardingobjectid_incident_socialactivity: WebExpand<SocialActivity_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_socialactivity: Incident_Result }>;
  regardingobjectid_invoice_socialactivity: WebExpand<SocialActivity_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_socialactivity: Invoice_Result }>;
  regardingobjectid_knowledgearticle_socialactivity: WebExpand<SocialActivity_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_socialactivity: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_socialactivity: WebExpand<SocialActivity_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_socialactivity: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_socialactivity: WebExpand<SocialActivity_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_socialactivity: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_socialactivity: WebExpand<SocialActivity_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_socialactivity: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_socialactivity: WebExpand<SocialActivity_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_socialactivity: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_socialactivity: WebExpand<SocialActivity_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_socialactivity: Opportunity_Result }>;
  regardingobjectid_quote_socialactivity: WebExpand<SocialActivity_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_socialactivity: Quote_Result }>;
  regardingobjectid_salesorder_socialactivity: WebExpand<SocialActivity_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_socialactivity: SalesOrder_Result }>;
  regardingobjectid_site_socialactivity: WebExpand<SocialActivity_Expand, Site_Select, Site_Filter, { regardingobjectid_site_socialactivity: Site_Result }>;
  serviceid_socialactivity: WebExpand<SocialActivity_Expand, Service_Select, Service_Filter, { serviceid_socialactivity: Service_Result }>;
  sla_socialactivity_sla: WebExpand<SocialActivity_Expand, SLA_Select, SLA_Filter, { sla_socialactivity_sla: SLA_Result }>;
  slainvokedid_socialactivity_sla: WebExpand<SocialActivity_Expand, SLA_Select, SLA_Filter, { slainvokedid_socialactivity_sla: SLA_Result }>;
  slakpiinstance_socialactivity: WebExpand<SocialActivity_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_socialactivity: SLAKPIInstance_Result[] }>;
  socialactivity_activity_parties: WebExpand<SocialActivity_Expand, ActivityParty_Select, ActivityParty_Filter, { socialactivity_activity_parties: ActivityParty_Result[] }>;
  socialactivity_connections1: WebExpand<SocialActivity_Expand, Connection_Select, Connection_Filter, { socialactivity_connections1: Connection_Result[] }>;
  socialactivity_connections2: WebExpand<SocialActivity_Expand, Connection_Select, Connection_Filter, { socialactivity_connections2: Connection_Result[] }>;
  socialactivity_principalobjectattributeaccess: WebExpand<SocialActivity_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { socialactivity_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  transactioncurrencyid_socialactivity: WebExpand<SocialActivity_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_socialactivity: TransactionCurrency_Result }>;
  userentityinstancedata_socialactivity: WebExpand<SocialActivity_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_socialactivity: UserEntityInstanceData_Result[] }>;
}
interface SocialActivity_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  from_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  postauthor_formatted?: string;
  postauthoraccount_formatted?: string;
  postedon_formatted?: string;
  postfromprofileid_formatted?: string;
  postmessagetype_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface SocialActivity_Result extends SocialActivity_Base, SocialActivity_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  postauthor_guid: string | null;
  postauthoraccount_guid: string | null;
  postfromprofileid_guid: string | null;
  regardingobjectid_guid: string | null;
  resources_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface SocialActivity_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_socialactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_socialactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_socialactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_socialactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_socialactivity: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_socialactivity1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_socialactivity: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_socialactivity: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_socialactivity: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  postauthor_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  postauthor_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  postauthoraccount_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  postauthoraccount_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  postfromprofileid: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  regardingobjectid_account_socialactivity: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_asyncoperation: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  regardingobjectid_awc_prototype_socialactivity: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_socialactivity: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_socialactivity: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_socialactivity: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_socialactivity: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_socialactivity: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_socialactivity: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_socialactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_socialactivity: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_socialactivity: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_socialactivity: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_socialactivity: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_socialactivity: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_socialactivity: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_socialactivity: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_socialactivity: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_socialactivity: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_socialactivity: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_socialactivity: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_socialactivity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_socialactivity: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_socialactivity: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_socialactivity: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  serviceid_socialactivity: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_socialactivity_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_socialactivity_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  transactioncurrencyid_socialactivity: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface SocialActivity_RelatedMany {
  SocialActivity_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  SocialActivity_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  SocialActivity_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  SocialActivity_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  SocialActivity_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  SocialActivity_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  SocialActivity_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  SocialActivity_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  slakpiinstance_socialactivity: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  socialactivity_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  socialactivity_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  socialactivity_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  socialactivity_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  userentityinstancedata_socialactivity: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  socialactivities: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
}
interface WebEntitiesRelated {
  socialactivities: WebMappingRelated<SocialActivity_RelatedOne,SocialActivity_RelatedMany>;
}
interface WebEntitiesCUDA {
  socialactivities: WebMappingCUDA<SocialActivity_Create,SocialActivity_Update,SocialActivity_Select>;
}
