interface Task_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  category?: string | null;
  createdon?: Date | null;
  crmtaskassigneduniqueid?: string | null;
  description?: string | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  isbilled?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  percentcomplete?: number | null;
  prioritycode?: task_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: task_statecode | null;
  statuscode?: task_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Task_Relationships {
  Task_Annotation?: Annotation_Result[] | null;
  Task_AsyncOperations?: AsyncOperation_Result[] | null;
  Task_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Task_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Task_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Task_ProcessSessions?: ProcessSession_Result[] | null;
  Task_QueueItem?: QueueItem_Result[] | null;
  Task_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_task?: SystemUser_Result | null;
  createdonbehalfby_task?: SystemUser_Result | null;
  modifiedby_task?: SystemUser_Result | null;
  modifiedonbehalfby_task?: SystemUser_Result | null;
  ownerid_task?: Team_Result | null;
  ownerid_task1?: SystemUser_Result | null;
  owningbusinessunit_task?: BusinessUnit_Result | null;
  owningteam_task?: Team_Result | null;
  owninguser_task?: SystemUser_Result | null;
  regardingobjectid_account_task?: Account_Result | null;
  regardingobjectid_awc_prototype_task?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_task?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_task?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_task?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_task?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_task?: BulkOperation_Result | null;
  regardingobjectid_campaign_task?: Campaign_Result | null;
  regardingobjectid_campaignactivity_task?: CampaignActivity_Result | null;
  regardingobjectid_contact_task?: Contact_Result | null;
  regardingobjectid_contract_task?: Contract_Result | null;
  regardingobjectid_entitlement_task?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_task?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_task?: Incident_Result | null;
  regardingobjectid_invoice_task?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_task?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_task?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_task?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_task?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_task?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_task?: Opportunity_Result | null;
  regardingobjectid_quote_task?: Quote_Result | null;
  regardingobjectid_salesorder_task?: SalesOrder_Result | null;
  regardingobjectid_site_task?: Site_Result | null;
  serviceid_task?: Service_Result | null;
  sla_task_sla?: SLA_Result | null;
  slainvokedid_task_sla?: SLA_Result | null;
  slakpiinstance_task?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  task_PostFollows?: PostFollow_Result[] | null;
  task_PostRegardings?: PostRegarding_Result[] | null;
  task_PostRoles?: PostRole_Result[] | null;
  task_actioncard?: ActionCard_Result[] | null;
  task_activity_parties?: ActivityParty_Result[] | null;
  task_activitymonitor?: activitymonitor_Result[] | null;
  task_connections1?: Connection_Result[] | null;
  task_connections2?: Connection_Result[] | null;
  task_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  task_subscription_association?: Subscription_Result[] | null;
  transactioncurrencyid_task?: TransactionCurrency_Result | null;
  userentityinstancedata_task?: UserEntityInstanceData_Result[] | null;
}
interface Task extends Task_Base, Task_Relationships {
  ownerid_task_bind$systemusers?: string | null;
  ownerid_task_bind$teams?: string | null;
  regardingobjectid_account_task_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_task_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_task_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_task_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_task_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_task_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_task_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_task_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_task_bind$campaignactivities?: string | null;
  regardingobjectid_contact_task_bind$contacts?: string | null;
  regardingobjectid_contract_task_bind$contracts?: string | null;
  regardingobjectid_entitlement_task_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_task_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_task_bind$incidents?: string | null;
  regardingobjectid_invoice_task_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_task_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_task_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_task_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_task_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_task_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_task_bind$opportunities?: string | null;
  regardingobjectid_quote_task_bind$quotes?: string | null;
  regardingobjectid_salesorder_task_bind$salesorders?: string | null;
  regardingobjectid_site_task_bind$sites?: string | null;
  serviceid_task_bind$services?: string | null;
  sla_task_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_task_bind$transactioncurrencies?: string | null;
}
interface Task_Create extends Task {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface Task_Update extends Task {
}
interface Task_Select {
  activityadditionalparams: WebAttribute<Task_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<Task_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<Task_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<Task_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<Task_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Task_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  category: WebAttribute<Task_Select, { category: string | null }, {  }>;
  createdby_guid: WebAttribute<Task_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Task_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Task_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  crmtaskassigneduniqueid: WebAttribute<Task_Select, { crmtaskassigneduniqueid: string | null }, {  }>;
  description: WebAttribute<Task_Select, { description: string | null }, {  }>;
  exchangerate: WebAttribute<Task_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<Task_Select, { importsequencenumber: number | null }, {  }>;
  isbilled: WebAttribute<Task_Select, { isbilled: boolean | null }, {  }>;
  isregularactivity: WebAttribute<Task_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<Task_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Task_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  modifiedby_guid: WebAttribute<Task_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Task_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Task_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<Task_Select, { onholdtime: number | null }, {  }>;
  overriddencreatedon: WebAttribute<Task_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Task_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Task_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Task_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Task_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  percentcomplete: WebAttribute<Task_Select, { percentcomplete: number | null }, {  }>;
  prioritycode: WebAttribute<Task_Select, { prioritycode: task_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Task_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<Task_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<Task_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<Task_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<Task_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  serviceid_guid: WebAttribute<Task_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<Task_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Task_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<Task_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<Task_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Task_Select, { statecode: task_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Task_Select, { statuscode: task_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<Task_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<Task_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<Task_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Task_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Task_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Task_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Task_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Task_Select, { versionnumber: number | null }, {  }>;
}
interface Task_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  category: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  crmtaskassigneduniqueid: XQW.Guid;
  description: string;
  exchangerate: any;
  importsequencenumber: number;
  isbilled: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  percentcomplete: number;
  prioritycode: task_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: task_statecode;
  statuscode: task_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Task_Expand {
  Task_Annotation: WebExpand<Task_Expand, Annotation_Select, Annotation_Filter, { Task_Annotation: Annotation_Result[] }>;
  Task_AsyncOperations: WebExpand<Task_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Task_AsyncOperations: AsyncOperation_Result[] }>;
  Task_BulkDeleteFailures: WebExpand<Task_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Task_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Task_DuplicateBaseRecord: WebExpand<Task_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Task_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Task_DuplicateMatchingRecord: WebExpand<Task_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Task_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Task_ProcessSessions: WebExpand<Task_Expand, ProcessSession_Select, ProcessSession_Filter, { Task_ProcessSessions: ProcessSession_Result[] }>;
  Task_QueueItem: WebExpand<Task_Expand, QueueItem_Select, QueueItem_Filter, { Task_QueueItem: QueueItem_Result[] }>;
  Task_SyncErrors: WebExpand<Task_Expand, SyncError_Select, SyncError_Filter, { Task_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<Task_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_task: WebExpand<Task_Expand, SystemUser_Select, SystemUser_Filter, { createdby_task: SystemUser_Result }>;
  createdonbehalfby_task: WebExpand<Task_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_task: SystemUser_Result }>;
  modifiedby_task: WebExpand<Task_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_task: SystemUser_Result }>;
  modifiedonbehalfby_task: WebExpand<Task_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_task: SystemUser_Result }>;
  ownerid_task: WebExpand<Task_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_task: SystemUser_Result } & { ownerid_task: Team_Result }>;
  owningbusinessunit_task: WebExpand<Task_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_task: BusinessUnit_Result }>;
  owningteam_task: WebExpand<Task_Expand, Team_Select, Team_Filter, { owningteam_task: Team_Result }>;
  owninguser_task: WebExpand<Task_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_task: SystemUser_Result }>;
  regardingobjectid_account_task: WebExpand<Task_Expand, Account_Select, Account_Filter, { regardingobjectid_account_task: Account_Result }>;
  regardingobjectid_awc_prototype_task: WebExpand<Task_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_task: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_task: WebExpand<Task_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_task: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_task: WebExpand<Task_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_task: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_task: WebExpand<Task_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_task: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_task: WebExpand<Task_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_task: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_task: WebExpand<Task_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_task: BulkOperation_Result }>;
  regardingobjectid_campaign_task: WebExpand<Task_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_task: Campaign_Result }>;
  regardingobjectid_campaignactivity_task: WebExpand<Task_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_task: CampaignActivity_Result }>;
  regardingobjectid_contact_task: WebExpand<Task_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_task: Contact_Result }>;
  regardingobjectid_contract_task: WebExpand<Task_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_task: Contract_Result }>;
  regardingobjectid_entitlement_task: WebExpand<Task_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_task: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_task: WebExpand<Task_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_task: EntitlementTemplate_Result }>;
  regardingobjectid_incident_task: WebExpand<Task_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_task: Incident_Result }>;
  regardingobjectid_invoice_task: WebExpand<Task_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_task: Invoice_Result }>;
  regardingobjectid_knowledgearticle_task: WebExpand<Task_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_task: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_task: WebExpand<Task_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_task: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_task: WebExpand<Task_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_task: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_task: WebExpand<Task_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_task: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_task: WebExpand<Task_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_task: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_task: WebExpand<Task_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_task: Opportunity_Result }>;
  regardingobjectid_quote_task: WebExpand<Task_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_task: Quote_Result }>;
  regardingobjectid_salesorder_task: WebExpand<Task_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_task: SalesOrder_Result }>;
  regardingobjectid_site_task: WebExpand<Task_Expand, Site_Select, Site_Filter, { regardingobjectid_site_task: Site_Result }>;
  serviceid_task: WebExpand<Task_Expand, Service_Select, Service_Filter, { serviceid_task: Service_Result }>;
  sla_task_sla: WebExpand<Task_Expand, SLA_Select, SLA_Filter, { sla_task_sla: SLA_Result }>;
  slainvokedid_task_sla: WebExpand<Task_Expand, SLA_Select, SLA_Filter, { slainvokedid_task_sla: SLA_Result }>;
  slakpiinstance_task: WebExpand<Task_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_task: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Task_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  task_PostFollows: WebExpand<Task_Expand, PostFollow_Select, PostFollow_Filter, { task_PostFollows: PostFollow_Result[] }>;
  task_PostRegardings: WebExpand<Task_Expand, PostRegarding_Select, PostRegarding_Filter, { task_PostRegardings: PostRegarding_Result[] }>;
  task_PostRoles: WebExpand<Task_Expand, PostRole_Select, PostRole_Filter, { task_PostRoles: PostRole_Result[] }>;
  task_actioncard: WebExpand<Task_Expand, ActionCard_Select, ActionCard_Filter, { task_actioncard: ActionCard_Result[] }>;
  task_activity_parties: WebExpand<Task_Expand, ActivityParty_Select, ActivityParty_Filter, { task_activity_parties: ActivityParty_Result[] }>;
  task_activitymonitor: WebExpand<Task_Expand, activitymonitor_Select, activitymonitor_Filter, { task_activitymonitor: activitymonitor_Result[] }>;
  task_connections1: WebExpand<Task_Expand, Connection_Select, Connection_Filter, { task_connections1: Connection_Result[] }>;
  task_connections2: WebExpand<Task_Expand, Connection_Select, Connection_Filter, { task_connections2: Connection_Result[] }>;
  task_principalobjectattributeaccess: WebExpand<Task_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { task_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  task_subscription_association: WebExpand<Task_Expand, Subscription_Select, Subscription_Filter, { task_subscription_association: Subscription_Result[] }>;
  transactioncurrencyid_task: WebExpand<Task_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_task: TransactionCurrency_Result }>;
  userentityinstancedata_task: WebExpand<Task_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_task: UserEntityInstanceData_Result[] }>;
}
interface Task_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Task_Result extends Task_Base, Task_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Task_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_task: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_task: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_task: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_task: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_task: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_task1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_task: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_task: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_task: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_task: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_task: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_task: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_task: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_task: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_task: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_task: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_task: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_task: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_task: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_task: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_task: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_task: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_task: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_task: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_task: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_task: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_task: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_task: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_task: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_task: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_task: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_task: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_task: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  serviceid_task: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_task_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_task_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_task: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Task_RelatedMany {
  Task_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Task_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Task_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Task_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Task_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Task_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Task_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  Task_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  slakpiinstance_task: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  task_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  task_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  task_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  task_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  task_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  task_activitymonitor: WebMappingRetrieve<activitymonitor_Select,activitymonitor_Expand,activitymonitor_Filter,activitymonitor_Fixed,activitymonitor_Result,activitymonitor_FormattedResult>;
  task_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  task_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  task_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  task_subscription_association: WebMappingRetrieve<Subscription_Select,Subscription_Expand,Subscription_Filter,Subscription_Fixed,Subscription_Result,Subscription_FormattedResult>;
  userentityinstancedata_task: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  tasks: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
}
interface WebEntitiesRelated {
  tasks: WebMappingRelated<Task_RelatedOne,Task_RelatedMany>;
}
interface WebEntitiesCUDA {
  tasks: WebMappingCUDA<Task_Create,Task_Update,Task_Select>;
}
