interface Team_Base extends WebEntity {
  azureactivedirectoryobjectid?: string | null;
  createdon?: Date | null;
  description?: string | null;
  emailaddress?: string | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  isdefault?: boolean | null;
  membershiptype?: team_membershiptype | null;
  modifiedon?: Date | null;
  name?: string | null;
  organizationid?: string | null;
  overriddencreatedon?: Date | null;
  processid?: string | null;
  stageid?: string | null;
  systemmanaged?: boolean | null;
  teamid?: string | null;
  teamtype?: team_type | null;
  traversedpath?: string | null;
  versionnumber?: number | null;
}
interface Team_Relationships {
  ImportFile_Team?: ImportFile_Result[] | null;
  OwningTeam_postfollows?: PostFollow_Result[] | null;
  Team_AsyncOperations?: AsyncOperation_Result[] | null;
  Team_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Team_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Team_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Team_ProcessSessions?: ProcessSession_Result[] | null;
  Team_SyncErrors?: SyncError_Result[] | null;
  associatedteamtemplateid?: TeamTemplate_Result | null;
  awcnpd_feedback_team_owningteam?: awcnpd_feedback_Result[] | null;
  lead_owning_team?: Lead_Result[] | null;
  organizationid_organization?: Organization_Result | null;
  regardingobjectid_knowledgearticle?: KnowledgeArticle_Result | null;
  regardingobjectid_opportunity?: Opportunity_Result | null;
  stageid_processstage?: ProcessStage_Result | null;
  team_BulkOperation?: BulkOperation_Result[] | null;
  team_Campaigns?: Campaign_Result[] | null;
  team_DuplicateRules?: DuplicateRule_Result[] | null;
  team_DynamicPropertyInstance?: DynamicPropertyInstance_Result[] | null;
  team_ImportData?: ImportData_Result[] | null;
  team_ImportFiles?: ImportFile_Result[] | null;
  team_ImportLogs?: ImportLog_Result[] | null;
  team_ImportMaps?: ImportMap_Result[] | null;
  team_Imports?: Import_Result[] | null;
  team_PostRegardings?: PostRegarding_Result[] | null;
  team_PostRoles?: PostRole_Result[] | null;
  team_SyncError?: SyncError_Result[] | null;
  team_accounts?: Account_Result[] | null;
  team_actioncardusersettings?: ActionCardUserSettings_Result[] | null;
  team_activity?: ActivityPointer_Result[] | null;
  team_activitymonitor?: activitymonitor_Result[] | null;
  team_adminsettingsentity?: adminsettingsentity_Result[] | null;
  team_annotations?: Annotation_Result[] | null;
  team_appointment?: Appointment_Result[] | null;
  team_asyncoperation?: AsyncOperation_Result[] | null;
  team_awc_customdemoentity?: awc_customdemoentity_Result[] | null;
  team_awc_idea?: awc_idea_Result[] | null;
  team_awc_prototype?: awc_prototype_Result[] | null;
  team_awc_venue?: awc_venue_Result[] | null;
  team_awcnpd_idea?: awcnpd_idea_Result[] | null;
  team_awcnpd_prototype?: awcnpd_prototype_Result[] | null;
  team_bookableresource?: BookableResource_Result[] | null;
  team_bookableresourcebooking?: BookableResourceBooking_Result[] | null;
  team_bookableresourcebookingexchangesyncidmapping?: BookableResourceBookingExchangeSyncIdMapping_Result[] | null;
  team_bookableresourcebookingheader?: BookableResourceBookingHeader_Result[] | null;
  team_bookableresourcecategory?: BookableResourceCategory_Result[] | null;
  team_bookableresourcecategoryassn?: BookableResourceCategoryAssn_Result[] | null;
  team_bookableresourcecharacteristic?: BookableResourceCharacteristic_Result[] | null;
  team_bookableresourcegroup?: BookableResourceGroup_Result[] | null;
  team_bookingstatus?: BookingStatus_Result[] | null;
  team_bot?: bot_Result[] | null;
  team_botcomponent?: botcomponent_Result[] | null;
  team_bulkoperationlog?: BulkOperationLog_Result[] | null;
  team_campaignactivity?: CampaignActivity_Result[] | null;
  team_campaignresponse?: CampaignResponse_Result[] | null;
  team_canvasappextendedmetadata?: CanvasAppExtendedMetadata_Result[] | null;
  team_channelaccessprofile?: ChannelAccessProfile_Result[] | null;
  team_characteristic?: Characteristic_Result[] | null;
  team_connectionreference?: connectionreference_Result[] | null;
  team_connections1?: Connection_Result[] | null;
  team_connections2?: Connection_Result[] | null;
  team_connector?: connector_Result[] | null;
  team_contacts?: Contact_Result[] | null;
  team_contractdetail?: ContractDetail_Result[] | null;
  team_conversationtranscript?: conversationtranscript_Result[] | null;
  team_convertrule?: ConvertRule_Result[] | null;
  team_customapi?: CustomAPI_Result[] | null;
  team_customapirequestparameter?: CustomAPIRequestParameter_Result[] | null;
  team_customapiresponseproperty?: CustomAPIResponseProperty_Result[] | null;
  team_customer_opportunity_roles?: CustomerOpportunityRole_Result[] | null;
  team_customer_relationship?: CustomerRelationship_Result[] | null;
  team_datalakefolder?: datalakefolder_Result[] | null;
  team_datalakefolderpermission?: datalakefolderpermission_Result[] | null;
  team_elca_project?: elca_Project_Result[] | null;
  team_elca_projectgroup?: elca_ProjectGroup_Result[] | null;
  team_email?: Email_Result[] | null;
  team_email_templates?: Template_Result[] | null;
  team_emailserverprofile?: EmailServerProfile_Result[] | null;
  team_entitlement?: Entitlement_Result[] | null;
  team_entitlementchannel?: EntitlementChannel_Result[] | null;
  team_entitlemententityallocationtypemapping?: EntitlementEntityAllocationTypeMapping_Result[] | null;
  team_environmentvariabledefinition?: EnvironmentVariableDefinition_Result[] | null;
  team_environmentvariablevalue?: EnvironmentVariableValue_Result[] | null;
  team_exchangesyncidmapping?: ExchangeSyncIdMapping_Result[] | null;
  team_exportsolutionupload?: ExportSolutionUpload_Result[] | null;
  team_externalparty?: ExternalParty_Result[] | null;
  team_fax?: Fax_Result[] | null;
  team_flowsession?: flowsession_Result[] | null;
  team_goal?: Goal_Result[] | null;
  team_goal_goalowner?: Goal_Result[] | null;
  team_goalrollupquery?: GoalRollupQuery_Result[] | null;
  team_incidentresolution?: IncidentResolution_Result[] | null;
  team_incidents?: Incident_Result[] | null;
  team_invoicedetail?: InvoiceDetail_Result[] | null;
  team_invoices?: Invoice_Result[] | null;
  team_knowledgearticle?: KnowledgeArticle_Result[] | null;
  team_knowledgearticleincident?: KnowledgeArticleIncident_Result[] | null;
  team_letter?: Letter_Result[] | null;
  team_list?: List_Result[] | null;
  team_listoperation?: listoperation_Result[] | null;
  team_mailbox?: Mailbox_Result[] | null;
  team_mailboxtrackingcategory?: MailboxTrackingCategory_Result[] | null;
  team_mailboxtrackingfolder?: MailboxTrackingFolder_Result[] | null;
  team_msdyn_actioncardregarding?: msdyn_actioncardregarding_Result[] | null;
  team_msdyn_actioncardrolesetting?: msdyn_actioncardrolesetting_Result[] | null;
  team_msdyn_aibdataset?: msdyn_AIBDataset_Result[] | null;
  team_msdyn_aibdatasetfile?: msdyn_AIBDatasetFile_Result[] | null;
  team_msdyn_aibdatasetrecord?: msdyn_AIBDatasetRecord_Result[] | null;
  team_msdyn_aibdatasetscontainer?: msdyn_AIBDatasetsContainer_Result[] | null;
  team_msdyn_aibfile?: msdyn_AIBFile_Result[] | null;
  team_msdyn_aibfileattacheddata?: msdyn_AIBFileAttachedData_Result[] | null;
  team_msdyn_aiconfiguration?: msdyn_AIConfiguration_Result[] | null;
  team_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result[] | null;
  team_msdyn_aimodel?: msdyn_AIModel_Result[] | null;
  team_msdyn_aiodimage?: msdyn_AIOdImage_Result[] | null;
  team_msdyn_aiodlabel?: msdyn_AIOdLabel_Result[] | null;
  team_msdyn_aiodtrainingboundingbox?: msdyn_AIOdTrainingBoundingBox_Result[] | null;
  team_msdyn_aiodtrainingimage?: msdyn_AIOdTrainingImage_Result[] | null;
  team_msdyn_aitemplate?: msdyn_AITemplate_Result[] | null;
  team_msdyn_autocapturerule?: msdyn_autocapturerule_Result[] | null;
  team_msdyn_autocapturesettings?: msdyn_autocapturesettings_Result[] | null;
  team_msdyn_callablecontext?: msdyn_callablecontext_Result[] | null;
  team_msdyn_entityrankingrule?: msdyn_entityrankingrule_Result[] | null;
  team_msdyn_federatedarticle?: msdyn_federatedarticle_Result[] | null;
  team_msdyn_flowcardtype?: msdyn_flowcardtype_Result[] | null;
  team_msdyn_icebreakersconfig?: msdyn_icebreakersconfig_Result[] | null;
  team_msdyn_kmfederatedsearchconfig?: msdyn_kmfederatedsearchconfig_Result[] | null;
  team_msdyn_knowledgearticleimage?: msdyn_knowledgearticleimage_Result[] | null;
  team_msdyn_knowledgearticletemplate?: msdyn_knowledgearticletemplate_Result[] | null;
  team_msdyn_knowledgeinteractioninsight?: msdyn_knowledgeinteractioninsight_Result[] | null;
  team_msdyn_knowledgesearchinsight?: msdyn_knowledgesearchinsight_Result[] | null;
  team_msdyn_msteamssetting?: msdyn_msteamssetting_Result[] | null;
  team_msdyn_notesanalysisconfig?: msdyn_notesanalysisconfig_Result[] | null;
  team_msdyn_playbookactivity?: msdyn_playbookactivity_Result[] | null;
  team_msdyn_playbookactivityattribute?: msdyn_playbookactivityattribute_Result[] | null;
  team_msdyn_playbookcategory?: msdyn_playbookcategory_Result[] | null;
  team_msdyn_playbookinstance?: msdyn_playbookinstance_Result[] | null;
  team_msdyn_playbooktemplate?: msdyn_playbooktemplate_Result[] | null;
  team_msdyn_postalbum?: msdyn_PostAlbum_Result[] | null;
  team_msdyn_relationshipinsightsunifiedconfig?: msdyn_relationshipinsightsunifiedconfig_Result[] | null;
  team_msdyn_richtextfile?: msdyn_richtextfile_Result[] | null;
  team_msdyn_salesinsightssettings?: msdyn_salesinsightssettings_Result[] | null;
  team_msdyn_siconfig?: msdyn_siconfig_Result[] | null;
  team_msdyn_untrackedappointment?: msdyn_untrackedappointment_Result[] | null;
  team_msdyn_wallsavedqueryusersettings?: msdyn_wallsavedqueryusersettings_Result[] | null;
  team_msdynce_botcontent?: msdynce_botcontent_Result[] | null;
  team_new_interactionforemail?: InteractionForEmail_Result[] | null;
  team_opportunities?: Opportunity_Result[] | null;
  team_opportunityclose?: OpportunityClose_Result[] | null;
  team_opportunityproduct?: OpportunityProduct_Result[] | null;
  team_orderclose?: OrderClose_Result[] | null;
  team_orders?: SalesOrder_Result[] | null;
  team_pdfsetting?: PDFSetting_Result[] | null;
  team_phonecall?: PhoneCall_Result[] | null;
  team_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  team_principalobjectattributeaccess_principalid?: PrincipalObjectAttributeAccess_Result[] | null;
  team_processsession?: ProcessSession_Result[] | null;
  team_processstageparameter?: processstageparameter_Result[] | null;
  team_profilerule?: ChannelAccessProfileRule_Result[] | null;
  team_queueitembase_workerid?: QueueItem_Result[] | null;
  team_quoteclose?: QuoteClose_Result[] | null;
  team_quotedetail?: QuoteDetail_Result[] | null;
  team_quotes?: Quote_Result[] | null;
  team_ratingmodel?: RatingModel_Result[] | null;
  team_ratingvalue?: RatingValue_Result[] | null;
  team_recurringappointmentmaster?: RecurringAppointmentMaster_Result[] | null;
  team_resource_groups?: ResourceGroup_Result[] | null;
  team_resource_specs?: ResourceSpec_Result[] | null;
  team_routingrule?: RoutingRule_Result[] | null;
  team_routingruleitem?: RoutingRuleItem_Result[] | null;
  team_salesorderdetail?: SalesOrderDetail_Result[] | null;
  team_service_appointments?: ServiceAppointment_Result[] | null;
  team_service_contracts?: Contract_Result[] | null;
  team_sharepointdocumentlocation?: SharePointDocumentLocation_Result[] | null;
  team_sharepointsite?: SharePointSite_Result[] | null;
  team_slaBase?: SLA_Result[] | null;
  team_socialactivity?: SocialActivity_Result[] | null;
  team_stagesolutionupload?: StageSolutionUpload_Result[] | null;
  team_task?: Task_Result[] | null;
  team_userentityinstancedata?: UserEntityInstanceData_Result[] | null;
  team_userentityuisettings?: UserEntityUISettings_Result[] | null;
  team_userform?: UserForm_Result[] | null;
  team_userquery?: UserQuery_Result[] | null;
  team_userqueryvisualizations?: UserQueryVisualization_Result[] | null;
  team_workflow?: Workflow_Result[] | null;
  team_workflowbinary?: workflowbinary_Result[] | null;
  team_workflowlog?: WorkflowLog_Result[] | null;
  teammembership_association?: SystemUser_Result[] | null;
  teamprofiles_association?: FieldSecurityProfile_Result[] | null;
  teamroles_association?: Role_Result[] | null;
  teamsyncattributemappingprofiles_association?: SyncAttributeMappingProfile_Result[] | null;
  userentityinstancedata_team?: UserEntityInstanceData_Result[] | null;
}
interface Team extends Team_Base, Team_Relationships {
  administratorid_bind$systemusers?: string | null;
  businessunitid_bind$businessunits?: string | null;
  queueid_bind$queues?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_bind$transactioncurrencies?: string | null;
}
interface Team_Create extends Team {
  associatedteamtemplateid_bind$teamtemplates?: string | null;
  regardingobjectid_knowledgearticle_bind$knowledgearticles?: string | null;
  regardingobjectid_opportunity_bind$opportunities?: string | null;
}
interface Team_Update extends Team {
}
interface Team_Select {
  administratorid_guid: WebAttribute<Team_Select, { administratorid_guid: string | null }, { administratorid_formatted?: string }>;
  azureactivedirectoryobjectid: WebAttribute<Team_Select, { azureactivedirectoryobjectid: string | null }, {  }>;
  businessunitid_guid: WebAttribute<Team_Select, { businessunitid_guid: string | null }, { businessunitid_formatted?: string }>;
  createdby_guid: WebAttribute<Team_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Team_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Team_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Team_Select, { description: string | null }, {  }>;
  emailaddress: WebAttribute<Team_Select, { emailaddress: string | null }, {  }>;
  exchangerate: WebAttribute<Team_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<Team_Select, { importsequencenumber: number | null }, {  }>;
  isdefault: WebAttribute<Team_Select, { isdefault: boolean | null }, {  }>;
  membershiptype: WebAttribute<Team_Select, { membershiptype: team_membershiptype | null }, { membershiptype_formatted?: string }>;
  modifiedby_guid: WebAttribute<Team_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Team_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Team_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  name: WebAttribute<Team_Select, { name: string | null }, {  }>;
  organizationid: WebAttribute<Team_Select, { organizationid: string | null }, {  }>;
  overriddencreatedon: WebAttribute<Team_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  processid: WebAttribute<Team_Select, { processid: string | null }, {  }>;
  queueid_guid: WebAttribute<Team_Select, { queueid_guid: string | null }, { queueid_formatted?: string }>;
  regardingobjectid_guid: WebAttribute<Team_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  stageid: WebAttribute<Team_Select, { stageid: string | null }, {  }>;
  systemmanaged: WebAttribute<Team_Select, { systemmanaged: boolean | null }, {  }>;
  teamid: WebAttribute<Team_Select, { teamid: string | null }, {  }>;
  teamtemplateid_guid: WebAttribute<Team_Select, { teamtemplateid_guid: string | null }, { teamtemplateid_formatted?: string }>;
  teamtype: WebAttribute<Team_Select, { teamtype: team_type | null }, { teamtype_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Team_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Team_Select, { traversedpath: string | null }, {  }>;
  versionnumber: WebAttribute<Team_Select, { versionnumber: number | null }, {  }>;
}
interface Team_Filter {
  administratorid_guid: XQW.Guid;
  azureactivedirectoryobjectid: XQW.Guid;
  businessunitid_guid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  emailaddress: string;
  exchangerate: any;
  importsequencenumber: number;
  isdefault: boolean;
  membershiptype: team_membershiptype;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  name: string;
  organizationid: XQW.Guid;
  overriddencreatedon: Date;
  processid: XQW.Guid;
  queueid_guid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  stageid: XQW.Guid;
  systemmanaged: boolean;
  teamid: XQW.Guid;
  teamtemplateid_guid: XQW.Guid;
  teamtype: team_type;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  versionnumber: number;
}
interface Team_Expand {
  ImportFile_Team: WebExpand<Team_Expand, ImportFile_Select, ImportFile_Filter, { ImportFile_Team: ImportFile_Result[] }>;
  OwningTeam_postfollows: WebExpand<Team_Expand, PostFollow_Select, PostFollow_Filter, { OwningTeam_postfollows: PostFollow_Result[] }>;
  Team_AsyncOperations: WebExpand<Team_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Team_AsyncOperations: AsyncOperation_Result[] }>;
  Team_BulkDeleteFailures: WebExpand<Team_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Team_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Team_DuplicateBaseRecord: WebExpand<Team_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Team_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Team_DuplicateMatchingRecord: WebExpand<Team_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Team_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Team_ProcessSessions: WebExpand<Team_Expand, ProcessSession_Select, ProcessSession_Filter, { Team_ProcessSessions: ProcessSession_Result[] }>;
  Team_SyncErrors: WebExpand<Team_Expand, SyncError_Select, SyncError_Filter, { Team_SyncErrors: SyncError_Result[] }>;
  administratorid: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { administratorid: SystemUser_Result }>;
  associatedteamtemplateid: WebExpand<Team_Expand, TeamTemplate_Select, TeamTemplate_Filter, { associatedteamtemplateid: TeamTemplate_Result }>;
  awcnpd_feedback_team_owningteam: WebExpand<Team_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { awcnpd_feedback_team_owningteam: awcnpd_feedback_Result[] }>;
  businessunitid: WebExpand<Team_Expand, BusinessUnit_Select, BusinessUnit_Filter, { businessunitid: BusinessUnit_Result }>;
  createdby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  lead_owning_team: WebExpand<Team_Expand, Lead_Select, Lead_Filter, { lead_owning_team: Lead_Result[] }>;
  modifiedby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  organizationid_organization: WebExpand<Team_Expand, Organization_Select, Organization_Filter, { organizationid_organization: Organization_Result }>;
  queueid: WebExpand<Team_Expand, Queue_Select, Queue_Filter, { queueid: Queue_Result }>;
  regardingobjectid_knowledgearticle: WebExpand<Team_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle: KnowledgeArticle_Result }>;
  regardingobjectid_opportunity: WebExpand<Team_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity: Opportunity_Result }>;
  stageid_processstage: WebExpand<Team_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  team_BulkOperation: WebExpand<Team_Expand, BulkOperation_Select, BulkOperation_Filter, { team_BulkOperation: BulkOperation_Result[] }>;
  team_Campaigns: WebExpand<Team_Expand, Campaign_Select, Campaign_Filter, { team_Campaigns: Campaign_Result[] }>;
  team_DuplicateRules: WebExpand<Team_Expand, DuplicateRule_Select, DuplicateRule_Filter, { team_DuplicateRules: DuplicateRule_Result[] }>;
  team_DynamicPropertyInstance: WebExpand<Team_Expand, DynamicPropertyInstance_Select, DynamicPropertyInstance_Filter, { team_DynamicPropertyInstance: DynamicPropertyInstance_Result[] }>;
  team_ImportData: WebExpand<Team_Expand, ImportData_Select, ImportData_Filter, { team_ImportData: ImportData_Result[] }>;
  team_ImportFiles: WebExpand<Team_Expand, ImportFile_Select, ImportFile_Filter, { team_ImportFiles: ImportFile_Result[] }>;
  team_ImportLogs: WebExpand<Team_Expand, ImportLog_Select, ImportLog_Filter, { team_ImportLogs: ImportLog_Result[] }>;
  team_ImportMaps: WebExpand<Team_Expand, ImportMap_Select, ImportMap_Filter, { team_ImportMaps: ImportMap_Result[] }>;
  team_Imports: WebExpand<Team_Expand, Import_Select, Import_Filter, { team_Imports: Import_Result[] }>;
  team_PostRegardings: WebExpand<Team_Expand, PostRegarding_Select, PostRegarding_Filter, { team_PostRegardings: PostRegarding_Result[] }>;
  team_PostRoles: WebExpand<Team_Expand, PostRole_Select, PostRole_Filter, { team_PostRoles: PostRole_Result[] }>;
  team_SyncError: WebExpand<Team_Expand, SyncError_Select, SyncError_Filter, { team_SyncError: SyncError_Result[] }>;
  team_accounts: WebExpand<Team_Expand, Account_Select, Account_Filter, { team_accounts: Account_Result[] }>;
  team_actioncardusersettings: WebExpand<Team_Expand, ActionCardUserSettings_Select, ActionCardUserSettings_Filter, { team_actioncardusersettings: ActionCardUserSettings_Result[] }>;
  team_activity: WebExpand<Team_Expand, ActivityPointer_Select, ActivityPointer_Filter, { team_activity: ActivityPointer_Result[] }>;
  team_activitymonitor: WebExpand<Team_Expand, activitymonitor_Select, activitymonitor_Filter, { team_activitymonitor: activitymonitor_Result[] }>;
  team_adminsettingsentity: WebExpand<Team_Expand, adminsettingsentity_Select, adminsettingsentity_Filter, { team_adminsettingsentity: adminsettingsentity_Result[] }>;
  team_annotations: WebExpand<Team_Expand, Annotation_Select, Annotation_Filter, { team_annotations: Annotation_Result[] }>;
  team_appointment: WebExpand<Team_Expand, Appointment_Select, Appointment_Filter, { team_appointment: Appointment_Result[] }>;
  team_asyncoperation: WebExpand<Team_Expand, AsyncOperation_Select, AsyncOperation_Filter, { team_asyncoperation: AsyncOperation_Result[] }>;
  team_awc_customdemoentity: WebExpand<Team_Expand, awc_customdemoentity_Select, awc_customdemoentity_Filter, { team_awc_customdemoentity: awc_customdemoentity_Result[] }>;
  team_awc_idea: WebExpand<Team_Expand, awc_idea_Select, awc_idea_Filter, { team_awc_idea: awc_idea_Result[] }>;
  team_awc_prototype: WebExpand<Team_Expand, awc_prototype_Select, awc_prototype_Filter, { team_awc_prototype: awc_prototype_Result[] }>;
  team_awc_venue: WebExpand<Team_Expand, awc_venue_Select, awc_venue_Filter, { team_awc_venue: awc_venue_Result[] }>;
  team_awcnpd_idea: WebExpand<Team_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { team_awcnpd_idea: awcnpd_idea_Result[] }>;
  team_awcnpd_prototype: WebExpand<Team_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { team_awcnpd_prototype: awcnpd_prototype_Result[] }>;
  team_bookableresource: WebExpand<Team_Expand, BookableResource_Select, BookableResource_Filter, { team_bookableresource: BookableResource_Result[] }>;
  team_bookableresourcebooking: WebExpand<Team_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { team_bookableresourcebooking: BookableResourceBooking_Result[] }>;
  team_bookableresourcebookingexchangesyncidmapping: WebExpand<Team_Expand, BookableResourceBookingExchangeSyncIdMapping_Select, BookableResourceBookingExchangeSyncIdMapping_Filter, { team_bookableresourcebookingexchangesyncidmapping: BookableResourceBookingExchangeSyncIdMapping_Result[] }>;
  team_bookableresourcebookingheader: WebExpand<Team_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { team_bookableresourcebookingheader: BookableResourceBookingHeader_Result[] }>;
  team_bookableresourcecategory: WebExpand<Team_Expand, BookableResourceCategory_Select, BookableResourceCategory_Filter, { team_bookableresourcecategory: BookableResourceCategory_Result[] }>;
  team_bookableresourcecategoryassn: WebExpand<Team_Expand, BookableResourceCategoryAssn_Select, BookableResourceCategoryAssn_Filter, { team_bookableresourcecategoryassn: BookableResourceCategoryAssn_Result[] }>;
  team_bookableresourcecharacteristic: WebExpand<Team_Expand, BookableResourceCharacteristic_Select, BookableResourceCharacteristic_Filter, { team_bookableresourcecharacteristic: BookableResourceCharacteristic_Result[] }>;
  team_bookableresourcegroup: WebExpand<Team_Expand, BookableResourceGroup_Select, BookableResourceGroup_Filter, { team_bookableresourcegroup: BookableResourceGroup_Result[] }>;
  team_bookingstatus: WebExpand<Team_Expand, BookingStatus_Select, BookingStatus_Filter, { team_bookingstatus: BookingStatus_Result[] }>;
  team_bot: WebExpand<Team_Expand, bot_Select, bot_Filter, { team_bot: bot_Result[] }>;
  team_botcomponent: WebExpand<Team_Expand, botcomponent_Select, botcomponent_Filter, { team_botcomponent: botcomponent_Result[] }>;
  team_bulkoperationlog: WebExpand<Team_Expand, BulkOperationLog_Select, BulkOperationLog_Filter, { team_bulkoperationlog: BulkOperationLog_Result[] }>;
  team_campaignactivity: WebExpand<Team_Expand, CampaignActivity_Select, CampaignActivity_Filter, { team_campaignactivity: CampaignActivity_Result[] }>;
  team_campaignresponse: WebExpand<Team_Expand, CampaignResponse_Select, CampaignResponse_Filter, { team_campaignresponse: CampaignResponse_Result[] }>;
  team_canvasappextendedmetadata: WebExpand<Team_Expand, CanvasAppExtendedMetadata_Select, CanvasAppExtendedMetadata_Filter, { team_canvasappextendedmetadata: CanvasAppExtendedMetadata_Result[] }>;
  team_channelaccessprofile: WebExpand<Team_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { team_channelaccessprofile: ChannelAccessProfile_Result[] }>;
  team_characteristic: WebExpand<Team_Expand, Characteristic_Select, Characteristic_Filter, { team_characteristic: Characteristic_Result[] }>;
  team_connectionreference: WebExpand<Team_Expand, connectionreference_Select, connectionreference_Filter, { team_connectionreference: connectionreference_Result[] }>;
  team_connections1: WebExpand<Team_Expand, Connection_Select, Connection_Filter, { team_connections1: Connection_Result[] }>;
  team_connections2: WebExpand<Team_Expand, Connection_Select, Connection_Filter, { team_connections2: Connection_Result[] }>;
  team_connector: WebExpand<Team_Expand, connector_Select, connector_Filter, { team_connector: connector_Result[] }>;
  team_contacts: WebExpand<Team_Expand, Contact_Select, Contact_Filter, { team_contacts: Contact_Result[] }>;
  team_contractdetail: WebExpand<Team_Expand, ContractDetail_Select, ContractDetail_Filter, { team_contractdetail: ContractDetail_Result[] }>;
  team_conversationtranscript: WebExpand<Team_Expand, conversationtranscript_Select, conversationtranscript_Filter, { team_conversationtranscript: conversationtranscript_Result[] }>;
  team_convertrule: WebExpand<Team_Expand, ConvertRule_Select, ConvertRule_Filter, { team_convertrule: ConvertRule_Result[] }>;
  team_customapi: WebExpand<Team_Expand, CustomAPI_Select, CustomAPI_Filter, { team_customapi: CustomAPI_Result[] }>;
  team_customapirequestparameter: WebExpand<Team_Expand, CustomAPIRequestParameter_Select, CustomAPIRequestParameter_Filter, { team_customapirequestparameter: CustomAPIRequestParameter_Result[] }>;
  team_customapiresponseproperty: WebExpand<Team_Expand, CustomAPIResponseProperty_Select, CustomAPIResponseProperty_Filter, { team_customapiresponseproperty: CustomAPIResponseProperty_Result[] }>;
  team_customer_opportunity_roles: WebExpand<Team_Expand, CustomerOpportunityRole_Select, CustomerOpportunityRole_Filter, { team_customer_opportunity_roles: CustomerOpportunityRole_Result[] }>;
  team_customer_relationship: WebExpand<Team_Expand, CustomerRelationship_Select, CustomerRelationship_Filter, { team_customer_relationship: CustomerRelationship_Result[] }>;
  team_datalakefolder: WebExpand<Team_Expand, datalakefolder_Select, datalakefolder_Filter, { team_datalakefolder: datalakefolder_Result[] }>;
  team_datalakefolderpermission: WebExpand<Team_Expand, datalakefolderpermission_Select, datalakefolderpermission_Filter, { team_datalakefolderpermission: datalakefolderpermission_Result[] }>;
  team_elca_project: WebExpand<Team_Expand, elca_Project_Select, elca_Project_Filter, { team_elca_project: elca_Project_Result[] }>;
  team_elca_projectgroup: WebExpand<Team_Expand, elca_ProjectGroup_Select, elca_ProjectGroup_Filter, { team_elca_projectgroup: elca_ProjectGroup_Result[] }>;
  team_email: WebExpand<Team_Expand, Email_Select, Email_Filter, { team_email: Email_Result[] }>;
  team_email_templates: WebExpand<Team_Expand, Template_Select, Template_Filter, { team_email_templates: Template_Result[] }>;
  team_emailserverprofile: WebExpand<Team_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { team_emailserverprofile: EmailServerProfile_Result[] }>;
  team_entitlement: WebExpand<Team_Expand, Entitlement_Select, Entitlement_Filter, { team_entitlement: Entitlement_Result[] }>;
  team_entitlementchannel: WebExpand<Team_Expand, EntitlementChannel_Select, EntitlementChannel_Filter, { team_entitlementchannel: EntitlementChannel_Result[] }>;
  team_entitlemententityallocationtypemapping: WebExpand<Team_Expand, EntitlementEntityAllocationTypeMapping_Select, EntitlementEntityAllocationTypeMapping_Filter, { team_entitlemententityallocationtypemapping: EntitlementEntityAllocationTypeMapping_Result[] }>;
  team_environmentvariabledefinition: WebExpand<Team_Expand, EnvironmentVariableDefinition_Select, EnvironmentVariableDefinition_Filter, { team_environmentvariabledefinition: EnvironmentVariableDefinition_Result[] }>;
  team_environmentvariablevalue: WebExpand<Team_Expand, EnvironmentVariableValue_Select, EnvironmentVariableValue_Filter, { team_environmentvariablevalue: EnvironmentVariableValue_Result[] }>;
  team_exchangesyncidmapping: WebExpand<Team_Expand, ExchangeSyncIdMapping_Select, ExchangeSyncIdMapping_Filter, { team_exchangesyncidmapping: ExchangeSyncIdMapping_Result[] }>;
  team_exportsolutionupload: WebExpand<Team_Expand, ExportSolutionUpload_Select, ExportSolutionUpload_Filter, { team_exportsolutionupload: ExportSolutionUpload_Result[] }>;
  team_externalparty: WebExpand<Team_Expand, ExternalParty_Select, ExternalParty_Filter, { team_externalparty: ExternalParty_Result[] }>;
  team_fax: WebExpand<Team_Expand, Fax_Select, Fax_Filter, { team_fax: Fax_Result[] }>;
  team_flowsession: WebExpand<Team_Expand, flowsession_Select, flowsession_Filter, { team_flowsession: flowsession_Result[] }>;
  team_goal: WebExpand<Team_Expand, Goal_Select, Goal_Filter, { team_goal: Goal_Result[] }>;
  team_goal_goalowner: WebExpand<Team_Expand, Goal_Select, Goal_Filter, { team_goal_goalowner: Goal_Result[] }>;
  team_goalrollupquery: WebExpand<Team_Expand, GoalRollupQuery_Select, GoalRollupQuery_Filter, { team_goalrollupquery: GoalRollupQuery_Result[] }>;
  team_incidentresolution: WebExpand<Team_Expand, IncidentResolution_Select, IncidentResolution_Filter, { team_incidentresolution: IncidentResolution_Result[] }>;
  team_incidents: WebExpand<Team_Expand, Incident_Select, Incident_Filter, { team_incidents: Incident_Result[] }>;
  team_invoicedetail: WebExpand<Team_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { team_invoicedetail: InvoiceDetail_Result[] }>;
  team_invoices: WebExpand<Team_Expand, Invoice_Select, Invoice_Filter, { team_invoices: Invoice_Result[] }>;
  team_knowledgearticle: WebExpand<Team_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { team_knowledgearticle: KnowledgeArticle_Result[] }>;
  team_knowledgearticleincident: WebExpand<Team_Expand, KnowledgeArticleIncident_Select, KnowledgeArticleIncident_Filter, { team_knowledgearticleincident: KnowledgeArticleIncident_Result[] }>;
  team_letter: WebExpand<Team_Expand, Letter_Select, Letter_Filter, { team_letter: Letter_Result[] }>;
  team_list: WebExpand<Team_Expand, List_Select, List_Filter, { team_list: List_Result[] }>;
  team_listoperation: WebExpand<Team_Expand, listoperation_Select, listoperation_Filter, { team_listoperation: listoperation_Result[] }>;
  team_mailbox: WebExpand<Team_Expand, Mailbox_Select, Mailbox_Filter, { team_mailbox: Mailbox_Result[] }>;
  team_mailboxtrackingcategory: WebExpand<Team_Expand, MailboxTrackingCategory_Select, MailboxTrackingCategory_Filter, { team_mailboxtrackingcategory: MailboxTrackingCategory_Result[] }>;
  team_mailboxtrackingfolder: WebExpand<Team_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { team_mailboxtrackingfolder: MailboxTrackingFolder_Result[] }>;
  team_msdyn_actioncardregarding: WebExpand<Team_Expand, msdyn_actioncardregarding_Select, msdyn_actioncardregarding_Filter, { team_msdyn_actioncardregarding: msdyn_actioncardregarding_Result[] }>;
  team_msdyn_actioncardrolesetting: WebExpand<Team_Expand, msdyn_actioncardrolesetting_Select, msdyn_actioncardrolesetting_Filter, { team_msdyn_actioncardrolesetting: msdyn_actioncardrolesetting_Result[] }>;
  team_msdyn_aibdataset: WebExpand<Team_Expand, msdyn_AIBDataset_Select, msdyn_AIBDataset_Filter, { team_msdyn_aibdataset: msdyn_AIBDataset_Result[] }>;
  team_msdyn_aibdatasetfile: WebExpand<Team_Expand, msdyn_AIBDatasetFile_Select, msdyn_AIBDatasetFile_Filter, { team_msdyn_aibdatasetfile: msdyn_AIBDatasetFile_Result[] }>;
  team_msdyn_aibdatasetrecord: WebExpand<Team_Expand, msdyn_AIBDatasetRecord_Select, msdyn_AIBDatasetRecord_Filter, { team_msdyn_aibdatasetrecord: msdyn_AIBDatasetRecord_Result[] }>;
  team_msdyn_aibdatasetscontainer: WebExpand<Team_Expand, msdyn_AIBDatasetsContainer_Select, msdyn_AIBDatasetsContainer_Filter, { team_msdyn_aibdatasetscontainer: msdyn_AIBDatasetsContainer_Result[] }>;
  team_msdyn_aibfile: WebExpand<Team_Expand, msdyn_AIBFile_Select, msdyn_AIBFile_Filter, { team_msdyn_aibfile: msdyn_AIBFile_Result[] }>;
  team_msdyn_aibfileattacheddata: WebExpand<Team_Expand, msdyn_AIBFileAttachedData_Select, msdyn_AIBFileAttachedData_Filter, { team_msdyn_aibfileattacheddata: msdyn_AIBFileAttachedData_Result[] }>;
  team_msdyn_aiconfiguration: WebExpand<Team_Expand, msdyn_AIConfiguration_Select, msdyn_AIConfiguration_Filter, { team_msdyn_aiconfiguration: msdyn_AIConfiguration_Result[] }>;
  team_msdyn_aifptrainingdocument: WebExpand<Team_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { team_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result[] }>;
  team_msdyn_aimodel: WebExpand<Team_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { team_msdyn_aimodel: msdyn_AIModel_Result[] }>;
  team_msdyn_aiodimage: WebExpand<Team_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { team_msdyn_aiodimage: msdyn_AIOdImage_Result[] }>;
  team_msdyn_aiodlabel: WebExpand<Team_Expand, msdyn_AIOdLabel_Select, msdyn_AIOdLabel_Filter, { team_msdyn_aiodlabel: msdyn_AIOdLabel_Result[] }>;
  team_msdyn_aiodtrainingboundingbox: WebExpand<Team_Expand, msdyn_AIOdTrainingBoundingBox_Select, msdyn_AIOdTrainingBoundingBox_Filter, { team_msdyn_aiodtrainingboundingbox: msdyn_AIOdTrainingBoundingBox_Result[] }>;
  team_msdyn_aiodtrainingimage: WebExpand<Team_Expand, msdyn_AIOdTrainingImage_Select, msdyn_AIOdTrainingImage_Filter, { team_msdyn_aiodtrainingimage: msdyn_AIOdTrainingImage_Result[] }>;
  team_msdyn_aitemplate: WebExpand<Team_Expand, msdyn_AITemplate_Select, msdyn_AITemplate_Filter, { team_msdyn_aitemplate: msdyn_AITemplate_Result[] }>;
  team_msdyn_autocapturerule: WebExpand<Team_Expand, msdyn_autocapturerule_Select, msdyn_autocapturerule_Filter, { team_msdyn_autocapturerule: msdyn_autocapturerule_Result[] }>;
  team_msdyn_autocapturesettings: WebExpand<Team_Expand, msdyn_autocapturesettings_Select, msdyn_autocapturesettings_Filter, { team_msdyn_autocapturesettings: msdyn_autocapturesettings_Result[] }>;
  team_msdyn_callablecontext: WebExpand<Team_Expand, msdyn_callablecontext_Select, msdyn_callablecontext_Filter, { team_msdyn_callablecontext: msdyn_callablecontext_Result[] }>;
  team_msdyn_entityrankingrule: WebExpand<Team_Expand, msdyn_entityrankingrule_Select, msdyn_entityrankingrule_Filter, { team_msdyn_entityrankingrule: msdyn_entityrankingrule_Result[] }>;
  team_msdyn_federatedarticle: WebExpand<Team_Expand, msdyn_federatedarticle_Select, msdyn_federatedarticle_Filter, { team_msdyn_federatedarticle: msdyn_federatedarticle_Result[] }>;
  team_msdyn_flowcardtype: WebExpand<Team_Expand, msdyn_flowcardtype_Select, msdyn_flowcardtype_Filter, { team_msdyn_flowcardtype: msdyn_flowcardtype_Result[] }>;
  team_msdyn_icebreakersconfig: WebExpand<Team_Expand, msdyn_icebreakersconfig_Select, msdyn_icebreakersconfig_Filter, { team_msdyn_icebreakersconfig: msdyn_icebreakersconfig_Result[] }>;
  team_msdyn_kmfederatedsearchconfig: WebExpand<Team_Expand, msdyn_kmfederatedsearchconfig_Select, msdyn_kmfederatedsearchconfig_Filter, { team_msdyn_kmfederatedsearchconfig: msdyn_kmfederatedsearchconfig_Result[] }>;
  team_msdyn_knowledgearticleimage: WebExpand<Team_Expand, msdyn_knowledgearticleimage_Select, msdyn_knowledgearticleimage_Filter, { team_msdyn_knowledgearticleimage: msdyn_knowledgearticleimage_Result[] }>;
  team_msdyn_knowledgearticletemplate: WebExpand<Team_Expand, msdyn_knowledgearticletemplate_Select, msdyn_knowledgearticletemplate_Filter, { team_msdyn_knowledgearticletemplate: msdyn_knowledgearticletemplate_Result[] }>;
  team_msdyn_knowledgeinteractioninsight: WebExpand<Team_Expand, msdyn_knowledgeinteractioninsight_Select, msdyn_knowledgeinteractioninsight_Filter, { team_msdyn_knowledgeinteractioninsight: msdyn_knowledgeinteractioninsight_Result[] }>;
  team_msdyn_knowledgesearchinsight: WebExpand<Team_Expand, msdyn_knowledgesearchinsight_Select, msdyn_knowledgesearchinsight_Filter, { team_msdyn_knowledgesearchinsight: msdyn_knowledgesearchinsight_Result[] }>;
  team_msdyn_msteamssetting: WebExpand<Team_Expand, msdyn_msteamssetting_Select, msdyn_msteamssetting_Filter, { team_msdyn_msteamssetting: msdyn_msteamssetting_Result[] }>;
  team_msdyn_notesanalysisconfig: WebExpand<Team_Expand, msdyn_notesanalysisconfig_Select, msdyn_notesanalysisconfig_Filter, { team_msdyn_notesanalysisconfig: msdyn_notesanalysisconfig_Result[] }>;
  team_msdyn_playbookactivity: WebExpand<Team_Expand, msdyn_playbookactivity_Select, msdyn_playbookactivity_Filter, { team_msdyn_playbookactivity: msdyn_playbookactivity_Result[] }>;
  team_msdyn_playbookactivityattribute: WebExpand<Team_Expand, msdyn_playbookactivityattribute_Select, msdyn_playbookactivityattribute_Filter, { team_msdyn_playbookactivityattribute: msdyn_playbookactivityattribute_Result[] }>;
  team_msdyn_playbookcategory: WebExpand<Team_Expand, msdyn_playbookcategory_Select, msdyn_playbookcategory_Filter, { team_msdyn_playbookcategory: msdyn_playbookcategory_Result[] }>;
  team_msdyn_playbookinstance: WebExpand<Team_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { team_msdyn_playbookinstance: msdyn_playbookinstance_Result[] }>;
  team_msdyn_playbooktemplate: WebExpand<Team_Expand, msdyn_playbooktemplate_Select, msdyn_playbooktemplate_Filter, { team_msdyn_playbooktemplate: msdyn_playbooktemplate_Result[] }>;
  team_msdyn_postalbum: WebExpand<Team_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { team_msdyn_postalbum: msdyn_PostAlbum_Result[] }>;
  team_msdyn_relationshipinsightsunifiedconfig: WebExpand<Team_Expand, msdyn_relationshipinsightsunifiedconfig_Select, msdyn_relationshipinsightsunifiedconfig_Filter, { team_msdyn_relationshipinsightsunifiedconfig: msdyn_relationshipinsightsunifiedconfig_Result[] }>;
  team_msdyn_richtextfile: WebExpand<Team_Expand, msdyn_richtextfile_Select, msdyn_richtextfile_Filter, { team_msdyn_richtextfile: msdyn_richtextfile_Result[] }>;
  team_msdyn_salesinsightssettings: WebExpand<Team_Expand, msdyn_salesinsightssettings_Select, msdyn_salesinsightssettings_Filter, { team_msdyn_salesinsightssettings: msdyn_salesinsightssettings_Result[] }>;
  team_msdyn_siconfig: WebExpand<Team_Expand, msdyn_siconfig_Select, msdyn_siconfig_Filter, { team_msdyn_siconfig: msdyn_siconfig_Result[] }>;
  team_msdyn_untrackedappointment: WebExpand<Team_Expand, msdyn_untrackedappointment_Select, msdyn_untrackedappointment_Filter, { team_msdyn_untrackedappointment: msdyn_untrackedappointment_Result[] }>;
  team_msdyn_wallsavedqueryusersettings: WebExpand<Team_Expand, msdyn_wallsavedqueryusersettings_Select, msdyn_wallsavedqueryusersettings_Filter, { team_msdyn_wallsavedqueryusersettings: msdyn_wallsavedqueryusersettings_Result[] }>;
  team_msdynce_botcontent: WebExpand<Team_Expand, msdynce_botcontent_Select, msdynce_botcontent_Filter, { team_msdynce_botcontent: msdynce_botcontent_Result[] }>;
  team_new_interactionforemail: WebExpand<Team_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { team_new_interactionforemail: InteractionForEmail_Result[] }>;
  team_opportunities: WebExpand<Team_Expand, Opportunity_Select, Opportunity_Filter, { team_opportunities: Opportunity_Result[] }>;
  team_opportunityclose: WebExpand<Team_Expand, OpportunityClose_Select, OpportunityClose_Filter, { team_opportunityclose: OpportunityClose_Result[] }>;
  team_opportunityproduct: WebExpand<Team_Expand, OpportunityProduct_Select, OpportunityProduct_Filter, { team_opportunityproduct: OpportunityProduct_Result[] }>;
  team_orderclose: WebExpand<Team_Expand, OrderClose_Select, OrderClose_Filter, { team_orderclose: OrderClose_Result[] }>;
  team_orders: WebExpand<Team_Expand, SalesOrder_Select, SalesOrder_Filter, { team_orders: SalesOrder_Result[] }>;
  team_pdfsetting: WebExpand<Team_Expand, PDFSetting_Select, PDFSetting_Filter, { team_pdfsetting: PDFSetting_Result[] }>;
  team_phonecall: WebExpand<Team_Expand, PhoneCall_Select, PhoneCall_Filter, { team_phonecall: PhoneCall_Result[] }>;
  team_principalobjectattributeaccess: WebExpand<Team_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { team_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  team_principalobjectattributeaccess_principalid: WebExpand<Team_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { team_principalobjectattributeaccess_principalid: PrincipalObjectAttributeAccess_Result[] }>;
  team_processsession: WebExpand<Team_Expand, ProcessSession_Select, ProcessSession_Filter, { team_processsession: ProcessSession_Result[] }>;
  team_processstageparameter: WebExpand<Team_Expand, processstageparameter_Select, processstageparameter_Filter, { team_processstageparameter: processstageparameter_Result[] }>;
  team_profilerule: WebExpand<Team_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { team_profilerule: ChannelAccessProfileRule_Result[] }>;
  team_queueitembase_workerid: WebExpand<Team_Expand, QueueItem_Select, QueueItem_Filter, { team_queueitembase_workerid: QueueItem_Result[] }>;
  team_quoteclose: WebExpand<Team_Expand, QuoteClose_Select, QuoteClose_Filter, { team_quoteclose: QuoteClose_Result[] }>;
  team_quotedetail: WebExpand<Team_Expand, QuoteDetail_Select, QuoteDetail_Filter, { team_quotedetail: QuoteDetail_Result[] }>;
  team_quotes: WebExpand<Team_Expand, Quote_Select, Quote_Filter, { team_quotes: Quote_Result[] }>;
  team_ratingmodel: WebExpand<Team_Expand, RatingModel_Select, RatingModel_Filter, { team_ratingmodel: RatingModel_Result[] }>;
  team_ratingvalue: WebExpand<Team_Expand, RatingValue_Select, RatingValue_Filter, { team_ratingvalue: RatingValue_Result[] }>;
  team_recurringappointmentmaster: WebExpand<Team_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { team_recurringappointmentmaster: RecurringAppointmentMaster_Result[] }>;
  team_resource_groups: WebExpand<Team_Expand, ResourceGroup_Select, ResourceGroup_Filter, { team_resource_groups: ResourceGroup_Result[] }>;
  team_resource_specs: WebExpand<Team_Expand, ResourceSpec_Select, ResourceSpec_Filter, { team_resource_specs: ResourceSpec_Result[] }>;
  team_routingrule: WebExpand<Team_Expand, RoutingRule_Select, RoutingRule_Filter, { team_routingrule: RoutingRule_Result[] }>;
  team_routingruleitem: WebExpand<Team_Expand, RoutingRuleItem_Select, RoutingRuleItem_Filter, { team_routingruleitem: RoutingRuleItem_Result[] }>;
  team_salesorderdetail: WebExpand<Team_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { team_salesorderdetail: SalesOrderDetail_Result[] }>;
  team_service_appointments: WebExpand<Team_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { team_service_appointments: ServiceAppointment_Result[] }>;
  team_service_contracts: WebExpand<Team_Expand, Contract_Select, Contract_Filter, { team_service_contracts: Contract_Result[] }>;
  team_sharepointdocumentlocation: WebExpand<Team_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { team_sharepointdocumentlocation: SharePointDocumentLocation_Result[] }>;
  team_sharepointsite: WebExpand<Team_Expand, SharePointSite_Select, SharePointSite_Filter, { team_sharepointsite: SharePointSite_Result[] }>;
  team_slaBase: WebExpand<Team_Expand, SLA_Select, SLA_Filter, { team_slaBase: SLA_Result[] }>;
  team_socialactivity: WebExpand<Team_Expand, SocialActivity_Select, SocialActivity_Filter, { team_socialactivity: SocialActivity_Result[] }>;
  team_stagesolutionupload: WebExpand<Team_Expand, StageSolutionUpload_Select, StageSolutionUpload_Filter, { team_stagesolutionupload: StageSolutionUpload_Result[] }>;
  team_task: WebExpand<Team_Expand, Task_Select, Task_Filter, { team_task: Task_Result[] }>;
  team_userentityinstancedata: WebExpand<Team_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { team_userentityinstancedata: UserEntityInstanceData_Result[] }>;
  team_userentityuisettings: WebExpand<Team_Expand, UserEntityUISettings_Select, UserEntityUISettings_Filter, { team_userentityuisettings: UserEntityUISettings_Result[] }>;
  team_userform: WebExpand<Team_Expand, UserForm_Select, UserForm_Filter, { team_userform: UserForm_Result[] }>;
  team_userquery: WebExpand<Team_Expand, UserQuery_Select, UserQuery_Filter, { team_userquery: UserQuery_Result[] }>;
  team_userqueryvisualizations: WebExpand<Team_Expand, UserQueryVisualization_Select, UserQueryVisualization_Filter, { team_userqueryvisualizations: UserQueryVisualization_Result[] }>;
  team_workflow: WebExpand<Team_Expand, Workflow_Select, Workflow_Filter, { team_workflow: Workflow_Result[] }>;
  team_workflowbinary: WebExpand<Team_Expand, workflowbinary_Select, workflowbinary_Filter, { team_workflowbinary: workflowbinary_Result[] }>;
  team_workflowlog: WebExpand<Team_Expand, WorkflowLog_Select, WorkflowLog_Filter, { team_workflowlog: WorkflowLog_Result[] }>;
  teammembership_association: WebExpand<Team_Expand, SystemUser_Select, SystemUser_Filter, { teammembership_association: SystemUser_Result[] }>;
  teamprofiles_association: WebExpand<Team_Expand, FieldSecurityProfile_Select, FieldSecurityProfile_Filter, { teamprofiles_association: FieldSecurityProfile_Result[] }>;
  teamroles_association: WebExpand<Team_Expand, Role_Select, Role_Filter, { teamroles_association: Role_Result[] }>;
  teamsyncattributemappingprofiles_association: WebExpand<Team_Expand, SyncAttributeMappingProfile_Select, SyncAttributeMappingProfile_Filter, { teamsyncattributemappingprofiles_association: SyncAttributeMappingProfile_Result[] }>;
  transactioncurrencyid: WebExpand<Team_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid: TransactionCurrency_Result }>;
  userentityinstancedata_team: WebExpand<Team_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_team: UserEntityInstanceData_Result[] }>;
}
interface Team_FormattedResult {
  administratorid_formatted?: string;
  businessunitid_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  membershiptype_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  queueid_formatted?: string;
  regardingobjectid_formatted?: string;
  teamtemplateid_formatted?: string;
  teamtype_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Team_Result extends Team_Base, Team_Relationships {
  "@odata.etag": string;
  administratorid_guid: string | null;
  businessunitid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  queueid_guid: string | null;
  regardingobjectid_guid: string | null;
  teamtemplateid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Team_RelatedOne {
  administratorid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  associatedteamtemplateid: WebMappingRetrieve<TeamTemplate_Select,TeamTemplate_Expand,TeamTemplate_Filter,TeamTemplate_Fixed,TeamTemplate_Result,TeamTemplate_FormattedResult>;
  businessunitid: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid_organization: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  queueid: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  regardingobjectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Team_RelatedMany {
  ImportFile_Team: WebMappingRetrieve<ImportFile_Select,ImportFile_Expand,ImportFile_Filter,ImportFile_Fixed,ImportFile_Result,ImportFile_FormattedResult>;
  OwningTeam_postfollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  Team_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Team_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Team_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Team_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Team_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Team_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  awcnpd_feedback_team_owningteam: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  lead_owning_team: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  team_BulkOperation: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  team_Campaigns: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  team_DuplicateRules: WebMappingRetrieve<DuplicateRule_Select,DuplicateRule_Expand,DuplicateRule_Filter,DuplicateRule_Fixed,DuplicateRule_Result,DuplicateRule_FormattedResult>;
  team_DynamicPropertyInstance: WebMappingRetrieve<DynamicPropertyInstance_Select,DynamicPropertyInstance_Expand,DynamicPropertyInstance_Filter,DynamicPropertyInstance_Fixed,DynamicPropertyInstance_Result,DynamicPropertyInstance_FormattedResult>;
  team_ImportData: WebMappingRetrieve<ImportData_Select,ImportData_Expand,ImportData_Filter,ImportData_Fixed,ImportData_Result,ImportData_FormattedResult>;
  team_ImportFiles: WebMappingRetrieve<ImportFile_Select,ImportFile_Expand,ImportFile_Filter,ImportFile_Fixed,ImportFile_Result,ImportFile_FormattedResult>;
  team_ImportLogs: WebMappingRetrieve<ImportLog_Select,ImportLog_Expand,ImportLog_Filter,ImportLog_Fixed,ImportLog_Result,ImportLog_FormattedResult>;
  team_ImportMaps: WebMappingRetrieve<ImportMap_Select,ImportMap_Expand,ImportMap_Filter,ImportMap_Fixed,ImportMap_Result,ImportMap_FormattedResult>;
  team_Imports: WebMappingRetrieve<Import_Select,Import_Expand,Import_Filter,Import_Fixed,Import_Result,Import_FormattedResult>;
  team_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  team_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  team_SyncError: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  team_accounts: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  team_actioncardusersettings: WebMappingRetrieve<ActionCardUserSettings_Select,ActionCardUserSettings_Expand,ActionCardUserSettings_Filter,ActionCardUserSettings_Fixed,ActionCardUserSettings_Result,ActionCardUserSettings_FormattedResult>;
  team_activity: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  team_activitymonitor: WebMappingRetrieve<activitymonitor_Select,activitymonitor_Expand,activitymonitor_Filter,activitymonitor_Fixed,activitymonitor_Result,activitymonitor_FormattedResult>;
  team_adminsettingsentity: WebMappingRetrieve<adminsettingsentity_Select,adminsettingsentity_Expand,adminsettingsentity_Filter,adminsettingsentity_Fixed,adminsettingsentity_Result,adminsettingsentity_FormattedResult>;
  team_annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  team_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  team_asyncoperation: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  team_awc_customdemoentity: WebMappingRetrieve<awc_customdemoentity_Select,awc_customdemoentity_Expand,awc_customdemoentity_Filter,awc_customdemoentity_Fixed,awc_customdemoentity_Result,awc_customdemoentity_FormattedResult>;
  team_awc_idea: WebMappingRetrieve<awc_idea_Select,awc_idea_Expand,awc_idea_Filter,awc_idea_Fixed,awc_idea_Result,awc_idea_FormattedResult>;
  team_awc_prototype: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  team_awc_venue: WebMappingRetrieve<awc_venue_Select,awc_venue_Expand,awc_venue_Filter,awc_venue_Fixed,awc_venue_Result,awc_venue_FormattedResult>;
  team_awcnpd_idea: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  team_awcnpd_prototype: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  team_bookableresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  team_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  team_bookableresourcebookingexchangesyncidmapping: WebMappingRetrieve<BookableResourceBookingExchangeSyncIdMapping_Select,BookableResourceBookingExchangeSyncIdMapping_Expand,BookableResourceBookingExchangeSyncIdMapping_Filter,BookableResourceBookingExchangeSyncIdMapping_Fixed,BookableResourceBookingExchangeSyncIdMapping_Result,BookableResourceBookingExchangeSyncIdMapping_FormattedResult>;
  team_bookableresourcebookingheader: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  team_bookableresourcecategory: WebMappingRetrieve<BookableResourceCategory_Select,BookableResourceCategory_Expand,BookableResourceCategory_Filter,BookableResourceCategory_Fixed,BookableResourceCategory_Result,BookableResourceCategory_FormattedResult>;
  team_bookableresourcecategoryassn: WebMappingRetrieve<BookableResourceCategoryAssn_Select,BookableResourceCategoryAssn_Expand,BookableResourceCategoryAssn_Filter,BookableResourceCategoryAssn_Fixed,BookableResourceCategoryAssn_Result,BookableResourceCategoryAssn_FormattedResult>;
  team_bookableresourcecharacteristic: WebMappingRetrieve<BookableResourceCharacteristic_Select,BookableResourceCharacteristic_Expand,BookableResourceCharacteristic_Filter,BookableResourceCharacteristic_Fixed,BookableResourceCharacteristic_Result,BookableResourceCharacteristic_FormattedResult>;
  team_bookableresourcegroup: WebMappingRetrieve<BookableResourceGroup_Select,BookableResourceGroup_Expand,BookableResourceGroup_Filter,BookableResourceGroup_Fixed,BookableResourceGroup_Result,BookableResourceGroup_FormattedResult>;
  team_bookingstatus: WebMappingRetrieve<BookingStatus_Select,BookingStatus_Expand,BookingStatus_Filter,BookingStatus_Fixed,BookingStatus_Result,BookingStatus_FormattedResult>;
  team_bot: WebMappingRetrieve<bot_Select,bot_Expand,bot_Filter,bot_Fixed,bot_Result,bot_FormattedResult>;
  team_botcomponent: WebMappingRetrieve<botcomponent_Select,botcomponent_Expand,botcomponent_Filter,botcomponent_Fixed,botcomponent_Result,botcomponent_FormattedResult>;
  team_bulkoperationlog: WebMappingRetrieve<BulkOperationLog_Select,BulkOperationLog_Expand,BulkOperationLog_Filter,BulkOperationLog_Fixed,BulkOperationLog_Result,BulkOperationLog_FormattedResult>;
  team_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  team_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  team_canvasappextendedmetadata: WebMappingRetrieve<CanvasAppExtendedMetadata_Select,CanvasAppExtendedMetadata_Expand,CanvasAppExtendedMetadata_Filter,CanvasAppExtendedMetadata_Fixed,CanvasAppExtendedMetadata_Result,CanvasAppExtendedMetadata_FormattedResult>;
  team_channelaccessprofile: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  team_characteristic: WebMappingRetrieve<Characteristic_Select,Characteristic_Expand,Characteristic_Filter,Characteristic_Fixed,Characteristic_Result,Characteristic_FormattedResult>;
  team_connectionreference: WebMappingRetrieve<connectionreference_Select,connectionreference_Expand,connectionreference_Filter,connectionreference_Fixed,connectionreference_Result,connectionreference_FormattedResult>;
  team_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  team_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  team_connector: WebMappingRetrieve<connector_Select,connector_Expand,connector_Filter,connector_Fixed,connector_Result,connector_FormattedResult>;
  team_contacts: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  team_contractdetail: WebMappingRetrieve<ContractDetail_Select,ContractDetail_Expand,ContractDetail_Filter,ContractDetail_Fixed,ContractDetail_Result,ContractDetail_FormattedResult>;
  team_conversationtranscript: WebMappingRetrieve<conversationtranscript_Select,conversationtranscript_Expand,conversationtranscript_Filter,conversationtranscript_Fixed,conversationtranscript_Result,conversationtranscript_FormattedResult>;
  team_convertrule: WebMappingRetrieve<ConvertRule_Select,ConvertRule_Expand,ConvertRule_Filter,ConvertRule_Fixed,ConvertRule_Result,ConvertRule_FormattedResult>;
  team_customapi: WebMappingRetrieve<CustomAPI_Select,CustomAPI_Expand,CustomAPI_Filter,CustomAPI_Fixed,CustomAPI_Result,CustomAPI_FormattedResult>;
  team_customapirequestparameter: WebMappingRetrieve<CustomAPIRequestParameter_Select,CustomAPIRequestParameter_Expand,CustomAPIRequestParameter_Filter,CustomAPIRequestParameter_Fixed,CustomAPIRequestParameter_Result,CustomAPIRequestParameter_FormattedResult>;
  team_customapiresponseproperty: WebMappingRetrieve<CustomAPIResponseProperty_Select,CustomAPIResponseProperty_Expand,CustomAPIResponseProperty_Filter,CustomAPIResponseProperty_Fixed,CustomAPIResponseProperty_Result,CustomAPIResponseProperty_FormattedResult>;
  team_customer_opportunity_roles: WebMappingRetrieve<CustomerOpportunityRole_Select,CustomerOpportunityRole_Expand,CustomerOpportunityRole_Filter,CustomerOpportunityRole_Fixed,CustomerOpportunityRole_Result,CustomerOpportunityRole_FormattedResult>;
  team_customer_relationship: WebMappingRetrieve<CustomerRelationship_Select,CustomerRelationship_Expand,CustomerRelationship_Filter,CustomerRelationship_Fixed,CustomerRelationship_Result,CustomerRelationship_FormattedResult>;
  team_datalakefolder: WebMappingRetrieve<datalakefolder_Select,datalakefolder_Expand,datalakefolder_Filter,datalakefolder_Fixed,datalakefolder_Result,datalakefolder_FormattedResult>;
  team_datalakefolderpermission: WebMappingRetrieve<datalakefolderpermission_Select,datalakefolderpermission_Expand,datalakefolderpermission_Filter,datalakefolderpermission_Fixed,datalakefolderpermission_Result,datalakefolderpermission_FormattedResult>;
  team_elca_project: WebMappingRetrieve<elca_Project_Select,elca_Project_Expand,elca_Project_Filter,elca_Project_Fixed,elca_Project_Result,elca_Project_FormattedResult>;
  team_elca_projectgroup: WebMappingRetrieve<elca_ProjectGroup_Select,elca_ProjectGroup_Expand,elca_ProjectGroup_Filter,elca_ProjectGroup_Fixed,elca_ProjectGroup_Result,elca_ProjectGroup_FormattedResult>;
  team_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  team_email_templates: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  team_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  team_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  team_entitlementchannel: WebMappingRetrieve<EntitlementChannel_Select,EntitlementChannel_Expand,EntitlementChannel_Filter,EntitlementChannel_Fixed,EntitlementChannel_Result,EntitlementChannel_FormattedResult>;
  team_entitlemententityallocationtypemapping: WebMappingRetrieve<EntitlementEntityAllocationTypeMapping_Select,EntitlementEntityAllocationTypeMapping_Expand,EntitlementEntityAllocationTypeMapping_Filter,EntitlementEntityAllocationTypeMapping_Fixed,EntitlementEntityAllocationTypeMapping_Result,EntitlementEntityAllocationTypeMapping_FormattedResult>;
  team_environmentvariabledefinition: WebMappingRetrieve<EnvironmentVariableDefinition_Select,EnvironmentVariableDefinition_Expand,EnvironmentVariableDefinition_Filter,EnvironmentVariableDefinition_Fixed,EnvironmentVariableDefinition_Result,EnvironmentVariableDefinition_FormattedResult>;
  team_environmentvariablevalue: WebMappingRetrieve<EnvironmentVariableValue_Select,EnvironmentVariableValue_Expand,EnvironmentVariableValue_Filter,EnvironmentVariableValue_Fixed,EnvironmentVariableValue_Result,EnvironmentVariableValue_FormattedResult>;
  team_exchangesyncidmapping: WebMappingRetrieve<ExchangeSyncIdMapping_Select,ExchangeSyncIdMapping_Expand,ExchangeSyncIdMapping_Filter,ExchangeSyncIdMapping_Fixed,ExchangeSyncIdMapping_Result,ExchangeSyncIdMapping_FormattedResult>;
  team_exportsolutionupload: WebMappingRetrieve<ExportSolutionUpload_Select,ExportSolutionUpload_Expand,ExportSolutionUpload_Filter,ExportSolutionUpload_Fixed,ExportSolutionUpload_Result,ExportSolutionUpload_FormattedResult>;
  team_externalparty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  team_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  team_flowsession: WebMappingRetrieve<flowsession_Select,flowsession_Expand,flowsession_Filter,flowsession_Fixed,flowsession_Result,flowsession_FormattedResult>;
  team_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  team_goal_goalowner: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  team_goalrollupquery: WebMappingRetrieve<GoalRollupQuery_Select,GoalRollupQuery_Expand,GoalRollupQuery_Filter,GoalRollupQuery_Fixed,GoalRollupQuery_Result,GoalRollupQuery_FormattedResult>;
  team_incidentresolution: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  team_incidents: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  team_invoicedetail: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  team_invoices: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  team_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  team_knowledgearticleincident: WebMappingRetrieve<KnowledgeArticleIncident_Select,KnowledgeArticleIncident_Expand,KnowledgeArticleIncident_Filter,KnowledgeArticleIncident_Fixed,KnowledgeArticleIncident_Result,KnowledgeArticleIncident_FormattedResult>;
  team_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  team_list: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  team_listoperation: WebMappingRetrieve<listoperation_Select,listoperation_Expand,listoperation_Filter,listoperation_Fixed,listoperation_Result,listoperation_FormattedResult>;
  team_mailbox: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  team_mailboxtrackingcategory: WebMappingRetrieve<MailboxTrackingCategory_Select,MailboxTrackingCategory_Expand,MailboxTrackingCategory_Filter,MailboxTrackingCategory_Fixed,MailboxTrackingCategory_Result,MailboxTrackingCategory_FormattedResult>;
  team_mailboxtrackingfolder: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  team_msdyn_actioncardregarding: WebMappingRetrieve<msdyn_actioncardregarding_Select,msdyn_actioncardregarding_Expand,msdyn_actioncardregarding_Filter,msdyn_actioncardregarding_Fixed,msdyn_actioncardregarding_Result,msdyn_actioncardregarding_FormattedResult>;
  team_msdyn_actioncardrolesetting: WebMappingRetrieve<msdyn_actioncardrolesetting_Select,msdyn_actioncardrolesetting_Expand,msdyn_actioncardrolesetting_Filter,msdyn_actioncardrolesetting_Fixed,msdyn_actioncardrolesetting_Result,msdyn_actioncardrolesetting_FormattedResult>;
  team_msdyn_aibdataset: WebMappingRetrieve<msdyn_AIBDataset_Select,msdyn_AIBDataset_Expand,msdyn_AIBDataset_Filter,msdyn_AIBDataset_Fixed,msdyn_AIBDataset_Result,msdyn_AIBDataset_FormattedResult>;
  team_msdyn_aibdatasetfile: WebMappingRetrieve<msdyn_AIBDatasetFile_Select,msdyn_AIBDatasetFile_Expand,msdyn_AIBDatasetFile_Filter,msdyn_AIBDatasetFile_Fixed,msdyn_AIBDatasetFile_Result,msdyn_AIBDatasetFile_FormattedResult>;
  team_msdyn_aibdatasetrecord: WebMappingRetrieve<msdyn_AIBDatasetRecord_Select,msdyn_AIBDatasetRecord_Expand,msdyn_AIBDatasetRecord_Filter,msdyn_AIBDatasetRecord_Fixed,msdyn_AIBDatasetRecord_Result,msdyn_AIBDatasetRecord_FormattedResult>;
  team_msdyn_aibdatasetscontainer: WebMappingRetrieve<msdyn_AIBDatasetsContainer_Select,msdyn_AIBDatasetsContainer_Expand,msdyn_AIBDatasetsContainer_Filter,msdyn_AIBDatasetsContainer_Fixed,msdyn_AIBDatasetsContainer_Result,msdyn_AIBDatasetsContainer_FormattedResult>;
  team_msdyn_aibfile: WebMappingRetrieve<msdyn_AIBFile_Select,msdyn_AIBFile_Expand,msdyn_AIBFile_Filter,msdyn_AIBFile_Fixed,msdyn_AIBFile_Result,msdyn_AIBFile_FormattedResult>;
  team_msdyn_aibfileattacheddata: WebMappingRetrieve<msdyn_AIBFileAttachedData_Select,msdyn_AIBFileAttachedData_Expand,msdyn_AIBFileAttachedData_Filter,msdyn_AIBFileAttachedData_Fixed,msdyn_AIBFileAttachedData_Result,msdyn_AIBFileAttachedData_FormattedResult>;
  team_msdyn_aiconfiguration: WebMappingRetrieve<msdyn_AIConfiguration_Select,msdyn_AIConfiguration_Expand,msdyn_AIConfiguration_Filter,msdyn_AIConfiguration_Fixed,msdyn_AIConfiguration_Result,msdyn_AIConfiguration_FormattedResult>;
  team_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  team_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  team_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  team_msdyn_aiodlabel: WebMappingRetrieve<msdyn_AIOdLabel_Select,msdyn_AIOdLabel_Expand,msdyn_AIOdLabel_Filter,msdyn_AIOdLabel_Fixed,msdyn_AIOdLabel_Result,msdyn_AIOdLabel_FormattedResult>;
  team_msdyn_aiodtrainingboundingbox: WebMappingRetrieve<msdyn_AIOdTrainingBoundingBox_Select,msdyn_AIOdTrainingBoundingBox_Expand,msdyn_AIOdTrainingBoundingBox_Filter,msdyn_AIOdTrainingBoundingBox_Fixed,msdyn_AIOdTrainingBoundingBox_Result,msdyn_AIOdTrainingBoundingBox_FormattedResult>;
  team_msdyn_aiodtrainingimage: WebMappingRetrieve<msdyn_AIOdTrainingImage_Select,msdyn_AIOdTrainingImage_Expand,msdyn_AIOdTrainingImage_Filter,msdyn_AIOdTrainingImage_Fixed,msdyn_AIOdTrainingImage_Result,msdyn_AIOdTrainingImage_FormattedResult>;
  team_msdyn_aitemplate: WebMappingRetrieve<msdyn_AITemplate_Select,msdyn_AITemplate_Expand,msdyn_AITemplate_Filter,msdyn_AITemplate_Fixed,msdyn_AITemplate_Result,msdyn_AITemplate_FormattedResult>;
  team_msdyn_autocapturerule: WebMappingRetrieve<msdyn_autocapturerule_Select,msdyn_autocapturerule_Expand,msdyn_autocapturerule_Filter,msdyn_autocapturerule_Fixed,msdyn_autocapturerule_Result,msdyn_autocapturerule_FormattedResult>;
  team_msdyn_autocapturesettings: WebMappingRetrieve<msdyn_autocapturesettings_Select,msdyn_autocapturesettings_Expand,msdyn_autocapturesettings_Filter,msdyn_autocapturesettings_Fixed,msdyn_autocapturesettings_Result,msdyn_autocapturesettings_FormattedResult>;
  team_msdyn_callablecontext: WebMappingRetrieve<msdyn_callablecontext_Select,msdyn_callablecontext_Expand,msdyn_callablecontext_Filter,msdyn_callablecontext_Fixed,msdyn_callablecontext_Result,msdyn_callablecontext_FormattedResult>;
  team_msdyn_entityrankingrule: WebMappingRetrieve<msdyn_entityrankingrule_Select,msdyn_entityrankingrule_Expand,msdyn_entityrankingrule_Filter,msdyn_entityrankingrule_Fixed,msdyn_entityrankingrule_Result,msdyn_entityrankingrule_FormattedResult>;
  team_msdyn_federatedarticle: WebMappingRetrieve<msdyn_federatedarticle_Select,msdyn_federatedarticle_Expand,msdyn_federatedarticle_Filter,msdyn_federatedarticle_Fixed,msdyn_federatedarticle_Result,msdyn_federatedarticle_FormattedResult>;
  team_msdyn_flowcardtype: WebMappingRetrieve<msdyn_flowcardtype_Select,msdyn_flowcardtype_Expand,msdyn_flowcardtype_Filter,msdyn_flowcardtype_Fixed,msdyn_flowcardtype_Result,msdyn_flowcardtype_FormattedResult>;
  team_msdyn_icebreakersconfig: WebMappingRetrieve<msdyn_icebreakersconfig_Select,msdyn_icebreakersconfig_Expand,msdyn_icebreakersconfig_Filter,msdyn_icebreakersconfig_Fixed,msdyn_icebreakersconfig_Result,msdyn_icebreakersconfig_FormattedResult>;
  team_msdyn_kmfederatedsearchconfig: WebMappingRetrieve<msdyn_kmfederatedsearchconfig_Select,msdyn_kmfederatedsearchconfig_Expand,msdyn_kmfederatedsearchconfig_Filter,msdyn_kmfederatedsearchconfig_Fixed,msdyn_kmfederatedsearchconfig_Result,msdyn_kmfederatedsearchconfig_FormattedResult>;
  team_msdyn_knowledgearticleimage: WebMappingRetrieve<msdyn_knowledgearticleimage_Select,msdyn_knowledgearticleimage_Expand,msdyn_knowledgearticleimage_Filter,msdyn_knowledgearticleimage_Fixed,msdyn_knowledgearticleimage_Result,msdyn_knowledgearticleimage_FormattedResult>;
  team_msdyn_knowledgearticletemplate: WebMappingRetrieve<msdyn_knowledgearticletemplate_Select,msdyn_knowledgearticletemplate_Expand,msdyn_knowledgearticletemplate_Filter,msdyn_knowledgearticletemplate_Fixed,msdyn_knowledgearticletemplate_Result,msdyn_knowledgearticletemplate_FormattedResult>;
  team_msdyn_knowledgeinteractioninsight: WebMappingRetrieve<msdyn_knowledgeinteractioninsight_Select,msdyn_knowledgeinteractioninsight_Expand,msdyn_knowledgeinteractioninsight_Filter,msdyn_knowledgeinteractioninsight_Fixed,msdyn_knowledgeinteractioninsight_Result,msdyn_knowledgeinteractioninsight_FormattedResult>;
  team_msdyn_knowledgesearchinsight: WebMappingRetrieve<msdyn_knowledgesearchinsight_Select,msdyn_knowledgesearchinsight_Expand,msdyn_knowledgesearchinsight_Filter,msdyn_knowledgesearchinsight_Fixed,msdyn_knowledgesearchinsight_Result,msdyn_knowledgesearchinsight_FormattedResult>;
  team_msdyn_msteamssetting: WebMappingRetrieve<msdyn_msteamssetting_Select,msdyn_msteamssetting_Expand,msdyn_msteamssetting_Filter,msdyn_msteamssetting_Fixed,msdyn_msteamssetting_Result,msdyn_msteamssetting_FormattedResult>;
  team_msdyn_notesanalysisconfig: WebMappingRetrieve<msdyn_notesanalysisconfig_Select,msdyn_notesanalysisconfig_Expand,msdyn_notesanalysisconfig_Filter,msdyn_notesanalysisconfig_Fixed,msdyn_notesanalysisconfig_Result,msdyn_notesanalysisconfig_FormattedResult>;
  team_msdyn_playbookactivity: WebMappingRetrieve<msdyn_playbookactivity_Select,msdyn_playbookactivity_Expand,msdyn_playbookactivity_Filter,msdyn_playbookactivity_Fixed,msdyn_playbookactivity_Result,msdyn_playbookactivity_FormattedResult>;
  team_msdyn_playbookactivityattribute: WebMappingRetrieve<msdyn_playbookactivityattribute_Select,msdyn_playbookactivityattribute_Expand,msdyn_playbookactivityattribute_Filter,msdyn_playbookactivityattribute_Fixed,msdyn_playbookactivityattribute_Result,msdyn_playbookactivityattribute_FormattedResult>;
  team_msdyn_playbookcategory: WebMappingRetrieve<msdyn_playbookcategory_Select,msdyn_playbookcategory_Expand,msdyn_playbookcategory_Filter,msdyn_playbookcategory_Fixed,msdyn_playbookcategory_Result,msdyn_playbookcategory_FormattedResult>;
  team_msdyn_playbookinstance: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  team_msdyn_playbooktemplate: WebMappingRetrieve<msdyn_playbooktemplate_Select,msdyn_playbooktemplate_Expand,msdyn_playbooktemplate_Filter,msdyn_playbooktemplate_Fixed,msdyn_playbooktemplate_Result,msdyn_playbooktemplate_FormattedResult>;
  team_msdyn_postalbum: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  team_msdyn_relationshipinsightsunifiedconfig: WebMappingRetrieve<msdyn_relationshipinsightsunifiedconfig_Select,msdyn_relationshipinsightsunifiedconfig_Expand,msdyn_relationshipinsightsunifiedconfig_Filter,msdyn_relationshipinsightsunifiedconfig_Fixed,msdyn_relationshipinsightsunifiedconfig_Result,msdyn_relationshipinsightsunifiedconfig_FormattedResult>;
  team_msdyn_richtextfile: WebMappingRetrieve<msdyn_richtextfile_Select,msdyn_richtextfile_Expand,msdyn_richtextfile_Filter,msdyn_richtextfile_Fixed,msdyn_richtextfile_Result,msdyn_richtextfile_FormattedResult>;
  team_msdyn_salesinsightssettings: WebMappingRetrieve<msdyn_salesinsightssettings_Select,msdyn_salesinsightssettings_Expand,msdyn_salesinsightssettings_Filter,msdyn_salesinsightssettings_Fixed,msdyn_salesinsightssettings_Result,msdyn_salesinsightssettings_FormattedResult>;
  team_msdyn_siconfig: WebMappingRetrieve<msdyn_siconfig_Select,msdyn_siconfig_Expand,msdyn_siconfig_Filter,msdyn_siconfig_Fixed,msdyn_siconfig_Result,msdyn_siconfig_FormattedResult>;
  team_msdyn_untrackedappointment: WebMappingRetrieve<msdyn_untrackedappointment_Select,msdyn_untrackedappointment_Expand,msdyn_untrackedappointment_Filter,msdyn_untrackedappointment_Fixed,msdyn_untrackedappointment_Result,msdyn_untrackedappointment_FormattedResult>;
  team_msdyn_wallsavedqueryusersettings: WebMappingRetrieve<msdyn_wallsavedqueryusersettings_Select,msdyn_wallsavedqueryusersettings_Expand,msdyn_wallsavedqueryusersettings_Filter,msdyn_wallsavedqueryusersettings_Fixed,msdyn_wallsavedqueryusersettings_Result,msdyn_wallsavedqueryusersettings_FormattedResult>;
  team_msdynce_botcontent: WebMappingRetrieve<msdynce_botcontent_Select,msdynce_botcontent_Expand,msdynce_botcontent_Filter,msdynce_botcontent_Fixed,msdynce_botcontent_Result,msdynce_botcontent_FormattedResult>;
  team_new_interactionforemail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  team_opportunities: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  team_opportunityclose: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  team_opportunityproduct: WebMappingRetrieve<OpportunityProduct_Select,OpportunityProduct_Expand,OpportunityProduct_Filter,OpportunityProduct_Fixed,OpportunityProduct_Result,OpportunityProduct_FormattedResult>;
  team_orderclose: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  team_orders: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  team_pdfsetting: WebMappingRetrieve<PDFSetting_Select,PDFSetting_Expand,PDFSetting_Filter,PDFSetting_Fixed,PDFSetting_Result,PDFSetting_FormattedResult>;
  team_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  team_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  team_principalobjectattributeaccess_principalid: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  team_processsession: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  team_processstageparameter: WebMappingRetrieve<processstageparameter_Select,processstageparameter_Expand,processstageparameter_Filter,processstageparameter_Fixed,processstageparameter_Result,processstageparameter_FormattedResult>;
  team_profilerule: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  team_queueitembase_workerid: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  team_quoteclose: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  team_quotedetail: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  team_quotes: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  team_ratingmodel: WebMappingRetrieve<RatingModel_Select,RatingModel_Expand,RatingModel_Filter,RatingModel_Fixed,RatingModel_Result,RatingModel_FormattedResult>;
  team_ratingvalue: WebMappingRetrieve<RatingValue_Select,RatingValue_Expand,RatingValue_Filter,RatingValue_Fixed,RatingValue_Result,RatingValue_FormattedResult>;
  team_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  team_resource_groups: WebMappingRetrieve<ResourceGroup_Select,ResourceGroup_Expand,ResourceGroup_Filter,ResourceGroup_Fixed,ResourceGroup_Result,ResourceGroup_FormattedResult>;
  team_resource_specs: WebMappingRetrieve<ResourceSpec_Select,ResourceSpec_Expand,ResourceSpec_Filter,ResourceSpec_Fixed,ResourceSpec_Result,ResourceSpec_FormattedResult>;
  team_routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  team_routingruleitem: WebMappingRetrieve<RoutingRuleItem_Select,RoutingRuleItem_Expand,RoutingRuleItem_Filter,RoutingRuleItem_Fixed,RoutingRuleItem_Result,RoutingRuleItem_FormattedResult>;
  team_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  team_service_appointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  team_service_contracts: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  team_sharepointdocumentlocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  team_sharepointsite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  team_slaBase: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  team_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  team_stagesolutionupload: WebMappingRetrieve<StageSolutionUpload_Select,StageSolutionUpload_Expand,StageSolutionUpload_Filter,StageSolutionUpload_Fixed,StageSolutionUpload_Result,StageSolutionUpload_FormattedResult>;
  team_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  team_userentityinstancedata: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
  team_userentityuisettings: WebMappingRetrieve<UserEntityUISettings_Select,UserEntityUISettings_Expand,UserEntityUISettings_Filter,UserEntityUISettings_Fixed,UserEntityUISettings_Result,UserEntityUISettings_FormattedResult>;
  team_userform: WebMappingRetrieve<UserForm_Select,UserForm_Expand,UserForm_Filter,UserForm_Fixed,UserForm_Result,UserForm_FormattedResult>;
  team_userquery: WebMappingRetrieve<UserQuery_Select,UserQuery_Expand,UserQuery_Filter,UserQuery_Fixed,UserQuery_Result,UserQuery_FormattedResult>;
  team_userqueryvisualizations: WebMappingRetrieve<UserQueryVisualization_Select,UserQueryVisualization_Expand,UserQueryVisualization_Filter,UserQueryVisualization_Fixed,UserQueryVisualization_Result,UserQueryVisualization_FormattedResult>;
  team_workflow: WebMappingRetrieve<Workflow_Select,Workflow_Expand,Workflow_Filter,Workflow_Fixed,Workflow_Result,Workflow_FormattedResult>;
  team_workflowbinary: WebMappingRetrieve<workflowbinary_Select,workflowbinary_Expand,workflowbinary_Filter,workflowbinary_Fixed,workflowbinary_Result,workflowbinary_FormattedResult>;
  team_workflowlog: WebMappingRetrieve<WorkflowLog_Select,WorkflowLog_Expand,WorkflowLog_Filter,WorkflowLog_Fixed,WorkflowLog_Result,WorkflowLog_FormattedResult>;
  teammembership_association: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  teamprofiles_association: WebMappingRetrieve<FieldSecurityProfile_Select,FieldSecurityProfile_Expand,FieldSecurityProfile_Filter,FieldSecurityProfile_Fixed,FieldSecurityProfile_Result,FieldSecurityProfile_FormattedResult>;
  teamroles_association: WebMappingRetrieve<Role_Select,Role_Expand,Role_Filter,Role_Fixed,Role_Result,Role_FormattedResult>;
  teamsyncattributemappingprofiles_association: WebMappingRetrieve<SyncAttributeMappingProfile_Select,SyncAttributeMappingProfile_Expand,SyncAttributeMappingProfile_Filter,SyncAttributeMappingProfile_Fixed,SyncAttributeMappingProfile_Result,SyncAttributeMappingProfile_FormattedResult>;
  userentityinstancedata_team: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  teams: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
}
interface WebEntitiesRelated {
  teams: WebMappingRelated<Team_RelatedOne,Team_RelatedMany>;
}
interface WebEntitiesCUDA {
  teams: WebMappingCUDA<Team_Create,Team_Update,Team_Select>;
}
