interface TransactionCurrency_Base extends WebEntity {
  createdon?: Date | null;
  currencyname?: string | null;
  currencyprecision?: number | null;
  currencysymbol?: string | null;
  entityimageid?: string | null;
  exchangerate?: number | null;
  importsequencenumber?: number | null;
  isocurrencycode?: string | null;
  modifiedon?: Date | null;
  overriddencreatedon?: Date | null;
  statecode?: transactioncurrency_statecode | null;
  statuscode?: transactioncurrency_statuscode | null;
  transactioncurrencyid?: string | null;
  uniquedscid?: string | null;
  versionnumber?: number | null;
}
interface TransactionCurrency_Relationships {
  DynamicPropertyAssociation_TransactionCurrency?: DynamicPropertyAssociation_Result[] | null;
  DynamicPropertyOptionSetItem_TransactionCurrency?: DynamicPropertyOptionSetItem_Result[] | null;
  TransactionCurrency_ActionCardUserState?: ActionCardUserState_Result[] | null;
  TransactionCurrency_ActivityPointer?: ActivityPointer_Result[] | null;
  TransactionCurrency_Appointment?: Appointment_Result[] | null;
  TransactionCurrency_AsyncOperations?: AsyncOperation_Result[] | null;
  TransactionCurrency_BusinessUnit?: BusinessUnit_Result[] | null;
  TransactionCurrency_CampaignResponse?: CampaignResponse_Result[] | null;
  TransactionCurrency_Connection?: Connection_Result[] | null;
  TransactionCurrency_ConvertRule?: ConvertRule_Result[] | null;
  TransactionCurrency_CustomerAddress?: CustomerAddress_Result[] | null;
  TransactionCurrency_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  TransactionCurrency_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  TransactionCurrency_Dynamicpropertyinsatance?: DynamicPropertyInstance_Result[] | null;
  TransactionCurrency_Email?: Email_Result[] | null;
  TransactionCurrency_Entitlement?: Entitlement_Result[] | null;
  TransactionCurrency_Equipment?: Equipment_Result[] | null;
  TransactionCurrency_Fax?: Fax_Result[] | null;
  TransactionCurrency_Goal?: Goal_Result[] | null;
  TransactionCurrency_Incident?: Incident_Result[] | null;
  TransactionCurrency_InteractionForEmail?: InteractionForEmail_Result[] | null;
  TransactionCurrency_KbArticle?: KbArticle_Result[] | null;
  TransactionCurrency_KnowledgeBaseRecord?: KnowledgeBaseRecord_Result[] | null;
  TransactionCurrency_LeadAddress?: LeadAddress_Result[] | null;
  TransactionCurrency_Letter?: Letter_Result[] | null;
  TransactionCurrency_MailMergeTemplate?: MailMergeTemplate_Result[] | null;
  TransactionCurrency_PhoneCall?: PhoneCall_Result[] | null;
  TransactionCurrency_ProcessSessions?: ProcessSession_Result[] | null;
  TransactionCurrency_Queue?: Queue_Result[] | null;
  TransactionCurrency_QueueItem?: QueueItem_Result[] | null;
  TransactionCurrency_RecurringAppointmentMaster?: RecurringAppointmentMaster_Result[] | null;
  TransactionCurrency_ReportCategory?: ReportCategory_Result[] | null;
  TransactionCurrency_Routingrule?: RoutingRule_Result[] | null;
  TransactionCurrency_SLA?: SLA_Result[] | null;
  TransactionCurrency_SLAItem?: SLAItem_Result[] | null;
  TransactionCurrency_SalesLiterature?: SalesLiterature_Result[] | null;
  TransactionCurrency_ServiceAppointment?: ServiceAppointment_Result[] | null;
  TransactionCurrency_SharePointDocument?: SharePointDocument_Result[] | null;
  TransactionCurrency_SharePointDocumentLocation?: SharePointDocumentLocation_Result[] | null;
  TransactionCurrency_SharePointSite?: SharePointSite_Result[] | null;
  TransactionCurrency_SimilarityRule?: SimilarityRule_Result[] | null;
  TransactionCurrency_SyncErrors?: SyncError_Result[] | null;
  TransactionCurrency_SystemUser?: SystemUser_Result[] | null;
  TransactionCurrency_Task?: Task_Result[] | null;
  TransactionCurrency_Team?: Team_Result[] | null;
  TransactionCurrency_Territory?: Territory_Result[] | null;
  TransactionCurrency_Theme?: Theme_Result[] | null;
  TransactionCurrency_UntrackedEmail?: UntrackedEmail_Result[] | null;
  TransactionCurrency_UserMapping?: UserMapping_Result[] | null;
  TransactionCurrency_bookableresource?: BookableResource_Result[] | null;
  TransactionCurrency_bookableresourcebooking?: BookableResourceBooking_Result[] | null;
  TransactionCurrency_bookableresourcebookingheader?: BookableResourceBookingHeader_Result[] | null;
  TransactionCurrency_bookableresourcecategory?: BookableResourceCategory_Result[] | null;
  TransactionCurrency_bookableresourcecategoryassn?: BookableResourceCategoryAssn_Result[] | null;
  TransactionCurrency_bookableresourcecharacteristic?: BookableResourceCharacteristic_Result[] | null;
  TransactionCurrency_bookableresourcegroup?: BookableResourceGroup_Result[] | null;
  TransactionCurrency_bookingstatus?: BookingStatus_Result[] | null;
  TransactionCurrency_characteristic?: Characteristic_Result[] | null;
  TransactionCurrency_delveactionhub?: DelveActionHub_Result[] | null;
  TransactionCurrency_entitlementchannel?: EntitlementChannel_Result[] | null;
  TransactionCurrency_entitlementtemplate?: EntitlementTemplate_Result[] | null;
  TransactionCurrency_entitlementtemplatechannel?: EntitlementTemplateChannel_Result[] | null;
  TransactionCurrency_externalpartyitem?: ExternalPartyItem_Result[] | null;
  TransactionCurrency_officegraphdocument?: OfficeGraphDocument_Result[] | null;
  TransactionCurrency_profilerule?: ChannelAccessProfileRule_Result[] | null;
  TransactionCurrency_profileruleitem?: ChannelAccessProfileRuleItem_Result[] | null;
  TransactionCurrency_ratingmodel?: RatingModel_Result[] | null;
  TransactionCurrency_ratingvalue?: RatingValue_Result[] | null;
  TransactionCurrency_recommendeddocument?: RecommendedDocument_Result[] | null;
  TransactionCurrency_routingruleitem?: RoutingRuleItem_Result[] | null;
  TransactionCurrency_slakpiinstance?: SLAKPIInstance_Result[] | null;
  awcnpd_feedback_transactioncurrency_transactioncurrencyid?: awcnpd_feedback_Result[] | null;
  basecurrency_organization?: Organization_Result[] | null;
  bulkoperation_transactioncurrency_transactioncurrencyid?: BulkOperation_Result[] | null;
  entityimageid_imagedescriptor?: ImageDescriptor_Result | null;
  incidentresolution_transactioncurrency_transactioncurrencyid?: IncidentResolution_Result[] | null;
  orderclose_transactioncurrency_transactioncurrencyid?: OrderClose_Result[] | null;
  quoteclose_transactioncurrency_transactioncurrencyid?: QuoteClose_Result[] | null;
  transactioncurrency_ProductAssociation?: ProductAssociation_Result[] | null;
  transactioncurrency_ProductSubstitute?: ProductSubstitute_Result[] | null;
  transactioncurrency_SocialProfile?: SocialProfile_Result[] | null;
  transactioncurrency_account?: Account_Result[] | null;
  transactioncurrency_actioncard?: ActionCard_Result[] | null;
  transactioncurrency_annualfiscalcalendar?: AnnualFiscalCalendar_Result[] | null;
  transactioncurrency_campaign?: Campaign_Result[] | null;
  transactioncurrency_campaignactivity?: CampaignActivity_Result[] | null;
  transactioncurrency_cardtype?: CardType_Result[] | null;
  transactioncurrency_category?: Category_Result[] | null;
  transactioncurrency_channelaccessprofile?: ChannelAccessProfile_Result[] | null;
  transactioncurrency_competitor?: Competitor_Result[] | null;
  transactioncurrency_contact?: Contact_Result[] | null;
  transactioncurrency_contract?: Contract_Result[] | null;
  transactioncurrency_contractdetail?: ContractDetail_Result[] | null;
  transactioncurrency_convertruleitem?: ConvertRuleItem_Result[] | null;
  transactioncurrency_discount?: Discount_Result[] | null;
  transactioncurrency_discounttype?: DiscountType_Result[] | null;
  transactioncurrency_expiredprocess?: ExpiredProcess_Result[] | null;
  transactioncurrency_externalparty?: ExternalParty_Result[] | null;
  transactioncurrency_feedback?: Feedback_Result[] | null;
  transactioncurrency_fixedmonthlyfiscalcalendar?: FixedMonthlyFiscalCalendar_Result[] | null;
  transactioncurrency_invoice?: Invoice_Result[] | null;
  transactioncurrency_invoicedetail?: InvoiceDetail_Result[] | null;
  transactioncurrency_knowledgearticle?: KnowledgeArticle_Result[] | null;
  transactioncurrency_knowledgearticleincident?: KnowledgeArticleIncident_Result[] | null;
  transactioncurrency_knowledgearticleviews?: KnowledgeArticleViews_Result[] | null;
  transactioncurrency_lead?: Lead_Result[] | null;
  transactioncurrency_leadtoopportunitysalesprocess?: LeadToOpportunitySalesProcess_Result[] | null;
  transactioncurrency_list?: List_Result[] | null;
  transactioncurrency_monthlyfiscalcalendar?: MonthlyFiscalCalendar_Result[] | null;
  transactioncurrency_newprocess?: NewProcess_Result[] | null;
  transactioncurrency_opportunity?: Opportunity_Result[] | null;
  transactioncurrency_opportunityclose?: OpportunityClose_Result[] | null;
  transactioncurrency_opportunityproduct?: OpportunityProduct_Result[] | null;
  transactioncurrency_opportunitysalesprocess?: OpportunitySalesProcess_Result[] | null;
  transactioncurrency_phonetocaseprocess?: PhoneToCaseProcess_Result[] | null;
  transactioncurrency_position?: Position_Result[] | null;
  transactioncurrency_pricelevel?: PriceLevel_Result[] | null;
  transactioncurrency_product?: Product_Result[] | null;
  transactioncurrency_productpricelevel?: ProductPriceLevel_Result[] | null;
  transactioncurrency_quarterlyfiscalcalendar?: QuarterlyFiscalCalendar_Result[] | null;
  transactioncurrency_quote?: Quote_Result[] | null;
  transactioncurrency_quotedetail?: QuoteDetail_Result[] | null;
  transactioncurrency_salesorder?: SalesOrder_Result[] | null;
  transactioncurrency_salesorderdetail?: SalesOrderDetail_Result[] | null;
  transactioncurrency_semiannualfiscalcalendar?: SemiAnnualFiscalCalendar_Result[] | null;
  transactioncurrency_socialactivity?: SocialActivity_Result[] | null;
  transactioncurrency_suggestioncardtemplate?: SuggestionCardTemplate_Result[] | null;
  transactioncurrency_translationprocess?: TranslationProcess_Result[] | null;
  transactioncurrency_userfiscalcalendar?: UserFiscalCalendar_Result[] | null;
  transactioncurrency_usersettings?: UserSettings_Result[] | null;
  userentityinstancedata_transactioncurrency?: UserEntityInstanceData_Result[] | null;
}
interface TransactionCurrency extends TransactionCurrency_Base, TransactionCurrency_Relationships {
}
interface TransactionCurrency_Create extends TransactionCurrency {
}
interface TransactionCurrency_Update extends TransactionCurrency {
}
interface TransactionCurrency_Select {
  createdby_guid: WebAttribute<TransactionCurrency_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<TransactionCurrency_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<TransactionCurrency_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  currencyname: WebAttribute<TransactionCurrency_Select, { currencyname: string | null }, {  }>;
  currencyprecision: WebAttribute<TransactionCurrency_Select, { currencyprecision: number | null }, {  }>;
  currencysymbol: WebAttribute<TransactionCurrency_Select, { currencysymbol: string | null }, {  }>;
  entityimageid: WebAttribute<TransactionCurrency_Select, { entityimageid: string | null }, {  }>;
  exchangerate: WebAttribute<TransactionCurrency_Select, { exchangerate: number | null }, {  }>;
  importsequencenumber: WebAttribute<TransactionCurrency_Select, { importsequencenumber: number | null }, {  }>;
  isocurrencycode: WebAttribute<TransactionCurrency_Select, { isocurrencycode: string | null }, {  }>;
  modifiedby_guid: WebAttribute<TransactionCurrency_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<TransactionCurrency_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<TransactionCurrency_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  organizationid_guid: WebAttribute<TransactionCurrency_Select, { organizationid_guid: string | null }, { organizationid_formatted?: string }>;
  overriddencreatedon: WebAttribute<TransactionCurrency_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  statecode: WebAttribute<TransactionCurrency_Select, { statecode: transactioncurrency_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<TransactionCurrency_Select, { statuscode: transactioncurrency_statuscode | null }, { statuscode_formatted?: string }>;
  transactioncurrencyid: WebAttribute<TransactionCurrency_Select, { transactioncurrencyid: string | null }, {  }>;
  uniquedscid: WebAttribute<TransactionCurrency_Select, { uniquedscid: string | null }, {  }>;
  versionnumber: WebAttribute<TransactionCurrency_Select, { versionnumber: number | null }, {  }>;
}
interface TransactionCurrency_Filter {
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  currencyname: string;
  currencyprecision: number;
  currencysymbol: string;
  entityimageid: XQW.Guid;
  exchangerate: any;
  importsequencenumber: number;
  isocurrencycode: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  organizationid_guid: XQW.Guid;
  overriddencreatedon: Date;
  statecode: transactioncurrency_statecode;
  statuscode: transactioncurrency_statuscode;
  transactioncurrencyid: XQW.Guid;
  uniquedscid: XQW.Guid;
  versionnumber: number;
}
interface TransactionCurrency_Expand {
  DynamicPropertyAssociation_TransactionCurrency: WebExpand<TransactionCurrency_Expand, DynamicPropertyAssociation_Select, DynamicPropertyAssociation_Filter, { DynamicPropertyAssociation_TransactionCurrency: DynamicPropertyAssociation_Result[] }>;
  DynamicPropertyOptionSetItem_TransactionCurrency: WebExpand<TransactionCurrency_Expand, DynamicPropertyOptionSetItem_Select, DynamicPropertyOptionSetItem_Filter, { DynamicPropertyOptionSetItem_TransactionCurrency: DynamicPropertyOptionSetItem_Result[] }>;
  TransactionCurrency_ActionCardUserState: WebExpand<TransactionCurrency_Expand, ActionCardUserState_Select, ActionCardUserState_Filter, { TransactionCurrency_ActionCardUserState: ActionCardUserState_Result[] }>;
  TransactionCurrency_ActivityPointer: WebExpand<TransactionCurrency_Expand, ActivityPointer_Select, ActivityPointer_Filter, { TransactionCurrency_ActivityPointer: ActivityPointer_Result[] }>;
  TransactionCurrency_Appointment: WebExpand<TransactionCurrency_Expand, Appointment_Select, Appointment_Filter, { TransactionCurrency_Appointment: Appointment_Result[] }>;
  TransactionCurrency_AsyncOperations: WebExpand<TransactionCurrency_Expand, AsyncOperation_Select, AsyncOperation_Filter, { TransactionCurrency_AsyncOperations: AsyncOperation_Result[] }>;
  TransactionCurrency_BusinessUnit: WebExpand<TransactionCurrency_Expand, BusinessUnit_Select, BusinessUnit_Filter, { TransactionCurrency_BusinessUnit: BusinessUnit_Result[] }>;
  TransactionCurrency_CampaignResponse: WebExpand<TransactionCurrency_Expand, CampaignResponse_Select, CampaignResponse_Filter, { TransactionCurrency_CampaignResponse: CampaignResponse_Result[] }>;
  TransactionCurrency_Connection: WebExpand<TransactionCurrency_Expand, Connection_Select, Connection_Filter, { TransactionCurrency_Connection: Connection_Result[] }>;
  TransactionCurrency_ConvertRule: WebExpand<TransactionCurrency_Expand, ConvertRule_Select, ConvertRule_Filter, { TransactionCurrency_ConvertRule: ConvertRule_Result[] }>;
  TransactionCurrency_CustomerAddress: WebExpand<TransactionCurrency_Expand, CustomerAddress_Select, CustomerAddress_Filter, { TransactionCurrency_CustomerAddress: CustomerAddress_Result[] }>;
  TransactionCurrency_DuplicateBaseRecord: WebExpand<TransactionCurrency_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { TransactionCurrency_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  TransactionCurrency_DuplicateMatchingRecord: WebExpand<TransactionCurrency_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { TransactionCurrency_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  TransactionCurrency_Dynamicpropertyinsatance: WebExpand<TransactionCurrency_Expand, DynamicPropertyInstance_Select, DynamicPropertyInstance_Filter, { TransactionCurrency_Dynamicpropertyinsatance: DynamicPropertyInstance_Result[] }>;
  TransactionCurrency_Email: WebExpand<TransactionCurrency_Expand, Email_Select, Email_Filter, { TransactionCurrency_Email: Email_Result[] }>;
  TransactionCurrency_Entitlement: WebExpand<TransactionCurrency_Expand, Entitlement_Select, Entitlement_Filter, { TransactionCurrency_Entitlement: Entitlement_Result[] }>;
  TransactionCurrency_Equipment: WebExpand<TransactionCurrency_Expand, Equipment_Select, Equipment_Filter, { TransactionCurrency_Equipment: Equipment_Result[] }>;
  TransactionCurrency_Fax: WebExpand<TransactionCurrency_Expand, Fax_Select, Fax_Filter, { TransactionCurrency_Fax: Fax_Result[] }>;
  TransactionCurrency_Goal: WebExpand<TransactionCurrency_Expand, Goal_Select, Goal_Filter, { TransactionCurrency_Goal: Goal_Result[] }>;
  TransactionCurrency_Incident: WebExpand<TransactionCurrency_Expand, Incident_Select, Incident_Filter, { TransactionCurrency_Incident: Incident_Result[] }>;
  TransactionCurrency_InteractionForEmail: WebExpand<TransactionCurrency_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { TransactionCurrency_InteractionForEmail: InteractionForEmail_Result[] }>;
  TransactionCurrency_KbArticle: WebExpand<TransactionCurrency_Expand, KbArticle_Select, KbArticle_Filter, { TransactionCurrency_KbArticle: KbArticle_Result[] }>;
  TransactionCurrency_KnowledgeBaseRecord: WebExpand<TransactionCurrency_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { TransactionCurrency_KnowledgeBaseRecord: KnowledgeBaseRecord_Result[] }>;
  TransactionCurrency_LeadAddress: WebExpand<TransactionCurrency_Expand, LeadAddress_Select, LeadAddress_Filter, { TransactionCurrency_LeadAddress: LeadAddress_Result[] }>;
  TransactionCurrency_Letter: WebExpand<TransactionCurrency_Expand, Letter_Select, Letter_Filter, { TransactionCurrency_Letter: Letter_Result[] }>;
  TransactionCurrency_MailMergeTemplate: WebExpand<TransactionCurrency_Expand, MailMergeTemplate_Select, MailMergeTemplate_Filter, { TransactionCurrency_MailMergeTemplate: MailMergeTemplate_Result[] }>;
  TransactionCurrency_PhoneCall: WebExpand<TransactionCurrency_Expand, PhoneCall_Select, PhoneCall_Filter, { TransactionCurrency_PhoneCall: PhoneCall_Result[] }>;
  TransactionCurrency_ProcessSessions: WebExpand<TransactionCurrency_Expand, ProcessSession_Select, ProcessSession_Filter, { TransactionCurrency_ProcessSessions: ProcessSession_Result[] }>;
  TransactionCurrency_Queue: WebExpand<TransactionCurrency_Expand, Queue_Select, Queue_Filter, { TransactionCurrency_Queue: Queue_Result[] }>;
  TransactionCurrency_QueueItem: WebExpand<TransactionCurrency_Expand, QueueItem_Select, QueueItem_Filter, { TransactionCurrency_QueueItem: QueueItem_Result[] }>;
  TransactionCurrency_RecurringAppointmentMaster: WebExpand<TransactionCurrency_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { TransactionCurrency_RecurringAppointmentMaster: RecurringAppointmentMaster_Result[] }>;
  TransactionCurrency_ReportCategory: WebExpand<TransactionCurrency_Expand, ReportCategory_Select, ReportCategory_Filter, { TransactionCurrency_ReportCategory: ReportCategory_Result[] }>;
  TransactionCurrency_Routingrule: WebExpand<TransactionCurrency_Expand, RoutingRule_Select, RoutingRule_Filter, { TransactionCurrency_Routingrule: RoutingRule_Result[] }>;
  TransactionCurrency_SLA: WebExpand<TransactionCurrency_Expand, SLA_Select, SLA_Filter, { TransactionCurrency_SLA: SLA_Result[] }>;
  TransactionCurrency_SLAItem: WebExpand<TransactionCurrency_Expand, SLAItem_Select, SLAItem_Filter, { TransactionCurrency_SLAItem: SLAItem_Result[] }>;
  TransactionCurrency_SalesLiterature: WebExpand<TransactionCurrency_Expand, SalesLiterature_Select, SalesLiterature_Filter, { TransactionCurrency_SalesLiterature: SalesLiterature_Result[] }>;
  TransactionCurrency_ServiceAppointment: WebExpand<TransactionCurrency_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { TransactionCurrency_ServiceAppointment: ServiceAppointment_Result[] }>;
  TransactionCurrency_SharePointDocument: WebExpand<TransactionCurrency_Expand, SharePointDocument_Select, SharePointDocument_Filter, { TransactionCurrency_SharePointDocument: SharePointDocument_Result[] }>;
  TransactionCurrency_SharePointDocumentLocation: WebExpand<TransactionCurrency_Expand, SharePointDocumentLocation_Select, SharePointDocumentLocation_Filter, { TransactionCurrency_SharePointDocumentLocation: SharePointDocumentLocation_Result[] }>;
  TransactionCurrency_SharePointSite: WebExpand<TransactionCurrency_Expand, SharePointSite_Select, SharePointSite_Filter, { TransactionCurrency_SharePointSite: SharePointSite_Result[] }>;
  TransactionCurrency_SimilarityRule: WebExpand<TransactionCurrency_Expand, SimilarityRule_Select, SimilarityRule_Filter, { TransactionCurrency_SimilarityRule: SimilarityRule_Result[] }>;
  TransactionCurrency_SyncErrors: WebExpand<TransactionCurrency_Expand, SyncError_Select, SyncError_Filter, { TransactionCurrency_SyncErrors: SyncError_Result[] }>;
  TransactionCurrency_SystemUser: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { TransactionCurrency_SystemUser: SystemUser_Result[] }>;
  TransactionCurrency_Task: WebExpand<TransactionCurrency_Expand, Task_Select, Task_Filter, { TransactionCurrency_Task: Task_Result[] }>;
  TransactionCurrency_Team: WebExpand<TransactionCurrency_Expand, Team_Select, Team_Filter, { TransactionCurrency_Team: Team_Result[] }>;
  TransactionCurrency_Territory: WebExpand<TransactionCurrency_Expand, Territory_Select, Territory_Filter, { TransactionCurrency_Territory: Territory_Result[] }>;
  TransactionCurrency_Theme: WebExpand<TransactionCurrency_Expand, Theme_Select, Theme_Filter, { TransactionCurrency_Theme: Theme_Result[] }>;
  TransactionCurrency_UntrackedEmail: WebExpand<TransactionCurrency_Expand, UntrackedEmail_Select, UntrackedEmail_Filter, { TransactionCurrency_UntrackedEmail: UntrackedEmail_Result[] }>;
  TransactionCurrency_UserMapping: WebExpand<TransactionCurrency_Expand, UserMapping_Select, UserMapping_Filter, { TransactionCurrency_UserMapping: UserMapping_Result[] }>;
  TransactionCurrency_bookableresource: WebExpand<TransactionCurrency_Expand, BookableResource_Select, BookableResource_Filter, { TransactionCurrency_bookableresource: BookableResource_Result[] }>;
  TransactionCurrency_bookableresourcebooking: WebExpand<TransactionCurrency_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { TransactionCurrency_bookableresourcebooking: BookableResourceBooking_Result[] }>;
  TransactionCurrency_bookableresourcebookingheader: WebExpand<TransactionCurrency_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { TransactionCurrency_bookableresourcebookingheader: BookableResourceBookingHeader_Result[] }>;
  TransactionCurrency_bookableresourcecategory: WebExpand<TransactionCurrency_Expand, BookableResourceCategory_Select, BookableResourceCategory_Filter, { TransactionCurrency_bookableresourcecategory: BookableResourceCategory_Result[] }>;
  TransactionCurrency_bookableresourcecategoryassn: WebExpand<TransactionCurrency_Expand, BookableResourceCategoryAssn_Select, BookableResourceCategoryAssn_Filter, { TransactionCurrency_bookableresourcecategoryassn: BookableResourceCategoryAssn_Result[] }>;
  TransactionCurrency_bookableresourcecharacteristic: WebExpand<TransactionCurrency_Expand, BookableResourceCharacteristic_Select, BookableResourceCharacteristic_Filter, { TransactionCurrency_bookableresourcecharacteristic: BookableResourceCharacteristic_Result[] }>;
  TransactionCurrency_bookableresourcegroup: WebExpand<TransactionCurrency_Expand, BookableResourceGroup_Select, BookableResourceGroup_Filter, { TransactionCurrency_bookableresourcegroup: BookableResourceGroup_Result[] }>;
  TransactionCurrency_bookingstatus: WebExpand<TransactionCurrency_Expand, BookingStatus_Select, BookingStatus_Filter, { TransactionCurrency_bookingstatus: BookingStatus_Result[] }>;
  TransactionCurrency_characteristic: WebExpand<TransactionCurrency_Expand, Characteristic_Select, Characteristic_Filter, { TransactionCurrency_characteristic: Characteristic_Result[] }>;
  TransactionCurrency_delveactionhub: WebExpand<TransactionCurrency_Expand, DelveActionHub_Select, DelveActionHub_Filter, { TransactionCurrency_delveactionhub: DelveActionHub_Result[] }>;
  TransactionCurrency_entitlementchannel: WebExpand<TransactionCurrency_Expand, EntitlementChannel_Select, EntitlementChannel_Filter, { TransactionCurrency_entitlementchannel: EntitlementChannel_Result[] }>;
  TransactionCurrency_entitlementtemplate: WebExpand<TransactionCurrency_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { TransactionCurrency_entitlementtemplate: EntitlementTemplate_Result[] }>;
  TransactionCurrency_entitlementtemplatechannel: WebExpand<TransactionCurrency_Expand, EntitlementTemplateChannel_Select, EntitlementTemplateChannel_Filter, { TransactionCurrency_entitlementtemplatechannel: EntitlementTemplateChannel_Result[] }>;
  TransactionCurrency_externalpartyitem: WebExpand<TransactionCurrency_Expand, ExternalPartyItem_Select, ExternalPartyItem_Filter, { TransactionCurrency_externalpartyitem: ExternalPartyItem_Result[] }>;
  TransactionCurrency_officegraphdocument: WebExpand<TransactionCurrency_Expand, OfficeGraphDocument_Select, OfficeGraphDocument_Filter, { TransactionCurrency_officegraphdocument: OfficeGraphDocument_Result[] }>;
  TransactionCurrency_profilerule: WebExpand<TransactionCurrency_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { TransactionCurrency_profilerule: ChannelAccessProfileRule_Result[] }>;
  TransactionCurrency_profileruleitem: WebExpand<TransactionCurrency_Expand, ChannelAccessProfileRuleItem_Select, ChannelAccessProfileRuleItem_Filter, { TransactionCurrency_profileruleitem: ChannelAccessProfileRuleItem_Result[] }>;
  TransactionCurrency_ratingmodel: WebExpand<TransactionCurrency_Expand, RatingModel_Select, RatingModel_Filter, { TransactionCurrency_ratingmodel: RatingModel_Result[] }>;
  TransactionCurrency_ratingvalue: WebExpand<TransactionCurrency_Expand, RatingValue_Select, RatingValue_Filter, { TransactionCurrency_ratingvalue: RatingValue_Result[] }>;
  TransactionCurrency_recommendeddocument: WebExpand<TransactionCurrency_Expand, RecommendedDocument_Select, RecommendedDocument_Filter, { TransactionCurrency_recommendeddocument: RecommendedDocument_Result[] }>;
  TransactionCurrency_routingruleitem: WebExpand<TransactionCurrency_Expand, RoutingRuleItem_Select, RoutingRuleItem_Filter, { TransactionCurrency_routingruleitem: RoutingRuleItem_Result[] }>;
  TransactionCurrency_slakpiinstance: WebExpand<TransactionCurrency_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { TransactionCurrency_slakpiinstance: SLAKPIInstance_Result[] }>;
  awcnpd_feedback_transactioncurrency_transactioncurrencyid: WebExpand<TransactionCurrency_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { awcnpd_feedback_transactioncurrency_transactioncurrencyid: awcnpd_feedback_Result[] }>;
  basecurrency_organization: WebExpand<TransactionCurrency_Expand, Organization_Select, Organization_Filter, { basecurrency_organization: Organization_Result[] }>;
  bulkoperation_transactioncurrency_transactioncurrencyid: WebExpand<TransactionCurrency_Expand, BulkOperation_Select, BulkOperation_Filter, { bulkoperation_transactioncurrency_transactioncurrencyid: BulkOperation_Result[] }>;
  createdby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  entityimageid_imagedescriptor: WebExpand<TransactionCurrency_Expand, ImageDescriptor_Select, ImageDescriptor_Filter, { entityimageid_imagedescriptor: ImageDescriptor_Result }>;
  incidentresolution_transactioncurrency_transactioncurrencyid: WebExpand<TransactionCurrency_Expand, IncidentResolution_Select, IncidentResolution_Filter, { incidentresolution_transactioncurrency_transactioncurrencyid: IncidentResolution_Result[] }>;
  modifiedby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<TransactionCurrency_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  orderclose_transactioncurrency_transactioncurrencyid: WebExpand<TransactionCurrency_Expand, OrderClose_Select, OrderClose_Filter, { orderclose_transactioncurrency_transactioncurrencyid: OrderClose_Result[] }>;
  organizationid: WebExpand<TransactionCurrency_Expand, Organization_Select, Organization_Filter, { organizationid: Organization_Result }>;
  quoteclose_transactioncurrency_transactioncurrencyid: WebExpand<TransactionCurrency_Expand, QuoteClose_Select, QuoteClose_Filter, { quoteclose_transactioncurrency_transactioncurrencyid: QuoteClose_Result[] }>;
  transactioncurrency_ProductAssociation: WebExpand<TransactionCurrency_Expand, ProductAssociation_Select, ProductAssociation_Filter, { transactioncurrency_ProductAssociation: ProductAssociation_Result[] }>;
  transactioncurrency_ProductSubstitute: WebExpand<TransactionCurrency_Expand, ProductSubstitute_Select, ProductSubstitute_Filter, { transactioncurrency_ProductSubstitute: ProductSubstitute_Result[] }>;
  transactioncurrency_SocialProfile: WebExpand<TransactionCurrency_Expand, SocialProfile_Select, SocialProfile_Filter, { transactioncurrency_SocialProfile: SocialProfile_Result[] }>;
  transactioncurrency_account: WebExpand<TransactionCurrency_Expand, Account_Select, Account_Filter, { transactioncurrency_account: Account_Result[] }>;
  transactioncurrency_actioncard: WebExpand<TransactionCurrency_Expand, ActionCard_Select, ActionCard_Filter, { transactioncurrency_actioncard: ActionCard_Result[] }>;
  transactioncurrency_annualfiscalcalendar: WebExpand<TransactionCurrency_Expand, AnnualFiscalCalendar_Select, AnnualFiscalCalendar_Filter, { transactioncurrency_annualfiscalcalendar: AnnualFiscalCalendar_Result[] }>;
  transactioncurrency_campaign: WebExpand<TransactionCurrency_Expand, Campaign_Select, Campaign_Filter, { transactioncurrency_campaign: Campaign_Result[] }>;
  transactioncurrency_campaignactivity: WebExpand<TransactionCurrency_Expand, CampaignActivity_Select, CampaignActivity_Filter, { transactioncurrency_campaignactivity: CampaignActivity_Result[] }>;
  transactioncurrency_cardtype: WebExpand<TransactionCurrency_Expand, CardType_Select, CardType_Filter, { transactioncurrency_cardtype: CardType_Result[] }>;
  transactioncurrency_category: WebExpand<TransactionCurrency_Expand, Category_Select, Category_Filter, { transactioncurrency_category: Category_Result[] }>;
  transactioncurrency_channelaccessprofile: WebExpand<TransactionCurrency_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { transactioncurrency_channelaccessprofile: ChannelAccessProfile_Result[] }>;
  transactioncurrency_competitor: WebExpand<TransactionCurrency_Expand, Competitor_Select, Competitor_Filter, { transactioncurrency_competitor: Competitor_Result[] }>;
  transactioncurrency_contact: WebExpand<TransactionCurrency_Expand, Contact_Select, Contact_Filter, { transactioncurrency_contact: Contact_Result[] }>;
  transactioncurrency_contract: WebExpand<TransactionCurrency_Expand, Contract_Select, Contract_Filter, { transactioncurrency_contract: Contract_Result[] }>;
  transactioncurrency_contractdetail: WebExpand<TransactionCurrency_Expand, ContractDetail_Select, ContractDetail_Filter, { transactioncurrency_contractdetail: ContractDetail_Result[] }>;
  transactioncurrency_convertruleitem: WebExpand<TransactionCurrency_Expand, ConvertRuleItem_Select, ConvertRuleItem_Filter, { transactioncurrency_convertruleitem: ConvertRuleItem_Result[] }>;
  transactioncurrency_discount: WebExpand<TransactionCurrency_Expand, Discount_Select, Discount_Filter, { transactioncurrency_discount: Discount_Result[] }>;
  transactioncurrency_discounttype: WebExpand<TransactionCurrency_Expand, DiscountType_Select, DiscountType_Filter, { transactioncurrency_discounttype: DiscountType_Result[] }>;
  transactioncurrency_expiredprocess: WebExpand<TransactionCurrency_Expand, ExpiredProcess_Select, ExpiredProcess_Filter, { transactioncurrency_expiredprocess: ExpiredProcess_Result[] }>;
  transactioncurrency_externalparty: WebExpand<TransactionCurrency_Expand, ExternalParty_Select, ExternalParty_Filter, { transactioncurrency_externalparty: ExternalParty_Result[] }>;
  transactioncurrency_feedback: WebExpand<TransactionCurrency_Expand, Feedback_Select, Feedback_Filter, { transactioncurrency_feedback: Feedback_Result[] }>;
  transactioncurrency_fixedmonthlyfiscalcalendar: WebExpand<TransactionCurrency_Expand, FixedMonthlyFiscalCalendar_Select, FixedMonthlyFiscalCalendar_Filter, { transactioncurrency_fixedmonthlyfiscalcalendar: FixedMonthlyFiscalCalendar_Result[] }>;
  transactioncurrency_invoice: WebExpand<TransactionCurrency_Expand, Invoice_Select, Invoice_Filter, { transactioncurrency_invoice: Invoice_Result[] }>;
  transactioncurrency_invoicedetail: WebExpand<TransactionCurrency_Expand, InvoiceDetail_Select, InvoiceDetail_Filter, { transactioncurrency_invoicedetail: InvoiceDetail_Result[] }>;
  transactioncurrency_knowledgearticle: WebExpand<TransactionCurrency_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { transactioncurrency_knowledgearticle: KnowledgeArticle_Result[] }>;
  transactioncurrency_knowledgearticleincident: WebExpand<TransactionCurrency_Expand, KnowledgeArticleIncident_Select, KnowledgeArticleIncident_Filter, { transactioncurrency_knowledgearticleincident: KnowledgeArticleIncident_Result[] }>;
  transactioncurrency_knowledgearticleviews: WebExpand<TransactionCurrency_Expand, KnowledgeArticleViews_Select, KnowledgeArticleViews_Filter, { transactioncurrency_knowledgearticleviews: KnowledgeArticleViews_Result[] }>;
  transactioncurrency_lead: WebExpand<TransactionCurrency_Expand, Lead_Select, Lead_Filter, { transactioncurrency_lead: Lead_Result[] }>;
  transactioncurrency_leadtoopportunitysalesprocess: WebExpand<TransactionCurrency_Expand, LeadToOpportunitySalesProcess_Select, LeadToOpportunitySalesProcess_Filter, { transactioncurrency_leadtoopportunitysalesprocess: LeadToOpportunitySalesProcess_Result[] }>;
  transactioncurrency_list: WebExpand<TransactionCurrency_Expand, List_Select, List_Filter, { transactioncurrency_list: List_Result[] }>;
  transactioncurrency_monthlyfiscalcalendar: WebExpand<TransactionCurrency_Expand, MonthlyFiscalCalendar_Select, MonthlyFiscalCalendar_Filter, { transactioncurrency_monthlyfiscalcalendar: MonthlyFiscalCalendar_Result[] }>;
  transactioncurrency_newprocess: WebExpand<TransactionCurrency_Expand, NewProcess_Select, NewProcess_Filter, { transactioncurrency_newprocess: NewProcess_Result[] }>;
  transactioncurrency_opportunity: WebExpand<TransactionCurrency_Expand, Opportunity_Select, Opportunity_Filter, { transactioncurrency_opportunity: Opportunity_Result[] }>;
  transactioncurrency_opportunityclose: WebExpand<TransactionCurrency_Expand, OpportunityClose_Select, OpportunityClose_Filter, { transactioncurrency_opportunityclose: OpportunityClose_Result[] }>;
  transactioncurrency_opportunityproduct: WebExpand<TransactionCurrency_Expand, OpportunityProduct_Select, OpportunityProduct_Filter, { transactioncurrency_opportunityproduct: OpportunityProduct_Result[] }>;
  transactioncurrency_opportunitysalesprocess: WebExpand<TransactionCurrency_Expand, OpportunitySalesProcess_Select, OpportunitySalesProcess_Filter, { transactioncurrency_opportunitysalesprocess: OpportunitySalesProcess_Result[] }>;
  transactioncurrency_phonetocaseprocess: WebExpand<TransactionCurrency_Expand, PhoneToCaseProcess_Select, PhoneToCaseProcess_Filter, { transactioncurrency_phonetocaseprocess: PhoneToCaseProcess_Result[] }>;
  transactioncurrency_position: WebExpand<TransactionCurrency_Expand, Position_Select, Position_Filter, { transactioncurrency_position: Position_Result[] }>;
  transactioncurrency_pricelevel: WebExpand<TransactionCurrency_Expand, PriceLevel_Select, PriceLevel_Filter, { transactioncurrency_pricelevel: PriceLevel_Result[] }>;
  transactioncurrency_product: WebExpand<TransactionCurrency_Expand, Product_Select, Product_Filter, { transactioncurrency_product: Product_Result[] }>;
  transactioncurrency_productpricelevel: WebExpand<TransactionCurrency_Expand, ProductPriceLevel_Select, ProductPriceLevel_Filter, { transactioncurrency_productpricelevel: ProductPriceLevel_Result[] }>;
  transactioncurrency_quarterlyfiscalcalendar: WebExpand<TransactionCurrency_Expand, QuarterlyFiscalCalendar_Select, QuarterlyFiscalCalendar_Filter, { transactioncurrency_quarterlyfiscalcalendar: QuarterlyFiscalCalendar_Result[] }>;
  transactioncurrency_quote: WebExpand<TransactionCurrency_Expand, Quote_Select, Quote_Filter, { transactioncurrency_quote: Quote_Result[] }>;
  transactioncurrency_quotedetail: WebExpand<TransactionCurrency_Expand, QuoteDetail_Select, QuoteDetail_Filter, { transactioncurrency_quotedetail: QuoteDetail_Result[] }>;
  transactioncurrency_salesorder: WebExpand<TransactionCurrency_Expand, SalesOrder_Select, SalesOrder_Filter, { transactioncurrency_salesorder: SalesOrder_Result[] }>;
  transactioncurrency_salesorderdetail: WebExpand<TransactionCurrency_Expand, SalesOrderDetail_Select, SalesOrderDetail_Filter, { transactioncurrency_salesorderdetail: SalesOrderDetail_Result[] }>;
  transactioncurrency_semiannualfiscalcalendar: WebExpand<TransactionCurrency_Expand, SemiAnnualFiscalCalendar_Select, SemiAnnualFiscalCalendar_Filter, { transactioncurrency_semiannualfiscalcalendar: SemiAnnualFiscalCalendar_Result[] }>;
  transactioncurrency_socialactivity: WebExpand<TransactionCurrency_Expand, SocialActivity_Select, SocialActivity_Filter, { transactioncurrency_socialactivity: SocialActivity_Result[] }>;
  transactioncurrency_suggestioncardtemplate: WebExpand<TransactionCurrency_Expand, SuggestionCardTemplate_Select, SuggestionCardTemplate_Filter, { transactioncurrency_suggestioncardtemplate: SuggestionCardTemplate_Result[] }>;
  transactioncurrency_translationprocess: WebExpand<TransactionCurrency_Expand, TranslationProcess_Select, TranslationProcess_Filter, { transactioncurrency_translationprocess: TranslationProcess_Result[] }>;
  transactioncurrency_userfiscalcalendar: WebExpand<TransactionCurrency_Expand, UserFiscalCalendar_Select, UserFiscalCalendar_Filter, { transactioncurrency_userfiscalcalendar: UserFiscalCalendar_Result[] }>;
  transactioncurrency_usersettings: WebExpand<TransactionCurrency_Expand, UserSettings_Select, UserSettings_Filter, { transactioncurrency_usersettings: UserSettings_Result[] }>;
  userentityinstancedata_transactioncurrency: WebExpand<TransactionCurrency_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_transactioncurrency: UserEntityInstanceData_Result[] }>;
}
interface TransactionCurrency_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  organizationid_formatted?: string;
  overriddencreatedon_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
}
interface TransactionCurrency_Result extends TransactionCurrency_Base, TransactionCurrency_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  organizationid_guid: string | null;
}
interface TransactionCurrency_RelatedOne {
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  entityimageid_imagedescriptor: WebMappingRetrieve<ImageDescriptor_Select,ImageDescriptor_Expand,ImageDescriptor_Filter,ImageDescriptor_Fixed,ImageDescriptor_Result,ImageDescriptor_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  organizationid: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
}
interface TransactionCurrency_RelatedMany {
  DynamicPropertyAssociation_TransactionCurrency: WebMappingRetrieve<DynamicPropertyAssociation_Select,DynamicPropertyAssociation_Expand,DynamicPropertyAssociation_Filter,DynamicPropertyAssociation_Fixed,DynamicPropertyAssociation_Result,DynamicPropertyAssociation_FormattedResult>;
  DynamicPropertyOptionSetItem_TransactionCurrency: WebMappingRetrieve<DynamicPropertyOptionSetItem_Select,DynamicPropertyOptionSetItem_Expand,DynamicPropertyOptionSetItem_Filter,DynamicPropertyOptionSetItem_Fixed,DynamicPropertyOptionSetItem_Result,DynamicPropertyOptionSetItem_FormattedResult>;
  TransactionCurrency_ActionCardUserState: WebMappingRetrieve<ActionCardUserState_Select,ActionCardUserState_Expand,ActionCardUserState_Filter,ActionCardUserState_Fixed,ActionCardUserState_Result,ActionCardUserState_FormattedResult>;
  TransactionCurrency_ActivityPointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  TransactionCurrency_Appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  TransactionCurrency_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  TransactionCurrency_BusinessUnit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  TransactionCurrency_CampaignResponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  TransactionCurrency_Connection: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  TransactionCurrency_ConvertRule: WebMappingRetrieve<ConvertRule_Select,ConvertRule_Expand,ConvertRule_Filter,ConvertRule_Fixed,ConvertRule_Result,ConvertRule_FormattedResult>;
  TransactionCurrency_CustomerAddress: WebMappingRetrieve<CustomerAddress_Select,CustomerAddress_Expand,CustomerAddress_Filter,CustomerAddress_Fixed,CustomerAddress_Result,CustomerAddress_FormattedResult>;
  TransactionCurrency_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  TransactionCurrency_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  TransactionCurrency_Dynamicpropertyinsatance: WebMappingRetrieve<DynamicPropertyInstance_Select,DynamicPropertyInstance_Expand,DynamicPropertyInstance_Filter,DynamicPropertyInstance_Fixed,DynamicPropertyInstance_Result,DynamicPropertyInstance_FormattedResult>;
  TransactionCurrency_Email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  TransactionCurrency_Entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  TransactionCurrency_Equipment: WebMappingRetrieve<Equipment_Select,Equipment_Expand,Equipment_Filter,Equipment_Fixed,Equipment_Result,Equipment_FormattedResult>;
  TransactionCurrency_Fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  TransactionCurrency_Goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  TransactionCurrency_Incident: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  TransactionCurrency_InteractionForEmail: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  TransactionCurrency_KbArticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  TransactionCurrency_KnowledgeBaseRecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  TransactionCurrency_LeadAddress: WebMappingRetrieve<LeadAddress_Select,LeadAddress_Expand,LeadAddress_Filter,LeadAddress_Fixed,LeadAddress_Result,LeadAddress_FormattedResult>;
  TransactionCurrency_Letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  TransactionCurrency_MailMergeTemplate: WebMappingRetrieve<MailMergeTemplate_Select,MailMergeTemplate_Expand,MailMergeTemplate_Filter,MailMergeTemplate_Fixed,MailMergeTemplate_Result,MailMergeTemplate_FormattedResult>;
  TransactionCurrency_PhoneCall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  TransactionCurrency_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  TransactionCurrency_Queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  TransactionCurrency_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  TransactionCurrency_RecurringAppointmentMaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  TransactionCurrency_ReportCategory: WebMappingRetrieve<ReportCategory_Select,ReportCategory_Expand,ReportCategory_Filter,ReportCategory_Fixed,ReportCategory_Result,ReportCategory_FormattedResult>;
  TransactionCurrency_Routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  TransactionCurrency_SLA: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  TransactionCurrency_SLAItem: WebMappingRetrieve<SLAItem_Select,SLAItem_Expand,SLAItem_Filter,SLAItem_Fixed,SLAItem_Result,SLAItem_FormattedResult>;
  TransactionCurrency_SalesLiterature: WebMappingRetrieve<SalesLiterature_Select,SalesLiterature_Expand,SalesLiterature_Filter,SalesLiterature_Fixed,SalesLiterature_Result,SalesLiterature_FormattedResult>;
  TransactionCurrency_ServiceAppointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  TransactionCurrency_SharePointDocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  TransactionCurrency_SharePointDocumentLocation: WebMappingRetrieve<SharePointDocumentLocation_Select,SharePointDocumentLocation_Expand,SharePointDocumentLocation_Filter,SharePointDocumentLocation_Fixed,SharePointDocumentLocation_Result,SharePointDocumentLocation_FormattedResult>;
  TransactionCurrency_SharePointSite: WebMappingRetrieve<SharePointSite_Select,SharePointSite_Expand,SharePointSite_Filter,SharePointSite_Fixed,SharePointSite_Result,SharePointSite_FormattedResult>;
  TransactionCurrency_SimilarityRule: WebMappingRetrieve<SimilarityRule_Select,SimilarityRule_Expand,SimilarityRule_Filter,SimilarityRule_Fixed,SimilarityRule_Result,SimilarityRule_FormattedResult>;
  TransactionCurrency_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  TransactionCurrency_SystemUser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  TransactionCurrency_Task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  TransactionCurrency_Team: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  TransactionCurrency_Territory: WebMappingRetrieve<Territory_Select,Territory_Expand,Territory_Filter,Territory_Fixed,Territory_Result,Territory_FormattedResult>;
  TransactionCurrency_Theme: WebMappingRetrieve<Theme_Select,Theme_Expand,Theme_Filter,Theme_Fixed,Theme_Result,Theme_FormattedResult>;
  TransactionCurrency_UntrackedEmail: WebMappingRetrieve<UntrackedEmail_Select,UntrackedEmail_Expand,UntrackedEmail_Filter,UntrackedEmail_Fixed,UntrackedEmail_Result,UntrackedEmail_FormattedResult>;
  TransactionCurrency_UserMapping: WebMappingRetrieve<UserMapping_Select,UserMapping_Expand,UserMapping_Filter,UserMapping_Fixed,UserMapping_Result,UserMapping_FormattedResult>;
  TransactionCurrency_bookableresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  TransactionCurrency_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  TransactionCurrency_bookableresourcebookingheader: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  TransactionCurrency_bookableresourcecategory: WebMappingRetrieve<BookableResourceCategory_Select,BookableResourceCategory_Expand,BookableResourceCategory_Filter,BookableResourceCategory_Fixed,BookableResourceCategory_Result,BookableResourceCategory_FormattedResult>;
  TransactionCurrency_bookableresourcecategoryassn: WebMappingRetrieve<BookableResourceCategoryAssn_Select,BookableResourceCategoryAssn_Expand,BookableResourceCategoryAssn_Filter,BookableResourceCategoryAssn_Fixed,BookableResourceCategoryAssn_Result,BookableResourceCategoryAssn_FormattedResult>;
  TransactionCurrency_bookableresourcecharacteristic: WebMappingRetrieve<BookableResourceCharacteristic_Select,BookableResourceCharacteristic_Expand,BookableResourceCharacteristic_Filter,BookableResourceCharacteristic_Fixed,BookableResourceCharacteristic_Result,BookableResourceCharacteristic_FormattedResult>;
  TransactionCurrency_bookableresourcegroup: WebMappingRetrieve<BookableResourceGroup_Select,BookableResourceGroup_Expand,BookableResourceGroup_Filter,BookableResourceGroup_Fixed,BookableResourceGroup_Result,BookableResourceGroup_FormattedResult>;
  TransactionCurrency_bookingstatus: WebMappingRetrieve<BookingStatus_Select,BookingStatus_Expand,BookingStatus_Filter,BookingStatus_Fixed,BookingStatus_Result,BookingStatus_FormattedResult>;
  TransactionCurrency_characteristic: WebMappingRetrieve<Characteristic_Select,Characteristic_Expand,Characteristic_Filter,Characteristic_Fixed,Characteristic_Result,Characteristic_FormattedResult>;
  TransactionCurrency_delveactionhub: WebMappingRetrieve<DelveActionHub_Select,DelveActionHub_Expand,DelveActionHub_Filter,DelveActionHub_Fixed,DelveActionHub_Result,DelveActionHub_FormattedResult>;
  TransactionCurrency_entitlementchannel: WebMappingRetrieve<EntitlementChannel_Select,EntitlementChannel_Expand,EntitlementChannel_Filter,EntitlementChannel_Fixed,EntitlementChannel_Result,EntitlementChannel_FormattedResult>;
  TransactionCurrency_entitlementtemplate: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  TransactionCurrency_entitlementtemplatechannel: WebMappingRetrieve<EntitlementTemplateChannel_Select,EntitlementTemplateChannel_Expand,EntitlementTemplateChannel_Filter,EntitlementTemplateChannel_Fixed,EntitlementTemplateChannel_Result,EntitlementTemplateChannel_FormattedResult>;
  TransactionCurrency_externalpartyitem: WebMappingRetrieve<ExternalPartyItem_Select,ExternalPartyItem_Expand,ExternalPartyItem_Filter,ExternalPartyItem_Fixed,ExternalPartyItem_Result,ExternalPartyItem_FormattedResult>;
  TransactionCurrency_officegraphdocument: WebMappingRetrieve<OfficeGraphDocument_Select,OfficeGraphDocument_Expand,OfficeGraphDocument_Filter,OfficeGraphDocument_Fixed,OfficeGraphDocument_Result,OfficeGraphDocument_FormattedResult>;
  TransactionCurrency_profilerule: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  TransactionCurrency_profileruleitem: WebMappingRetrieve<ChannelAccessProfileRuleItem_Select,ChannelAccessProfileRuleItem_Expand,ChannelAccessProfileRuleItem_Filter,ChannelAccessProfileRuleItem_Fixed,ChannelAccessProfileRuleItem_Result,ChannelAccessProfileRuleItem_FormattedResult>;
  TransactionCurrency_ratingmodel: WebMappingRetrieve<RatingModel_Select,RatingModel_Expand,RatingModel_Filter,RatingModel_Fixed,RatingModel_Result,RatingModel_FormattedResult>;
  TransactionCurrency_ratingvalue: WebMappingRetrieve<RatingValue_Select,RatingValue_Expand,RatingValue_Filter,RatingValue_Fixed,RatingValue_Result,RatingValue_FormattedResult>;
  TransactionCurrency_recommendeddocument: WebMappingRetrieve<RecommendedDocument_Select,RecommendedDocument_Expand,RecommendedDocument_Filter,RecommendedDocument_Fixed,RecommendedDocument_Result,RecommendedDocument_FormattedResult>;
  TransactionCurrency_routingruleitem: WebMappingRetrieve<RoutingRuleItem_Select,RoutingRuleItem_Expand,RoutingRuleItem_Filter,RoutingRuleItem_Fixed,RoutingRuleItem_Result,RoutingRuleItem_FormattedResult>;
  TransactionCurrency_slakpiinstance: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  awcnpd_feedback_transactioncurrency_transactioncurrencyid: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  basecurrency_organization: WebMappingRetrieve<Organization_Select,Organization_Expand,Organization_Filter,Organization_Fixed,Organization_Result,Organization_FormattedResult>;
  bulkoperation_transactioncurrency_transactioncurrencyid: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  incidentresolution_transactioncurrency_transactioncurrencyid: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  orderclose_transactioncurrency_transactioncurrencyid: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  quoteclose_transactioncurrency_transactioncurrencyid: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  transactioncurrency_ProductAssociation: WebMappingRetrieve<ProductAssociation_Select,ProductAssociation_Expand,ProductAssociation_Filter,ProductAssociation_Fixed,ProductAssociation_Result,ProductAssociation_FormattedResult>;
  transactioncurrency_ProductSubstitute: WebMappingRetrieve<ProductSubstitute_Select,ProductSubstitute_Expand,ProductSubstitute_Filter,ProductSubstitute_Fixed,ProductSubstitute_Result,ProductSubstitute_FormattedResult>;
  transactioncurrency_SocialProfile: WebMappingRetrieve<SocialProfile_Select,SocialProfile_Expand,SocialProfile_Filter,SocialProfile_Fixed,SocialProfile_Result,SocialProfile_FormattedResult>;
  transactioncurrency_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  transactioncurrency_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  transactioncurrency_annualfiscalcalendar: WebMappingRetrieve<AnnualFiscalCalendar_Select,AnnualFiscalCalendar_Expand,AnnualFiscalCalendar_Filter,AnnualFiscalCalendar_Fixed,AnnualFiscalCalendar_Result,AnnualFiscalCalendar_FormattedResult>;
  transactioncurrency_campaign: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  transactioncurrency_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  transactioncurrency_cardtype: WebMappingRetrieve<CardType_Select,CardType_Expand,CardType_Filter,CardType_Fixed,CardType_Result,CardType_FormattedResult>;
  transactioncurrency_category: WebMappingRetrieve<Category_Select,Category_Expand,Category_Filter,Category_Fixed,Category_Result,Category_FormattedResult>;
  transactioncurrency_channelaccessprofile: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  transactioncurrency_competitor: WebMappingRetrieve<Competitor_Select,Competitor_Expand,Competitor_Filter,Competitor_Fixed,Competitor_Result,Competitor_FormattedResult>;
  transactioncurrency_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  transactioncurrency_contract: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  transactioncurrency_contractdetail: WebMappingRetrieve<ContractDetail_Select,ContractDetail_Expand,ContractDetail_Filter,ContractDetail_Fixed,ContractDetail_Result,ContractDetail_FormattedResult>;
  transactioncurrency_convertruleitem: WebMappingRetrieve<ConvertRuleItem_Select,ConvertRuleItem_Expand,ConvertRuleItem_Filter,ConvertRuleItem_Fixed,ConvertRuleItem_Result,ConvertRuleItem_FormattedResult>;
  transactioncurrency_discount: WebMappingRetrieve<Discount_Select,Discount_Expand,Discount_Filter,Discount_Fixed,Discount_Result,Discount_FormattedResult>;
  transactioncurrency_discounttype: WebMappingRetrieve<DiscountType_Select,DiscountType_Expand,DiscountType_Filter,DiscountType_Fixed,DiscountType_Result,DiscountType_FormattedResult>;
  transactioncurrency_expiredprocess: WebMappingRetrieve<ExpiredProcess_Select,ExpiredProcess_Expand,ExpiredProcess_Filter,ExpiredProcess_Fixed,ExpiredProcess_Result,ExpiredProcess_FormattedResult>;
  transactioncurrency_externalparty: WebMappingRetrieve<ExternalParty_Select,ExternalParty_Expand,ExternalParty_Filter,ExternalParty_Fixed,ExternalParty_Result,ExternalParty_FormattedResult>;
  transactioncurrency_feedback: WebMappingRetrieve<Feedback_Select,Feedback_Expand,Feedback_Filter,Feedback_Fixed,Feedback_Result,Feedback_FormattedResult>;
  transactioncurrency_fixedmonthlyfiscalcalendar: WebMappingRetrieve<FixedMonthlyFiscalCalendar_Select,FixedMonthlyFiscalCalendar_Expand,FixedMonthlyFiscalCalendar_Filter,FixedMonthlyFiscalCalendar_Fixed,FixedMonthlyFiscalCalendar_Result,FixedMonthlyFiscalCalendar_FormattedResult>;
  transactioncurrency_invoice: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  transactioncurrency_invoicedetail: WebMappingRetrieve<InvoiceDetail_Select,InvoiceDetail_Expand,InvoiceDetail_Filter,InvoiceDetail_Fixed,InvoiceDetail_Result,InvoiceDetail_FormattedResult>;
  transactioncurrency_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  transactioncurrency_knowledgearticleincident: WebMappingRetrieve<KnowledgeArticleIncident_Select,KnowledgeArticleIncident_Expand,KnowledgeArticleIncident_Filter,KnowledgeArticleIncident_Fixed,KnowledgeArticleIncident_Result,KnowledgeArticleIncident_FormattedResult>;
  transactioncurrency_knowledgearticleviews: WebMappingRetrieve<KnowledgeArticleViews_Select,KnowledgeArticleViews_Expand,KnowledgeArticleViews_Filter,KnowledgeArticleViews_Fixed,KnowledgeArticleViews_Result,KnowledgeArticleViews_FormattedResult>;
  transactioncurrency_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  transactioncurrency_leadtoopportunitysalesprocess: WebMappingRetrieve<LeadToOpportunitySalesProcess_Select,LeadToOpportunitySalesProcess_Expand,LeadToOpportunitySalesProcess_Filter,LeadToOpportunitySalesProcess_Fixed,LeadToOpportunitySalesProcess_Result,LeadToOpportunitySalesProcess_FormattedResult>;
  transactioncurrency_list: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  transactioncurrency_monthlyfiscalcalendar: WebMappingRetrieve<MonthlyFiscalCalendar_Select,MonthlyFiscalCalendar_Expand,MonthlyFiscalCalendar_Filter,MonthlyFiscalCalendar_Fixed,MonthlyFiscalCalendar_Result,MonthlyFiscalCalendar_FormattedResult>;
  transactioncurrency_newprocess: WebMappingRetrieve<NewProcess_Select,NewProcess_Expand,NewProcess_Filter,NewProcess_Fixed,NewProcess_Result,NewProcess_FormattedResult>;
  transactioncurrency_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  transactioncurrency_opportunityclose: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  transactioncurrency_opportunityproduct: WebMappingRetrieve<OpportunityProduct_Select,OpportunityProduct_Expand,OpportunityProduct_Filter,OpportunityProduct_Fixed,OpportunityProduct_Result,OpportunityProduct_FormattedResult>;
  transactioncurrency_opportunitysalesprocess: WebMappingRetrieve<OpportunitySalesProcess_Select,OpportunitySalesProcess_Expand,OpportunitySalesProcess_Filter,OpportunitySalesProcess_Fixed,OpportunitySalesProcess_Result,OpportunitySalesProcess_FormattedResult>;
  transactioncurrency_phonetocaseprocess: WebMappingRetrieve<PhoneToCaseProcess_Select,PhoneToCaseProcess_Expand,PhoneToCaseProcess_Filter,PhoneToCaseProcess_Fixed,PhoneToCaseProcess_Result,PhoneToCaseProcess_FormattedResult>;
  transactioncurrency_position: WebMappingRetrieve<Position_Select,Position_Expand,Position_Filter,Position_Fixed,Position_Result,Position_FormattedResult>;
  transactioncurrency_pricelevel: WebMappingRetrieve<PriceLevel_Select,PriceLevel_Expand,PriceLevel_Filter,PriceLevel_Fixed,PriceLevel_Result,PriceLevel_FormattedResult>;
  transactioncurrency_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  transactioncurrency_productpricelevel: WebMappingRetrieve<ProductPriceLevel_Select,ProductPriceLevel_Expand,ProductPriceLevel_Filter,ProductPriceLevel_Fixed,ProductPriceLevel_Result,ProductPriceLevel_FormattedResult>;
  transactioncurrency_quarterlyfiscalcalendar: WebMappingRetrieve<QuarterlyFiscalCalendar_Select,QuarterlyFiscalCalendar_Expand,QuarterlyFiscalCalendar_Filter,QuarterlyFiscalCalendar_Fixed,QuarterlyFiscalCalendar_Result,QuarterlyFiscalCalendar_FormattedResult>;
  transactioncurrency_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  transactioncurrency_quotedetail: WebMappingRetrieve<QuoteDetail_Select,QuoteDetail_Expand,QuoteDetail_Filter,QuoteDetail_Fixed,QuoteDetail_Result,QuoteDetail_FormattedResult>;
  transactioncurrency_salesorder: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  transactioncurrency_salesorderdetail: WebMappingRetrieve<SalesOrderDetail_Select,SalesOrderDetail_Expand,SalesOrderDetail_Filter,SalesOrderDetail_Fixed,SalesOrderDetail_Result,SalesOrderDetail_FormattedResult>;
  transactioncurrency_semiannualfiscalcalendar: WebMappingRetrieve<SemiAnnualFiscalCalendar_Select,SemiAnnualFiscalCalendar_Expand,SemiAnnualFiscalCalendar_Filter,SemiAnnualFiscalCalendar_Fixed,SemiAnnualFiscalCalendar_Result,SemiAnnualFiscalCalendar_FormattedResult>;
  transactioncurrency_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  transactioncurrency_suggestioncardtemplate: WebMappingRetrieve<SuggestionCardTemplate_Select,SuggestionCardTemplate_Expand,SuggestionCardTemplate_Filter,SuggestionCardTemplate_Fixed,SuggestionCardTemplate_Result,SuggestionCardTemplate_FormattedResult>;
  transactioncurrency_translationprocess: WebMappingRetrieve<TranslationProcess_Select,TranslationProcess_Expand,TranslationProcess_Filter,TranslationProcess_Fixed,TranslationProcess_Result,TranslationProcess_FormattedResult>;
  transactioncurrency_userfiscalcalendar: WebMappingRetrieve<UserFiscalCalendar_Select,UserFiscalCalendar_Expand,UserFiscalCalendar_Filter,UserFiscalCalendar_Fixed,UserFiscalCalendar_Result,UserFiscalCalendar_FormattedResult>;
  transactioncurrency_usersettings: WebMappingRetrieve<UserSettings_Select,UserSettings_Expand,UserSettings_Filter,UserSettings_Fixed,UserSettings_Result,UserSettings_FormattedResult>;
  userentityinstancedata_transactioncurrency: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  transactioncurrencies: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface WebEntitiesRelated {
  transactioncurrencies: WebMappingRelated<TransactionCurrency_RelatedOne,TransactionCurrency_RelatedMany>;
}
interface WebEntitiesCUDA {
  transactioncurrencies: WebMappingCUDA<TransactionCurrency_Create,TransactionCurrency_Update,TransactionCurrency_Select>;
}
