interface Annotation_Base extends WebEntity {
  annotationid?: string | null;
  createdon?: Date | null;
  documentbody?: string | null;
  filename?: string | null;
  filepointer?: string | null;
  filesize?: number | null;
  importsequencenumber?: number | null;
  isdocument?: boolean | null;
  isprivate?: boolean | null;
  langid?: string | null;
  mimetype?: string | null;
  modifiedon?: Date | null;
  notetext?: string | null;
  objecttypecode?: string | null;
  overriddencreatedon?: Date | null;
  prefix?: string | null;
  stepid?: string | null;
  storagepointer?: string | null;
  subject?: string | null;
  versionnumber?: number | null;
}
interface Annotation_Relationships {
  Annotation_AsyncOperations?: AsyncOperation_Result[] | null;
  Annotation_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Annotation_ProcessSessions?: ProcessSession_Result[] | null;
  Annotation_SyncErrors?: SyncError_Result[] | null;
  channelaccessprofile_annotations?: ChannelAccessProfile_Result | null;
  channelaccessprofileruleid?: ChannelAccessProfileRule_Result | null;
  objectid_account?: Account_Result | null;
  objectid_appointment?: Appointment_Result | null;
  objectid_awc_prototype?: awc_prototype_Result | null;
  objectid_awcnpd_feedback?: awcnpd_feedback_Result | null;
  objectid_awcnpd_idea?: awcnpd_idea_Result | null;
  objectid_awcnpd_prototype?: awcnpd_prototype_Result | null;
  objectid_bookableresource?: BookableResource_Result | null;
  objectid_bookableresourcebooking?: BookableResourceBooking_Result | null;
  objectid_bookableresourcebookingheader?: BookableResourceBookingHeader_Result | null;
  objectid_bookableresourcecategoryassn?: BookableResourceCategoryAssn_Result | null;
  objectid_bookableresourcecharacteristic?: BookableResourceCharacteristic_Result | null;
  objectid_bookableresourcegroup?: BookableResourceGroup_Result | null;
  objectid_bulkoperation?: BulkOperation_Result | null;
  objectid_calendar?: Calendar_Result | null;
  objectid_campaign?: Campaign_Result | null;
  objectid_campaignactivity?: CampaignActivity_Result | null;
  objectid_campaignresponse?: CampaignResponse_Result | null;
  objectid_commitment?: Commitment_Result | null;
  objectid_competitor?: Competitor_Result | null;
  objectid_contact?: Contact_Result | null;
  objectid_contract?: Contract_Result | null;
  objectid_contractdetail?: ContractDetail_Result | null;
  objectid_convertrule?: ConvertRule_Result | null;
  objectid_duplicaterule?: DuplicateRule_Result | null;
  objectid_email?: Email_Result | null;
  objectid_emailserverprofile?: EmailServerProfile_Result | null;
  objectid_entitlement?: Entitlement_Result | null;
  objectid_entitlementchannel?: EntitlementChannel_Result | null;
  objectid_entitlementtemplate?: EntitlementTemplate_Result | null;
  objectid_equipment?: Equipment_Result | null;
  objectid_fax?: Fax_Result | null;
  objectid_goal?: Goal_Result | null;
  objectid_incident?: Incident_Result | null;
  objectid_incidentresolution?: IncidentResolution_Result | null;
  objectid_invoice?: Invoice_Result | null;
  objectid_kbarticle?: KbArticle_Result | null;
  objectid_knowledgearticle?: KnowledgeArticle_Result | null;
  objectid_knowledgebaserecord?: KnowledgeBaseRecord_Result | null;
  objectid_lead?: Lead_Result | null;
  objectid_letter?: Letter_Result | null;
  objectid_list?: List_Result | null;
  objectid_mailbox?: Mailbox_Result | null;
  objectid_msdyn_aifptrainingdocument?: msdyn_AIFpTrainingDocument_Result | null;
  objectid_msdyn_aimodel?: msdyn_AIModel_Result | null;
  objectid_msdyn_aiodimage?: msdyn_AIOdImage_Result | null;
  objectid_msdyn_playbookinstance?: msdyn_playbookinstance_Result | null;
  objectid_msdyn_playbooktemplate?: msdyn_playbooktemplate_Result | null;
  objectid_msdyn_postalbum?: msdyn_PostAlbum_Result | null;
  objectid_msdyn_solutioncomponentdatasource?: msdyn_solutioncomponentdatasource_Result | null;
  objectid_opportunity?: Opportunity_Result | null;
  objectid_opportunityclose?: OpportunityClose_Result | null;
  objectid_orderclose?: OrderClose_Result | null;
  objectid_phonecall?: PhoneCall_Result | null;
  objectid_product?: Product_Result | null;
  objectid_profileruleitem?: ChannelAccessProfileRuleItem_Result | null;
  objectid_quote?: Quote_Result | null;
  objectid_quoteclose?: QuoteClose_Result | null;
  objectid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  objectid_resourcespec?: ResourceSpec_Result | null;
  objectid_routingrule?: RoutingRule_Result | null;
  objectid_routingruleitem?: RoutingRuleItem_Result | null;
  objectid_salesorder?: SalesOrder_Result | null;
  objectid_service?: Service_Result | null;
  objectid_serviceappointment?: ServiceAppointment_Result | null;
  objectid_sharepointdocument?: SharePointDocument_Result | null;
  objectid_sla?: SLA_Result | null;
  objectid_socialactivity?: SocialActivity_Result | null;
  objectid_task?: Task_Result | null;
  objectid_workflow?: Workflow_Result | null;
  userentityinstancedata_annotation?: UserEntityInstanceData_Result[] | null;
}
interface Annotation extends Annotation_Base, Annotation_Relationships {
  channelaccessprofile_annotations_bind$channelaccessprofiles?: string | null;
  channelaccessprofileruleid_bind$channelaccessprofilerules?: string | null;
  objectid_account_bind$accounts?: string | null;
  objectid_appointment_bind$appointments?: string | null;
  objectid_awc_prototype_bind$awc_prototypes?: string | null;
  objectid_awcnpd_feedback_bind$awcnpd_feedbacks?: string | null;
  objectid_awcnpd_idea_bind$awcnpd_ideas?: string | null;
  objectid_awcnpd_prototype_bind$awcnpd_prototypes?: string | null;
  objectid_bookableresource_bind$bookableresources?: string | null;
  objectid_bookableresourcebooking_bind$bookableresourcebookings?: string | null;
  objectid_bookableresourcebookingheader_bind$bookableresourcebookingheaders?: string | null;
  objectid_bookableresourcecategoryassn_bind$bookableresourcecategoryassns?: string | null;
  objectid_bookableresourcecharacteristic_bind$bookableresourcecharacteristics?: string | null;
  objectid_bookableresourcegroup_bind$bookableresourcegroups?: string | null;
  objectid_bulkoperation_bind$bulkoperations?: string | null;
  objectid_calendar_bind$calendars?: string | null;
  objectid_campaign_bind$campaigns?: string | null;
  objectid_campaignactivity_bind$campaignactivities?: string | null;
  objectid_campaignresponse_bind$campaignresponses?: string | null;
  objectid_commitment_bind$commitments?: string | null;
  objectid_competitor_bind$competitors?: string | null;
  objectid_contact_bind$contacts?: string | null;
  objectid_contract_bind$contracts?: string | null;
  objectid_contractdetail_bind$contractdetails?: string | null;
  objectid_convertrule_bind$convertrules?: string | null;
  objectid_duplicaterule_bind$duplicaterules?: string | null;
  objectid_email_bind$emails?: string | null;
  objectid_emailserverprofile_bind$emailserverprofiles?: string | null;
  objectid_entitlement_bind$entitlements?: string | null;
  objectid_entitlementchannel_bind$entitlementchannels?: string | null;
  objectid_entitlementtemplate_bind$entitlementtemplates?: string | null;
  objectid_equipment_bind$equipments?: string | null;
  objectid_fax_bind$faxes?: string | null;
  objectid_goal_bind$goals?: string | null;
  objectid_incident_bind$incidents?: string | null;
  objectid_incidentresolution_bind$incidentresolutions?: string | null;
  objectid_invoice_bind$invoices?: string | null;
  objectid_kbarticle_bind$kbarticles?: string | null;
  objectid_knowledgearticle_bind$knowledgearticles?: string | null;
  objectid_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
  objectid_lead_bind$leads?: string | null;
  objectid_letter_bind$letters?: string | null;
  objectid_list_bind$lists?: string | null;
  objectid_mailbox_bind$mailboxes?: string | null;
  objectid_msdyn_aifptrainingdocument_bind$msdyn_aifptrainingdocuments?: string | null;
  objectid_msdyn_aimodel_bind$msdyn_aimodels?: string | null;
  objectid_msdyn_aiodimage_bind$msdyn_aiodimages?: string | null;
  objectid_msdyn_playbookinstance_bind$msdyn_playbookinstances?: string | null;
  objectid_msdyn_playbooktemplate_bind$msdyn_playbooktemplates?: string | null;
  objectid_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
  objectid_msdyn_solutioncomponentdatasource_bind$msdyn_solutioncomponentdatasources?: string | null;
  objectid_opportunity_bind$opportunities?: string | null;
  objectid_opportunityclose_bind$opportunitycloses?: string | null;
  objectid_orderclose_bind$ordercloses?: string | null;
  objectid_phonecall_bind$phonecalls?: string | null;
  objectid_product_bind$products?: string | null;
  objectid_profileruleitem_bind$channelaccessprofileruleitems?: string | null;
  objectid_quote_bind$quotes?: string | null;
  objectid_quoteclose_bind$quotecloses?: string | null;
  objectid_recurringappointmentmaster_bind$recurringappointmentmasters?: string | null;
  objectid_resourcespec_bind$resourcespecs?: string | null;
  objectid_routingrule_bind$routingrules?: string | null;
  objectid_routingruleitem_bind$routingruleitems?: string | null;
  objectid_salesorder_bind$salesorders?: string | null;
  objectid_service_bind$services?: string | null;
  objectid_serviceappointment_bind$serviceappointments?: string | null;
  objectid_sharepointdocument_bind$sharepointdocuments?: string | null;
  objectid_sla_bind$slas?: string | null;
  objectid_socialactivity_bind$socialactivities?: string | null;
  objectid_task_bind$tasks?: string | null;
  objectid_workflow_bind$workflows?: string | null;
  ownerid_bind$systemusers?: string | null;
  ownerid_bind$teams?: string | null;
}
interface Annotation_Create extends Annotation {
}
interface Annotation_Update extends Annotation {
}
interface Annotation_Select {
  annotationid: WebAttribute<Annotation_Select, { annotationid: string | null }, {  }>;
  createdby_guid: WebAttribute<Annotation_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Annotation_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Annotation_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  documentbody: WebAttribute<Annotation_Select, { documentbody: string | null }, {  }>;
  filename: WebAttribute<Annotation_Select, { filename: string | null }, {  }>;
  filepointer: WebAttribute<Annotation_Select, { filepointer: string | null }, {  }>;
  filesize: WebAttribute<Annotation_Select, { filesize: number | null }, {  }>;
  importsequencenumber: WebAttribute<Annotation_Select, { importsequencenumber: number | null }, {  }>;
  isdocument: WebAttribute<Annotation_Select, { isdocument: boolean | null }, {  }>;
  isprivate: WebAttribute<Annotation_Select, { isprivate: boolean | null }, {  }>;
  langid: WebAttribute<Annotation_Select, { langid: string | null }, {  }>;
  mimetype: WebAttribute<Annotation_Select, { mimetype: string | null }, {  }>;
  modifiedby_guid: WebAttribute<Annotation_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Annotation_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Annotation_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  notetext: WebAttribute<Annotation_Select, { notetext: string | null }, {  }>;
  objectid_guid: WebAttribute<Annotation_Select, { objectid_guid: string | null }, { objectid_formatted?: string }>;
  objecttypecode: WebAttribute<Annotation_Select, { objecttypecode: string | null }, {  }>;
  overriddencreatedon: WebAttribute<Annotation_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Annotation_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Annotation_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Annotation_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Annotation_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  prefix: WebAttribute<Annotation_Select, { prefix: string | null }, {  }>;
  stepid: WebAttribute<Annotation_Select, { stepid: string | null }, {  }>;
  storagepointer: WebAttribute<Annotation_Select, { storagepointer: string | null }, {  }>;
  subject: WebAttribute<Annotation_Select, { subject: string | null }, {  }>;
  versionnumber: WebAttribute<Annotation_Select, { versionnumber: number | null }, {  }>;
}
interface Annotation_Filter {
  annotationid: XQW.Guid;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  documentbody: string;
  filename: string;
  filepointer: string;
  filesize: number;
  importsequencenumber: number;
  isdocument: boolean;
  isprivate: boolean;
  langid: string;
  mimetype: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  notetext: string;
  objectid_guid: XQW.Guid;
  objecttypecode: string;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  prefix: string;
  stepid: string;
  storagepointer: string;
  subject: string;
  versionnumber: number;
}
interface Annotation_Expand {
  Annotation_AsyncOperations: WebExpand<Annotation_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Annotation_AsyncOperations: AsyncOperation_Result[] }>;
  Annotation_BulkDeleteFailures: WebExpand<Annotation_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Annotation_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Annotation_ProcessSessions: WebExpand<Annotation_Expand, ProcessSession_Select, ProcessSession_Filter, { Annotation_ProcessSessions: ProcessSession_Result[] }>;
  Annotation_SyncErrors: WebExpand<Annotation_Expand, SyncError_Select, SyncError_Filter, { Annotation_SyncErrors: SyncError_Result[] }>;
  channelaccessprofile_annotations: WebExpand<Annotation_Expand, ChannelAccessProfile_Select, ChannelAccessProfile_Filter, { channelaccessprofile_annotations: ChannelAccessProfile_Result }>;
  channelaccessprofileruleid: WebExpand<Annotation_Expand, ChannelAccessProfileRule_Select, ChannelAccessProfileRule_Filter, { channelaccessprofileruleid: ChannelAccessProfileRule_Result }>;
  createdby: WebExpand<Annotation_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
  createdonbehalfby: WebExpand<Annotation_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
  modifiedby: WebExpand<Annotation_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
  modifiedonbehalfby: WebExpand<Annotation_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
  objectid_account: WebExpand<Annotation_Expand, Account_Select, Account_Filter, { objectid_account: Account_Result }>;
  objectid_appointment: WebExpand<Annotation_Expand, Appointment_Select, Appointment_Filter, { objectid_appointment: Appointment_Result }>;
  objectid_awc_prototype: WebExpand<Annotation_Expand, awc_prototype_Select, awc_prototype_Filter, { objectid_awc_prototype: awc_prototype_Result }>;
  objectid_awcnpd_feedback: WebExpand<Annotation_Expand, awcnpd_feedback_Select, awcnpd_feedback_Filter, { objectid_awcnpd_feedback: awcnpd_feedback_Result }>;
  objectid_awcnpd_idea: WebExpand<Annotation_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { objectid_awcnpd_idea: awcnpd_idea_Result }>;
  objectid_awcnpd_prototype: WebExpand<Annotation_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { objectid_awcnpd_prototype: awcnpd_prototype_Result }>;
  objectid_bookableresource: WebExpand<Annotation_Expand, BookableResource_Select, BookableResource_Filter, { objectid_bookableresource: BookableResource_Result }>;
  objectid_bookableresourcebooking: WebExpand<Annotation_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { objectid_bookableresourcebooking: BookableResourceBooking_Result }>;
  objectid_bookableresourcebookingheader: WebExpand<Annotation_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { objectid_bookableresourcebookingheader: BookableResourceBookingHeader_Result }>;
  objectid_bookableresourcecategoryassn: WebExpand<Annotation_Expand, BookableResourceCategoryAssn_Select, BookableResourceCategoryAssn_Filter, { objectid_bookableresourcecategoryassn: BookableResourceCategoryAssn_Result }>;
  objectid_bookableresourcecharacteristic: WebExpand<Annotation_Expand, BookableResourceCharacteristic_Select, BookableResourceCharacteristic_Filter, { objectid_bookableresourcecharacteristic: BookableResourceCharacteristic_Result }>;
  objectid_bookableresourcegroup: WebExpand<Annotation_Expand, BookableResourceGroup_Select, BookableResourceGroup_Filter, { objectid_bookableresourcegroup: BookableResourceGroup_Result }>;
  objectid_bulkoperation: WebExpand<Annotation_Expand, BulkOperation_Select, BulkOperation_Filter, { objectid_bulkoperation: BulkOperation_Result }>;
  objectid_calendar: WebExpand<Annotation_Expand, Calendar_Select, Calendar_Filter, { objectid_calendar: Calendar_Result }>;
  objectid_campaign: WebExpand<Annotation_Expand, Campaign_Select, Campaign_Filter, { objectid_campaign: Campaign_Result }>;
  objectid_campaignactivity: WebExpand<Annotation_Expand, CampaignActivity_Select, CampaignActivity_Filter, { objectid_campaignactivity: CampaignActivity_Result }>;
  objectid_campaignresponse: WebExpand<Annotation_Expand, CampaignResponse_Select, CampaignResponse_Filter, { objectid_campaignresponse: CampaignResponse_Result }>;
  objectid_commitment: WebExpand<Annotation_Expand, Commitment_Select, Commitment_Filter, { objectid_commitment: Commitment_Result }>;
  objectid_competitor: WebExpand<Annotation_Expand, Competitor_Select, Competitor_Filter, { objectid_competitor: Competitor_Result }>;
  objectid_contact: WebExpand<Annotation_Expand, Contact_Select, Contact_Filter, { objectid_contact: Contact_Result }>;
  objectid_contract: WebExpand<Annotation_Expand, Contract_Select, Contract_Filter, { objectid_contract: Contract_Result }>;
  objectid_contractdetail: WebExpand<Annotation_Expand, ContractDetail_Select, ContractDetail_Filter, { objectid_contractdetail: ContractDetail_Result }>;
  objectid_convertrule: WebExpand<Annotation_Expand, ConvertRule_Select, ConvertRule_Filter, { objectid_convertrule: ConvertRule_Result }>;
  objectid_duplicaterule: WebExpand<Annotation_Expand, DuplicateRule_Select, DuplicateRule_Filter, { objectid_duplicaterule: DuplicateRule_Result }>;
  objectid_email: WebExpand<Annotation_Expand, Email_Select, Email_Filter, { objectid_email: Email_Result }>;
  objectid_emailserverprofile: WebExpand<Annotation_Expand, EmailServerProfile_Select, EmailServerProfile_Filter, { objectid_emailserverprofile: EmailServerProfile_Result }>;
  objectid_entitlement: WebExpand<Annotation_Expand, Entitlement_Select, Entitlement_Filter, { objectid_entitlement: Entitlement_Result }>;
  objectid_entitlementchannel: WebExpand<Annotation_Expand, EntitlementChannel_Select, EntitlementChannel_Filter, { objectid_entitlementchannel: EntitlementChannel_Result }>;
  objectid_entitlementtemplate: WebExpand<Annotation_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { objectid_entitlementtemplate: EntitlementTemplate_Result }>;
  objectid_equipment: WebExpand<Annotation_Expand, Equipment_Select, Equipment_Filter, { objectid_equipment: Equipment_Result }>;
  objectid_fax: WebExpand<Annotation_Expand, Fax_Select, Fax_Filter, { objectid_fax: Fax_Result }>;
  objectid_goal: WebExpand<Annotation_Expand, Goal_Select, Goal_Filter, { objectid_goal: Goal_Result }>;
  objectid_incident: WebExpand<Annotation_Expand, Incident_Select, Incident_Filter, { objectid_incident: Incident_Result }>;
  objectid_incidentresolution: WebExpand<Annotation_Expand, IncidentResolution_Select, IncidentResolution_Filter, { objectid_incidentresolution: IncidentResolution_Result }>;
  objectid_invoice: WebExpand<Annotation_Expand, Invoice_Select, Invoice_Filter, { objectid_invoice: Invoice_Result }>;
  objectid_kbarticle: WebExpand<Annotation_Expand, KbArticle_Select, KbArticle_Filter, { objectid_kbarticle: KbArticle_Result }>;
  objectid_knowledgearticle: WebExpand<Annotation_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { objectid_knowledgearticle: KnowledgeArticle_Result }>;
  objectid_knowledgebaserecord: WebExpand<Annotation_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { objectid_knowledgebaserecord: KnowledgeBaseRecord_Result }>;
  objectid_lead: WebExpand<Annotation_Expand, Lead_Select, Lead_Filter, { objectid_lead: Lead_Result }>;
  objectid_letter: WebExpand<Annotation_Expand, Letter_Select, Letter_Filter, { objectid_letter: Letter_Result }>;
  objectid_list: WebExpand<Annotation_Expand, List_Select, List_Filter, { objectid_list: List_Result }>;
  objectid_mailbox: WebExpand<Annotation_Expand, Mailbox_Select, Mailbox_Filter, { objectid_mailbox: Mailbox_Result }>;
  objectid_msdyn_aifptrainingdocument: WebExpand<Annotation_Expand, msdyn_AIFpTrainingDocument_Select, msdyn_AIFpTrainingDocument_Filter, { objectid_msdyn_aifptrainingdocument: msdyn_AIFpTrainingDocument_Result }>;
  objectid_msdyn_aimodel: WebExpand<Annotation_Expand, msdyn_AIModel_Select, msdyn_AIModel_Filter, { objectid_msdyn_aimodel: msdyn_AIModel_Result }>;
  objectid_msdyn_aiodimage: WebExpand<Annotation_Expand, msdyn_AIOdImage_Select, msdyn_AIOdImage_Filter, { objectid_msdyn_aiodimage: msdyn_AIOdImage_Result }>;
  objectid_msdyn_playbookinstance: WebExpand<Annotation_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { objectid_msdyn_playbookinstance: msdyn_playbookinstance_Result }>;
  objectid_msdyn_playbooktemplate: WebExpand<Annotation_Expand, msdyn_playbooktemplate_Select, msdyn_playbooktemplate_Filter, { objectid_msdyn_playbooktemplate: msdyn_playbooktemplate_Result }>;
  objectid_msdyn_postalbum: WebExpand<Annotation_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { objectid_msdyn_postalbum: msdyn_PostAlbum_Result }>;
  objectid_msdyn_solutioncomponentdatasource: WebExpand<Annotation_Expand, msdyn_solutioncomponentdatasource_Select, msdyn_solutioncomponentdatasource_Filter, { objectid_msdyn_solutioncomponentdatasource: msdyn_solutioncomponentdatasource_Result }>;
  objectid_opportunity: WebExpand<Annotation_Expand, Opportunity_Select, Opportunity_Filter, { objectid_opportunity: Opportunity_Result }>;
  objectid_opportunityclose: WebExpand<Annotation_Expand, OpportunityClose_Select, OpportunityClose_Filter, { objectid_opportunityclose: OpportunityClose_Result }>;
  objectid_orderclose: WebExpand<Annotation_Expand, OrderClose_Select, OrderClose_Filter, { objectid_orderclose: OrderClose_Result }>;
  objectid_phonecall: WebExpand<Annotation_Expand, PhoneCall_Select, PhoneCall_Filter, { objectid_phonecall: PhoneCall_Result }>;
  objectid_product: WebExpand<Annotation_Expand, Product_Select, Product_Filter, { objectid_product: Product_Result }>;
  objectid_profileruleitem: WebExpand<Annotation_Expand, ChannelAccessProfileRuleItem_Select, ChannelAccessProfileRuleItem_Filter, { objectid_profileruleitem: ChannelAccessProfileRuleItem_Result }>;
  objectid_quote: WebExpand<Annotation_Expand, Quote_Select, Quote_Filter, { objectid_quote: Quote_Result }>;
  objectid_quoteclose: WebExpand<Annotation_Expand, QuoteClose_Select, QuoteClose_Filter, { objectid_quoteclose: QuoteClose_Result }>;
  objectid_recurringappointmentmaster: WebExpand<Annotation_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { objectid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  objectid_resourcespec: WebExpand<Annotation_Expand, ResourceSpec_Select, ResourceSpec_Filter, { objectid_resourcespec: ResourceSpec_Result }>;
  objectid_routingrule: WebExpand<Annotation_Expand, RoutingRule_Select, RoutingRule_Filter, { objectid_routingrule: RoutingRule_Result }>;
  objectid_routingruleitem: WebExpand<Annotation_Expand, RoutingRuleItem_Select, RoutingRuleItem_Filter, { objectid_routingruleitem: RoutingRuleItem_Result }>;
  objectid_salesorder: WebExpand<Annotation_Expand, SalesOrder_Select, SalesOrder_Filter, { objectid_salesorder: SalesOrder_Result }>;
  objectid_service: WebExpand<Annotation_Expand, Service_Select, Service_Filter, { objectid_service: Service_Result }>;
  objectid_serviceappointment: WebExpand<Annotation_Expand, ServiceAppointment_Select, ServiceAppointment_Filter, { objectid_serviceappointment: ServiceAppointment_Result }>;
  objectid_sharepointdocument: WebExpand<Annotation_Expand, SharePointDocument_Select, SharePointDocument_Filter, { objectid_sharepointdocument: SharePointDocument_Result }>;
  objectid_sla: WebExpand<Annotation_Expand, SLA_Select, SLA_Filter, { objectid_sla: SLA_Result }>;
  objectid_socialactivity: WebExpand<Annotation_Expand, SocialActivity_Select, SocialActivity_Filter, { objectid_socialactivity: SocialActivity_Result }>;
  objectid_task: WebExpand<Annotation_Expand, Task_Select, Task_Filter, { objectid_task: Task_Result }>;
  objectid_workflow: WebExpand<Annotation_Expand, Workflow_Select, Workflow_Filter, { objectid_workflow: Workflow_Result }>;
  ownerid: WebExpand<Annotation_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid: SystemUser_Result } & { ownerid: Team_Result }>;
  owningbusinessunit: WebExpand<Annotation_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit: BusinessUnit_Result }>;
  owningteam: WebExpand<Annotation_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
  owninguser: WebExpand<Annotation_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  userentityinstancedata_annotation: WebExpand<Annotation_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_annotation: UserEntityInstanceData_Result[] }>;
}
interface Annotation_FormattedResult {
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  objectid_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
}
interface Annotation_Result extends Annotation_Base, Annotation_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  objectid_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
}
interface Annotation_RelatedOne {
  channelaccessprofile_annotations: WebMappingRetrieve<ChannelAccessProfile_Select,ChannelAccessProfile_Expand,ChannelAccessProfile_Filter,ChannelAccessProfile_Fixed,ChannelAccessProfile_Result,ChannelAccessProfile_FormattedResult>;
  channelaccessprofileruleid: WebMappingRetrieve<ChannelAccessProfileRule_Select,ChannelAccessProfileRule_Expand,ChannelAccessProfileRule_Filter,ChannelAccessProfileRule_Fixed,ChannelAccessProfileRule_Result,ChannelAccessProfileRule_FormattedResult>;
  createdby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  objectid_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  objectid_appointment: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
  objectid_awc_prototype: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  objectid_awcnpd_feedback: WebMappingRetrieve<awcnpd_feedback_Select,awcnpd_feedback_Expand,awcnpd_feedback_Filter,awcnpd_feedback_Fixed,awcnpd_feedback_Result,awcnpd_feedback_FormattedResult>;
  objectid_awcnpd_idea: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  objectid_awcnpd_prototype: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  objectid_bookableresource: WebMappingRetrieve<BookableResource_Select,BookableResource_Expand,BookableResource_Filter,BookableResource_Fixed,BookableResource_Result,BookableResource_FormattedResult>;
  objectid_bookableresourcebooking: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  objectid_bookableresourcebookingheader: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  objectid_bookableresourcecategoryassn: WebMappingRetrieve<BookableResourceCategoryAssn_Select,BookableResourceCategoryAssn_Expand,BookableResourceCategoryAssn_Filter,BookableResourceCategoryAssn_Fixed,BookableResourceCategoryAssn_Result,BookableResourceCategoryAssn_FormattedResult>;
  objectid_bookableresourcecharacteristic: WebMappingRetrieve<BookableResourceCharacteristic_Select,BookableResourceCharacteristic_Expand,BookableResourceCharacteristic_Filter,BookableResourceCharacteristic_Fixed,BookableResourceCharacteristic_Result,BookableResourceCharacteristic_FormattedResult>;
  objectid_bookableresourcegroup: WebMappingRetrieve<BookableResourceGroup_Select,BookableResourceGroup_Expand,BookableResourceGroup_Filter,BookableResourceGroup_Fixed,BookableResourceGroup_Result,BookableResourceGroup_FormattedResult>;
  objectid_bulkoperation: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  objectid_calendar: WebMappingRetrieve<Calendar_Select,Calendar_Expand,Calendar_Filter,Calendar_Fixed,Calendar_Result,Calendar_FormattedResult>;
  objectid_campaign: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  objectid_campaignactivity: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  objectid_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  objectid_commitment: WebMappingRetrieve<Commitment_Select,Commitment_Expand,Commitment_Filter,Commitment_Fixed,Commitment_Result,Commitment_FormattedResult>;
  objectid_competitor: WebMappingRetrieve<Competitor_Select,Competitor_Expand,Competitor_Filter,Competitor_Fixed,Competitor_Result,Competitor_FormattedResult>;
  objectid_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  objectid_contract: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  objectid_contractdetail: WebMappingRetrieve<ContractDetail_Select,ContractDetail_Expand,ContractDetail_Filter,ContractDetail_Fixed,ContractDetail_Result,ContractDetail_FormattedResult>;
  objectid_convertrule: WebMappingRetrieve<ConvertRule_Select,ConvertRule_Expand,ConvertRule_Filter,ConvertRule_Fixed,ConvertRule_Result,ConvertRule_FormattedResult>;
  objectid_duplicaterule: WebMappingRetrieve<DuplicateRule_Select,DuplicateRule_Expand,DuplicateRule_Filter,DuplicateRule_Fixed,DuplicateRule_Result,DuplicateRule_FormattedResult>;
  objectid_email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  objectid_emailserverprofile: WebMappingRetrieve<EmailServerProfile_Select,EmailServerProfile_Expand,EmailServerProfile_Filter,EmailServerProfile_Fixed,EmailServerProfile_Result,EmailServerProfile_FormattedResult>;
  objectid_entitlement: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  objectid_entitlementchannel: WebMappingRetrieve<EntitlementChannel_Select,EntitlementChannel_Expand,EntitlementChannel_Filter,EntitlementChannel_Fixed,EntitlementChannel_Result,EntitlementChannel_FormattedResult>;
  objectid_entitlementtemplate: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  objectid_equipment: WebMappingRetrieve<Equipment_Select,Equipment_Expand,Equipment_Filter,Equipment_Fixed,Equipment_Result,Equipment_FormattedResult>;
  objectid_fax: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
  objectid_goal: WebMappingRetrieve<Goal_Select,Goal_Expand,Goal_Filter,Goal_Fixed,Goal_Result,Goal_FormattedResult>;
  objectid_incident: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  objectid_incidentresolution: WebMappingRetrieve<IncidentResolution_Select,IncidentResolution_Expand,IncidentResolution_Filter,IncidentResolution_Fixed,IncidentResolution_Result,IncidentResolution_FormattedResult>;
  objectid_invoice: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  objectid_kbarticle: WebMappingRetrieve<KbArticle_Select,KbArticle_Expand,KbArticle_Filter,KbArticle_Fixed,KbArticle_Result,KbArticle_FormattedResult>;
  objectid_knowledgearticle: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  objectid_knowledgebaserecord: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  objectid_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  objectid_letter: WebMappingRetrieve<Letter_Select,Letter_Expand,Letter_Filter,Letter_Fixed,Letter_Result,Letter_FormattedResult>;
  objectid_list: WebMappingRetrieve<List_Select,List_Expand,List_Filter,List_Fixed,List_Result,List_FormattedResult>;
  objectid_mailbox: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  objectid_msdyn_aifptrainingdocument: WebMappingRetrieve<msdyn_AIFpTrainingDocument_Select,msdyn_AIFpTrainingDocument_Expand,msdyn_AIFpTrainingDocument_Filter,msdyn_AIFpTrainingDocument_Fixed,msdyn_AIFpTrainingDocument_Result,msdyn_AIFpTrainingDocument_FormattedResult>;
  objectid_msdyn_aimodel: WebMappingRetrieve<msdyn_AIModel_Select,msdyn_AIModel_Expand,msdyn_AIModel_Filter,msdyn_AIModel_Fixed,msdyn_AIModel_Result,msdyn_AIModel_FormattedResult>;
  objectid_msdyn_aiodimage: WebMappingRetrieve<msdyn_AIOdImage_Select,msdyn_AIOdImage_Expand,msdyn_AIOdImage_Filter,msdyn_AIOdImage_Fixed,msdyn_AIOdImage_Result,msdyn_AIOdImage_FormattedResult>;
  objectid_msdyn_playbookinstance: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  objectid_msdyn_playbooktemplate: WebMappingRetrieve<msdyn_playbooktemplate_Select,msdyn_playbooktemplate_Expand,msdyn_playbooktemplate_Filter,msdyn_playbooktemplate_Fixed,msdyn_playbooktemplate_Result,msdyn_playbooktemplate_FormattedResult>;
  objectid_msdyn_postalbum: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  objectid_msdyn_solutioncomponentdatasource: WebMappingRetrieve<msdyn_solutioncomponentdatasource_Select,msdyn_solutioncomponentdatasource_Expand,msdyn_solutioncomponentdatasource_Filter,msdyn_solutioncomponentdatasource_Fixed,msdyn_solutioncomponentdatasource_Result,msdyn_solutioncomponentdatasource_FormattedResult>;
  objectid_opportunity: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  objectid_opportunityclose: WebMappingRetrieve<OpportunityClose_Select,OpportunityClose_Expand,OpportunityClose_Filter,OpportunityClose_Fixed,OpportunityClose_Result,OpportunityClose_FormattedResult>;
  objectid_orderclose: WebMappingRetrieve<OrderClose_Select,OrderClose_Expand,OrderClose_Filter,OrderClose_Fixed,OrderClose_Result,OrderClose_FormattedResult>;
  objectid_phonecall: WebMappingRetrieve<PhoneCall_Select,PhoneCall_Expand,PhoneCall_Filter,PhoneCall_Fixed,PhoneCall_Result,PhoneCall_FormattedResult>;
  objectid_product: WebMappingRetrieve<Product_Select,Product_Expand,Product_Filter,Product_Fixed,Product_Result,Product_FormattedResult>;
  objectid_profileruleitem: WebMappingRetrieve<ChannelAccessProfileRuleItem_Select,ChannelAccessProfileRuleItem_Expand,ChannelAccessProfileRuleItem_Filter,ChannelAccessProfileRuleItem_Fixed,ChannelAccessProfileRuleItem_Result,ChannelAccessProfileRuleItem_FormattedResult>;
  objectid_quote: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  objectid_quoteclose: WebMappingRetrieve<QuoteClose_Select,QuoteClose_Expand,QuoteClose_Filter,QuoteClose_Fixed,QuoteClose_Result,QuoteClose_FormattedResult>;
  objectid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  objectid_resourcespec: WebMappingRetrieve<ResourceSpec_Select,ResourceSpec_Expand,ResourceSpec_Filter,ResourceSpec_Fixed,ResourceSpec_Result,ResourceSpec_FormattedResult>;
  objectid_routingrule: WebMappingRetrieve<RoutingRule_Select,RoutingRule_Expand,RoutingRule_Filter,RoutingRule_Fixed,RoutingRule_Result,RoutingRule_FormattedResult>;
  objectid_routingruleitem: WebMappingRetrieve<RoutingRuleItem_Select,RoutingRuleItem_Expand,RoutingRuleItem_Filter,RoutingRuleItem_Fixed,RoutingRuleItem_Result,RoutingRuleItem_FormattedResult>;
  objectid_salesorder: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  objectid_service: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  objectid_serviceappointment: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
  objectid_sharepointdocument: WebMappingRetrieve<SharePointDocument_Select,SharePointDocument_Expand,SharePointDocument_Filter,SharePointDocument_Fixed,SharePointDocument_Result,SharePointDocument_FormattedResult>;
  objectid_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  objectid_socialactivity: WebMappingRetrieve<SocialActivity_Select,SocialActivity_Expand,SocialActivity_Filter,SocialActivity_Fixed,SocialActivity_Result,SocialActivity_FormattedResult>;
  objectid_task: WebMappingRetrieve<Task_Select,Task_Expand,Task_Filter,Task_Fixed,Task_Result,Task_FormattedResult>;
  objectid_workflow: WebMappingRetrieve<Workflow_Select,Workflow_Expand,Workflow_Filter,Workflow_Fixed,Workflow_Result,Workflow_FormattedResult>;
  ownerid: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult> & WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owningbusinessunit: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
}
interface Annotation_RelatedMany {
  Annotation_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Annotation_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Annotation_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Annotation_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  userentityinstancedata_annotation: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  annotations: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
}
interface WebEntitiesRelated {
  annotations: WebMappingRelated<Annotation_RelatedOne,Annotation_RelatedMany>;
}
interface WebEntitiesCUDA {
  annotations: WebMappingCUDA<Annotation_Create,Annotation_Update,Annotation_Select>;
}
