interface Appointment_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  attachmentcount?: number | null;
  attachmenterrors?: appointment_attachmenterrors | null;
  category?: string | null;
  createdon?: Date | null;
  description?: string | null;
  exchangerate?: number | null;
  globalobjectid?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: appointment_instancetypecode | null;
  isalldayevent?: boolean | null;
  isbilled?: boolean | null;
  isdraft?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isunsafe?: number | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  location?: string | null;
  modifiedfieldsmask?: string | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  originalstartdate?: Date | null;
  outlookownerapptid?: number | null;
  overriddencreatedon?: Date | null;
  prioritycode?: appointment_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: appointment_statecode | null;
  statuscode?: appointment_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Appointment_Relationships {
  Appointment_Annotation?: Annotation_Result[] | null;
  Appointment_AsyncOperations?: AsyncOperation_Result[] | null;
  Appointment_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Appointment_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Appointment_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Appointment_ProcessSessions?: ProcessSession_Result[] | null;
  Appointment_QueueItem?: QueueItem_Result[] | null;
  Appointment_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  appointment_PostFollows?: PostFollow_Result[] | null;
  appointment_PostRegardings?: PostRegarding_Result[] | null;
  appointment_PostRoles?: PostRole_Result[] | null;
  appointment_actioncard?: ActionCard_Result[] | null;
  appointment_activity_mime_attachment?: ActivityMimeAttachment_Result[] | null;
  appointment_activity_parties?: ActivityParty_Result[] | null;
  appointment_campaignresponse?: CampaignResponse_Result[] | null;
  appointment_connections1?: Connection_Result[] | null;
  appointment_connections2?: Connection_Result[] | null;
  appointment_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  createdby_appointment?: SystemUser_Result | null;
  createdonbehalfby_appointment?: SystemUser_Result | null;
  modifiedby_appointment?: SystemUser_Result | null;
  modifiedonbehalfby_appointment?: SystemUser_Result | null;
  ownerid_appointment?: Team_Result | null;
  ownerid_appointment1?: SystemUser_Result | null;
  owningbusinessunit_appointment?: BusinessUnit_Result | null;
  owningteam_appointment?: Team_Result | null;
  owninguser_appointment?: SystemUser_Result | null;
  regardingobjectid_account_appointment?: Account_Result | null;
  regardingobjectid_awc_prototype_appointment?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_appointment?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_appointment?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_appointment?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_appointment?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_appointment?: BulkOperation_Result | null;
  regardingobjectid_campaign_appointment?: Campaign_Result | null;
  regardingobjectid_campaignactivity_appointment?: CampaignActivity_Result | null;
  regardingobjectid_contact_appointment?: Contact_Result | null;
  regardingobjectid_contract_appointment?: Contract_Result | null;
  regardingobjectid_entitlement_appointment?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_appointment?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_appointment?: Incident_Result | null;
  regardingobjectid_invoice_appointment?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_appointment?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_appointment?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_appointment?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_appointment?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_appointment?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_appointment?: Opportunity_Result | null;
  regardingobjectid_quote_appointment?: Quote_Result | null;
  regardingobjectid_salesorder_appointment?: SalesOrder_Result | null;
  regardingobjectid_site_appointment?: Site_Result | null;
  seriesid_recurringappointmentmaster?: RecurringAppointmentMaster_Result | null;
  serviceid_appointment?: Service_Result | null;
  sla_appointment_sla?: SLA_Result | null;
  slainvokedid_appointment_sla?: SLA_Result | null;
  slakpiinstance_appointment?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_appointment?: TransactionCurrency_Result | null;
  userentityinstancedata_appointment?: UserEntityInstanceData_Result[] | null;
}
interface Appointment extends Appointment_Base, Appointment_Relationships {
  ownerid_appointment_bind$systemusers?: string | null;
  ownerid_appointment_bind$teams?: string | null;
  regardingobjectid_account_appointment_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_appointment_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_appointment_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_appointment_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_appointment_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_appointment_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_appointment_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_appointment_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_appointment_bind$campaignactivities?: string | null;
  regardingobjectid_contact_appointment_bind$contacts?: string | null;
  regardingobjectid_contract_appointment_bind$contracts?: string | null;
  regardingobjectid_entitlement_appointment_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_appointment_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_appointment_bind$incidents?: string | null;
  regardingobjectid_invoice_appointment_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_appointment_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_appointment_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_appointment_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_appointment_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_appointment_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_appointment_bind$opportunities?: string | null;
  regardingobjectid_quote_appointment_bind$quotes?: string | null;
  regardingobjectid_salesorder_appointment_bind$salesorders?: string | null;
  regardingobjectid_site_appointment_bind$sites?: string | null;
  serviceid_appointment_bind$services?: string | null;
  sla_appointment_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_appointment_bind$transactioncurrencies?: string | null;
}
interface Appointment_Create extends Appointment {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface Appointment_Update extends Appointment {
}
interface Appointment_Select {
  activityadditionalparams: WebAttribute<Appointment_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<Appointment_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<Appointment_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<Appointment_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<Appointment_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Appointment_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  attachmentcount: WebAttribute<Appointment_Select, { attachmentcount: number | null }, {  }>;
  attachmenterrors: WebAttribute<Appointment_Select, { attachmenterrors: appointment_attachmenterrors | null }, { attachmenterrors_formatted?: string }>;
  category: WebAttribute<Appointment_Select, { category: string | null }, {  }>;
  createdby_guid: WebAttribute<Appointment_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Appointment_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Appointment_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Appointment_Select, { description: string | null }, {  }>;
  exchangerate: WebAttribute<Appointment_Select, { exchangerate: number | null }, {  }>;
  globalobjectid: WebAttribute<Appointment_Select, { globalobjectid: string | null }, {  }>;
  importsequencenumber: WebAttribute<Appointment_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<Appointment_Select, { instancetypecode: appointment_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isalldayevent: WebAttribute<Appointment_Select, { isalldayevent: boolean | null }, {  }>;
  isbilled: WebAttribute<Appointment_Select, { isbilled: boolean | null }, {  }>;
  isdraft: WebAttribute<Appointment_Select, { isdraft: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<Appointment_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<Appointment_Select, { isregularactivity: boolean | null }, {  }>;
  isunsafe: WebAttribute<Appointment_Select, { isunsafe: number | null }, {  }>;
  isworkflowcreated: WebAttribute<Appointment_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Appointment_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  location: WebAttribute<Appointment_Select, { location: string | null }, {  }>;
  modifiedby_guid: WebAttribute<Appointment_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedfieldsmask: WebAttribute<Appointment_Select, { modifiedfieldsmask: string | null }, {  }>;
  modifiedon: WebAttribute<Appointment_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Appointment_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<Appointment_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<Appointment_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<Appointment_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  originalstartdate: WebAttribute<Appointment_Select, { originalstartdate: Date | null }, { originalstartdate_formatted?: string }>;
  outlookownerapptid: WebAttribute<Appointment_Select, { outlookownerapptid: number | null }, {  }>;
  overriddencreatedon: WebAttribute<Appointment_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Appointment_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Appointment_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Appointment_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Appointment_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  prioritycode: WebAttribute<Appointment_Select, { prioritycode: appointment_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Appointment_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<Appointment_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<Appointment_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<Appointment_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<Appointment_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<Appointment_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  seriesid: WebAttribute<Appointment_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<Appointment_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<Appointment_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Appointment_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<Appointment_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<Appointment_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Appointment_Select, { statecode: appointment_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Appointment_Select, { statuscode: appointment_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<Appointment_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<Appointment_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<Appointment_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Appointment_Select, { timezoneruleversionnumber: number | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Appointment_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Appointment_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Appointment_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Appointment_Select, { versionnumber: number | null }, {  }>;
}
interface Appointment_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  attachmentcount: number;
  attachmenterrors: appointment_attachmenterrors;
  category: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  exchangerate: any;
  globalobjectid: string;
  importsequencenumber: number;
  instancetypecode: appointment_instancetypecode;
  isalldayevent: boolean;
  isbilled: boolean;
  isdraft: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isunsafe: number;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  location: string;
  modifiedby_guid: XQW.Guid;
  modifiedfieldsmask: string;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  originalstartdate: Date;
  outlookownerapptid: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  prioritycode: appointment_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: appointment_statecode;
  statuscode: appointment_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Appointment_Expand {
  Appointment_Annotation: WebExpand<Appointment_Expand, Annotation_Select, Annotation_Filter, { Appointment_Annotation: Annotation_Result[] }>;
  Appointment_AsyncOperations: WebExpand<Appointment_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Appointment_AsyncOperations: AsyncOperation_Result[] }>;
  Appointment_BulkDeleteFailures: WebExpand<Appointment_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Appointment_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Appointment_DuplicateBaseRecord: WebExpand<Appointment_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Appointment_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Appointment_DuplicateMatchingRecord: WebExpand<Appointment_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Appointment_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Appointment_ProcessSessions: WebExpand<Appointment_Expand, ProcessSession_Select, ProcessSession_Filter, { Appointment_ProcessSessions: ProcessSession_Result[] }>;
  Appointment_QueueItem: WebExpand<Appointment_Expand, QueueItem_Select, QueueItem_Filter, { Appointment_QueueItem: QueueItem_Result[] }>;
  Appointment_SyncErrors: WebExpand<Appointment_Expand, SyncError_Select, SyncError_Filter, { Appointment_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<Appointment_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  appointment_PostFollows: WebExpand<Appointment_Expand, PostFollow_Select, PostFollow_Filter, { appointment_PostFollows: PostFollow_Result[] }>;
  appointment_PostRegardings: WebExpand<Appointment_Expand, PostRegarding_Select, PostRegarding_Filter, { appointment_PostRegardings: PostRegarding_Result[] }>;
  appointment_PostRoles: WebExpand<Appointment_Expand, PostRole_Select, PostRole_Filter, { appointment_PostRoles: PostRole_Result[] }>;
  appointment_actioncard: WebExpand<Appointment_Expand, ActionCard_Select, ActionCard_Filter, { appointment_actioncard: ActionCard_Result[] }>;
  appointment_activity_mime_attachment: WebExpand<Appointment_Expand, ActivityMimeAttachment_Select, ActivityMimeAttachment_Filter, { appointment_activity_mime_attachment: ActivityMimeAttachment_Result[] }>;
  appointment_activity_parties: WebExpand<Appointment_Expand, ActivityParty_Select, ActivityParty_Filter, { appointment_activity_parties: ActivityParty_Result[] }>;
  appointment_campaignresponse: WebExpand<Appointment_Expand, CampaignResponse_Select, CampaignResponse_Filter, { appointment_campaignresponse: CampaignResponse_Result[] }>;
  appointment_connections1: WebExpand<Appointment_Expand, Connection_Select, Connection_Filter, { appointment_connections1: Connection_Result[] }>;
  appointment_connections2: WebExpand<Appointment_Expand, Connection_Select, Connection_Filter, { appointment_connections2: Connection_Result[] }>;
  appointment_principalobjectattributeaccess: WebExpand<Appointment_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { appointment_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  createdby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { createdby_appointment: SystemUser_Result }>;
  createdonbehalfby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_appointment: SystemUser_Result }>;
  modifiedby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_appointment: SystemUser_Result }>;
  modifiedonbehalfby_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_appointment: SystemUser_Result }>;
  ownerid_appointment: WebExpand<Appointment_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_appointment: SystemUser_Result } & { ownerid_appointment: Team_Result }>;
  owningbusinessunit_appointment: WebExpand<Appointment_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_appointment: BusinessUnit_Result }>;
  owningteam_appointment: WebExpand<Appointment_Expand, Team_Select, Team_Filter, { owningteam_appointment: Team_Result }>;
  owninguser_appointment: WebExpand<Appointment_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_appointment: SystemUser_Result }>;
  regardingobjectid_account_appointment: WebExpand<Appointment_Expand, Account_Select, Account_Filter, { regardingobjectid_account_appointment: Account_Result }>;
  regardingobjectid_awc_prototype_appointment: WebExpand<Appointment_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_appointment: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_appointment: WebExpand<Appointment_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_appointment: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_appointment: WebExpand<Appointment_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_appointment: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_appointment: WebExpand<Appointment_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_appointment: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_appointment: WebExpand<Appointment_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_appointment: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_appointment: WebExpand<Appointment_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_appointment: BulkOperation_Result }>;
  regardingobjectid_campaign_appointment: WebExpand<Appointment_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_appointment: Campaign_Result }>;
  regardingobjectid_campaignactivity_appointment: WebExpand<Appointment_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_appointment: CampaignActivity_Result }>;
  regardingobjectid_contact_appointment: WebExpand<Appointment_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_appointment: Contact_Result }>;
  regardingobjectid_contract_appointment: WebExpand<Appointment_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_appointment: Contract_Result }>;
  regardingobjectid_entitlement_appointment: WebExpand<Appointment_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_appointment: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_appointment: WebExpand<Appointment_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_appointment: EntitlementTemplate_Result }>;
  regardingobjectid_incident_appointment: WebExpand<Appointment_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_appointment: Incident_Result }>;
  regardingobjectid_invoice_appointment: WebExpand<Appointment_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_appointment: Invoice_Result }>;
  regardingobjectid_knowledgearticle_appointment: WebExpand<Appointment_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_appointment: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_appointment: WebExpand<Appointment_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_appointment: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_appointment: WebExpand<Appointment_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_appointment: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_appointment: WebExpand<Appointment_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_appointment: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_appointment: WebExpand<Appointment_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_appointment: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_appointment: WebExpand<Appointment_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_appointment: Opportunity_Result }>;
  regardingobjectid_quote_appointment: WebExpand<Appointment_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_appointment: Quote_Result }>;
  regardingobjectid_salesorder_appointment: WebExpand<Appointment_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_appointment: SalesOrder_Result }>;
  regardingobjectid_site_appointment: WebExpand<Appointment_Expand, Site_Select, Site_Filter, { regardingobjectid_site_appointment: Site_Result }>;
  seriesid_recurringappointmentmaster: WebExpand<Appointment_Expand, RecurringAppointmentMaster_Select, RecurringAppointmentMaster_Filter, { seriesid_recurringappointmentmaster: RecurringAppointmentMaster_Result }>;
  serviceid_appointment: WebExpand<Appointment_Expand, Service_Select, Service_Filter, { serviceid_appointment: Service_Result }>;
  sla_appointment_sla: WebExpand<Appointment_Expand, SLA_Select, SLA_Filter, { sla_appointment_sla: SLA_Result }>;
  slainvokedid_appointment_sla: WebExpand<Appointment_Expand, SLA_Select, SLA_Filter, { slainvokedid_appointment_sla: SLA_Result }>;
  slakpiinstance_appointment: WebExpand<Appointment_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_appointment: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Appointment_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_appointment: WebExpand<Appointment_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_appointment: TransactionCurrency_Result }>;
  userentityinstancedata_appointment: WebExpand<Appointment_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_appointment: UserEntityInstanceData_Result[] }>;
}
interface Appointment_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  attachmenterrors_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  originalstartdate_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Appointment_Result extends Appointment_Base, Appointment_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Appointment_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_appointment: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_appointment1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_appointment: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_appointment: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_appointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_appointment: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_appointment: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_appointment: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_appointment: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_appointment: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_appointment: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_appointment: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_appointment: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_appointment: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_appointment: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_appointment: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_appointment: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_appointment: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_appointment: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_appointment: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_appointment: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_appointment: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_appointment: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_appointment: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_appointment: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_appointment: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_appointment: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_appointment: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_appointment: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  seriesid_recurringappointmentmaster: WebMappingRetrieve<RecurringAppointmentMaster_Select,RecurringAppointmentMaster_Expand,RecurringAppointmentMaster_Filter,RecurringAppointmentMaster_Fixed,RecurringAppointmentMaster_Result,RecurringAppointmentMaster_FormattedResult>;
  serviceid_appointment: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_appointment_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_appointment_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_appointment: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Appointment_RelatedMany {
  Appointment_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Appointment_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Appointment_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Appointment_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Appointment_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Appointment_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Appointment_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  Appointment_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  appointment_PostFollows: WebMappingRetrieve<PostFollow_Select,PostFollow_Expand,PostFollow_Filter,PostFollow_Fixed,PostFollow_Result,PostFollow_FormattedResult>;
  appointment_PostRegardings: WebMappingRetrieve<PostRegarding_Select,PostRegarding_Expand,PostRegarding_Filter,PostRegarding_Fixed,PostRegarding_Result,PostRegarding_FormattedResult>;
  appointment_PostRoles: WebMappingRetrieve<PostRole_Select,PostRole_Expand,PostRole_Filter,PostRole_Fixed,PostRole_Result,PostRole_FormattedResult>;
  appointment_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  appointment_activity_mime_attachment: WebMappingRetrieve<ActivityMimeAttachment_Select,ActivityMimeAttachment_Expand,ActivityMimeAttachment_Filter,ActivityMimeAttachment_Fixed,ActivityMimeAttachment_Result,ActivityMimeAttachment_FormattedResult>;
  appointment_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  appointment_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  appointment_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  appointment_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  appointment_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_appointment: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_appointment: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  appointments: WebMappingRetrieve<Appointment_Select,Appointment_Expand,Appointment_Filter,Appointment_Fixed,Appointment_Result,Appointment_FormattedResult>;
}
interface WebEntitiesRelated {
  appointments: WebMappingRelated<Appointment_RelatedOne,Appointment_RelatedMany>;
}
interface WebEntitiesCUDA {
  appointments: WebMappingCUDA<Appointment_Create,Appointment_Update,Appointment_Select>;
}
