interface Email_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  attachmentcount?: number | null;
  attachmentopencount?: number | null;
  baseconversationindexhash?: number | null;
  category?: string | null;
  compressed?: boolean | null;
  conversationindex?: string | null;
  conversationtrackingid?: string | null;
  correlationmethod?: email_correlationmethod | null;
  createdon?: Date | null;
  delayedemailsendtime?: Date | null;
  deliveryattempts?: number | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  deliveryreceiptrequested?: boolean | null;
  description?: string | null;
  directioncode?: boolean | null;
  emailreminderexpirytime?: Date | null;
  emailreminderstatus?: email_reminderstatus | null;
  emailremindertext?: string | null;
  emailremindertype?: email_remindertype | null;
  emailtrackingid?: string | null;
  exchangerate?: number | null;
  followemailuserpreference?: boolean | null;
  importsequencenumber?: number | null;
  inreplyto?: string | null;
  isbilled?: boolean | null;
  isemailfollowed?: boolean | null;
  isemailreminderset?: boolean | null;
  isregularactivity?: boolean | null;
  isunsafe?: number | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  lastopenedtime?: Date | null;
  linksclickedcount?: number | null;
  messageid?: string | null;
  messageiddupcheck?: string | null;
  mimetype?: string | null;
  modifiedon?: Date | null;
  notifications?: email_notifications | null;
  onholdtime?: number | null;
  opencount?: number | null;
  overriddencreatedon?: Date | null;
  postponeemailprocessinguntil?: Date | null;
  prioritycode?: email_prioritycode | null;
  processid?: string | null;
  readreceiptrequested?: boolean | null;
  reminderactioncardid?: string | null;
  replycount?: number | null;
  reservedforinternaluse?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  sender?: string | null;
  senton?: Date | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: email_statecode | null;
  statuscode?: email_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  submittedby?: string | null;
  timezoneruleversionnumber?: number | null;
  torecipients?: string | null;
  trackingtoken?: string | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Email_Relationships {
  CorrelatedActivityId_Email?: Email_Result | null;
  Email_Annotation?: Annotation_Result[] | null;
  Email_AsyncOperations?: AsyncOperation_Result[] | null;
  Email_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Email_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Email_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Email_ProcessSessions?: ProcessSession_Result[] | null;
  Email_QueueItem?: QueueItem_Result[] | null;
  Email_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_email?: SystemUser_Result | null;
  createdonbehalfby_email?: SystemUser_Result | null;
  email_actioncard?: ActionCard_Result[] | null;
  email_activity_mime_attachment?: ActivityMimeAttachment_Result[] | null;
  email_activity_parties?: ActivityParty_Result[] | null;
  email_activitymonitor?: activitymonitor_Result[] | null;
  email_campaignresponse?: CampaignResponse_Result[] | null;
  email_connections1?: Connection_Result[] | null;
  email_connections2?: Connection_Result[] | null;
  email_email_CorrelatedActivityId?: Email_Result[] | null;
  email_email_hash?: EmailHash_Result[] | null;
  email_email_parentactivityid?: Email_Result[] | null;
  email_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  emailsender_account?: Account_Result | null;
  emailsender_contact?: Contact_Result | null;
  emailsender_equipment?: Equipment_Result | null;
  emailsender_lead?: Lead_Result | null;
  emailsender_queue?: Queue_Result | null;
  emailsender_systemuser?: SystemUser_Result | null;
  modifiedby_email?: SystemUser_Result | null;
  modifiedonbehalfby_email?: SystemUser_Result | null;
  ownerid_email?: Team_Result | null;
  ownerid_email1?: SystemUser_Result | null;
  owningbusinessunit_email?: BusinessUnit_Result | null;
  owningteam_email?: Team_Result | null;
  owninguser_email?: SystemUser_Result | null;
  regardingobjectid_account_email?: Account_Result | null;
  regardingobjectid_asyncoperation?: AsyncOperation_Result | null;
  regardingobjectid_awc_prototype_email?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_email?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_email?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_email?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_email?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_email?: BulkOperation_Result | null;
  regardingobjectid_campaign_email?: Campaign_Result | null;
  regardingobjectid_campaignactivity_email?: CampaignActivity_Result | null;
  regardingobjectid_contact_email?: Contact_Result | null;
  regardingobjectid_contract_email?: Contract_Result | null;
  regardingobjectid_entitlement_email?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_email?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_email?: Incident_Result | null;
  regardingobjectid_invoice_email?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_email?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_email?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_email?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_email?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_email?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_email?: Opportunity_Result | null;
  regardingobjectid_quote_email?: Quote_Result | null;
  regardingobjectid_salesorder_email?: SalesOrder_Result | null;
  regardingobjectid_site_email?: Site_Result | null;
  sendermailboxid_email?: Mailbox_Result | null;
  serviceid_email?: Service_Result | null;
  sla_email_sla?: SLA_Result | null;
  slainvokedid_email_sla?: SLA_Result | null;
  slakpiinstance_email?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_email?: TransactionCurrency_Result | null;
  userentityinstancedata_email?: UserEntityInstanceData_Result[] | null;
}
interface Email extends Email_Base, Email_Relationships {
  ownerid_email_bind$systemusers?: string | null;
  ownerid_email_bind$teams?: string | null;
  regardingobjectid_account_email_bind$accounts?: string | null;
  regardingobjectid_asyncoperation_bind$asyncoperations?: string | null;
  regardingobjectid_awc_prototype_email_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_email_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_email_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_email_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_email_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_email_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_email_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_email_bind$campaignactivities?: string | null;
  regardingobjectid_contact_email_bind$contacts?: string | null;
  regardingobjectid_contract_email_bind$contracts?: string | null;
  regardingobjectid_entitlement_email_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_email_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_email_bind$incidents?: string | null;
  regardingobjectid_invoice_email_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_email_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_email_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_email_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_email_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_email_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_email_bind$opportunities?: string | null;
  regardingobjectid_quote_email_bind$quotes?: string | null;
  regardingobjectid_salesorder_email_bind$salesorders?: string | null;
  regardingobjectid_site_email_bind$sites?: string | null;
  serviceid_email_bind$services?: string | null;
  sla_email_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  templateid_bind$templates?: string | null;
  transactioncurrencyid_email_bind$transactioncurrencies?: string | null;
}
interface Email_Create extends Email {
  CorrelatedActivityId_Email_bind$emails?: string | null;
  activityid_activitypointer_bind$activitypointers?: string | null;
  parentactivityid_bind$emails?: string | null;
}
interface Email_Update extends Email {
}
interface Email_Select {
  activityadditionalparams: WebAttribute<Email_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<Email_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<Email_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<Email_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<Email_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Email_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  attachmentcount: WebAttribute<Email_Select, { attachmentcount: number | null }, {  }>;
  attachmentopencount: WebAttribute<Email_Select, { attachmentopencount: number | null }, {  }>;
  baseconversationindexhash: WebAttribute<Email_Select, { baseconversationindexhash: number | null }, {  }>;
  bcc_guid: WebAttribute<Email_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  category: WebAttribute<Email_Select, { category: string | null }, {  }>;
  cc_guid: WebAttribute<Email_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  compressed: WebAttribute<Email_Select, { compressed: boolean | null }, {  }>;
  conversationindex: WebAttribute<Email_Select, { conversationindex: string | null }, {  }>;
  conversationtrackingid: WebAttribute<Email_Select, { conversationtrackingid: string | null }, {  }>;
  correlatedactivityid_guid: WebAttribute<Email_Select, { correlatedactivityid_guid: string | null }, { correlatedactivityid_formatted?: string }>;
  correlationmethod: WebAttribute<Email_Select, { correlationmethod: email_correlationmethod | null }, { correlationmethod_formatted?: string }>;
  createdby_guid: WebAttribute<Email_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Email_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Email_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  delayedemailsendtime: WebAttribute<Email_Select, { delayedemailsendtime: Date | null }, { delayedemailsendtime_formatted?: string }>;
  deliveryattempts: WebAttribute<Email_Select, { deliveryattempts: number | null }, {  }>;
  deliveryprioritycode: WebAttribute<Email_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  deliveryreceiptrequested: WebAttribute<Email_Select, { deliveryreceiptrequested: boolean | null }, {  }>;
  description: WebAttribute<Email_Select, { description: string | null }, {  }>;
  directioncode: WebAttribute<Email_Select, { directioncode: boolean | null }, {  }>;
  emailreminderexpirytime: WebAttribute<Email_Select, { emailreminderexpirytime: Date | null }, { emailreminderexpirytime_formatted?: string }>;
  emailreminderstatus: WebAttribute<Email_Select, { emailreminderstatus: email_reminderstatus | null }, { emailreminderstatus_formatted?: string }>;
  emailremindertext: WebAttribute<Email_Select, { emailremindertext: string | null }, {  }>;
  emailremindertype: WebAttribute<Email_Select, { emailremindertype: email_remindertype | null }, { emailremindertype_formatted?: string }>;
  emailsender_guid: WebAttribute<Email_Select, { emailsender_guid: string | null }, { emailsender_formatted?: string }>;
  emailtrackingid: WebAttribute<Email_Select, { emailtrackingid: string | null }, {  }>;
  exchangerate: WebAttribute<Email_Select, { exchangerate: number | null }, {  }>;
  followemailuserpreference: WebAttribute<Email_Select, { followemailuserpreference: boolean | null }, {  }>;
  from_guid: WebAttribute<Email_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<Email_Select, { importsequencenumber: number | null }, {  }>;
  inreplyto: WebAttribute<Email_Select, { inreplyto: string | null }, {  }>;
  isbilled: WebAttribute<Email_Select, { isbilled: boolean | null }, {  }>;
  isemailfollowed: WebAttribute<Email_Select, { isemailfollowed: boolean | null }, {  }>;
  isemailreminderset: WebAttribute<Email_Select, { isemailreminderset: boolean | null }, {  }>;
  isregularactivity: WebAttribute<Email_Select, { isregularactivity: boolean | null }, {  }>;
  isunsafe: WebAttribute<Email_Select, { isunsafe: number | null }, {  }>;
  isworkflowcreated: WebAttribute<Email_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Email_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  lastopenedtime: WebAttribute<Email_Select, { lastopenedtime: Date | null }, { lastopenedtime_formatted?: string }>;
  linksclickedcount: WebAttribute<Email_Select, { linksclickedcount: number | null }, {  }>;
  messageid: WebAttribute<Email_Select, { messageid: string | null }, {  }>;
  messageiddupcheck: WebAttribute<Email_Select, { messageiddupcheck: string | null }, {  }>;
  mimetype: WebAttribute<Email_Select, { mimetype: string | null }, {  }>;
  modifiedby_guid: WebAttribute<Email_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Email_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Email_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  notifications: WebAttribute<Email_Select, { notifications: email_notifications | null }, { notifications_formatted?: string }>;
  onholdtime: WebAttribute<Email_Select, { onholdtime: number | null }, {  }>;
  opencount: WebAttribute<Email_Select, { opencount: number | null }, {  }>;
  overriddencreatedon: WebAttribute<Email_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Email_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Email_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Email_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Email_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  parentactivityid_guid: WebAttribute<Email_Select, { parentactivityid_guid: string | null }, { parentactivityid_formatted?: string }>;
  postponeemailprocessinguntil: WebAttribute<Email_Select, { postponeemailprocessinguntil: Date | null }, { postponeemailprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<Email_Select, { prioritycode: email_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Email_Select, { processid: string | null }, {  }>;
  readreceiptrequested: WebAttribute<Email_Select, { readreceiptrequested: boolean | null }, {  }>;
  regardingobjectid_guid: WebAttribute<Email_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  reminderactioncardid: WebAttribute<Email_Select, { reminderactioncardid: string | null }, {  }>;
  replycount: WebAttribute<Email_Select, { replycount: number | null }, {  }>;
  reservedforinternaluse: WebAttribute<Email_Select, { reservedforinternaluse: string | null }, {  }>;
  scheduleddurationminutes: WebAttribute<Email_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<Email_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<Email_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sender: WebAttribute<Email_Select, { sender: string | null }, {  }>;
  sendermailboxid_guid: WebAttribute<Email_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  sendersaccount_guid: WebAttribute<Email_Select, { sendersaccount_guid: string | null }, { sendersaccount_formatted?: string }>;
  senton: WebAttribute<Email_Select, { senton: Date | null }, { senton_formatted?: string }>;
  serviceid_guid: WebAttribute<Email_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<Email_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Email_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<Email_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<Email_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Email_Select, { statecode: email_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Email_Select, { statuscode: email_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<Email_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<Email_Select, { subject: string | null }, {  }>;
  submittedby: WebAttribute<Email_Select, { submittedby: string | null }, {  }>;
  templateid_guid: WebAttribute<Email_Select, { templateid_guid: string | null }, { templateid_formatted?: string }>;
  timezoneruleversionnumber: WebAttribute<Email_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<Email_Select, { to_guid: string | null }, { to_formatted?: string }>;
  torecipients: WebAttribute<Email_Select, { torecipients: string | null }, {  }>;
  trackingtoken: WebAttribute<Email_Select, { trackingtoken: string | null }, {  }>;
  transactioncurrencyid_guid: WebAttribute<Email_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Email_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Email_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Email_Select, { versionnumber: number | null }, {  }>;
}
interface Email_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  attachmentcount: number;
  attachmentopencount: number;
  baseconversationindexhash: number;
  bcc_guid: XQW.Guid;
  category: string;
  cc_guid: XQW.Guid;
  compressed: boolean;
  conversationindex: string;
  conversationtrackingid: XQW.Guid;
  correlatedactivityid_guid: XQW.Guid;
  correlationmethod: email_correlationmethod;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  delayedemailsendtime: Date;
  deliveryattempts: number;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  deliveryreceiptrequested: boolean;
  description: string;
  directioncode: boolean;
  emailreminderexpirytime: Date;
  emailreminderstatus: email_reminderstatus;
  emailremindertext: string;
  emailremindertype: email_remindertype;
  emailsender_guid: XQW.Guid;
  emailtrackingid: XQW.Guid;
  exchangerate: any;
  followemailuserpreference: boolean;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  inreplyto: string;
  isbilled: boolean;
  isemailfollowed: boolean;
  isemailreminderset: boolean;
  isregularactivity: boolean;
  isunsafe: number;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  lastopenedtime: Date;
  linksclickedcount: number;
  messageid: string;
  messageiddupcheck: XQW.Guid;
  mimetype: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  notifications: email_notifications;
  onholdtime: number;
  opencount: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  parentactivityid_guid: XQW.Guid;
  postponeemailprocessinguntil: Date;
  prioritycode: email_prioritycode;
  processid: XQW.Guid;
  readreceiptrequested: boolean;
  regardingobjectid_guid: XQW.Guid;
  reminderactioncardid: XQW.Guid;
  replycount: number;
  reservedforinternaluse: string;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sender: string;
  sendermailboxid_guid: XQW.Guid;
  sendersaccount_guid: XQW.Guid;
  senton: Date;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: email_statecode;
  statuscode: email_statuscode;
  subcategory: string;
  subject: string;
  submittedby: string;
  templateid_guid: XQW.Guid;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  torecipients: string;
  trackingtoken: string;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Email_Expand {
  CorrelatedActivityId_Email: WebExpand<Email_Expand, Email_Select, Email_Filter, { CorrelatedActivityId_Email: Email_Result }>;
  Email_Annotation: WebExpand<Email_Expand, Annotation_Select, Annotation_Filter, { Email_Annotation: Annotation_Result[] }>;
  Email_AsyncOperations: WebExpand<Email_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Email_AsyncOperations: AsyncOperation_Result[] }>;
  Email_BulkDeleteFailures: WebExpand<Email_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Email_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Email_DuplicateBaseRecord: WebExpand<Email_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Email_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Email_DuplicateMatchingRecord: WebExpand<Email_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Email_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Email_ProcessSessions: WebExpand<Email_Expand, ProcessSession_Select, ProcessSession_Filter, { Email_ProcessSessions: ProcessSession_Result[] }>;
  Email_QueueItem: WebExpand<Email_Expand, QueueItem_Select, QueueItem_Filter, { Email_QueueItem: QueueItem_Result[] }>;
  Email_SyncErrors: WebExpand<Email_Expand, SyncError_Select, SyncError_Filter, { Email_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<Email_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { createdby_email: SystemUser_Result }>;
  createdonbehalfby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_email: SystemUser_Result }>;
  email_actioncard: WebExpand<Email_Expand, ActionCard_Select, ActionCard_Filter, { email_actioncard: ActionCard_Result[] }>;
  email_activity_mime_attachment: WebExpand<Email_Expand, ActivityMimeAttachment_Select, ActivityMimeAttachment_Filter, { email_activity_mime_attachment: ActivityMimeAttachment_Result[] }>;
  email_activity_parties: WebExpand<Email_Expand, ActivityParty_Select, ActivityParty_Filter, { email_activity_parties: ActivityParty_Result[] }>;
  email_activitymonitor: WebExpand<Email_Expand, activitymonitor_Select, activitymonitor_Filter, { email_activitymonitor: activitymonitor_Result[] }>;
  email_campaignresponse: WebExpand<Email_Expand, CampaignResponse_Select, CampaignResponse_Filter, { email_campaignresponse: CampaignResponse_Result[] }>;
  email_connections1: WebExpand<Email_Expand, Connection_Select, Connection_Filter, { email_connections1: Connection_Result[] }>;
  email_connections2: WebExpand<Email_Expand, Connection_Select, Connection_Filter, { email_connections2: Connection_Result[] }>;
  email_email_CorrelatedActivityId: WebExpand<Email_Expand, Email_Select, Email_Filter, { email_email_CorrelatedActivityId: Email_Result[] }>;
  email_email_hash: WebExpand<Email_Expand, EmailHash_Select, EmailHash_Filter, { email_email_hash: EmailHash_Result[] }>;
  email_email_parentactivityid: WebExpand<Email_Expand, Email_Select, Email_Filter, { email_email_parentactivityid: Email_Result[] }>;
  email_principalobjectattributeaccess: WebExpand<Email_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { email_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  emailsender_account: WebExpand<Email_Expand, Account_Select, Account_Filter, { emailsender_account: Account_Result }>;
  emailsender_contact: WebExpand<Email_Expand, Contact_Select, Contact_Filter, { emailsender_contact: Contact_Result }>;
  emailsender_equipment: WebExpand<Email_Expand, Equipment_Select, Equipment_Filter, { emailsender_equipment: Equipment_Result }>;
  emailsender_lead: WebExpand<Email_Expand, Lead_Select, Lead_Filter, { emailsender_lead: Lead_Result }>;
  emailsender_queue: WebExpand<Email_Expand, Queue_Select, Queue_Filter, { emailsender_queue: Queue_Result }>;
  emailsender_systemuser: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { emailsender_systemuser: SystemUser_Result }>;
  modifiedby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_email: SystemUser_Result }>;
  modifiedonbehalfby_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_email: SystemUser_Result }>;
  ownerid_email: WebExpand<Email_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_email: SystemUser_Result } & { ownerid_email: Team_Result }>;
  owningbusinessunit_email: WebExpand<Email_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_email: BusinessUnit_Result }>;
  owningteam_email: WebExpand<Email_Expand, Team_Select, Team_Filter, { owningteam_email: Team_Result }>;
  owninguser_email: WebExpand<Email_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_email: SystemUser_Result }>;
  parentactivityid: WebExpand<Email_Expand, Email_Select, Email_Filter, { parentactivityid: Email_Result }>;
  regardingobjectid_account_email: WebExpand<Email_Expand, Account_Select, Account_Filter, { regardingobjectid_account_email: Account_Result }>;
  regardingobjectid_asyncoperation: WebExpand<Email_Expand, AsyncOperation_Select, AsyncOperation_Filter, { regardingobjectid_asyncoperation: AsyncOperation_Result }>;
  regardingobjectid_awc_prototype_email: WebExpand<Email_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_email: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_email: WebExpand<Email_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_email: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_email: WebExpand<Email_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_email: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_email: WebExpand<Email_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_email: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_email: WebExpand<Email_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_email: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_email: WebExpand<Email_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_email: BulkOperation_Result }>;
  regardingobjectid_campaign_email: WebExpand<Email_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_email: Campaign_Result }>;
  regardingobjectid_campaignactivity_email: WebExpand<Email_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_email: CampaignActivity_Result }>;
  regardingobjectid_contact_email: WebExpand<Email_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_email: Contact_Result }>;
  regardingobjectid_contract_email: WebExpand<Email_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_email: Contract_Result }>;
  regardingobjectid_entitlement_email: WebExpand<Email_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_email: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_email: WebExpand<Email_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_email: EntitlementTemplate_Result }>;
  regardingobjectid_incident_email: WebExpand<Email_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_email: Incident_Result }>;
  regardingobjectid_invoice_email: WebExpand<Email_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_email: Invoice_Result }>;
  regardingobjectid_knowledgearticle_email: WebExpand<Email_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_email: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_email: WebExpand<Email_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_email: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_email: WebExpand<Email_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_email: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_email: WebExpand<Email_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_email: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_email: WebExpand<Email_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_email: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_email: WebExpand<Email_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_email: Opportunity_Result }>;
  regardingobjectid_quote_email: WebExpand<Email_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_email: Quote_Result }>;
  regardingobjectid_salesorder_email: WebExpand<Email_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_email: SalesOrder_Result }>;
  regardingobjectid_site_email: WebExpand<Email_Expand, Site_Select, Site_Filter, { regardingobjectid_site_email: Site_Result }>;
  sendermailboxid_email: WebExpand<Email_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid_email: Mailbox_Result }>;
  sendersaccount: WebExpand<Email_Expand, Account_Select, Account_Filter, { sendersaccount: Account_Result }>;
  serviceid_email: WebExpand<Email_Expand, Service_Select, Service_Filter, { serviceid_email: Service_Result }>;
  sla_email_sla: WebExpand<Email_Expand, SLA_Select, SLA_Filter, { sla_email_sla: SLA_Result }>;
  slainvokedid_email_sla: WebExpand<Email_Expand, SLA_Select, SLA_Filter, { slainvokedid_email_sla: SLA_Result }>;
  slakpiinstance_email: WebExpand<Email_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_email: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Email_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  templateid: WebExpand<Email_Expand, Template_Select, Template_Filter, { templateid: Template_Result }>;
  transactioncurrencyid_email: WebExpand<Email_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_email: TransactionCurrency_Result }>;
  userentityinstancedata_email: WebExpand<Email_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_email: UserEntityInstanceData_Result[] }>;
}
interface Email_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  correlatedactivityid_formatted?: string;
  correlationmethod_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  delayedemailsendtime_formatted?: string;
  deliveryprioritycode_formatted?: string;
  emailreminderexpirytime_formatted?: string;
  emailreminderstatus_formatted?: string;
  emailremindertype_formatted?: string;
  emailsender_formatted?: string;
  from_formatted?: string;
  lastonholdtime_formatted?: string;
  lastopenedtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  notifications_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  parentactivityid_formatted?: string;
  postponeemailprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  sendersaccount_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  templateid_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Email_Result extends Email_Base, Email_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  correlatedactivityid_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  emailsender_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  parentactivityid_guid: string | null;
  regardingobjectid_guid: string | null;
  sendermailboxid_guid: string | null;
  sendersaccount_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  templateid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Email_RelatedOne {
  CorrelatedActivityId_Email: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_email: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_email: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  emailsender_account: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  emailsender_contact: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  emailsender_equipment: WebMappingRetrieve<Equipment_Select,Equipment_Expand,Equipment_Filter,Equipment_Fixed,Equipment_Result,Equipment_FormattedResult>;
  emailsender_lead: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  emailsender_queue: WebMappingRetrieve<Queue_Select,Queue_Expand,Queue_Filter,Queue_Fixed,Queue_Result,Queue_FormattedResult>;
  emailsender_systemuser: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_email: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_email: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_email: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_email1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_email: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_email: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_email: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  parentactivityid: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  regardingobjectid_account_email: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_asyncoperation: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  regardingobjectid_awc_prototype_email: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_email: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_email: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_email: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_email: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_email: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_email: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_email: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_email: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_email: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_email: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_email: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_email: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_email: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_email: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_email: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_email: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_email: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_email: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_email: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_email: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_email: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_email: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  sendermailboxid_email: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  sendersaccount: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  serviceid_email: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_email_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_email_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  templateid: WebMappingRetrieve<Template_Select,Template_Expand,Template_Filter,Template_Fixed,Template_Result,Template_FormattedResult>;
  transactioncurrencyid_email: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Email_RelatedMany {
  Email_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Email_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Email_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Email_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Email_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Email_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Email_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  Email_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  email_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  email_activity_mime_attachment: WebMappingRetrieve<ActivityMimeAttachment_Select,ActivityMimeAttachment_Expand,ActivityMimeAttachment_Filter,ActivityMimeAttachment_Fixed,ActivityMimeAttachment_Result,ActivityMimeAttachment_FormattedResult>;
  email_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  email_activitymonitor: WebMappingRetrieve<activitymonitor_Select,activitymonitor_Expand,activitymonitor_Filter,activitymonitor_Fixed,activitymonitor_Result,activitymonitor_FormattedResult>;
  email_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  email_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  email_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  email_email_CorrelatedActivityId: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  email_email_hash: WebMappingRetrieve<EmailHash_Select,EmailHash_Expand,EmailHash_Filter,EmailHash_Fixed,EmailHash_Result,EmailHash_FormattedResult>;
  email_email_parentactivityid: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
  email_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_email: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_email: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  emails: WebMappingRetrieve<Email_Select,Email_Expand,Email_Filter,Email_Fixed,Email_Result,Email_FormattedResult>;
}
interface WebEntitiesRelated {
  emails: WebMappingRelated<Email_RelatedOne,Email_RelatedMany>;
}
interface WebEntitiesCUDA {
  emails: WebMappingCUDA<Email_Create,Email_Update,Email_Select>;
}
