interface Fax_Base extends WebEntity {
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  billingcode?: string | null;
  category?: string | null;
  coverpagename?: string | null;
  createdon?: Date | null;
  description?: string | null;
  directioncode?: boolean | null;
  exchangerate?: number | null;
  faxnumber?: string | null;
  importsequencenumber?: number | null;
  isbilled?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  modifiedon?: Date | null;
  numberofpages?: number | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  prioritycode?: fax_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: fax_statecode | null;
  statuscode?: fax_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  tsid?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface Fax_Relationships {
  Fax_Annotation?: Annotation_Result[] | null;
  Fax_AsyncOperations?: AsyncOperation_Result[] | null;
  Fax_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  Fax_DuplicateBaseRecord?: DuplicateRecord_Result[] | null;
  Fax_DuplicateMatchingRecord?: DuplicateRecord_Result[] | null;
  Fax_ProcessSessions?: ProcessSession_Result[] | null;
  Fax_QueueItem?: QueueItem_Result[] | null;
  Fax_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_fax?: SystemUser_Result | null;
  createdonbehalfby_fax?: SystemUser_Result | null;
  fax_actioncard?: ActionCard_Result[] | null;
  fax_activity_parties?: ActivityParty_Result[] | null;
  fax_campaignresponse?: CampaignResponse_Result[] | null;
  fax_connections1?: Connection_Result[] | null;
  fax_connections2?: Connection_Result[] | null;
  fax_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  modifiedby_fax?: SystemUser_Result | null;
  modifiedonbehalfby_fax?: SystemUser_Result | null;
  ownerid_fax?: Team_Result | null;
  ownerid_fax1?: SystemUser_Result | null;
  owningbusinessunit_fax?: BusinessUnit_Result | null;
  owningteam_fax?: Team_Result | null;
  owninguser_fax?: SystemUser_Result | null;
  regardingobjectid_account_fax?: Account_Result | null;
  regardingobjectid_awc_prototype_fax?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_fax?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_fax?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_fax?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_fax?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_fax?: BulkOperation_Result | null;
  regardingobjectid_campaign_fax?: Campaign_Result | null;
  regardingobjectid_campaignactivity_fax?: CampaignActivity_Result | null;
  regardingobjectid_contact_fax?: Contact_Result | null;
  regardingobjectid_contract_fax?: Contract_Result | null;
  regardingobjectid_entitlement_fax?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_fax?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_fax?: Incident_Result | null;
  regardingobjectid_invoice_fax?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_fax?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_fax?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_fax?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_fax?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_fax?: msdyn_PostAlbum_Result | null;
  regardingobjectid_opportunity_fax?: Opportunity_Result | null;
  regardingobjectid_quote_fax?: Quote_Result | null;
  regardingobjectid_salesorder_fax?: SalesOrder_Result | null;
  regardingobjectid_site_fax?: Site_Result | null;
  serviceid_fax?: Service_Result | null;
  sla_fax_sla?: SLA_Result | null;
  slainvokedid_fax_sla?: SLA_Result | null;
  slakpiinstance_fax?: SLAKPIInstance_Result[] | null;
  stageid_processstage?: ProcessStage_Result | null;
  transactioncurrencyid_fax?: TransactionCurrency_Result | null;
  userentityinstancedata_fax?: UserEntityInstanceData_Result[] | null;
}
interface Fax extends Fax_Base, Fax_Relationships {
  ownerid_fax_bind$systemusers?: string | null;
  ownerid_fax_bind$teams?: string | null;
  regardingobjectid_account_fax_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_fax_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_fax_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_fax_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_fax_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_fax_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_fax_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_fax_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_fax_bind$campaignactivities?: string | null;
  regardingobjectid_contact_fax_bind$contacts?: string | null;
  regardingobjectid_contract_fax_bind$contracts?: string | null;
  regardingobjectid_entitlement_fax_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_fax_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_fax_bind$incidents?: string | null;
  regardingobjectid_invoice_fax_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_fax_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_fax_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_fax_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_fax_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_fax_bind$msdyn_postalbums?: string | null;
  regardingobjectid_opportunity_fax_bind$opportunities?: string | null;
  regardingobjectid_quote_fax_bind$quotes?: string | null;
  regardingobjectid_salesorder_fax_bind$salesorders?: string | null;
  regardingobjectid_site_fax_bind$sites?: string | null;
  serviceid_fax_bind$services?: string | null;
  sla_fax_sla_bind$slas?: string | null;
  stageid_processstage_bind$processstages?: string | null;
  transactioncurrencyid_fax_bind$transactioncurrencies?: string | null;
}
interface Fax_Create extends Fax {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface Fax_Update extends Fax {
}
interface Fax_Select {
  activityid: WebAttribute<Fax_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<Fax_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<Fax_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<Fax_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<Fax_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  billingcode: WebAttribute<Fax_Select, { billingcode: string | null }, {  }>;
  category: WebAttribute<Fax_Select, { category: string | null }, {  }>;
  coverpagename: WebAttribute<Fax_Select, { coverpagename: string | null }, {  }>;
  createdby_guid: WebAttribute<Fax_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<Fax_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<Fax_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  description: WebAttribute<Fax_Select, { description: string | null }, {  }>;
  directioncode: WebAttribute<Fax_Select, { directioncode: boolean | null }, {  }>;
  exchangerate: WebAttribute<Fax_Select, { exchangerate: number | null }, {  }>;
  faxnumber: WebAttribute<Fax_Select, { faxnumber: string | null }, {  }>;
  from_guid: WebAttribute<Fax_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<Fax_Select, { importsequencenumber: number | null }, {  }>;
  isbilled: WebAttribute<Fax_Select, { isbilled: boolean | null }, {  }>;
  isregularactivity: WebAttribute<Fax_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<Fax_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<Fax_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  modifiedby_guid: WebAttribute<Fax_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<Fax_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<Fax_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  numberofpages: WebAttribute<Fax_Select, { numberofpages: number | null }, {  }>;
  onholdtime: WebAttribute<Fax_Select, { onholdtime: number | null }, {  }>;
  overriddencreatedon: WebAttribute<Fax_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<Fax_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<Fax_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<Fax_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<Fax_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  prioritycode: WebAttribute<Fax_Select, { prioritycode: fax_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<Fax_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<Fax_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<Fax_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<Fax_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<Fax_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  serviceid_guid: WebAttribute<Fax_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  slaid_guid: WebAttribute<Fax_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<Fax_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<Fax_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<Fax_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<Fax_Select, { statecode: fax_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<Fax_Select, { statuscode: fax_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<Fax_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<Fax_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<Fax_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<Fax_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<Fax_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<Fax_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<Fax_Select, { traversedpath: string | null }, {  }>;
  tsid: WebAttribute<Fax_Select, { tsid: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<Fax_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<Fax_Select, { versionnumber: number | null }, {  }>;
}
interface Fax_Filter {
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  billingcode: string;
  category: string;
  coverpagename: string;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  description: string;
  directioncode: boolean;
  exchangerate: any;
  faxnumber: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  isbilled: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  numberofpages: number;
  onholdtime: number;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  prioritycode: fax_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  serviceid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: fax_statecode;
  statuscode: fax_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  tsid: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface Fax_Expand {
  Fax_Annotation: WebExpand<Fax_Expand, Annotation_Select, Annotation_Filter, { Fax_Annotation: Annotation_Result[] }>;
  Fax_AsyncOperations: WebExpand<Fax_Expand, AsyncOperation_Select, AsyncOperation_Filter, { Fax_AsyncOperations: AsyncOperation_Result[] }>;
  Fax_BulkDeleteFailures: WebExpand<Fax_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { Fax_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  Fax_DuplicateBaseRecord: WebExpand<Fax_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Fax_DuplicateBaseRecord: DuplicateRecord_Result[] }>;
  Fax_DuplicateMatchingRecord: WebExpand<Fax_Expand, DuplicateRecord_Select, DuplicateRecord_Filter, { Fax_DuplicateMatchingRecord: DuplicateRecord_Result[] }>;
  Fax_ProcessSessions: WebExpand<Fax_Expand, ProcessSession_Select, ProcessSession_Filter, { Fax_ProcessSessions: ProcessSession_Result[] }>;
  Fax_QueueItem: WebExpand<Fax_Expand, QueueItem_Select, QueueItem_Filter, { Fax_QueueItem: QueueItem_Result[] }>;
  Fax_SyncErrors: WebExpand<Fax_Expand, SyncError_Select, SyncError_Filter, { Fax_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<Fax_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { createdby_fax: SystemUser_Result }>;
  createdonbehalfby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_fax: SystemUser_Result }>;
  fax_actioncard: WebExpand<Fax_Expand, ActionCard_Select, ActionCard_Filter, { fax_actioncard: ActionCard_Result[] }>;
  fax_activity_parties: WebExpand<Fax_Expand, ActivityParty_Select, ActivityParty_Filter, { fax_activity_parties: ActivityParty_Result[] }>;
  fax_campaignresponse: WebExpand<Fax_Expand, CampaignResponse_Select, CampaignResponse_Filter, { fax_campaignresponse: CampaignResponse_Result[] }>;
  fax_connections1: WebExpand<Fax_Expand, Connection_Select, Connection_Filter, { fax_connections1: Connection_Result[] }>;
  fax_connections2: WebExpand<Fax_Expand, Connection_Select, Connection_Filter, { fax_connections2: Connection_Result[] }>;
  fax_principalobjectattributeaccess: WebExpand<Fax_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { fax_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  modifiedby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_fax: SystemUser_Result }>;
  modifiedonbehalfby_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_fax: SystemUser_Result }>;
  ownerid_fax: WebExpand<Fax_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_fax: SystemUser_Result } & { ownerid_fax: Team_Result }>;
  owningbusinessunit_fax: WebExpand<Fax_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_fax: BusinessUnit_Result }>;
  owningteam_fax: WebExpand<Fax_Expand, Team_Select, Team_Filter, { owningteam_fax: Team_Result }>;
  owninguser_fax: WebExpand<Fax_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_fax: SystemUser_Result }>;
  regardingobjectid_account_fax: WebExpand<Fax_Expand, Account_Select, Account_Filter, { regardingobjectid_account_fax: Account_Result }>;
  regardingobjectid_awc_prototype_fax: WebExpand<Fax_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_fax: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_fax: WebExpand<Fax_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_fax: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_fax: WebExpand<Fax_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_fax: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_fax: WebExpand<Fax_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_fax: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_fax: WebExpand<Fax_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_fax: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_fax: WebExpand<Fax_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_fax: BulkOperation_Result }>;
  regardingobjectid_campaign_fax: WebExpand<Fax_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_fax: Campaign_Result }>;
  regardingobjectid_campaignactivity_fax: WebExpand<Fax_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_fax: CampaignActivity_Result }>;
  regardingobjectid_contact_fax: WebExpand<Fax_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_fax: Contact_Result }>;
  regardingobjectid_contract_fax: WebExpand<Fax_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_fax: Contract_Result }>;
  regardingobjectid_entitlement_fax: WebExpand<Fax_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_fax: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_fax: WebExpand<Fax_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_fax: EntitlementTemplate_Result }>;
  regardingobjectid_incident_fax: WebExpand<Fax_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_fax: Incident_Result }>;
  regardingobjectid_invoice_fax: WebExpand<Fax_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_fax: Invoice_Result }>;
  regardingobjectid_knowledgearticle_fax: WebExpand<Fax_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_fax: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_fax: WebExpand<Fax_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_fax: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_fax: WebExpand<Fax_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_fax: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_fax: WebExpand<Fax_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_fax: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_fax: WebExpand<Fax_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_fax: msdyn_PostAlbum_Result }>;
  regardingobjectid_opportunity_fax: WebExpand<Fax_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_fax: Opportunity_Result }>;
  regardingobjectid_quote_fax: WebExpand<Fax_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_fax: Quote_Result }>;
  regardingobjectid_salesorder_fax: WebExpand<Fax_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_fax: SalesOrder_Result }>;
  regardingobjectid_site_fax: WebExpand<Fax_Expand, Site_Select, Site_Filter, { regardingobjectid_site_fax: Site_Result }>;
  serviceid_fax: WebExpand<Fax_Expand, Service_Select, Service_Filter, { serviceid_fax: Service_Result }>;
  sla_fax_sla: WebExpand<Fax_Expand, SLA_Select, SLA_Filter, { sla_fax_sla: SLA_Result }>;
  slainvokedid_fax_sla: WebExpand<Fax_Expand, SLA_Select, SLA_Filter, { slainvokedid_fax_sla: SLA_Result }>;
  slakpiinstance_fax: WebExpand<Fax_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_fax: SLAKPIInstance_Result[] }>;
  stageid_processstage: WebExpand<Fax_Expand, ProcessStage_Select, ProcessStage_Filter, { stageid_processstage: ProcessStage_Result }>;
  transactioncurrencyid_fax: WebExpand<Fax_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_fax: TransactionCurrency_Result }>;
  userentityinstancedata_fax: WebExpand<Fax_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_fax: UserEntityInstanceData_Result[] }>;
}
interface Fax_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  from_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  serviceid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface Fax_Result extends Fax_Base, Fax_Relationships {
  "@odata.etag": string;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  regardingobjectid_guid: string | null;
  serviceid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface Fax_RelatedOne {
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_fax: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_fax1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_fax: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_fax: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_fax: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_fax: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_fax: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_fax: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_fax: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_fax: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_fax: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_fax: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_fax: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_fax: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_fax: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_fax: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_fax: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_fax: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_fax: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_fax: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_fax: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_fax: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_fax: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_fax: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_fax: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_opportunity_fax: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_fax: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_fax: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_fax: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  serviceid_fax: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  sla_fax_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  slainvokedid_fax_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  stageid_processstage: WebMappingRetrieve<ProcessStage_Select,ProcessStage_Expand,ProcessStage_Filter,ProcessStage_Fixed,ProcessStage_Result,ProcessStage_FormattedResult>;
  transactioncurrencyid_fax: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface Fax_RelatedMany {
  Fax_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  Fax_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  Fax_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  Fax_DuplicateBaseRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Fax_DuplicateMatchingRecord: WebMappingRetrieve<DuplicateRecord_Select,DuplicateRecord_Expand,DuplicateRecord_Filter,DuplicateRecord_Fixed,DuplicateRecord_Result,DuplicateRecord_FormattedResult>;
  Fax_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  Fax_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  Fax_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  fax_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  fax_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  fax_campaignresponse: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  fax_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  fax_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  fax_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_fax: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_fax: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  faxes: WebMappingRetrieve<Fax_Select,Fax_Expand,Fax_Filter,Fax_Fixed,Fax_Result,Fax_FormattedResult>;
}
interface WebEntitiesRelated {
  faxes: WebMappingRelated<Fax_RelatedOne,Fax_RelatedMany>;
}
interface WebEntitiesCUDA {
  faxes: WebMappingCUDA<Fax_Create,Fax_Update,Fax_Select>;
}
