interface ServiceAppointment_Base extends WebEntity {
  activityadditionalparams?: string | null;
  activityid?: string | null;
  activitytypecode?: string | null;
  actualdurationminutes?: number | null;
  actualend?: Date | null;
  actualstart?: Date | null;
  category?: string | null;
  community?: socialprofile_community | null;
  createdon?: Date | null;
  deliverylastattemptedon?: Date | null;
  deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
  description?: string | null;
  exchangeitemid?: string | null;
  exchangerate?: number | null;
  exchangeweblink?: string | null;
  importsequencenumber?: number | null;
  instancetypecode?: none_serviceappointment_instancetypecode | null;
  isalldayevent?: boolean | null;
  isbilled?: boolean | null;
  ismapiprivate?: boolean | null;
  isregularactivity?: boolean | null;
  isworkflowcreated?: boolean | null;
  lastonholdtime?: Date | null;
  leftvoicemail?: boolean | null;
  location?: string | null;
  modifiedon?: Date | null;
  onholdtime?: number | null;
  overriddencreatedon?: Date | null;
  postponeactivityprocessinguntil?: Date | null;
  prioritycode?: serviceappointment_prioritycode | null;
  processid?: string | null;
  scheduleddurationminutes?: number | null;
  scheduledend?: Date | null;
  scheduledstart?: Date | null;
  senton?: Date | null;
  seriesid?: string | null;
  sortdate?: Date | null;
  stageid?: string | null;
  statecode?: serviceappointment_statecode | null;
  statuscode?: serviceappointment_statuscode | null;
  subcategory?: string | null;
  subject?: string | null;
  subscriptionid?: string | null;
  timezoneruleversionnumber?: number | null;
  traversedpath?: string | null;
  utcconversiontimezonecode?: number | null;
  versionnumber?: number | null;
}
interface ServiceAppointment_Relationships {
  CampaignResponse_ServiceAppointments?: CampaignResponse_Result[] | null;
  SLAId?: SLA_Result | null;
  ServiceAppointment_Annotation?: Annotation_Result[] | null;
  ServiceAppointment_AsyncOperations?: AsyncOperation_Result[] | null;
  ServiceAppointment_BulkDeleteFailures?: BulkDeleteFailure_Result[] | null;
  ServiceAppointment_ProcessSessions?: ProcessSession_Result[] | null;
  ServiceAppointment_QueueItem?: QueueItem_Result[] | null;
  ServiceAppointment_SyncErrors?: SyncError_Result[] | null;
  activityid_activitypointer?: ActivityPointer_Result | null;
  createdby_serviceappointment?: SystemUser_Result | null;
  createdonbehalfby_serviceappointment?: SystemUser_Result | null;
  modifiedby_serviceappointment?: SystemUser_Result | null;
  modifiedonbehalfby_serviceappointment?: SystemUser_Result | null;
  ownerid_serviceappointment?: Team_Result | null;
  ownerid_serviceappointment1?: SystemUser_Result | null;
  owningbusinessunit_serviceappointment?: BusinessUnit_Result | null;
  owningteam_serviceappointment?: Team_Result | null;
  owninguser_serviceappointment?: SystemUser_Result | null;
  regardingobjectid_account_serviceappointment?: Account_Result | null;
  regardingobjectid_awc_prototype_serviceappointment?: awc_prototype_Result | null;
  regardingobjectid_awcnpd_idea_serviceappointment?: awcnpd_idea_Result | null;
  regardingobjectid_awcnpd_prototype_serviceappointment?: awcnpd_prototype_Result | null;
  regardingobjectid_bookableresourcebooking_serviceappointment?: BookableResourceBooking_Result | null;
  regardingobjectid_bookableresourcebookingheader_serviceappointment?: BookableResourceBookingHeader_Result | null;
  regardingobjectid_bulkoperation_serviceappointment?: BulkOperation_Result | null;
  regardingobjectid_campaign_serviceappointment?: Campaign_Result | null;
  regardingobjectid_campaignactivity_serviceappointment?: CampaignActivity_Result | null;
  regardingobjectid_contact_serviceappointment?: Contact_Result | null;
  regardingobjectid_contract_serviceappointment?: Contract_Result | null;
  regardingobjectid_entitlement_serviceappointment?: Entitlement_Result | null;
  regardingobjectid_entitlementtemplate_serviceappointment?: EntitlementTemplate_Result | null;
  regardingobjectid_incident_serviceappointment?: Incident_Result | null;
  regardingobjectid_invoice_serviceappointment?: Invoice_Result | null;
  regardingobjectid_knowledgearticle_serviceappointment?: KnowledgeArticle_Result | null;
  regardingobjectid_knowledgebaserecord_serviceappointment?: KnowledgeBaseRecord_Result | null;
  regardingobjectid_lead_serviceappointment?: Lead_Result | null;
  regardingobjectid_msdyn_playbookinstance_serviceappointment?: msdyn_playbookinstance_Result | null;
  regardingobjectid_msdyn_postalbum_serviceappointment?: msdyn_PostAlbum_Result | null;
  regardingobjectid_new_interactionforemail_serviceappointment?: InteractionForEmail_Result | null;
  regardingobjectid_opportunity_serviceappointment?: Opportunity_Result | null;
  regardingobjectid_quote_serviceappointment?: Quote_Result | null;
  regardingobjectid_salesorder_serviceappointment?: SalesOrder_Result | null;
  regardingobjectid_site_serviceappointment?: Site_Result | null;
  sendermailboxid_serviceappointment?: Mailbox_Result | null;
  serviceappointment_MailboxTrackingFolders?: MailboxTrackingFolder_Result[] | null;
  serviceappointment_actioncard?: ActionCard_Result[] | null;
  serviceappointment_activity_parties?: ActivityParty_Result[] | null;
  serviceappointment_connections1?: Connection_Result[] | null;
  serviceappointment_connections2?: Connection_Result[] | null;
  serviceappointment_principalobjectattributeaccess?: PrincipalObjectAttributeAccess_Result[] | null;
  serviceid_serviceappointment?: Service_Result | null;
  slainvokedid_serviceappointment_sla?: SLA_Result | null;
  slakpiinstance_serviceappointment?: SLAKPIInstance_Result[] | null;
  transactioncurrencyid_serviceappointment?: TransactionCurrency_Result | null;
  userentityinstancedata_serviceappointment?: UserEntityInstanceData_Result[] | null;
}
interface ServiceAppointment extends ServiceAppointment_Base, ServiceAppointment_Relationships {
  SLAId_bind$slas?: string | null;
  ownerid_serviceappointment_bind$systemusers?: string | null;
  ownerid_serviceappointment_bind$teams?: string | null;
  regardingobjectid_account_serviceappointment_bind$accounts?: string | null;
  regardingobjectid_awc_prototype_serviceappointment_bind$awc_prototypes?: string | null;
  regardingobjectid_awcnpd_idea_serviceappointment_bind$awcnpd_ideas?: string | null;
  regardingobjectid_awcnpd_prototype_serviceappointment_bind$awcnpd_prototypes?: string | null;
  regardingobjectid_bookableresourcebooking_serviceappointment_bind$bookableresourcebookings?: string | null;
  regardingobjectid_bookableresourcebookingheader_serviceappointment_bind$bookableresourcebookingheaders?: string | null;
  regardingobjectid_bulkoperation_serviceappointment_bind$bulkoperations?: string | null;
  regardingobjectid_campaign_serviceappointment_bind$campaigns?: string | null;
  regardingobjectid_campaignactivity_serviceappointment_bind$campaignactivities?: string | null;
  regardingobjectid_contact_serviceappointment_bind$contacts?: string | null;
  regardingobjectid_contract_serviceappointment_bind$contracts?: string | null;
  regardingobjectid_entitlement_serviceappointment_bind$entitlements?: string | null;
  regardingobjectid_entitlementtemplate_serviceappointment_bind$entitlementtemplates?: string | null;
  regardingobjectid_incident_serviceappointment_bind$incidents?: string | null;
  regardingobjectid_invoice_serviceappointment_bind$invoices?: string | null;
  regardingobjectid_knowledgearticle_serviceappointment_bind$knowledgearticles?: string | null;
  regardingobjectid_knowledgebaserecord_serviceappointment_bind$knowledgebaserecords?: string | null;
  regardingobjectid_lead_serviceappointment_bind$leads?: string | null;
  regardingobjectid_msdyn_playbookinstance_serviceappointment_bind$msdyn_playbookinstances?: string | null;
  regardingobjectid_msdyn_postalbum_serviceappointment_bind$msdyn_postalbums?: string | null;
  regardingobjectid_new_interactionforemail_serviceappointment_bind$interactionforemails?: string | null;
  regardingobjectid_opportunity_serviceappointment_bind$opportunities?: string | null;
  regardingobjectid_quote_serviceappointment_bind$quotes?: string | null;
  regardingobjectid_salesorder_serviceappointment_bind$salesorders?: string | null;
  regardingobjectid_site_serviceappointment_bind$sites?: string | null;
  serviceid_serviceappointment_bind$services?: string | null;
  siteid_bind$sites?: string | null;
  transactioncurrencyid_serviceappointment_bind$transactioncurrencies?: string | null;
}
interface ServiceAppointment_Create extends ServiceAppointment {
  activityid_activitypointer_bind$activitypointers?: string | null;
}
interface ServiceAppointment_Update extends ServiceAppointment {
}
interface ServiceAppointment_Select {
  activityadditionalparams: WebAttribute<ServiceAppointment_Select, { activityadditionalparams: string | null }, {  }>;
  activityid: WebAttribute<ServiceAppointment_Select, { activityid: string | null }, {  }>;
  activitytypecode: WebAttribute<ServiceAppointment_Select, { activitytypecode: string | null }, {  }>;
  actualdurationminutes: WebAttribute<ServiceAppointment_Select, { actualdurationminutes: number | null }, {  }>;
  actualend: WebAttribute<ServiceAppointment_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
  actualstart: WebAttribute<ServiceAppointment_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
  bcc_guid: WebAttribute<ServiceAppointment_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
  category: WebAttribute<ServiceAppointment_Select, { category: string | null }, {  }>;
  cc_guid: WebAttribute<ServiceAppointment_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
  community: WebAttribute<ServiceAppointment_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
  createdby_guid: WebAttribute<ServiceAppointment_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
  createdon: WebAttribute<ServiceAppointment_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
  createdonbehalfby_guid: WebAttribute<ServiceAppointment_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
  customers_guid: WebAttribute<ServiceAppointment_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
  deliverylastattemptedon: WebAttribute<ServiceAppointment_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
  deliveryprioritycode: WebAttribute<ServiceAppointment_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
  description: WebAttribute<ServiceAppointment_Select, { description: string | null }, {  }>;
  exchangeitemid: WebAttribute<ServiceAppointment_Select, { exchangeitemid: string | null }, {  }>;
  exchangerate: WebAttribute<ServiceAppointment_Select, { exchangerate: number | null }, {  }>;
  exchangeweblink: WebAttribute<ServiceAppointment_Select, { exchangeweblink: string | null }, {  }>;
  from_guid: WebAttribute<ServiceAppointment_Select, { from_guid: string | null }, { from_formatted?: string }>;
  importsequencenumber: WebAttribute<ServiceAppointment_Select, { importsequencenumber: number | null }, {  }>;
  instancetypecode: WebAttribute<ServiceAppointment_Select, { instancetypecode: none_serviceappointment_instancetypecode | null }, { instancetypecode_formatted?: string }>;
  isalldayevent: WebAttribute<ServiceAppointment_Select, { isalldayevent: boolean | null }, {  }>;
  isbilled: WebAttribute<ServiceAppointment_Select, { isbilled: boolean | null }, {  }>;
  ismapiprivate: WebAttribute<ServiceAppointment_Select, { ismapiprivate: boolean | null }, {  }>;
  isregularactivity: WebAttribute<ServiceAppointment_Select, { isregularactivity: boolean | null }, {  }>;
  isworkflowcreated: WebAttribute<ServiceAppointment_Select, { isworkflowcreated: boolean | null }, {  }>;
  lastonholdtime: WebAttribute<ServiceAppointment_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
  leftvoicemail: WebAttribute<ServiceAppointment_Select, { leftvoicemail: boolean | null }, {  }>;
  location: WebAttribute<ServiceAppointment_Select, { location: string | null }, {  }>;
  modifiedby_guid: WebAttribute<ServiceAppointment_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
  modifiedon: WebAttribute<ServiceAppointment_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
  modifiedonbehalfby_guid: WebAttribute<ServiceAppointment_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
  onholdtime: WebAttribute<ServiceAppointment_Select, { onholdtime: number | null }, {  }>;
  optionalattendees_guid: WebAttribute<ServiceAppointment_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
  organizer_guid: WebAttribute<ServiceAppointment_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
  overriddencreatedon: WebAttribute<ServiceAppointment_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
  ownerid_guid: WebAttribute<ServiceAppointment_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
  owningbusinessunit_guid: WebAttribute<ServiceAppointment_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
  owningteam_guid: WebAttribute<ServiceAppointment_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
  owninguser_guid: WebAttribute<ServiceAppointment_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
  partners_guid: WebAttribute<ServiceAppointment_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
  postponeactivityprocessinguntil: WebAttribute<ServiceAppointment_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
  prioritycode: WebAttribute<ServiceAppointment_Select, { prioritycode: serviceappointment_prioritycode | null }, { prioritycode_formatted?: string }>;
  processid: WebAttribute<ServiceAppointment_Select, { processid: string | null }, {  }>;
  regardingobjectid_guid: WebAttribute<ServiceAppointment_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
  requiredattendees_guid: WebAttribute<ServiceAppointment_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
  resources_guid: WebAttribute<ServiceAppointment_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
  scheduleddurationminutes: WebAttribute<ServiceAppointment_Select, { scheduleddurationminutes: number | null }, {  }>;
  scheduledend: WebAttribute<ServiceAppointment_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
  scheduledstart: WebAttribute<ServiceAppointment_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
  sendermailboxid_guid: WebAttribute<ServiceAppointment_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
  senton: WebAttribute<ServiceAppointment_Select, { senton: Date | null }, { senton_formatted?: string }>;
  seriesid: WebAttribute<ServiceAppointment_Select, { seriesid: string | null }, {  }>;
  serviceid_guid: WebAttribute<ServiceAppointment_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
  siteid_guid: WebAttribute<ServiceAppointment_Select, { siteid_guid: string | null }, { siteid_formatted?: string }>;
  slaid_guid: WebAttribute<ServiceAppointment_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
  slainvokedid_guid: WebAttribute<ServiceAppointment_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
  sortdate: WebAttribute<ServiceAppointment_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
  stageid: WebAttribute<ServiceAppointment_Select, { stageid: string | null }, {  }>;
  statecode: WebAttribute<ServiceAppointment_Select, { statecode: serviceappointment_statecode | null }, { statecode_formatted?: string }>;
  statuscode: WebAttribute<ServiceAppointment_Select, { statuscode: serviceappointment_statuscode | null }, { statuscode_formatted?: string }>;
  subcategory: WebAttribute<ServiceAppointment_Select, { subcategory: string | null }, {  }>;
  subject: WebAttribute<ServiceAppointment_Select, { subject: string | null }, {  }>;
  subscriptionid: WebAttribute<ServiceAppointment_Select, { subscriptionid: string | null }, {  }>;
  timezoneruleversionnumber: WebAttribute<ServiceAppointment_Select, { timezoneruleversionnumber: number | null }, {  }>;
  to_guid: WebAttribute<ServiceAppointment_Select, { to_guid: string | null }, { to_formatted?: string }>;
  transactioncurrencyid_guid: WebAttribute<ServiceAppointment_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
  traversedpath: WebAttribute<ServiceAppointment_Select, { traversedpath: string | null }, {  }>;
  utcconversiontimezonecode: WebAttribute<ServiceAppointment_Select, { utcconversiontimezonecode: number | null }, {  }>;
  versionnumber: WebAttribute<ServiceAppointment_Select, { versionnumber: number | null }, {  }>;
}
interface ServiceAppointment_Filter {
  activityadditionalparams: string;
  activityid: XQW.Guid;
  activitytypecode: string;
  actualdurationminutes: number;
  actualend: Date;
  actualstart: Date;
  bcc_guid: XQW.Guid;
  category: string;
  cc_guid: XQW.Guid;
  community: socialprofile_community;
  createdby_guid: XQW.Guid;
  createdon: Date;
  createdonbehalfby_guid: XQW.Guid;
  customers_guid: XQW.Guid;
  deliverylastattemptedon: Date;
  deliveryprioritycode: activitypointer_deliveryprioritycode;
  description: string;
  exchangeitemid: string;
  exchangerate: any;
  exchangeweblink: string;
  from_guid: XQW.Guid;
  importsequencenumber: number;
  instancetypecode: none_serviceappointment_instancetypecode;
  isalldayevent: boolean;
  isbilled: boolean;
  ismapiprivate: boolean;
  isregularactivity: boolean;
  isworkflowcreated: boolean;
  lastonholdtime: Date;
  leftvoicemail: boolean;
  location: string;
  modifiedby_guid: XQW.Guid;
  modifiedon: Date;
  modifiedonbehalfby_guid: XQW.Guid;
  onholdtime: number;
  optionalattendees_guid: XQW.Guid;
  organizer_guid: XQW.Guid;
  overriddencreatedon: Date;
  ownerid_guid: XQW.Guid;
  owningbusinessunit_guid: XQW.Guid;
  owningteam_guid: XQW.Guid;
  owninguser_guid: XQW.Guid;
  partners_guid: XQW.Guid;
  postponeactivityprocessinguntil: Date;
  prioritycode: serviceappointment_prioritycode;
  processid: XQW.Guid;
  regardingobjectid_guid: XQW.Guid;
  requiredattendees_guid: XQW.Guid;
  resources_guid: XQW.Guid;
  scheduleddurationminutes: number;
  scheduledend: Date;
  scheduledstart: Date;
  sendermailboxid_guid: XQW.Guid;
  senton: Date;
  seriesid: XQW.Guid;
  serviceid_guid: XQW.Guid;
  siteid_guid: XQW.Guid;
  slaid_guid: XQW.Guid;
  slainvokedid_guid: XQW.Guid;
  sortdate: Date;
  stageid: XQW.Guid;
  statecode: serviceappointment_statecode;
  statuscode: serviceappointment_statuscode;
  subcategory: string;
  subject: string;
  subscriptionid: XQW.Guid;
  timezoneruleversionnumber: number;
  to_guid: XQW.Guid;
  transactioncurrencyid_guid: XQW.Guid;
  traversedpath: string;
  utcconversiontimezonecode: number;
  versionnumber: number;
}
interface ServiceAppointment_Expand {
  CampaignResponse_ServiceAppointments: WebExpand<ServiceAppointment_Expand, CampaignResponse_Select, CampaignResponse_Filter, { CampaignResponse_ServiceAppointments: CampaignResponse_Result[] }>;
  SLAId: WebExpand<ServiceAppointment_Expand, SLA_Select, SLA_Filter, { SLAId: SLA_Result }>;
  ServiceAppointment_Annotation: WebExpand<ServiceAppointment_Expand, Annotation_Select, Annotation_Filter, { ServiceAppointment_Annotation: Annotation_Result[] }>;
  ServiceAppointment_AsyncOperations: WebExpand<ServiceAppointment_Expand, AsyncOperation_Select, AsyncOperation_Filter, { ServiceAppointment_AsyncOperations: AsyncOperation_Result[] }>;
  ServiceAppointment_BulkDeleteFailures: WebExpand<ServiceAppointment_Expand, BulkDeleteFailure_Select, BulkDeleteFailure_Filter, { ServiceAppointment_BulkDeleteFailures: BulkDeleteFailure_Result[] }>;
  ServiceAppointment_ProcessSessions: WebExpand<ServiceAppointment_Expand, ProcessSession_Select, ProcessSession_Filter, { ServiceAppointment_ProcessSessions: ProcessSession_Result[] }>;
  ServiceAppointment_QueueItem: WebExpand<ServiceAppointment_Expand, QueueItem_Select, QueueItem_Filter, { ServiceAppointment_QueueItem: QueueItem_Result[] }>;
  ServiceAppointment_SyncErrors: WebExpand<ServiceAppointment_Expand, SyncError_Select, SyncError_Filter, { ServiceAppointment_SyncErrors: SyncError_Result[] }>;
  activityid_activitypointer: WebExpand<ServiceAppointment_Expand, ActivityPointer_Select, ActivityPointer_Filter, { activityid_activitypointer: ActivityPointer_Result }>;
  createdby_serviceappointment: WebExpand<ServiceAppointment_Expand, SystemUser_Select, SystemUser_Filter, { createdby_serviceappointment: SystemUser_Result }>;
  createdonbehalfby_serviceappointment: WebExpand<ServiceAppointment_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby_serviceappointment: SystemUser_Result }>;
  modifiedby_serviceappointment: WebExpand<ServiceAppointment_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby_serviceappointment: SystemUser_Result }>;
  modifiedonbehalfby_serviceappointment: WebExpand<ServiceAppointment_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby_serviceappointment: SystemUser_Result }>;
  ownerid_serviceappointment: WebExpand<ServiceAppointment_Expand, SystemUser_Select & Team_Select, SystemUser_Filter & Team_Filter, { ownerid_serviceappointment: SystemUser_Result } & { ownerid_serviceappointment: Team_Result }>;
  owningbusinessunit_serviceappointment: WebExpand<ServiceAppointment_Expand, BusinessUnit_Select, BusinessUnit_Filter, { owningbusinessunit_serviceappointment: BusinessUnit_Result }>;
  owningteam_serviceappointment: WebExpand<ServiceAppointment_Expand, Team_Select, Team_Filter, { owningteam_serviceappointment: Team_Result }>;
  owninguser_serviceappointment: WebExpand<ServiceAppointment_Expand, SystemUser_Select, SystemUser_Filter, { owninguser_serviceappointment: SystemUser_Result }>;
  regardingobjectid_account_serviceappointment: WebExpand<ServiceAppointment_Expand, Account_Select, Account_Filter, { regardingobjectid_account_serviceappointment: Account_Result }>;
  regardingobjectid_awc_prototype_serviceappointment: WebExpand<ServiceAppointment_Expand, awc_prototype_Select, awc_prototype_Filter, { regardingobjectid_awc_prototype_serviceappointment: awc_prototype_Result }>;
  regardingobjectid_awcnpd_idea_serviceappointment: WebExpand<ServiceAppointment_Expand, awcnpd_idea_Select, awcnpd_idea_Filter, { regardingobjectid_awcnpd_idea_serviceappointment: awcnpd_idea_Result }>;
  regardingobjectid_awcnpd_prototype_serviceappointment: WebExpand<ServiceAppointment_Expand, awcnpd_prototype_Select, awcnpd_prototype_Filter, { regardingobjectid_awcnpd_prototype_serviceappointment: awcnpd_prototype_Result }>;
  regardingobjectid_bookableresourcebooking_serviceappointment: WebExpand<ServiceAppointment_Expand, BookableResourceBooking_Select, BookableResourceBooking_Filter, { regardingobjectid_bookableresourcebooking_serviceappointment: BookableResourceBooking_Result }>;
  regardingobjectid_bookableresourcebookingheader_serviceappointment: WebExpand<ServiceAppointment_Expand, BookableResourceBookingHeader_Select, BookableResourceBookingHeader_Filter, { regardingobjectid_bookableresourcebookingheader_serviceappointment: BookableResourceBookingHeader_Result }>;
  regardingobjectid_bulkoperation_serviceappointment: WebExpand<ServiceAppointment_Expand, BulkOperation_Select, BulkOperation_Filter, { regardingobjectid_bulkoperation_serviceappointment: BulkOperation_Result }>;
  regardingobjectid_campaign_serviceappointment: WebExpand<ServiceAppointment_Expand, Campaign_Select, Campaign_Filter, { regardingobjectid_campaign_serviceappointment: Campaign_Result }>;
  regardingobjectid_campaignactivity_serviceappointment: WebExpand<ServiceAppointment_Expand, CampaignActivity_Select, CampaignActivity_Filter, { regardingobjectid_campaignactivity_serviceappointment: CampaignActivity_Result }>;
  regardingobjectid_contact_serviceappointment: WebExpand<ServiceAppointment_Expand, Contact_Select, Contact_Filter, { regardingobjectid_contact_serviceappointment: Contact_Result }>;
  regardingobjectid_contract_serviceappointment: WebExpand<ServiceAppointment_Expand, Contract_Select, Contract_Filter, { regardingobjectid_contract_serviceappointment: Contract_Result }>;
  regardingobjectid_entitlement_serviceappointment: WebExpand<ServiceAppointment_Expand, Entitlement_Select, Entitlement_Filter, { regardingobjectid_entitlement_serviceappointment: Entitlement_Result }>;
  regardingobjectid_entitlementtemplate_serviceappointment: WebExpand<ServiceAppointment_Expand, EntitlementTemplate_Select, EntitlementTemplate_Filter, { regardingobjectid_entitlementtemplate_serviceappointment: EntitlementTemplate_Result }>;
  regardingobjectid_incident_serviceappointment: WebExpand<ServiceAppointment_Expand, Incident_Select, Incident_Filter, { regardingobjectid_incident_serviceappointment: Incident_Result }>;
  regardingobjectid_invoice_serviceappointment: WebExpand<ServiceAppointment_Expand, Invoice_Select, Invoice_Filter, { regardingobjectid_invoice_serviceappointment: Invoice_Result }>;
  regardingobjectid_knowledgearticle_serviceappointment: WebExpand<ServiceAppointment_Expand, KnowledgeArticle_Select, KnowledgeArticle_Filter, { regardingobjectid_knowledgearticle_serviceappointment: KnowledgeArticle_Result }>;
  regardingobjectid_knowledgebaserecord_serviceappointment: WebExpand<ServiceAppointment_Expand, KnowledgeBaseRecord_Select, KnowledgeBaseRecord_Filter, { regardingobjectid_knowledgebaserecord_serviceappointment: KnowledgeBaseRecord_Result }>;
  regardingobjectid_lead_serviceappointment: WebExpand<ServiceAppointment_Expand, Lead_Select, Lead_Filter, { regardingobjectid_lead_serviceappointment: Lead_Result }>;
  regardingobjectid_msdyn_playbookinstance_serviceappointment: WebExpand<ServiceAppointment_Expand, msdyn_playbookinstance_Select, msdyn_playbookinstance_Filter, { regardingobjectid_msdyn_playbookinstance_serviceappointment: msdyn_playbookinstance_Result }>;
  regardingobjectid_msdyn_postalbum_serviceappointment: WebExpand<ServiceAppointment_Expand, msdyn_PostAlbum_Select, msdyn_PostAlbum_Filter, { regardingobjectid_msdyn_postalbum_serviceappointment: msdyn_PostAlbum_Result }>;
  regardingobjectid_new_interactionforemail_serviceappointment: WebExpand<ServiceAppointment_Expand, InteractionForEmail_Select, InteractionForEmail_Filter, { regardingobjectid_new_interactionforemail_serviceappointment: InteractionForEmail_Result }>;
  regardingobjectid_opportunity_serviceappointment: WebExpand<ServiceAppointment_Expand, Opportunity_Select, Opportunity_Filter, { regardingobjectid_opportunity_serviceappointment: Opportunity_Result }>;
  regardingobjectid_quote_serviceappointment: WebExpand<ServiceAppointment_Expand, Quote_Select, Quote_Filter, { regardingobjectid_quote_serviceappointment: Quote_Result }>;
  regardingobjectid_salesorder_serviceappointment: WebExpand<ServiceAppointment_Expand, SalesOrder_Select, SalesOrder_Filter, { regardingobjectid_salesorder_serviceappointment: SalesOrder_Result }>;
  regardingobjectid_site_serviceappointment: WebExpand<ServiceAppointment_Expand, Site_Select, Site_Filter, { regardingobjectid_site_serviceappointment: Site_Result }>;
  sendermailboxid_serviceappointment: WebExpand<ServiceAppointment_Expand, Mailbox_Select, Mailbox_Filter, { sendermailboxid_serviceappointment: Mailbox_Result }>;
  serviceappointment_MailboxTrackingFolders: WebExpand<ServiceAppointment_Expand, MailboxTrackingFolder_Select, MailboxTrackingFolder_Filter, { serviceappointment_MailboxTrackingFolders: MailboxTrackingFolder_Result[] }>;
  serviceappointment_actioncard: WebExpand<ServiceAppointment_Expand, ActionCard_Select, ActionCard_Filter, { serviceappointment_actioncard: ActionCard_Result[] }>;
  serviceappointment_activity_parties: WebExpand<ServiceAppointment_Expand, ActivityParty_Select, ActivityParty_Filter, { serviceappointment_activity_parties: ActivityParty_Result[] }>;
  serviceappointment_connections1: WebExpand<ServiceAppointment_Expand, Connection_Select, Connection_Filter, { serviceappointment_connections1: Connection_Result[] }>;
  serviceappointment_connections2: WebExpand<ServiceAppointment_Expand, Connection_Select, Connection_Filter, { serviceappointment_connections2: Connection_Result[] }>;
  serviceappointment_principalobjectattributeaccess: WebExpand<ServiceAppointment_Expand, PrincipalObjectAttributeAccess_Select, PrincipalObjectAttributeAccess_Filter, { serviceappointment_principalobjectattributeaccess: PrincipalObjectAttributeAccess_Result[] }>;
  serviceid_serviceappointment: WebExpand<ServiceAppointment_Expand, Service_Select, Service_Filter, { serviceid_serviceappointment: Service_Result }>;
  siteid: WebExpand<ServiceAppointment_Expand, Site_Select, Site_Filter, { siteid: Site_Result }>;
  slainvokedid_serviceappointment_sla: WebExpand<ServiceAppointment_Expand, SLA_Select, SLA_Filter, { slainvokedid_serviceappointment_sla: SLA_Result }>;
  slakpiinstance_serviceappointment: WebExpand<ServiceAppointment_Expand, SLAKPIInstance_Select, SLAKPIInstance_Filter, { slakpiinstance_serviceappointment: SLAKPIInstance_Result[] }>;
  transactioncurrencyid_serviceappointment: WebExpand<ServiceAppointment_Expand, TransactionCurrency_Select, TransactionCurrency_Filter, { transactioncurrencyid_serviceappointment: TransactionCurrency_Result }>;
  userentityinstancedata_serviceappointment: WebExpand<ServiceAppointment_Expand, UserEntityInstanceData_Select, UserEntityInstanceData_Filter, { userentityinstancedata_serviceappointment: UserEntityInstanceData_Result[] }>;
}
interface ServiceAppointment_FormattedResult {
  actualend_formatted?: string;
  actualstart_formatted?: string;
  bcc_formatted?: string;
  cc_formatted?: string;
  community_formatted?: string;
  createdby_formatted?: string;
  createdon_formatted?: string;
  createdonbehalfby_formatted?: string;
  customers_formatted?: string;
  deliverylastattemptedon_formatted?: string;
  deliveryprioritycode_formatted?: string;
  from_formatted?: string;
  instancetypecode_formatted?: string;
  lastonholdtime_formatted?: string;
  modifiedby_formatted?: string;
  modifiedon_formatted?: string;
  modifiedonbehalfby_formatted?: string;
  optionalattendees_formatted?: string;
  organizer_formatted?: string;
  overriddencreatedon_formatted?: string;
  ownerid_formatted?: string;
  owningbusinessunit_formatted?: string;
  owningteam_formatted?: string;
  owninguser_formatted?: string;
  partners_formatted?: string;
  postponeactivityprocessinguntil_formatted?: string;
  prioritycode_formatted?: string;
  regardingobjectid_formatted?: string;
  requiredattendees_formatted?: string;
  resources_formatted?: string;
  scheduledend_formatted?: string;
  scheduledstart_formatted?: string;
  sendermailboxid_formatted?: string;
  senton_formatted?: string;
  serviceid_formatted?: string;
  siteid_formatted?: string;
  slaid_formatted?: string;
  slainvokedid_formatted?: string;
  sortdate_formatted?: string;
  statecode_formatted?: string;
  statuscode_formatted?: string;
  to_formatted?: string;
  transactioncurrencyid_formatted?: string;
}
interface ServiceAppointment_Result extends ServiceAppointment_Base, ServiceAppointment_Relationships {
  "@odata.etag": string;
  bcc_guid: string | null;
  cc_guid: string | null;
  createdby_guid: string | null;
  createdonbehalfby_guid: string | null;
  customers_guid: string | null;
  from_guid: string | null;
  modifiedby_guid: string | null;
  modifiedonbehalfby_guid: string | null;
  optionalattendees_guid: string | null;
  organizer_guid: string | null;
  ownerid_guid: string | null;
  owningbusinessunit_guid: string | null;
  owningteam_guid: string | null;
  owninguser_guid: string | null;
  partners_guid: string | null;
  regardingobjectid_guid: string | null;
  requiredattendees_guid: string | null;
  resources_guid: string | null;
  sendermailboxid_guid: string | null;
  serviceid_guid: string | null;
  siteid_guid: string | null;
  slaid_guid: string | null;
  slainvokedid_guid: string | null;
  to_guid: string | null;
  transactioncurrencyid_guid: string | null;
}
interface ServiceAppointment_RelatedOne {
  SLAId: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  activityid_activitypointer: WebMappingRetrieve<ActivityPointer_Select,ActivityPointer_Expand,ActivityPointer_Filter,ActivityPointer_Fixed,ActivityPointer_Result,ActivityPointer_FormattedResult>;
  createdby_serviceappointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  createdonbehalfby_serviceappointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedby_serviceappointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  modifiedonbehalfby_serviceappointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  ownerid_serviceappointment: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  ownerid_serviceappointment1: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  owningbusinessunit_serviceappointment: WebMappingRetrieve<BusinessUnit_Select,BusinessUnit_Expand,BusinessUnit_Filter,BusinessUnit_Fixed,BusinessUnit_Result,BusinessUnit_FormattedResult>;
  owningteam_serviceappointment: WebMappingRetrieve<Team_Select,Team_Expand,Team_Filter,Team_Fixed,Team_Result,Team_FormattedResult>;
  owninguser_serviceappointment: WebMappingRetrieve<SystemUser_Select,SystemUser_Expand,SystemUser_Filter,SystemUser_Fixed,SystemUser_Result,SystemUser_FormattedResult>;
  regardingobjectid_account_serviceappointment: WebMappingRetrieve<Account_Select,Account_Expand,Account_Filter,Account_Fixed,Account_Result,Account_FormattedResult>;
  regardingobjectid_awc_prototype_serviceappointment: WebMappingRetrieve<awc_prototype_Select,awc_prototype_Expand,awc_prototype_Filter,awc_prototype_Fixed,awc_prototype_Result,awc_prototype_FormattedResult>;
  regardingobjectid_awcnpd_idea_serviceappointment: WebMappingRetrieve<awcnpd_idea_Select,awcnpd_idea_Expand,awcnpd_idea_Filter,awcnpd_idea_Fixed,awcnpd_idea_Result,awcnpd_idea_FormattedResult>;
  regardingobjectid_awcnpd_prototype_serviceappointment: WebMappingRetrieve<awcnpd_prototype_Select,awcnpd_prototype_Expand,awcnpd_prototype_Filter,awcnpd_prototype_Fixed,awcnpd_prototype_Result,awcnpd_prototype_FormattedResult>;
  regardingobjectid_bookableresourcebooking_serviceappointment: WebMappingRetrieve<BookableResourceBooking_Select,BookableResourceBooking_Expand,BookableResourceBooking_Filter,BookableResourceBooking_Fixed,BookableResourceBooking_Result,BookableResourceBooking_FormattedResult>;
  regardingobjectid_bookableresourcebookingheader_serviceappointment: WebMappingRetrieve<BookableResourceBookingHeader_Select,BookableResourceBookingHeader_Expand,BookableResourceBookingHeader_Filter,BookableResourceBookingHeader_Fixed,BookableResourceBookingHeader_Result,BookableResourceBookingHeader_FormattedResult>;
  regardingobjectid_bulkoperation_serviceappointment: WebMappingRetrieve<BulkOperation_Select,BulkOperation_Expand,BulkOperation_Filter,BulkOperation_Fixed,BulkOperation_Result,BulkOperation_FormattedResult>;
  regardingobjectid_campaign_serviceappointment: WebMappingRetrieve<Campaign_Select,Campaign_Expand,Campaign_Filter,Campaign_Fixed,Campaign_Result,Campaign_FormattedResult>;
  regardingobjectid_campaignactivity_serviceappointment: WebMappingRetrieve<CampaignActivity_Select,CampaignActivity_Expand,CampaignActivity_Filter,CampaignActivity_Fixed,CampaignActivity_Result,CampaignActivity_FormattedResult>;
  regardingobjectid_contact_serviceappointment: WebMappingRetrieve<Contact_Select,Contact_Expand,Contact_Filter,Contact_Fixed,Contact_Result,Contact_FormattedResult>;
  regardingobjectid_contract_serviceappointment: WebMappingRetrieve<Contract_Select,Contract_Expand,Contract_Filter,Contract_Fixed,Contract_Result,Contract_FormattedResult>;
  regardingobjectid_entitlement_serviceappointment: WebMappingRetrieve<Entitlement_Select,Entitlement_Expand,Entitlement_Filter,Entitlement_Fixed,Entitlement_Result,Entitlement_FormattedResult>;
  regardingobjectid_entitlementtemplate_serviceappointment: WebMappingRetrieve<EntitlementTemplate_Select,EntitlementTemplate_Expand,EntitlementTemplate_Filter,EntitlementTemplate_Fixed,EntitlementTemplate_Result,EntitlementTemplate_FormattedResult>;
  regardingobjectid_incident_serviceappointment: WebMappingRetrieve<Incident_Select,Incident_Expand,Incident_Filter,Incident_Fixed,Incident_Result,Incident_FormattedResult>;
  regardingobjectid_invoice_serviceappointment: WebMappingRetrieve<Invoice_Select,Invoice_Expand,Invoice_Filter,Invoice_Fixed,Invoice_Result,Invoice_FormattedResult>;
  regardingobjectid_knowledgearticle_serviceappointment: WebMappingRetrieve<KnowledgeArticle_Select,KnowledgeArticle_Expand,KnowledgeArticle_Filter,KnowledgeArticle_Fixed,KnowledgeArticle_Result,KnowledgeArticle_FormattedResult>;
  regardingobjectid_knowledgebaserecord_serviceappointment: WebMappingRetrieve<KnowledgeBaseRecord_Select,KnowledgeBaseRecord_Expand,KnowledgeBaseRecord_Filter,KnowledgeBaseRecord_Fixed,KnowledgeBaseRecord_Result,KnowledgeBaseRecord_FormattedResult>;
  regardingobjectid_lead_serviceappointment: WebMappingRetrieve<Lead_Select,Lead_Expand,Lead_Filter,Lead_Fixed,Lead_Result,Lead_FormattedResult>;
  regardingobjectid_msdyn_playbookinstance_serviceappointment: WebMappingRetrieve<msdyn_playbookinstance_Select,msdyn_playbookinstance_Expand,msdyn_playbookinstance_Filter,msdyn_playbookinstance_Fixed,msdyn_playbookinstance_Result,msdyn_playbookinstance_FormattedResult>;
  regardingobjectid_msdyn_postalbum_serviceappointment: WebMappingRetrieve<msdyn_PostAlbum_Select,msdyn_PostAlbum_Expand,msdyn_PostAlbum_Filter,msdyn_PostAlbum_Fixed,msdyn_PostAlbum_Result,msdyn_PostAlbum_FormattedResult>;
  regardingobjectid_new_interactionforemail_serviceappointment: WebMappingRetrieve<InteractionForEmail_Select,InteractionForEmail_Expand,InteractionForEmail_Filter,InteractionForEmail_Fixed,InteractionForEmail_Result,InteractionForEmail_FormattedResult>;
  regardingobjectid_opportunity_serviceappointment: WebMappingRetrieve<Opportunity_Select,Opportunity_Expand,Opportunity_Filter,Opportunity_Fixed,Opportunity_Result,Opportunity_FormattedResult>;
  regardingobjectid_quote_serviceappointment: WebMappingRetrieve<Quote_Select,Quote_Expand,Quote_Filter,Quote_Fixed,Quote_Result,Quote_FormattedResult>;
  regardingobjectid_salesorder_serviceappointment: WebMappingRetrieve<SalesOrder_Select,SalesOrder_Expand,SalesOrder_Filter,SalesOrder_Fixed,SalesOrder_Result,SalesOrder_FormattedResult>;
  regardingobjectid_site_serviceappointment: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  sendermailboxid_serviceappointment: WebMappingRetrieve<Mailbox_Select,Mailbox_Expand,Mailbox_Filter,Mailbox_Fixed,Mailbox_Result,Mailbox_FormattedResult>;
  serviceid_serviceappointment: WebMappingRetrieve<Service_Select,Service_Expand,Service_Filter,Service_Fixed,Service_Result,Service_FormattedResult>;
  siteid: WebMappingRetrieve<Site_Select,Site_Expand,Site_Filter,Site_Fixed,Site_Result,Site_FormattedResult>;
  slainvokedid_serviceappointment_sla: WebMappingRetrieve<SLA_Select,SLA_Expand,SLA_Filter,SLA_Fixed,SLA_Result,SLA_FormattedResult>;
  transactioncurrencyid_serviceappointment: WebMappingRetrieve<TransactionCurrency_Select,TransactionCurrency_Expand,TransactionCurrency_Filter,TransactionCurrency_Fixed,TransactionCurrency_Result,TransactionCurrency_FormattedResult>;
}
interface ServiceAppointment_RelatedMany {
  CampaignResponse_ServiceAppointments: WebMappingRetrieve<CampaignResponse_Select,CampaignResponse_Expand,CampaignResponse_Filter,CampaignResponse_Fixed,CampaignResponse_Result,CampaignResponse_FormattedResult>;
  ServiceAppointment_Annotation: WebMappingRetrieve<Annotation_Select,Annotation_Expand,Annotation_Filter,Annotation_Fixed,Annotation_Result,Annotation_FormattedResult>;
  ServiceAppointment_AsyncOperations: WebMappingRetrieve<AsyncOperation_Select,AsyncOperation_Expand,AsyncOperation_Filter,AsyncOperation_Fixed,AsyncOperation_Result,AsyncOperation_FormattedResult>;
  ServiceAppointment_BulkDeleteFailures: WebMappingRetrieve<BulkDeleteFailure_Select,BulkDeleteFailure_Expand,BulkDeleteFailure_Filter,BulkDeleteFailure_Fixed,BulkDeleteFailure_Result,BulkDeleteFailure_FormattedResult>;
  ServiceAppointment_ProcessSessions: WebMappingRetrieve<ProcessSession_Select,ProcessSession_Expand,ProcessSession_Filter,ProcessSession_Fixed,ProcessSession_Result,ProcessSession_FormattedResult>;
  ServiceAppointment_QueueItem: WebMappingRetrieve<QueueItem_Select,QueueItem_Expand,QueueItem_Filter,QueueItem_Fixed,QueueItem_Result,QueueItem_FormattedResult>;
  ServiceAppointment_SyncErrors: WebMappingRetrieve<SyncError_Select,SyncError_Expand,SyncError_Filter,SyncError_Fixed,SyncError_Result,SyncError_FormattedResult>;
  serviceappointment_MailboxTrackingFolders: WebMappingRetrieve<MailboxTrackingFolder_Select,MailboxTrackingFolder_Expand,MailboxTrackingFolder_Filter,MailboxTrackingFolder_Fixed,MailboxTrackingFolder_Result,MailboxTrackingFolder_FormattedResult>;
  serviceappointment_actioncard: WebMappingRetrieve<ActionCard_Select,ActionCard_Expand,ActionCard_Filter,ActionCard_Fixed,ActionCard_Result,ActionCard_FormattedResult>;
  serviceappointment_activity_parties: WebMappingRetrieve<ActivityParty_Select,ActivityParty_Expand,ActivityParty_Filter,ActivityParty_Fixed,ActivityParty_Result,ActivityParty_FormattedResult>;
  serviceappointment_connections1: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  serviceappointment_connections2: WebMappingRetrieve<Connection_Select,Connection_Expand,Connection_Filter,Connection_Fixed,Connection_Result,Connection_FormattedResult>;
  serviceappointment_principalobjectattributeaccess: WebMappingRetrieve<PrincipalObjectAttributeAccess_Select,PrincipalObjectAttributeAccess_Expand,PrincipalObjectAttributeAccess_Filter,PrincipalObjectAttributeAccess_Fixed,PrincipalObjectAttributeAccess_Result,PrincipalObjectAttributeAccess_FormattedResult>;
  slakpiinstance_serviceappointment: WebMappingRetrieve<SLAKPIInstance_Select,SLAKPIInstance_Expand,SLAKPIInstance_Filter,SLAKPIInstance_Fixed,SLAKPIInstance_Result,SLAKPIInstance_FormattedResult>;
  userentityinstancedata_serviceappointment: WebMappingRetrieve<UserEntityInstanceData_Select,UserEntityInstanceData_Expand,UserEntityInstanceData_Filter,UserEntityInstanceData_Fixed,UserEntityInstanceData_Result,UserEntityInstanceData_FormattedResult>;
}
interface WebEntitiesRetrieve {
  serviceappointments: WebMappingRetrieve<ServiceAppointment_Select,ServiceAppointment_Expand,ServiceAppointment_Filter,ServiceAppointment_Fixed,ServiceAppointment_Result,ServiceAppointment_FormattedResult>;
}
interface WebEntitiesRelated {
  serviceappointments: WebMappingRelated<ServiceAppointment_RelatedOne,ServiceAppointment_RelatedMany>;
}
interface WebEntitiesCUDA {
  serviceappointments: WebMappingCUDA<ServiceAppointment_Create,ServiceAppointment_Update,ServiceAppointment_Select>;
}
